force-app/main/default/objects/FS_Group_Settings__mdt/FS_Group_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Settings for each FS group</description>
    <label>FS Group Settings</label>
    <pluralLabel>FS Group Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if this is an active FS group.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Designated_Role_for_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Designated_Role_for_Ownership__c</fullName>
    <description>Name of Role to use for assigning ownership of records for this FS group.</description>
    <label>Designated Role for Ownership</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/GFW_COA_Name__c.field-meta.xml
<CustomField>
    <fullName>GFW_COA_Name__c</fullName>
    <description>Name of relevant Chart of Account record in GFW db.</description>
    <label>GFW COA Name</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Sync_QueueableSchedule.cls
/*
* Invoke sync from GFW to FSDB for each fiscal sponsor group.
*/
global class Sync_QueueableSchedule implements Schedulable {
    global void execute(SchedulableContext sc) {
        // Run sync for each FS COA
        List<FS_Group_Settings__mdt> fsGroups = [SELECT GFW_COA_Name__c, Designated_Role_for_Ownership__c
            FROM FS_Group_Settings__mdt WHERE Active__c = TRUE];

        System.enqueueJob(new Sync_Queueable(fsGroups));
    }
}