force-app/main/default/objects/FS_Group_Settings__mdt/FS_Group_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Settings for each FS group</description>
    <label>FS Group Settings</label>
    <pluralLabel>FS Group Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Designated_Role_for_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Designated_Role_for_Ownership__c</fullName>
    <description>Name of Role to use for assigning ownership of records for this FS group.</description>
    <label>Designated Role for Ownership</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/GFW_COA_Name__c.field-meta.xml
<CustomField>
    <fullName>GFW_COA_Name__c</fullName>
    <description>Name of relevant Chart of Account record in GFW db.</description>
    <label>GFW COA Name</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Sync_Queueable.cls
public class Sync_Queueable implements Queueable, Database.AllowsCallouts {
		
        // Launch sync and logs actions
        public void execute(QueueableContext context) { 
		 
        // Initialize variables
        String fsRole;
        List<FS_Group_Settings__mdt> fsGroups;

 

        // Run sync for each FS COA
        fsGroups = [SELECT GFW_COA_Name__c, Designated_Role_for_Ownership__c
            FROM FS_Group_Settings__mdt
        ];

        if (fsGroups != null && !fsGroups.isEmpty()) {
            // For each FS, set vars and launch sync
            for (FS_Group_Settings__mdt fs : fsGroups) {
                // Create sync log
                Id newSyncLogId = SyncController.newSyncLog();

                SyncController scThisFS = new SyncController();
                scThisFS.syncLogId = newSyncLogId;
                system.debug('New sync log id from queueable: ' + scThisFS.syncLogId); 
                scThisFS.fsCOA = fs.GFW_COA_Name__c;
                scThisFS.fsRole = fs.Designated_Role_for_Ownership__c;


                scThisFS.LaunchSync();
            }    
        }  
    }        
}