force-app/main/default/objects/FS_Group_Settings__mdt/FS_Group_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Settings for each FS group</description>
    <label>FS Group Settings</label>
    <pluralLabel>FS Group Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if this is an active FS group.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Designated_Role_for_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Designated_Role_for_Ownership__c</fullName>
    <description>Name of Role to use for assigning ownership of records for this FS group.</description>
    <label>Designated Role for Ownership</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/GFW_COA_Name__c.field-meta.xml
<CustomField>
    <fullName>GFW_COA_Name__c</fullName>
    <description>Name of relevant Chart of Account record in GFW db.</description>
    <label>GFW COA Name</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/Sync_Log_Record__c.object-meta.xml
<CustomObject>
    <label>Sync Log Record</label>
    <nameField>
        <displayFormat>SLR-{0000}</displayFormat>
        <label>Sync Log Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Log Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Log_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of sync log record: Pending, Success or Error</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncControllerTest.cls
@isTest
public without sharing class SyncControllerTest {
    
    @isTest 
    static void testLaunchSync() {

        Test.setMock(HttpCalloutMock.class, new SyncMock());
        List<FS_Group_Settings__mdt> fsGroups = [SELECT GFW_COA_Name__c, Designated_Role_for_Ownership__c
        FROM FS_Group_Settings__mdt WHERE Active__c = TRUE];

        Test.startTest();
        SyncController scThisFS = new SyncController();
        scThisFS.startDateTime = datetime.now();
        scThisFS.fsCOA = fsGroups[0].GFW_COA_Name__c;
        scThisFS.fsRole = fsGroups[0].Designated_Role_for_Ownership__c;
        String jsonResults = scThisFS.doQueryNextBatchCallout('testURL');
        scThisFS.LaunchSync();
        system.assert(jsonResults!='');
        List<Sync_Log_Record__c> logRecs = [SELECT Id, Name FROM Sync_Log_Record__c WHERE Status__c = 'Pending'];
        system.assert(logRecs.size()>0);
        Test.stopTest();
    }
}