force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Top level in a hierarchically structured HTML form for online submissions</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Form_Phrase_confirm__c.field-meta.xml
<CustomField>
    <fullName>Form_Phrase_confirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The text to display on the confirm page for this form (Confirm page appears prior to entering the form and only for &quot;non-invited&quot; proposals, ie auto-assigned invites to allocations). If blank, confirm page is skipped.</description>
    <inlineHelpText>The text to display on the confirm page for this form (Confirm page appears prior to entering the form and only for &quot;non-invited&quot; proposals, ie auto-assigned invites to allocations). If blank, confirm page is skipped.</inlineHelpText>
    <label>Form Phrase confirm</label>
    <referenceTo>Form_Phrase__c</referenceTo>
    <relationshipLabel>Forms (Form Phrase confirm)</relationshipLabel>
    <relationshipName>Forms9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this form</description>
    <inlineHelpText>The type of this form</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Form_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Phrase__c/Form_Phrase__c.object-meta.xml
<CustomObject>
    <description>Identifies a piece of text appearing one or more times in forms. The translations of that text, including English, are stored in a separate object.</description>
    <label>Form Phrase</label>
    <nameField>
        <label>Form Phrase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Phrases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Form_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prequal</fullName>
    </customValue>
    <customValue>
        <fullName>ContactInfo</fullName>
    </customValue>
    <customValue>
        <fullName>Profile</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility</fullName>
    </customValue>
    <customValue>
        <fullName>Application</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Admin</fullName>
    </customValue>
    <customValue>
        <fullName>SelfAssessment</fullName>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Endorsement</fullName>
    </customValue>
    <customValue>
        <fullName>Assessment</fullName>
    </customValue>
    <description>The admissible types of forms</description>
    <masterLabel>Form type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FormControllerTest.cls
@isTest
public with sharing class FormControllerTest {
    
    // Test form phrase tagging code
    static testmethod void FormCloneTest3 () {
        // Build records.
        insert new Form_Phrase__c (Name = 'test phrase');
        Form_Phrase__c fp = [SELECT Id FROM Form_Phrase__c LIMIT 1];
        insert new Form_Phrase__c (Name = 'test phrase pre-tagged', SavedSetNames__c = 'test form');
        insert new Form__c (Name = 'test form', Type__c = 'Admin', Form_Phrase_confirm__c = fp.Id);
        Form__c f = [SELECT Id FROM Form__c LIMIT 1];
        Test.startTest();
        FormTagFormPhrasesInvocable.tagFormPhrases(new List<Id>{f.Id});
        Test.stopTest();
        fp = [SELECT SavedSetNames__c FROM Form_Phrase__c WHERE Name = 'test phrase' LIMIT 1];
        Form_Phrase__c fp1 = [SELECT SavedSetNames__c FROM Form_Phrase__c WHERE Name = 'test phrase pre-tagged' LIMIT 1];
        system.assertEquals('test form', fp.SavedSetNames__c);
        system.assertEquals(null, fp1.SavedSetNames__c);
    }
}