force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Top level in a hierarchically structured HTML form for online submissions</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Sort_number__c.field-meta.xml
<CustomField>
    <fullName>Sort_number__c</fullName>
    <description>Determines the sort order for this form within its app</description>
    <inlineHelpText>Determines the sort order for this form within its app</inlineHelpText>
    <label>Sort number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this form</description>
    <inlineHelpText>The type of this form</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Form_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Component__c/Form_Component__c.object-meta.xml
<CustomObject>
    <description>Component level in a hierarchically structured HTML form for online submissions</description>
    <label>Form Component</label>
    <nameField>
        <label>Form Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Component__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent form of this component</description>
    <inlineHelpText>The parent form of this component</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Components</relationshipLabel>
    <relationshipName>Form_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Component__c/fields/Form_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Form_Phrase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The (translatable) text phrase for this component</description>
    <inlineHelpText>The (translatable) text phrase for this component</inlineHelpText>
    <label>Form Phrase</label>
    <referenceTo>Form_Phrase__c</referenceTo>
    <relationshipLabel>Form Components</relationshipLabel>
    <relationshipName>Form_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Component__c/fields/Form_phrase_in_English__c.field-meta.xml
<CustomField>
    <fullName>Form_phrase_in_English__c</fullName>
    <description>The text of this component&apos;s form phrase in English</description>
    <inlineHelpText>The text of this component&apos;s form phrase in English</inlineHelpText>
    <label>Form phrase in English</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Component__c/fields/Sort_number__c.field-meta.xml
<CustomField>
    <fullName>Sort_number__c</fullName>
    <description>Determines the sort order for this component within its item</description>
    <inlineHelpText>Determines the sort order for this component within its item</inlineHelpText>
    <label>Sort number</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this form component</description>
    <inlineHelpText>The type of this form component</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>checkbox group</fullName>
            </value>
            <value>
                <fullName>checkbox in-line</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>file upload</fullName>
            </value>
            <value>
                <fullName>group</fullName>
            </value>
            <value>
                <fullName>indicator</fullName>
            </value>
            <value>
                <fullName>label</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>percent</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>radio</fullName>
            </value>
            <value>
                <fullName>radio in-line</fullName>
            </value>
            <value>
                <fullName>section</fullName>
            </value>
            <value>
                <fullName>select</fullName>
            </value>
            <value>
                <fullName>table dynamic</fullName>
            </value>
            <value>
                <fullName>table static</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>textarea</fullName>
            </value>
            <value>
                <fullName>textarea latin chars</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Phrase__c/Form_Phrase__c.object-meta.xml
<CustomObject>
    <description>Identifies a piece of text appearing one or more times in forms. The translations of that text, including English, are stored in a separate object.</description>
    <label>Form Phrase</label>
    <nameField>
        <label>Form Phrase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Phrases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Phrase__c/fields/Phrase_in_English__c.field-meta.xml
<CustomField>
    <fullName>Phrase_in_English__c</fullName>
    <description>The text of this phrase in English</description>
    <inlineHelpText>The text of this phrase in English</inlineHelpText>
    <label>Phrase in English</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Phrase__c/fields/Phrase_in_English_trimmed__c.field-meta.xml
<CustomField>
    <fullName>Phrase_in_English_trimmed__c</fullName>
    <description>First 255 characters of the &quot;Phrase in English&quot; field (auto-maintained)</description>
    <inlineHelpText>First 255 characters of the &quot;Phrase in English&quot; field (auto-maintained)</inlineHelpText>
    <label>Phrase in English (trimmed)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_Phrase_Translation__c/Form_Phrase_Translation__c.object-meta.xml
<CustomObject>
    <description>Translation of a phrase into a particular language</description>
    <label>Form Phrase Translation</label>
    <nameField>
        <displayFormat>PHRT-{0000}</displayFormat>
        <label>Form Phrase Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Phrase Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Phrase_Translation__c/fields/Form_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Form_Phrase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The phrase for which this is a translation</description>
    <inlineHelpText>The phrase for which this is a translation</inlineHelpText>
    <label>Form Phrase</label>
    <referenceTo>Form_Phrase__c</referenceTo>
    <relationshipLabel>Form Phrase Translations</relationshipLabel>
    <relationshipName>Form_Phrase_Translations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Phrase_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>The language of this phrase translation</description>
    <inlineHelpText>The language of this phrase translation</inlineHelpText>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Phrase_Translation__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>The text for this phrase in the given language</description>
    <inlineHelpText>The text for this phrase in the given language</inlineHelpText>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Phrase_Translation__c/fields/Text_in_English__c.field-meta.xml
<CustomField>
    <fullName>Text_in_English__c</fullName>
    <description>The text of this phrase in English</description>
    <inlineHelpText>The text of this phrase in English</inlineHelpText>
    <label>Text in English</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Form_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prequal</fullName>
    </customValue>
    <customValue>
        <fullName>ContactInfo</fullName>
    </customValue>
    <customValue>
        <fullName>Profile</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility</fullName>
    </customValue>
    <customValue>
        <fullName>Application</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Admin</fullName>
    </customValue>
    <customValue>
        <fullName>SelfAssessment</fullName>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Endorsement</fullName>
    </customValue>
    <customValue>
        <fullName>Assessment</fullName>
    </customValue>
    <description>The admissible types of forms</description>
    <masterLabel>Form type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FormPhraseControllerTest.cls
@isTest
public class FormPhraseControllerTest {

    static testmethod void FormPhraseControllerTest () {
        // Build test records.
        insert new Form_Phrase__c (Name = 'test phrase');
        Form_Phrase__c phr = [SELECT Id FROM Form_Phrase__c WHERE Name='test phrase' LIMIT 1];
        insert new Form_Phrase_Translation__c (Form_Phrase__c = phr.Id, Language__c = 'English', Text__c = 'testing');
        Form_Phrase_Translation__c transEng = [SELECT Id FROM Form_Phrase_Translation__c WHERE Language__c='English' LIMIT 1];
        insert new Form_Phrase_Translation__c (Form_Phrase__c = phr.Id, Language__c = 'Spanish', Text__c = 'pruebas');
        Form_Phrase_Translation__c transSpan = [SELECT Id FROM Form_Phrase_Translation__c WHERE Language__c='Spanish' LIMIT 1];
        insert new Form__c (Name = 'test form', Type__c = 'Admin');
        Form__c f = [SELECT Id FROM Form__c LIMIT 1];
        insert new Form_Component__c (Name = 'test form component', Form__c = f.Id, Sort_number__c = 1, Form_Phrase__c = phr.Id);
        Form_Component__c comp = [SELECT Id FROM Form_Component__c LIMIT 1];
        
        Test.startTest();
        FormPhraseUpdateEnglishInvocable.updatePhraseInEnglish(new List<Id> {phr.Id});
        Test.stopTest();
        
        phr = [SELECT Phrase_in_English__c, Phrase_in_English_trimmed__c FROM Form_Phrase__c WHERE Id = : phr.Id];
        system.assertEquals('testing', phr.Phrase_in_English__c);
        system.assertEquals('testing', phr.Phrase_in_English_trimmed__c);
        transEng = [SELECT Text_in_English__c FROM Form_Phrase_Translation__c WHERE Id = : transEng.Id];
        system.assertEquals('testing', transEng.Text_in_English__c);
        transSpan = [SELECT Text_in_English__c FROM Form_Phrase_Translation__c WHERE Id = : transSpan.Id];
        system.assertEquals('testing', transSpan.Text_in_English__c);
        comp = [SELECT Form_phrase_in_English__c FROM Form_Component__c WHERE Id = : comp.Id];
        system.assertEquals('testing', comp.Form_phrase_in_English__c);
    }

}