force-app/main/default/objects/Advisor__c/Advisor__c.object-meta.xml
<CustomObject>
    <description>Holds information about an advisor&apos;s interests, region of expertise.  Links from letters, endorsements and advisor terms.</description>
    <label>Advisor</label>
    <nameField>
        <label>Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The account, either household or organization, containing mailing information for this advisor</description>
    <inlineHelpText>The account, either household or organization, containing mailing information for this advisor</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/Advisor_Term__c.object-meta.xml
<CustomObject>
    <description>Represents a term of an official GFW advisor</description>
    <label>Advisor Term</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Advisor Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisor Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor_Term__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <description>Parent advisor of this advisor term</description>
    <inlineHelpText>Parent advisor of this advisor term</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>Advisor__c</referenceTo>
    <relationshipLabel>Advisor Terms</relationshipLabel>
    <relationshipName>Advisor_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For &quot;View Forms&quot; advisor terms, this portfolio contains the proposals/accounts to be shared with the advisor</description>
    <inlineHelpText>For &quot;View Forms&quot; advisor terms, this portfolio contains the proposals/accounts to be shared with the advisor</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Advisor Terms</relationshipLabel>
    <relationshipName>Advisor_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this advisor term</description>
    <formula>IF ( NOT(ISBLANK(Date_declined__c)), &quot;0 Declined&quot;,
IF (
 AND( 
  NOT(ISBLANK(Date_term_ends__c)),
  Date_term_ends__c &lt; TODAY()
 ), &quot;10 Completed&quot;,
IF (
 OR(
  TEXT(Type__c) = &quot;Reference&quot;, 
  NOT(ISBLANK(Date_accepted__c))
 ), &quot;6 Active&quot;,
IF (NOT(ISBLANK(Date_invited__c)), &quot;2 Invited&quot;, 
&quot;1 Pending&quot;
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Status of this advisor term</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>An assessment created by an advisor for a particular account/proposal/profile/portfolio</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account to which this assessment is linked</description>
    <inlineHelpText>The account to which this assessment is linked</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <description>The advisor to which this assessment is linked</description>
    <inlineHelpText>The advisor to which this assessment is linked</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>Advisor__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Advisor_Term__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The advisor term record linked to this assessment</description>
    <inlineHelpText>The advisor term record linked to this assessment</inlineHelpText>
    <label>Advisor Term</label>
    <referenceTo>Advisor_Term__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <description>Date on which this assessment was submitted</description>
    <inlineHelpText>Date on which this assessment was submitted</inlineHelpText>
    <label>Date submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The milestone to which this assessment is linked</description>
    <inlineHelpText>The milestone to which this assessment is linked</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The portfolio to which this assessment is linked</description>
    <inlineHelpText>The portfolio to which this assessment is linked</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this assessment is linked</description>
    <inlineHelpText>The profile to which this assessment is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal to which this assessment is linked</description>
    <inlineHelpText>The proposal to which this assessment is linked</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Review_Form__c.field-meta.xml
<CustomField>
    <fullName>Review_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The review form to be used for this assessment</description>
    <inlineHelpText>The review form to be used for this assessment</inlineHelpText>
    <label>Review Form</label>
    <referenceTo>Review_Form__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this assessment</description>
    <formula>IF ( NOT(ISBLANK(Date_submitted__c)), &quot;2 Submitted&quot;,

&quot;1 Assessment pending&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The status of this assessment</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Represents a milestone (report, payment, site visit, etc.) due or received for this grant</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <description>The date on which this milestone/report was submitted</description>
    <inlineHelpText>The date on which this milestone/report was submitted</inlineHelpText>
    <label>Date submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal (grant) to which this milestone belongs</description>
    <inlineHelpText>The proposal (grant) to which this milestone belongs</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account of the org responsible for this profile</description>
    <inlineHelpText>The account of the org responsible for this profile</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <description>Date on which this profile was submitted</description>
    <inlineHelpText>Date on which this profile was submitted</inlineHelpText>
    <label>Date submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this proposal is linked</description>
    <inlineHelpText>The profile to which this proposal is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Assessment.cls
public with sharing class Assessment extends Review {
    
    public String name;
    public Id accountId;
    public Id Id;
    public String accountName;
    public Id advisorId;
    public Id advisorTermId;
    public Date dateSubmitted;
    public String status;
    public String statusExternal;


    public Assessment(Id assessmentId) {
        try {
            Assessment__c assess = [SELECT Id, Name, Account__c, Account__r.Name, Advisor__c, Advisor__r.Name, Advisor_Term__c, Date_submitted__c, Milestone__c, Portfolio__c, Profile__c, Proposal__c, Review_Form__c, Status__c, Status_external__c FROM Assessment__c WHERE ID=:assessmentId];

            // if there is no linked review form, there is nothing to load
            if (assess.Review_Form__c !=null ) {
                this.Id = assess.Id;
                this.name = assess.Name;
                this.accountId = assess.Account__c;
                this.reviewerName = assess.Advisor__r.Name;
                this.accountName = assess.Account__r.Name;
                this.advisorId = assess.Advisor__c;
                this.advisorTermId = assess.Advisor_Term__c;
                this.dateSubmitted = assess.Date_submitted__c;
                this.status = assess.Status__c;
                this.statusExternal = assess.Status_external__c;
                this.reviewFormId = assess.Review_Form__c;
                // Initialize Maps and lists
                indicatorAssignMap = new Map < String, Map < String, IndicatorAssign > >();
                classificationAssignMap = new Map < String, List < ClassificationAssign > >();
                formComponents = new List < FormComponent >();
                portfolioAssignments = new List < PortfolioAssign >();
    
                if (assess.Milestone__c!=null) {
                    this.type = 'Milestone';
                    loadMilestone(assess.Milestone__c);
                } else if (assess.Profile__c!=null) {
                    this.type = 'Profile';
                    loadProfile(assess.Profile__c);
                } else {
                    this.type = 'Proposal';
                    loadProposal(assess.Proposal__c);
                }
    
                loadReviewFormComponents();
                loadPortfolioAssigns();
                loadProfilePortfolioAssigns();
                loadIndicatorAssigns();
                loadClassificationAssigns();
                finishFormComponentBuild();
            }

        } catch (Exception e) {
            throw new GFW_Exception ('Assessment.IdConstructor', 'Could Not load the requested Assessment.', e);
        }
        
    }

    public void submit() {
        try {
            Date today = System.today();
            this.dateSubmitted = today;

            //Update Assessment Submitted Date
            Assessment__c completedAssessment = new Assessment__c (
                ID=this.Id,
                Date_submitted__c=today
            );
            update completedAssessment;

            // Update the Milestone or Proposal Review Completion Date if not already filled in
            if (this.type=='Milestone') {
                if (this.linkedMilestone.Date_reviewed__c==null) {
                    Milestone__c m = new Milestone__c (
                        Id=this.linkedMilestone.Id,
                        Date_reviewed__c = today
                    );
                    update m;
                }
            } else if (this.type=='Proposal') {
                if (this.linkedProposal.Date_review_completed__c==null) {
                    Proposal__c prop = new Proposal__c (
                        Id=this.linkedProposal.Id,
                        Date_review_completed__c = today
                    );
                    update prop;
                }
            } else if (this.type=='Profile') {
                if (this.linkedProfile.Date_review_completed__c==null) {
                    Profile__c prof = new Profile__c (
                        Id=this.linkedProfile.Id,
                        Date_review_completed__c = today
                    );
                    update prof;
                }
            }
        } catch (Exception e) {
            throw new GFW_Exception('Assessment.submit', 'Review Submit Failed, please refresh and try again.', e);
        }
        
    }
}