force-app/main/default/objects/Advisor__c/Advisor__c.object-meta.xml
<CustomObject>
    <description>Holds information about an advisor&apos;s interests, region of expertise.  Links from letters, endorsements and advisor terms.</description>
    <label>Advisor</label>
    <nameField>
        <label>Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>The language prefered by this advisor (for correspondence)</description>
    <inlineHelpText>The language prefered by this advisor (for correspondence)</inlineHelpText>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of advisor (including official, informal, reference)</description>
    <inlineHelpText>Type of advisor (including official, informal, reference)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Official</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/Advisor_Term__c.object-meta.xml
<CustomObject>
    <description>Represents a term of an official GFW advisor</description>
    <label>Advisor Term</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Advisor Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisor Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor_Term__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <description>Parent advisor of this advisor term</description>
    <inlineHelpText>Parent advisor of this advisor term</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>Advisor__c</referenceTo>
    <relationshipLabel>Advisor Terms</relationshipLabel>
    <relationshipName>Advisor_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For &quot;View Forms&quot; advisor terms, this portfolio contains the proposals/accounts to be shared with the advisor</description>
    <inlineHelpText>For &quot;View Forms&quot; advisor terms, this portfolio contains the proposals/accounts to be shared with the advisor</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Advisor Terms</relationshipLabel>
    <relationshipName>Advisor_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Status_external__c.field-meta.xml
<CustomField>
    <fullName>Status_external__c</fullName>
    <description>External status of this advisor term (the version that is viewed by the advisor)</description>
    <formula>IF (CONTAINS(Status__c, &quot; &quot;),
 TRIM(RIGHT(Status__c, LEN(Status__c) - FIND(&quot; &quot;, Status__c))),
 Status__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>External status of this advisor term (the version that is viewed by the advisor)</inlineHelpText>
    <label>Status external</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this advisor term, that is, the role of the advisor for the duration of this advisor term. Normally populated on acceptance.</description>
    <inlineHelpText>The type of this advisor term, that is, the role of the advisor for the duration of this advisor term. Normally populated on acceptance.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Advisor_term_types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>An assessment created by an advisor for a particular account/proposal/profile/portfolio</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <description>The advisor to which this assessment is linked</description>
    <inlineHelpText>The advisor to which this assessment is linked</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>Advisor__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The form to be used for this assessment</description>
    <inlineHelpText>The form to be used for this assessment</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The milestone to which this assessment is linked</description>
    <inlineHelpText>The milestone to which this assessment is linked</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The portfolio to which this assessment is linked</description>
    <inlineHelpText>The portfolio to which this assessment is linked</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Status_external__c.field-meta.xml
<CustomField>
    <fullName>Status_external__c</fullName>
    <description>External status of this assessment (the version that is viewed by the advisor)</description>
    <formula>IF ( CONTAINS( LOWER(Status__c) , &quot;pending&quot; ), &quot;Pending&quot;,
&quot;Submitted&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>External status of this assessment (the version that is viewed by the advisor)</inlineHelpText>
    <label>Status external</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Top level in a hierarchically structured HTML form for online submissions</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this form</description>
    <inlineHelpText>The type of this form</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Form_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Represents a milestone (report, payment, site visit, etc.) due or received for this grant</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of milestone</description>
    <inlineHelpText>The type of milestone</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</description>
    <inlineHelpText>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Advisor assignments</fullName>
            </value>
            <value>
                <fullName>Saved Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>The language used in this profile</description>
    <inlineHelpText>The language used in this profile</inlineHelpText>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Status_external__c.field-meta.xml
<CustomField>
    <fullName>Status_external__c</fullName>
    <description>External status of this profile (the version that is viewed by applicant)</description>
    <formula>IF ( CONTAINS( LOWER(Status__c) , &quot;declined&quot; ), &quot;Declined&quot;,
IF ( NOT (ISBLANK ( Date_submitted__c )), &quot;Submitted&quot;,
&quot;Pending&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>External status of this profile (the version that is viewed by applicant)</inlineHelpText>
    <label>Status external</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Status_external__c.field-meta.xml
<CustomField>
    <fullName>Status_external__c</fullName>
    <description>A version of this proposal&apos;s status suitable for viewing on the online apps site</description>
    <formula>IF (NOT (ISBLANK ( Date_declined__c )), &quot;Declined&quot;,
IF (NOT (ISBLANK ( Date_request_withdrawn__c )) &amp;&amp; TEXT(Request_withdrawn_reason__c) = &quot;AUTOMATED: Lack of online form activity&quot;,
&quot;Withdrawn_NoRecentActivity&quot;,
IF (NOT (ISBLANK ( Date_request_withdrawn__c )) || NOT(ISBLANK(Date_award_withdrawn__c)), &quot;Withdrawn&quot;,
IF ( Status_numeric__c &gt;= 6.2 , &quot;Awarded&quot;,
IF (NOT (ISBLANK ( Date_received__c )), &quot;Submitted&quot; ,

&quot;Pending&quot;
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A version of this proposal&apos;s status suitable for viewing on the online apps site</inlineHelpText>
    <label>Status external</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Advisor_term_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Expert</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>Assessor</fullName>
    </customValue>
    <customValue>
        <fullName>View forms</fullName>
    </customValue>
    <description>The types of advisor terms</description>
    <masterLabel>Advisor term types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Form_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prequal</fullName>
    </customValue>
    <customValue>
        <fullName>ContactInfo</fullName>
    </customValue>
    <customValue>
        <fullName>Profile</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility</fullName>
    </customValue>
    <customValue>
        <fullName>Application</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Admin</fullName>
    </customValue>
    <customValue>
        <fullName>SelfAssessment</fullName>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Endorsement</fullName>
    </customValue>
    <customValue>
        <fullName>Assessment</fullName>
    </customValue>
    <description>The admissible types of forms</description>
    <masterLabel>Form type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <description>The languages in use for correspondence</description>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Milestone_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Report</fullName>
    </customValue>
    <customValue>
        <fullName>Report narrative</fullName>
    </customValue>
    <customValue>
        <fullName>Report financial</fullName>
    </customValue>
    <customValue>
        <fullName>Report activities</fullName>
    </customValue>
    <customValue>
        <fullName>Site visit</fullName>
    </customValue>
    <description>Milestone types</description>
    <masterLabel>Milestone type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AdvisorSummary.cls
public with sharing class AdvisorSummary {

    public Boolean hasForms = false;
    public Boolean hasMilestones = false;
    public Boolean hasProfiles = false;
    public Boolean hasProposals = false;
    public Boolean hasRatings = false;
    public Integer formsCount = 0;
    public Integer pendingMilestonesCount = 0;
    public Integer pendingProfilesCount = 0;
    public Integer pendingProposalsCount = 0;
    public Integer pendingRatingsCount = 0;
    public Integer priorityMCount = 0;
    public Integer priorityProfileCount =0;
    public Integer priorityProposalCount = 0;
    public Integer totalPendingItems = 0;
    public Integer totalPriorityItems = 0;
    public String firstName;
    public String fullName;
    public String lastName;
    public String preferredLanguage;

    public List < ItemSummary > milestoneReviewsAssigned;
    public List < ItemSummary > profileReviewsAssigned;
    public List < ItemSummary > proposalReviewsAssigned;
    public List < ItemSummary > ratingsAssigned;
    public List < ItemSummary > viewFormsAvailable;
    
    
    public class ItemSummary {
        public Boolean isPriority;
        public Date dateValue;
        public ID sfId;
        public String dateDescription;
        public String detail1;
        public String detail1Label;
        public String detail2;
        public String detail2Label;
        public String linkURL;
        public String objectName;
        public String title;
        public String titleLabel;
    }

    public AdvisorSummary(String advisorId) {
        
        Advisor__c advRecord = [SELECT ID, Language__c, (SELECT ID, Type__c, Status_external__c, Portfolio__c FROM Advisor_Terms__r WHERE Status_external__c='Active') FROM Advisor__c WHERE ID=:advisorId];

        this.fullName = System.UserInfo.getName();
        this.firstName = System.UserInfo.getFirstName();
        this.lastName = System.UserInfo.getLastName();
        this.preferredLanguage = advRecord.Language__c;

        this.milestoneReviewsAssigned = new List <ItemSummary>();
        this.proposalReviewsAssigned = new List <ItemSummary>();
        this.profileReviewsAssigned = new List <ItemSummary>();
        this.ratingsAssigned = new List <ItemSummary>();
        this.viewFormsAvailable = new List <ItemSummary>();
        

        List < Assessment__c > milestoneAssessments = AssessorSiteController.getMilestoneAssessments(advisorId, 'pending', 3);
        this.pendingMilestonesCount = milestoneAssessments.size();
        
        Integer allMs = [SELECT COUNT()
                            FROM Assessment__c
                            WHERE Advisor__c=:advisorId
                            AND Form__c=null
                            AND Milestone__c!=null];
        
        if (allMs>0) {
            this.hasMilestones = true;
        }

        for (Integer i=0; i<3; i++) {
            if (milestoneAssessments.size()>i) {
                ItemSummary mSumm = new ItemSummary();
                mSumm.sfId = milestoneAssessments[i].Id;
                mSumm.objectName = 'Milestone__c';
                mSumm.linkURL = '/lightning/r/Assessment_Detail__c/'+mSumm.sfId+'/view';
                if (milestoneAssessments[i].Milestone__r.Review_priority__c=='2 - High') {
                    mSumm.isPriority = true;
                    this.priorityMCount++; 
                    this.totalPriorityItems++;
                }
                mSumm.titleLabel = 'Milestone #';
                mSumm.title = milestoneAssessments[i].Milestone__r.Name;
                mSumm.detail1Label = 'Organization Name';
                mSumm.detail1 = milestoneAssessments[i].Milestone__r.Account_name__c;
                mSumm.dateDescription = 'Date Recieved';
                mSumm.dateValue = milestoneAssessments[i].Milestone__r.Date_submitted__c;
                milestoneReviewsAssigned.add(mSumm);
            }
        }
        List < Assessment__c > proposalAssessments = AssessorSiteController.getProposalAssessments(advisorId, 'Pending', null);

        this.pendingProposalsCount = proposalAssessments.size();

        Integer allPropReviews = [SELECT COUNT()
                                    FROM Assessment__c
                                    WHERE Advisor__c=:advisorId
                                    AND Form__c=null
                                    AND Milestone__c=null 
                                    AND Profile__c=null
                                    AND Proposal__c!=null];
        if (allPropReviews>0) {
            this.hasProposals = true;
        }

        for (Integer i=0; i<3; i++) {
            if (proposalAssessments.size()>i) {
                ItemSummary prRev = new ItemSummary();
                prRev.sfId = proposalAssessments[i].Id;
                prRev.objectName = 'Proposal__c';
                prRev.linkURL = '/lightning/r/Assessment_Detail__c/${'+prRev.sfId+'}/view';
                //Todo priority logic
                prRev.titleLabel = 'Proposal #';
                prRev.title = proposalAssessments[i].Proposal__r.Name;
                prRev.detail1Label = 'Organization Name';
                prRev.detail1 = proposalAssessments[i].Proposal__r.Account__r.Name;
                prRev.dateDescription = 'Date Recieved';
                prRev.dateValue = proposalAssessments[i].Proposal__r.Date_received__c;
                proposalReviewsAssigned.add(prRev);
            }
        }

        List <Assessment__c> profileAssessments = AssessorSiteController.getProfileAssessments(advisorId, 'Pending', null);

        this.pendingProfilesCount = profileAssessments.size();

        Integer allProfReviews = [SELECT COUNT()
                                    FROM Assessment__c
                                    WHERE Advisor__c=:advisorId
                                    AND Form__c=null
                                    AND Milestone__c=null
                                    AND Profile__c!=null];
        if (allProfReviews>0) {
            this.hasProfiles = true;
        }

        for (Integer i=0; i<3; i++) {
            if (profileAssessments.size()>i) {
                ItemSummary prRev = new ItemSummary();
                prRev.sfId = profileAssessments[i].Id;
                prRev.objectName = 'Profile__c';
                prRev.linkURL = '/lightning/r/Assessment_Detail__c/${'+prRev.sfId+'}/view';
                prRev.titleLabel = 'Profile #';
                prRev.title = profileAssessments[i].Profile__r.Name;
                prRev.detail1Label = 'Applicant';
                prRev.detail1 = profileAssessments[i].Profile__r.Org_name__c;
                prRev.dateDescription = 'Date Received';
                prRev.dateValue = profileAssessments[i].Profile__r.Date_submitted__c;
                profileReviewsAssigned.add(prRev);
            }
        }

        //Load Ratings Assessments
        List <Assessment__c> pendingRatingsAssessments = AssessorSiteController.getRatingAssessments(advisorId, 'Pending', null);

        this.pendingRatingsCount = pendingRatingsAssessments.size();

        Integer ratingsCount = [SELECT COUNT()
                                FROM Assessment__c
                                WHERE Advisor__c=:advisorId
                                AND Form__c!=null]; 
                                
        if (ratingsCount>0) {
            this.hasRatings = true;
        }

        for (Integer i=0; i<3; i++) {
            if (pendingRatingsAssessments.size()>i) {
                ItemSummary ratingSumm = new ItemSummary();
                ratingSumm.sfId = pendingRatingsAssessments[i].Id;
                ratingSumm.objectName = 'Rating';
                ratingSumm.linkURL = '/lightning/r/Assessment_Detail__c/${'+ratingSumm.sfId+'}/view';
                ratingSumm.titleLabel = 'Proposal #';
                ratingSumm.title = pendingRatingsAssessments[i].Proposal__r.Name;
                ratingSumm.detail1Label = 'Organization Name';
                ratingSumm.detail1 = pendingRatingsAssessments[i].Proposal__r.Account__r.Name;
                ratingSumm.dateDescription = 'Date Recieved';
                ratingSumm.dateValue = pendingRatingsAssessments[i].Proposal__r.Date_received__c;
                ratingsAssigned.add(ratingSumm);
            }
        }

        //Load all the viewable forms that this user has available
        List < Invite__c > invites = AssessorSiteController.loadInviteViewForms(advRecord.Advisor_Terms__r,null);
        if (invites!=null) {
            this.formsCount = invites.size();
        } else {
            this.formsCount = 0;
        }

        if (this.formsCount>0) {
            this.hasForms = true;
        }

        for (Integer i=0; i<3; i++) {
            if (invites!=null && invites.size()>i) {
                ItemSummary invItem = new ItemSummary();
                if (invites[i].Proposal__c!=null) {
                    invItem.objectName = 'Proposal__c';
                } else if (invites[i].Profile__c!=null) {
                    invItem.objectName = 'Profile__c';
                }

                invItem.sfId = invites[i].Id;
                invItem.titleLabel = 'Organization Name';
                invItem.title = invites[i].Account__r.Name;
                invItem.detail1Label = 'Proposal #';
                invItem.detail1 = invites[i].Proposal__r.Name;
                invItem.detail2Label = 'Country';
                invItem.detail2 = invites[i].Account__r.GM_country__r.Name;
                viewFormsAvailable.add(invItem);
            }
        }

        this.totalPendingItems = milestoneAssessments.size() + proposalAssessments.size() + profileAssessments.size() + pendingRatingsAssessments.size();

    }
    
}