force-app/main/default/objects/Periodic_delete_queries__c/Periodic_delete_queries__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>NOTE: Check with IM before editing, as this can mass delete records without saving in the recycle bin! Each record contains a query that returns a collection of records to be deleted via scheduled apex.</description>
    <label>Periodic delete queries</label>
</CustomObject>

force-app/main/default/objects/Periodic_delete_queries__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this delete query is active</description>
    <inlineHelpText>Checked if this delete query is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periodic_delete_queries__c/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <defaultValue>10000</defaultValue>
    <description>The size of the batch used by the batch apex to make the deletes.  Default is 10,000.</description>
    <inlineHelpText>The size of the batch used by the batch apex to make the deletes.  Default is 10,000.</inlineHelpText>
    <label>Batch size</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Periodic_delete_queries__c/fields/Hard_delete__c.field-meta.xml
<CustomField>
    <fullName>Hard_delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, then do a hard delete - that is, remove from the recycle bin immediately after deleting.</description>
    <inlineHelpText>If checked, then do a hard delete - that is, remove from the recycle bin immediately after deleting.</inlineHelpText>
    <label>Hard delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periodic_delete_queries__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>The query used to find records to delete</description>
    <inlineHelpText>The query used to find records to delete</inlineHelpText>
    <label>Query</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteRecordsSchedulable.cls
/*
 * Delete collections of records determined by SOQL queries found in custom settings.
 * Run this on a regular basis, by using the Schedule button from the Setup/apex classes/ interface.
 */
global with sharing class DeleteRecordsSchedulable implements Schedulable {
    global void execute(SchedulableContext scMain) {
        // Look for active queries to run from custom settings.
        // Note that the max length of a query is 255 characters.
        Map<String, Periodic_delete_queries__c> pdqs = Periodic_delete_queries__c.getAll();
        for (Periodic_delete_queries__c pdq : pdqs.values()) {
            if (pdq.Active__c) {
                Database.executeBatch(
                    new DeleteRecordsBatch(pdq.Query__c, pdq.Hard_delete__c),
                    (Integer) pdq.Batch_size__c
                );
            }
        }
    }
}