force-app/main/default/objects/Advisor_Payment__c/Advisor_Payment__c.object-meta.xml
<CustomObject>
    <description>Represents a payment made for an advisor term</description>
    <label>Advisor Payment</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Advisor Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor_Payment__c/fields/Advisor_Term__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Term__c</fullName>
    <description>The advisor term to which this payment applies</description>
    <inlineHelpText>The advisor term to which this payment applies</inlineHelpText>
    <label>Advisor Term</label>
    <referenceTo>Advisor_Term__c</referenceTo>
    <relationshipLabel>Advisor Payments</relationshipLabel>
    <relationshipName>Advisor_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advisor_Payment__c/fields/Amount_paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_paid__c</fullName>
    <description>Amount of this payment</description>
    <inlineHelpText>Amount of this payment</inlineHelpText>
    <label>Amount paid</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Advisor_Payment__c/fields/Date_paid_accounting__c.field-meta.xml
<CustomField>
    <fullName>Date_paid_accounting__c</fullName>
    <description>The date paid assigned by Finance</description>
    <inlineHelpText>The date paid assigned by Finance</inlineHelpText>
    <label>Date paid accounting</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Advisor_Payment__c/fields/Payment_ref__c.field-meta.xml
<CustomField>
    <fullName>Payment_ref__c</fullName>
    <description>Should start with &apos;cash&apos; for cash, &apos;ck&apos; for check, &apos;of&apos; for official check, or &apos;mt&apos; for Western Union. All other codes should be used for wire transfers with different numbering conventions depending on the bank.</description>
    <inlineHelpText>Should start with &apos;cash&apos; for cash, &apos;ck&apos; for check, &apos;of&apos; for official check, or &apos;mt&apos; for Western Union. All other codes should be used for wire transfers with different numbering conventions depending on the bank.</inlineHelpText>
    <label>Payment ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/Advisor_Term__c.object-meta.xml
<CustomObject>
    <description>Represents a term of an official GFW advisor</description>
    <label>Advisor Term</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Advisor Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisor Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Advisor_Payment__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The advisor payment linked to this letter</description>
    <inlineHelpText>The advisor payment linked to this letter</inlineHelpText>
    <label>Advisor Payment</label>
    <referenceTo>Advisor_Payment__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Advisor_Term__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advisor term to which this letter is linked</description>
    <inlineHelpText>Advisor term to which this letter is linked</inlineHelpText>
    <label>Advisor Term</label>
    <referenceTo>Advisor_Term__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Source_object__c.field-meta.xml
<CustomField>
    <fullName>Source_object__c</fullName>
    <description>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</description>
    <inlineHelpText>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</inlineHelpText>
    <label>Source object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>GM_Data__c</fullName>
            </value>
            <value>
                <fullName>Milestone__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Payment__c</fullName>
            </value>
            <value>
                <fullName>Payment_Method__c</fullName>
            </value>
            <value>
                <fullName>Profile__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdvisorPaymentControllerTest.cls
@isTest
public class AdvisorPaymentControllerTest {
    static testmethod void AdvisorPaymentControllerTest1 () {
        // Build new advisors and accounts and advisor terms.
        AdvisorControllerTest.InitTestObjects(1, 1);
        Advisor_Term__c at = [SELECT Id FROM Advisor_Term__c LIMIT 1];
        Date d = System.today();
        insert new Advisor_Payment__c (Advisor_Term__c = at.Id, Amount_paid__c=0, Date_paid_accounting__c=d, Payment_ref__c='Cash');
        Map<Id, Advisor_Payment__c> apMap = new Map<Id, Advisor_Payment__c> ([SELECT Id FROM Advisor_Payment__c]);
        // Build new standard set controller and select the new advisor terms.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(apMap.values());
        ssc.setSelected(apMap.values());
        
        Test.StartTest();
        // Build a new advisor payment controller and use it to build new letters for the selected advisor payments.
        Template__c temp = new Template__c (Name = 'Test template', Source_object__c = 'Advisor_Payment__c');
        insert temp;
        AdvisorPaymentController pc = new AdvisorPaymentController (ssc);
        pc.selectedTemplate = temp.Id;
        system.assertNotEquals(pc.selectedTemplate, null);
        pc.buildLetters();
        Test.StopTest();
        
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c> ([SELECT Id FROM Letter__c]);
        AdvisorControllerTest.validate(lMap.keySet());
    }
    
    static testmethod void AdvisorPaymentControllerTest2 () {
        // Build new advisors and accounts and advisor terms.
        AdvisorControllerTest.InitTestObjects(1, 1);
        Advisor_Term__c at = [SELECT Id FROM Advisor_Term__c LIMIT 1];
        Date d = System.today();
        insert new Advisor_Payment__c (Advisor_Term__c = at.Id, Amount_paid__c=0, Date_paid_accounting__c=d, Payment_ref__c='Cash');
        Map<Id, Advisor_Payment__c> apMap = new Map<Id, Advisor_Payment__c> ([SELECT Id FROM Advisor_Payment__c]);
        // Build new standard controller.
        ApexPages.StandardController sc = new ApexPages.StandardController(apMap.values()[0]);
        
        Test.StartTest();
        // Build a new advisor payment controller and use it to build new letter.
        Template__c temp = new Template__c (Name = 'Test template', Source_object__c = 'Advisor_Payment__c');
        insert temp;

        AdvisorPaymentController pc = new AdvisorPaymentController (sc);
        pc.selectedTemplate = temp.Id;
        system.assertNotEquals(pc.selectedTemplate, null);
        pc.buildLetters();
        Test.StopTest();
        
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c> ([SELECT Id FROM Letter__c]);
        AdvisorControllerTest.validate(lMap.keySet());
    }
}