force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Classification_Category__c.field-meta.xml
<CustomField>
    <fullName>Classification_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This classification&apos;s category</description>
    <inlineHelpText>This classification&apos;s category</inlineHelpText>
    <label>Classification Category</label>
    <referenceTo>Classification_Category__c</referenceTo>
    <relationshipLabel>Classifications</relationshipLabel>
    <relationshipName>Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Classification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this classification: Population, Strategy, or Issue</description>
    <inlineHelpText>Type of this classification: Population, Strategy, or Issue</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Population</fullName>
            </value>
            <value>
                <fullName>Strategy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification_Category__c/Classification_Category__c.object-meta.xml
<CustomObject>
    <description>Represents a category of classifications within a type, for example, Increasing Access to Education for the Issue type</description>
    <label>Classification Category</label>
    <nameField>
        <label>Classification Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this classification category: Population, Strategy, or Issue</description>
    <inlineHelpText>Type of this classification category: Population, Strategy, or Issue</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Population</fullName>
            </value>
            <value>
                <fullName>Strategy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/Classification_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single classification to a profile</description>
    <label>Classification-Profile Assign</label>
    <nameField>
        <displayFormat>CA-Prof-{00000}</displayFormat>
        <label>Classification-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification linked from this join record</description>
    <inlineHelpText>The classification linked from this join record</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProfileClassificationsInvocableTest.cls
@isTest
public with sharing class ProfileClassificationsInvocableTest {
    static testMethod void ProfileClassificationsInvocableTest() {
        // Build new records
        insert new Profile__c();
        Profile__c p = [SELECT Id FROM Profile__c LIMIT 1];
        Id pId = p.Id;
        insert new Classification_Category__c(Name = 'Age');
        Id ccId = [SELECT Id FROM Classification_Category__c LIMIT 1].Id;
        insert new Classification__c(
            Name = 'Girls',
            Type__c = 'Population',
            Classification_Category__c = ccId
        );
        Id cId = [SELECT Id FROM Classification__c LIMIT 1].Id;
        insert new Classification_Profile_Assign__c(
            Profile__c = pId,
            Classification__c = cId
        );
        insert new Classification__c(
            Name = 'Adult men',
            Type__c = 'Population',
            Classification_Category__c = ccId
        );

        Test.StartTest();
        // Update profile to have two joins.
        ProfileClassificationsInvocable.UpdateClassificationsRequest req = new ProfileClassificationsInvocable.UpdateClassificationsRequest();
        req.categoryName = 'Age';
        req.classificationType = 'Population';
        req.profileId = pId;
        req.selectedNames = 'Girls||AdultMen';
        ProfileClassificationsInvocable.updateProfileClassifications(
            new List<ProfileClassificationsInvocable.UpdateClassificationsRequest>{
                req
            }
        );
        Integer numJoins = [
            SELECT COUNT()
            FROM Classification_Profile_Assign__c
            WHERE Profile__c = :pId
        ];
        system.assertEquals(2, numJoins);
        // Update profile to have no joins.
        req.selectedNames = '||';
        ProfileClassificationsInvocable.handleRequest(req);
        numJoins = [
            SELECT COUNT()
            FROM Classification_Profile_Assign__c
            WHERE Profile__c = :pId
        ];
        system.assertEquals(0, numJoins);
        // Generate an error with bad classification type.
        req.classificationType = 'BADTYPE';
        req.selectedNames = 'Girls';
        try {
            ProfileClassificationsInvocable.handleRequest(req);
        } catch (exception myException) {
        }
        // Generate an error with unknown classification.
        req.classificationType = 'Population';
        req.selectedNames = 'BADCLASSIFICATION';
        try {
            ProfileClassificationsInvocable.handleRequest(req);
        } catch (exception myException) {
        }
        Test.StopTest();
    }
}