force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this classification is in active use and may be assigned to profiles and proposals.</description>
    <inlineHelpText>If checked, this classification is in active use and may be assigned to profiles and proposals.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/Classification_Assign__c.object-meta.xml
<CustomObject>
    <description>Assignment of a single classification to a proposal</description>
    <label>Classification Assign</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Classification Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Assign__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal to which the classification is assigned</description>
    <inlineHelpText>The proposal to which the classification is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Reqs__c/Custom_Reqs__c.object-meta.xml
<CustomObject>
    <description>Represents the custom requirements imposed by restricted funds that apply to the linked proposals</description>
    <label>Custom Reqs</label>
    <nameField>
        <label>Custom Reqs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Reqs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Reqs__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this reporting reqs record is active</description>
    <inlineHelpText>Checked if this reporting reqs record is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Top level in a hierarchically structured HTML form for online submissions</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this form record is active</description>
    <inlineHelpText>Checked if this form record is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Instance__c/Form_Instance__c.object-meta.xml
<CustomObject>
    <description>This &quot;join&quot; object connects an application/profile with a form that has been opened and possibly completed</description>
    <label>Form Instance</label>
    <nameField>
        <displayFormat>FI-{000000}</displayFormat>
        <label>Form Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Instance__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The form for this form instance</description>
    <inlineHelpText>The form for this form instance</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Instances</relationshipLabel>
    <relationshipName>Application_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Instance__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal record (if any) linked to this form instance</description>
    <inlineHelpText>The proposal record (if any) linked to this form instance</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Form Instances</relationshipLabel>
    <relationshipName>Form_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GM_Data__c/GM_Data__c.object-meta.xml
<CustomObject>
    <description>Contains grant-related data and indicators stemming from the group&apos;s grant application and their milestones</description>
    <label>GM Data</label>
    <nameField>
        <displayFormat>GMD-{0000000}</displayFormat>
        <label>GM Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GM Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GM_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account linked to this GM data</description>
    <inlineHelpText>The account linked to this GM data</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GM_Data__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this GM data</description>
    <inlineHelpText>The proposal linked to this GM data</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this letter</description>
    <inlineHelpText>The proposal linked to this letter</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Represents a milestone (report, payment, site visit, etc.) due or received for this grant</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal (grant) to which this milestone belongs</description>
    <inlineHelpText>The proposal (grant) to which this milestone belongs</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this portfolio is in active use</description>
    <inlineHelpText>Checked if this portfolio is in active use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Portfolio_Assignment__c/Portfolio_Assignment__c.object-meta.xml
<CustomObject>
    <description>An assignment of one proposal to one portfolio</description>
    <label>Portfolio Assignment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Portfolio Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Assignment__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>Proposal to which this &quot;join&quot; assignment record is assigned</description>
    <inlineHelpText>Proposal to which this &quot;join&quot; assignment record is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Portfolio Assignments</relationshipLabel>
    <relationshipName>Initiative_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account of the org responsible for this profile</description>
    <inlineHelpText>The account of the org responsible for this profile</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review_Form__c/Review_Form__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of components for field entry, used in review interfaces to populate fields in specified objects in the database.</description>
    <label>Review Form</label>
    <nameField>
        <label>Review Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Form__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this review form is in active use</description>
    <inlineHelpText>Checked if this review form is in active use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProposalControllerTest.cls
@isTest
public class ProposalControllerTest {
    /**********************************
     * Test the component/Experience-related methods
     * *******************************/

    static testMethod void ProposalSummaryTest() {
        Date tday = Date.today();
        BuildTestProposals.InitTestObjects(1, 1);
        Proposal__c p = [SELECT Id, Account__c FROM Proposal__c LIMIT 1];
        Form__c testForm = new Form__c(
            Name='Test',
            Active__c = true,
            Type__c = 'Application'
        );
        insert testForm;
        insert new Form_Instance__c(
            Form__c = testForm.Id,
            Proposal__c = p.Id,
            Language__c = 'English'
        );
        Template__c template = new Template__c(
            Name='Test',
            Active__c = true,
            Type__c = 'Grantmaking',
            Source_object__c = 'Proposal__c'
        );
        insert template;
        insert new Letter__c(
            Template__c = template.Id,
            Account__c = p.Account__c,
            Proposal__c = p.Id,
            Date_emailed__c = tday-2
        );

        Test.StartTest();
        ProposalController.ProposalSummary pSummary = ProposalController.ProposalSummary(
            p.Id
        );
        Test.StopTest();

        List<Letter__c> let = new List<Letter__c>([SELECT Id FROM Letter__c WHERE Proposal__c = :p.Id AND Date_sent__c<>null]);
        List<Form_Instance__c> fmInst = new List<Form_Instance__c>([SELECT Id FROM Form_Instance__c WHERE Proposal__c = :p.Id]);

        System.assertEquals(let.size(), pSummary.letterList.size());
        System.assertEquals(fmInst.size(), pSummary.formInstanceList.size());
    }

    static testMethod void ProposalControllerTest() {
        // Build new records
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'test account',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Account a = [SELECT Id FROM Account LIMIT 1];
        insert new Review_Form__c(Name = 'test proposal review form');
        Review_Form__c rf = [SELECT Id FROM Review_Form__c LIMIT 1];
        insert new Review_Form_Component__c(
            Review_Form__c = rf.Id,
            Lightning_component_name__c = 'InputCheckbox',
            Sort_number__c = 1
        );
        insert new Custom_Reqs__c(
            Name = 'test custom reqs',
            Proposal_review_form__c = rf.Id
        );
        Custom_Reqs__c cr = [SELECT Id FROM Custom_Reqs__c LIMIT 1];
        insert new Profile__c();
        Profile__c pr = [SELECT Id FROM Profile__c LIMIT 1];
        insert new Proposal__c(
            Account__c = a.Id,
            Profile__c = pr.Id,
            Custom_Reqs__c = cr.Id
        );
        Proposal__c p = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new Classification__c(
            Name = 'Test Population',
            Type__c = 'Population'
        );
        Classification__c cp = [
            SELECT Id
            FROM Classification__c
            WHERE Type__c = 'Population'
            LIMIT 1
        ];
        insert new Classification__c(
            Name = 'Test Strategy',
            Type__c = 'Strategy'
        );
        Classification__c cs = [
            SELECT Id
            FROM Classification__c
            WHERE Type__c = 'Strategy'
            LIMIT 1
        ];
        insert new Classification__c(Name = 'Test Issue 1', Type__c = 'Issue');
        Classification__c ci1 = [
            SELECT Id
            FROM Classification__c
            WHERE Name = 'Test Issue 1'
            LIMIT 1
        ];
        insert new Classification__c(Name = 'Test Issue 2', Type__c = 'Issue');
        Classification__c ci2 = [
            SELECT Id
            FROM Classification__c
            WHERE Name = 'Test Issue 2'
            LIMIT 1
        ];
        insert new Classification_Assign__c(
            Proposal__c = p.Id,
            Classification__c = cs.Id
        );
        insert new Classification_Profile_Assign__c(
            Profile__c = pr.Id,
            Classification__c = cs.Id
        );
        insert new Classification_Profile_Assign__c(
            Profile__c = pr.Id,
            Classification__c = ci1.Id
        );
        insert new Classification_Profile_Assign__c(
            Profile__c = pr.Id,
            Classification__c = ci2.Id
        );
        insert new Portfolio__c(Name = 'Test portfolio', Type__c = 'Priority');
        Id portId = [SELECT Id FROM Portfolio__c LIMIT 1].Id;
        insert new Portfolio_Assignment__c(
            Proposal__c = p.Id,
            Portfolio__c = portId
        );

        Test.StartTest();
        //system.assertEquals((String)d.Id, fis.gmDataId);
        ProposalController.ProposalInfo pInfo = ProposalController.getProposalInfo(
            p.Id
        );
        ProposalController.getClassificationInfo('Issue', p.Id);
        GM_Data__c d = [SELECT Id FROM GM_Data__c WHERE Proposal__c = :p.Id];
        ProposalController.saveProposalInfo1(
            p,
            d,
            String.valueOf(cp.Id),
            String.valueOf(cs.Id),
            String.valueOf(ci1.Id),
            String.valueOf(portId)
        );
        Test.StopTest();

        // Copy classification assigns from profile, check that we don't duplicate the ones that proposal already has.
        ProposalController.copyClassificationAssignsFromProfile(p.Id, pr.Id);
        Classification_Assign__c[] propClassAssigns = [
            SELECT Id
            FROM Classification_Assign__c
        ];
        Classification_Profile_Assign__c[] profClassAssigns = [
            SELECT Id
            FROM Classification_Profile_Assign__c
        ];
        system.assertEquals(3, profClassAssigns.size());
        system.assertEquals(4, propClassAssigns.size());
    }

    /**********************************
     * Test the VF-related methods
     * *******************************/

    static testMethod void ProposalControllerTest1() {
        // Build new proposals and accounts
        BuildTestProposals.InitTestObjects(2, 2);
        Map<Id, Proposal__c> pMap = new Map<Id, Proposal__c>(
            [SELECT Id FROM Proposal__c]
        );
        // Build new standard set controller and select the new proposals.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            pMap.values()
        );
        ssc.setSelected(pMap.values());

        Test.StartTest();
        // Build a new proposal controller and use it to build new letters for the selected proposals.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'Proposal__c'
        ));
        ProposalController pc = new ProposalController(ssc);
        pc.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', pc.selectedTemplate),
            null
        );
        pc.buildLetters();
        Test.StopTest();

        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );
        validate(lMap.keySet());
    }

    static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [
                SELECT Account__c, Emails__c, Proposal__c
                FROM Letter__c
                WHERE Id IN :lIds
            ]
        );
        Map<Id, Proposal__c> pMap = new Map<Id, Proposal__c>(
            [
                SELECT Id
                FROM Proposal__c
                WHERE
                    Id IN (SELECT Proposal__c FROM Letter__c WHERE Id IN :lIds)
            ]
        );
        // Should be a different letter for each proposal.
        system.assertEquals(lMap.size(), pMap.size());
        // Gather email addresses for the accounts of these proposals.
        Map<Id, Account> aMap = new Map<Id, Account>(
            [
                SELECT Id
                FROM Account
                WHERE
                    Id IN (
                        SELECT Account__c
                        FROM Proposal__c
                        WHERE Id IN :pMap.keySet()
                    )
            ]
        );
        Map<Id, List<String>> emailMap = AccountController.emailsForAccounts(
            aMap.keySet()
        );
        // The emails stored on the letter need to agree with the account's emails.
        for (Letter__c l : lMap.values()) {
            system.assertEquals(
                l.Emails__c,
                String.join(emailMap.get(l.Account__c), ',')
            );
        }
    }

    static testMethod void ProposalControllerTest2() {
        // Build 1 new proposal/account
        BuildTestProposals.InitTestObjects(1, 1);
        Proposal__c prop = [SELECT Id FROM Proposal__c LIMIT 1];
        Test.StartTest();
        String templateName = 'Test template';
        insert (new Template__c(
            Name = templateName,
            Source_object__c = 'Milestone__c'
        ));
        Template__c template = [
            SELECT Id
            FROM Template__c
            WHERE Name = :templateName
            LIMIT 1
        ];
        // Use invocable class to build and email letter.
        ProposalEmailLetterInvocable.EmailLetterRequest req = new ProposalEmailLetterInvocable.EmailLetterRequest();
        req.propId = prop.Id;
        req.templateId = template.Id;
        ProposalEmailLetterInvocable.buildAndEmailLetter(
            new List<ProposalEmailLetterInvocable.EmailLetterRequest>{ req }
        );
        Test.StopTest();
    }

    // Test batch OFAC search.
    static testMethod void ProposalControllerTest4() {
        // Set mock callout class and build custom settings for OFAC lookup test.
        Test.setMock(HttpCalloutMock.class, new OFACLookupMock());
        OFACLookupTest.buildCustomSettings();
        // Build new proposals and accounts
        BuildTestProposals.InitTestObjects(1, 1);
        Map<Id, Proposal__c> pMap = new Map<Id, Proposal__c>(
            [SELECT Id FROM Proposal__c]
        );
        // Build new standard set controller and select the new proposals.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            pMap.values()
        );
        ssc.setSelected(pMap.values());

        Test.StartTest();
        // Build a new proposal controller.
        ProposalController pc = new ProposalController(ssc);
        pc.performOFACLookupBatch(); // Do OFAC lookup for each proposal.
        Test.StopTest();
    }

    // Test the BuildSubmissions code (similar to BuildLetters).
    static testMethod void ProposalControllerTest5() {
        // Build new proposals and accounts
        BuildTestProposals.InitTestObjects(2, 2);
        Map<Id, Proposal__c> pMap = new Map<Id, Proposal__c>(
            [SELECT Id FROM Proposal__c]
        );
        // Build new standard set controller and select the new proposals.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            pMap.values()
        );
        ssc.setSelected(pMap.values());

        Test.StartTest();
        // Build a new proposal controller and use it to build submissions for the selected proposals.
        ProposalController pc = new ProposalController(ssc);
        pc.buildSubmissions();
        Test.StopTest();

        system.debug(
            'ProposalControllerTest5: pc.submissions = ' + pc.submissions
        );
    }


}