force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Assign__c/Classification_Assign__c.object-meta.xml
<CustomObject>
    <description>Assignment of a single classification to a proposal</description>
    <label>Classification Assign</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Classification Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification assigned to the proposal</description>
    <inlineHelpText>The classification assigned to the proposal</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal to which the classification is assigned</description>
    <inlineHelpText>The proposal to which the classification is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>The rank (or primacy) of this classification for this proposal.  1 is considered highest.</description>
    <inlineHelpText>The rank (or primacy) of this classification for this proposal.  1 is considered highest.</inlineHelpText>
    <label>Rank</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/Classification_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single classification to a profile</description>
    <label>Classification-Profile Assign</label>
    <nameField>
        <displayFormat>CA-Prof-{00000}</displayFormat>
        <label>Classification-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification linked from this join record</description>
    <inlineHelpText>The classification linked from this join record</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>The rank (or primacy) of this classification for this profile. 1 is considered highest.</description>
    <inlineHelpText>The rank (or primacy) of this classification for this profile. 1 is considered highest.</inlineHelpText>
    <label>Rank</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this proposal is linked</description>
    <inlineHelpText>The profile to which this proposal is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProfileClassificationsCloneInvocable.cls
public with sharing class ProfileClassificationsCloneInvocable {
    public with sharing class myException extends Exception {
    }

    @InvocableMethod(
        label='Clone profile classifications for proposal'
        description='Clone the classification assigns of a profile and assign as join records to the given proposal'
    )
    public static void cloneProfileClassifications(
        List<CloneClassificationsRequest> requests
    ) {
        for (CloneClassificationsRequest request : requests) {
            handleRequest(request);
        }
    }

    // Gather classification joins for the profile, and build assignments for the proposal.
    public static void handleRequest(CloneClassificationsRequest request) {
        system.debug('handleRequest: request = ' + JSON.serialize(request));
        // Get all classifications assigned to profile.
        List<Classification_Profile_Assign__c> joins = new List<Classification_Profile_Assign__c>(
            [
                SELECT Id, Classification__c, Rank__c
                FROM Classification_Profile_Assign__c
                WHERE Profile__c = :request.profileId
            ]
        );
        // Build new classification joins for the proposal.
        List<Classification_Assign__c> newJoins = new List<Classification_Assign__c>();
        for (Classification_Profile_Assign__c j : joins) {
            newJoins.add(
                new Classification_Assign__c(
                    Classification__c = j.Classification__c,
                    Proposal__c = request.proposalId,
                    Rank__c = j.Rank__c
                )
            );
        }
        if (newJoins.size() > 0)
            insert newJoins;
    }

    public with sharing class CloneClassificationsRequest {
        @InvocableVariable(required=true)
        public ID profileId;
        @InvocableVariable(required=true)
        public ID proposalId;
    }
}