force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Definition__c.field-meta.xml
<CustomField>
    <fullName>Definition__c</fullName>
    <description>Definition of this classification</description>
    <inlineHelpText>Definition of this classification</inlineHelpText>
    <label>Definition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Classification__c/fields/Name_with_prefix__c.field-meta.xml
<CustomField>
    <fullName>Name_with_prefix__c</fullName>
    <description>Classification name preceded by the initials of its category</description>
    <formula>Classification_Category__r.Initials__c &amp; &quot; &quot; &amp;  Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Classification name preceded by the initials of its category</inlineHelpText>
    <label>Name with prefix</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this classification: Population, Strategy, or Issue</description>
    <inlineHelpText>Type of this classification: Population, Strategy, or Issue</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Population</fullName>
            </value>
            <value>
                <fullName>Strategy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/Classification_Assign__c.object-meta.xml
<CustomObject>
    <description>Assignment of a single classification to a proposal</description>
    <label>Classification Assign</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Classification Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification assigned to the proposal</description>
    <inlineHelpText>The classification assigned to the proposal</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal to which the classification is assigned</description>
    <inlineHelpText>The proposal to which the classification is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Prop_num_with_renewal__c.field-meta.xml
<CustomField>
    <fullName>Prop_num_with_renewal__c</fullName>
    <description>This is the proposal code used to identify the proposal/grant</description>
    <formula>/* 
Format is last two digits of date received/created along with ID and &quot;R&quot; if a renewal,
for example, 15-12345R
*/

RIGHT(
 TEXT(
  YEAR(
   IF(NOT(ISBLANK ( Date_received__c )), Date_received__c,
     DATEVALUE(CreatedDate)
    )
  )
 ), 2
) &amp;
&quot;-&quot; &amp;
Name &amp;
IF(Is_renewal__c, &quot;R&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is the proposal code used to identify the proposal/grant</inlineHelpText>
    <label>Prop num with renewal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProposalControllerClassifications.cls
public with sharing class ProposalControllerClassifications {
    private ApexPages.StandardController standardController;

    public ProposalControllerClassifications(
        ApexPages.StandardController standardController
    ) {
        this.standardController = standardController;
    }

    public Proposal__c prop;
    public Proposal__c getProp() {
        return [
            SELECT Prop_num_with_renewal__c, Account__r.Name
            FROM Proposal__c
            WHERE Id = :standardController.getId()
        ];
    }
    // Selected IDs are mapped to a hidden input field on the page, and set by jquery.
    public String selectedIds { get; set; }

    // Wrapper class to prevent security breaches when injecting the HTML for the checkbox tags.
    // Source: http://www.laceysnr.com/2012/11/checkboxes-and-columns-line-em-up.html
    @TestVisible
    private class CCheckbox {
        public String label { get; set; }
        public String HTML { get; private set; }

        public CCheckbox(
            String label,
            String value,
            String title,
            Boolean isChecked
        ) {
            this.label = label;
            this.HTML =
                '<input type="checkbox" class="cboxChoice" onClick="saveValues();" id="' +
                value +
                '" title="' +
                title +
                '" ' +
                (isChecked ? 'checked' : '') +
                '/>';
        }
    }

    // Build three lists of checkboxes for admissible classifications.
    public List<CCheckbox> populations, strategies, issues;
    public List<CCheckbox> getPopulations() {
        return buildCheckboxes('Population');
    }
    public List<CCheckbox> getStrategies() {
        return buildCheckboxes('Strategy');
    }
    public List<CCheckbox> getIssues() {
        return buildCheckboxes('Issue');
    }

    // Build HTML for classification checkboxes, including IsChecked for the ones
    // currently assigned to given proposal.
    private List<CCheckbox> buildCheckboxes(String cType) {
        Id propId = standardController.getId();
        system.debug(
            'In buildCheckboxes: cType = ' +
            cType +
            '; propId = ' +
            propId
        );
        // Fetch classifications of given type
        List<Classification__c> cs = new List<Classification__c>(
            [
                SELECT Name_with_prefix__c, Definition__c
                FROM Classification__c
                WHERE Type__c = :cType
                ORDER BY Name_with_prefix__c
            ]
        );
        // Fetch classifications that have been assigned to this proposal.
        Map<Id, Classification__c> assigned = new Map<Id, Classification__c>(
            [
                SELECT Id
                FROM Classification__c
                WHERE
                    Id IN (
                        SELECT Classification__c
                        FROM Classification_Assign__c
                        WHERE Proposal__c = :propId
                    )
                    AND Type__c = :cType
            ]
        );
        system.debug(
            'In buildCheckboxes: cs.size() = ' +
            cs.size() +
            '; assigned.size() = ' +
            assigned.size()
        );
        // Stash list of initially selected IDs.
        //selectedIds = String.join(new List<Id> (assigned.keySet()), ';');
        // Build HTML for checkboxes.
        List<CCheckbox> checkboxes = new List<CCheckbox>();
        for (Classification__c c : cs)
            checkboxes.add(
                new CCheckbox(
                    c.Name_with_prefix__c,
                    c.Id,
                    c.Definition__c,
                    assigned.containsKey(c.Id)
                )
            );
        return checkboxes;
    }

    // Get selected classifications, then insert/delete join records to match.
    public void saveChanges() {
        Id propId = standardController.getId();
        // Get current classification assignments.
        Map<Id, Classification_Assign__c> assigned = new Map<Id, Classification_Assign__c>(
            [
                SELECT Id, Classification__c
                FROM Classification_Assign__c
                WHERE Proposal__c = :propId
            ]
        );
        system.debug('In doSave: assigned = ' + JSON.serialize(assigned));
        // Get selected classifications from VF hidden input field.
        Set<String> setIds = new Set<String>(selectedIds.split(';', 0));
        system.debug(
            'In doSave: selectedIds = ' +
            selectedIds +
            '; setIds = ' +
            JSON.serialize(setIds)
        );
        // Build list of classifications to delete - they were assigned, but are no longer selected.
        List<Classification_Assign__c> toDelete = new List<Classification_Assign__c>();
        for (Classification_Assign__c ca : assigned.values()) {
            if (!setIds.contains(String.valueof(ca.Classification__c)))
                toDelete.add(ca);
        }
        system.debug('In doSave: toDelete = ' + JSON.serialize(toDelete));
        // Build list of classifications to insert - they weren't originally assigned, but are now selected.
        List<Classification_Assign__c> toInsert = new List<Classification_Assign__c>();
        for (String s : setIds) {
            if (String.isBlank(s))
                continue;
            Id i = Id.valueOf(s);
            if (!assigned.containsKey(i))
                toInsert.add(
                    new Classification_Assign__c(
                        Classification__c = i,
                        Proposal__c = propId
                    )
                );
        }
        system.debug('In doSave: toInsert = ' + JSON.serialize(toInsert));
        if (toDelete.size() > 0)
            delete toDelete;
        if (toInsert.size() > 0)
            insert toInsert;
    }

    // Save and return from this page.
    public PageReference doSave() {
        saveChanges();
        return standardController.cancel();
    }

    // Save and stay on this page.
    public PageReference doQuickSave() {
        saveChanges();
        return null;
    }
}