force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this classification is in active use and may be assigned to profiles and proposals.</description>
    <inlineHelpText>If checked, this classification is in active use and may be assigned to profiles and proposals.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Classification__c/fields/Name_with_prefix__c.field-meta.xml
<CustomField>
    <fullName>Name_with_prefix__c</fullName>
    <description>Classification name preceded by the initials of its category</description>
    <formula>Classification_Category__r.Initials__c &amp; &quot; &quot; &amp;  Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Classification name preceded by the initials of its category</inlineHelpText>
    <label>Name with prefix</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this classification: Population, Strategy, or Issue</description>
    <inlineHelpText>Type of this classification: Population, Strategy, or Issue</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Population</fullName>
            </value>
            <value>
                <fullName>Strategy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/Classification_Assign__c.object-meta.xml
<CustomObject>
    <description>Assignment of a single classification to a proposal</description>
    <label>Classification Assign</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Classification Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification assigned to the proposal</description>
    <inlineHelpText>The classification assigned to the proposal</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal to which the classification is assigned</description>
    <inlineHelpText>The proposal to which the classification is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/Classification_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single classification to a profile</description>
    <label>Classification-Profile Assign</label>
    <nameField>
        <displayFormat>CA-Prof-{00000}</displayFormat>
        <label>Classification-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification linked from this join record</description>
    <inlineHelpText>The classification linked from this join record</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this proposal is linked</description>
    <inlineHelpText>The profile to which this proposal is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClassificationController.cls
public class ClassificationController {

    public static Map<string, string> objNameToAssignObjName = new Map<string, string> {
        'Proposal__c' => 'Classification_Assign__c',
        'Profile__c' => 'Classification_Profile_Assign__c'
    };
    
    // Update the classification assigns for an appropriate record (say, Profile or Proposal).
    // Create/delete joins to align with given selected classification ids.
    // Two shapes depending on whether we're called with classification names or ids.
    // Note that if classIds list is empty, the current classification assignments for the record are deleted.
    public static void updateClassificationAssigns (Id recId, String classType, String[] classNames) {
        Map<Id, Classification__c> cMap = new Map<Id, Classification__c> ([
            SELECT Name, Name_with_prefix__c
            FROM Classification__c
            WHERE Type__c = : classType
            AND Active__c = true
            AND (Name IN : classNames OR Name_with_prefix__c IN :classNames)
        ]);
        updateClassificationAssigns (recId, classType, new List<Id>(cMap.keySet()));
    }
    public static void updateClassificationAssigns (Id recId, String classType, Id[] classIds) {
        String objName = Utilities.objectNameFromRecordId(recId);
        String assignObjName = objNameToAssignObjName.get(objName);
        // Bail if record's object doesn't have classification assign join object.
        if (assignObjName == null) return;
        sObject[] toDelete = new List<sObject>();
        sObject[] toInsert = new List<sObject>();
        system.debug('updateClassificationAssigns: recId = ' +recId+ '; classType = ' +classType+ '; classIds = ' +classIds);
        // Get current assignments. Note that master/detail field is assumed to have same name as object. 
        String whereClause = 'WHERE ' +objName+ ' = \'' +recId+ '\'' +
            ' AND Classification__r.Type__c = \'' +classType+ '\'' +
            ' AND Classification__r.Active__c = true';
        Map<Id, sObject> cAssigns = new Map<Id, sObject> (Utilities.fetchRecords(assignObjName, whereClause, null));
        system.debug('In updateClassificationAssigns: cAssigns = ' + JSON.serialize(cAssigns));
        // Stash current classification ids.
        Set<Id> currClassIds = new Set<Id>();
        for (sObject ca : cAssigns.values()) currClassIds.add((Id)ca.get('Classification__c'));
        // Augment list of classifications to delete - they were assigned, but are no longer selected.
        for (sObject ca : cAssigns.values()) {
            if (!classIds.contains((Id)ca.get('Classification__c'))) toDelete.add(ca);
        }
        system.debug('In updateClassificationAssigns: toDelete = ' + JSON.serialize(toDelete));
        // Augment list of classifications to insert - they weren't originally assigned, but are now selected.
        for (Id cId : classIds) {
            if (!currClassIds.contains(cId)) {
                sObject cAssign = Utilities.newRecord(assignObjName);
                cAssign.put('Classification__c', cId);
                cAssign.put(objName, recId);
                toInsert.add(cAssign); 
            }
        }
        system.debug('In updateClassificationAssigns: toInsert = ' + JSON.serialize(toInsert));
        if (toDelete.size() > 0) delete toDelete;
        if (toInsert.size() > 0) insert toInsert;
    }
}