force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this classification is in active use and may be assigned to profiles and proposals.</description>
    <inlineHelpText>If checked, this classification is in active use and may be assigned to profiles and proposals.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periodic_touch_queries__c/Periodic_touch_queries__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Each record contains a query that returns a collection of records to be &quot;touched&quot; via scheduled apex.</description>
    <label>Periodic touch queries</label>
</CustomObject>

force-app/main/default/objects/Periodic_touch_queries__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, then the scheduler will touch the records returned by the query.</description>
    <inlineHelpText>If checked, then the scheduler will touch the records returned by the query.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periodic_touch_queries__c/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The batch size (number of records run at a time in a batch process) when touching the records</description>
    <inlineHelpText>The batch size (number of records run at a time in a batch process) when touching the records</inlineHelpText>
    <label>Batch size</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Periodic_touch_queries__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>The query returning records to be touched</description>
    <inlineHelpText>The query returning records to be touched</inlineHelpText>
    <label>Query</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TouchRecordsSchedulableTest.cls
@isTest
public class TouchRecordsSchedulableTest {
    static testMethod void TouchRecordsSchedulableTest() {
        // Build custom setting instance with dummy data.
        insert (new Classification__c(Name = 'test class'));
        insert (new Periodic_touch_queries__c(
            Name = 'ptq1',
            Active__c = true,
            Query__c = 'select Id from Classification__c',
            Batch_size__c = 1
        ));
        // The schedule time isn't actually used; it just runs after Test.StopTest().
        String CRON_EXP = '0 0 0 15 3 ?';
        Test.StartTest();
        String jobId = System.schedule(
            'Touch records',
            CRON_EXP,
            new TouchRecordsSchedulable()
        );
        Test.StopTest();
    }
}