force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs (if any) linked to the proposal/grant behind this letter</description>
    <inlineHelpText>The custom reqs (if any) linked to the proposal/grant behind this letter</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <description>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</description>
    <inlineHelpText>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</inlineHelpText>
    <label>Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The payment linked to this letter</description>
    <inlineHelpText>The payment linked to this letter</inlineHelpText>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this letter</description>
    <inlineHelpText>The proposal linked to this letter</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Represents a milestone (report, payment, site visit, etc.) due or received for this grant</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Date_due__c.field-meta.xml
<CustomField>
    <fullName>Date_due__c</fullName>
    <description>The date by which we should receive the milestone</description>
    <inlineHelpText>The date by which we should receive the milestone</inlineHelpText>
    <label>Date due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Milestone_Spec__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Spec__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The milestone spec part of the proposal&apos;s custom req, if any, that is linked to this milestone</description>
    <inlineHelpText>The milestone spec part of the proposal&apos;s custom req, if any, that is linked to this milestone</inlineHelpText>
    <label>Milestone Spec</label>
    <referenceTo>Milestone_Spec__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal (grant) to which this milestone belongs</description>
    <inlineHelpText>The proposal (grant) to which this milestone belongs</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of milestone</description>
    <inlineHelpText>The type of milestone</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/Milestone_Spec__c.object-meta.xml
<CustomObject>
    <description>Specification of a milestone including type, date due, etc.</description>
    <label>Milestone Spec</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Milestone Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Spec__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <description>The custom reporting reqs record for this milestone spec record</description>
    <inlineHelpText>The custom reporting reqs record for this milestone spec record</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Milestone Specs</relationshipLabel>
    <relationshipName>Milestone_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/fields/Date_due__c.field-meta.xml
<CustomField>
    <fullName>Date_due__c</fullName>
    <description>Due date for milestone
Note: Overrides Num months due</description>
    <inlineHelpText>Due date for milestone
Note: Overrides Num months due</inlineHelpText>
    <label>Date due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/fields/Fraction_of_amount_awarded__c.field-meta.xml
<CustomField>
    <fullName>Fraction_of_amount_awarded__c</fullName>
    <description>The fraction of the proposal&apos;s amount awarded to be paid according to this (payment) milestone spec</description>
    <inlineHelpText>The fraction of the proposal&apos;s amount awarded to be paid according to this (payment) milestone spec</inlineHelpText>
    <label>Fraction of amount awarded</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this milestone</description>
    <inlineHelpText>The type of this milestone</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Represents a payment made for a grant</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Date_paid__c.field-meta.xml
<CustomField>
    <fullName>Date_paid__c</fullName>
    <description>Date that the payment was processed by the bank (or Western Union, etc.)  May be different from Date paid accounting if payment was retried at a later date following a stall. 
Note: status dependent on this date</description>
    <inlineHelpText>Date that the payment was processed by the bank (or Western Union, etc.) May be different from Date paid accounting if payment was retried at a later date following a stall. 
Note: status dependent on this date</inlineHelpText>
    <label>Date paid</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal to which this payment belongs</description>
    <inlineHelpText>The proposal to which this payment belongs</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Amount_awarded__c.field-meta.xml
<CustomField>
    <fullName>Amount_awarded__c</fullName>
    <description>Actual amount awarded to the group (possibly over multiple payments)</description>
    <inlineHelpText>Actual amount awarded to the group (possibly over multiple payments)</inlineHelpText>
    <label>Amount awarded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs for this proposal (if any)</description>
    <inlineHelpText>The custom reqs for this proposal (if any)</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_awarded__c</fullName>
    <description>Date on which the proposal becomes a grant</description>
    <inlineHelpText>Date on which the proposal becomes a grant</inlineHelpText>
    <label>Date awarded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Source_object__c.field-meta.xml
<CustomField>
    <fullName>Source_object__c</fullName>
    <description>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</description>
    <inlineHelpText>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</inlineHelpText>
    <label>Source object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>GM_Data__c</fullName>
            </value>
            <value>
                <fullName>Milestone__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Payment__c</fullName>
            </value>
            <value>
                <fullName>Payment_Method__c</fullName>
            </value>
            <value>
                <fullName>Profile__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Milestone_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Report</fullName>
    </customValue>
    <customValue>
        <fullName>Report narrative</fullName>
    </customValue>
    <customValue>
        <fullName>Report financial</fullName>
    </customValue>
    <customValue>
        <fullName>Report activities</fullName>
    </customValue>
    <customValue>
        <fullName>Site visit</fullName>
    </customValue>
    <description>Milestone types</description>
    <masterLabel>Milestone type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentControllerTest.cls
@isTest
public class PaymentControllerTest {
    static testMethod void PaymentControllerTest1() {
        // Build new payments, proposals and accounts
        BuildTestProposals.InitTestObjects(1, 1);

        Test.StartTest();
        Proposal__c prop = [SELECT Id FROM Proposal__c LIMIT 1];
        // Push the proposal to award stage, and force creation of milestone.
        prop.Date_awarded__c = Date.today();
        update prop;
        MilestoneController.buildMilestones(prop.Id);
        Test.StopTest();

        insert new Payment__c(
            Proposal__c = prop.Id,
            Date_paid__c = Date.today()
        );
        buildLettersFUTURE(); // Build letters in future method to avoid too-many-soql errors in production.
        // NOTE: Uncomment validation call for testing in sandbox!  Commented out when deploying to production to avoid governor limits.
        /* 
Map<Id, Letter__c> lMap = new Map<Id, Letter__c> ([SELECT Id FROM Letter__c]);
validate(lMap.keySet());
*/
    }

    @future
    static void buildLettersFUTURE() {
        Map<Id, Payment__c> pMap = new Map<Id, Payment__c>(
            [SELECT Id FROM Payment__c]
        );
        // Build new standard set controller and select the new payments.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            pMap.values()
        );
        ssc.setSelected(pMap.values());
        // Build a new payment controller and use it to build new letters for the selected payments.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'Payment__c'
        ));
        PaymentController pc = new PaymentController(ssc);
        pc.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', pc.selectedTemplate),
            null
        );
        pc.buildLetters();
        // For code coverage, run again with standard controller and no selected template (forcing error).
        ApexPages.StandardController sc = new ApexPages.StandardController(
            pMap.values()[0]
        );
        pc = new PaymentController(sc);
        pc.selectedTemplate = null;
        pc.buildLetters();
    }

    static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [
                SELECT Account__c, Emails__c, Payment__c
                FROM Letter__c
                WHERE Id IN :lIds
            ]
        );
        Map<Id, Payment__c> pMap = new Map<Id, Payment__c>(
            [
                SELECT Id
                FROM Payment__c
                WHERE Id IN (SELECT Payment__c FROM Letter__c WHERE Id IN :lIds)
            ]
        );
        // Should be a different letter for each proposal.
        system.assertEquals(lMap.size(), pMap.size());
        // Gather email addresses for contacts under the accounts.
        Map<Id, Account> aMap = new Map<Id, Account>([SELECT Id FROM Account]);
        Map<Id, List<String>> emailMap = Utilities.emailsForAccounts(
            aMap.keySet()
        );
        // The emails stored on the letter need to agree with the account's emails.
        for (Letter__c l : lMap.values()) {
            system.assertEquals(
                l.Emails__c,
                String.join(emailMap.get(l.Account__c), ',')
            );
        }
    }

    // Test update of existing report milestone
    static testMethod void PaymentControllerTest2() {
        // Build template and macros for proposal status
        ProposalUpdateTest.buildTemplateMacros();
        // Build proposals and accounts
        BuildTestProposals.InitTestObjects(1, 1);
        insert new Custom_Reqs__c(Name = 'test reporting reqs');
        Id repReqsId = [SELECT Id FROM Custom_Reqs__c LIMIT 1].Id;
        insert new Milestone_Spec__c(
            Custom_Reqs__c = repReqsId,
            Date_due__c = Date.today().addDays(50),
            Fraction_of_amount_awarded__c = 1,
            Type__c = 'Payment'
        );
        insert new Milestone_Spec__c(
            Custom_Reqs__c = repReqsId,
            Date_due__c = Date.today().addDays(100),
            Type__c = 'Report'
        );

        Test.StartTest();
        Proposal__c prop = [
            SELECT Id, Current_payment_milestone__c
            FROM Proposal__c
            LIMIT 1
        ];
        // Push the proposal to award stage, and force creation of milestones.
        prop.Amount_awarded__c = 100;
        prop.Custom_reqs__c = repReqsId;
        update prop;
        // Have to update date awarded separately because of a validation rule on changes to amount/date awarded fields.
        prop.Date_awarded__c = Date.today();
        update prop;
        MilestoneController.buildMilestones(prop.Id);
        Test.StopTest();

        prop = [
            SELECT Id, Current_payment_milestone__c
            FROM Proposal__c
            LIMIT 1
        ];
        // Build payment.
        insert new Payment__c(
            Proposal__c = prop.Id,
            Date_paid__c = Date.today(),
            Amount_paid__c = 100,
            Milestone__c = prop.Current_payment_milestone__c
        );
        Payment__c payment = [
            SELECT Id, Milestone__c, Date_paid__c
            FROM Payment__c
            LIMIT 1
        ];
        ProposalUpdate.updateProposal(prop.Id, true); // Update prop status

        List<Milestone__c> ms = [
            SELECT Id, Date_of_first_payment_actual__c
            FROM Milestone__c
            ORDER BY Date_due__c
        ];
        system.assertEquals(2, ms.size());
        system.assertEquals(ms[0].Id, payment.Milestone__c);
        system.assertEquals(
            ms[0].Date_of_first_payment_actual__c,
            payment.Date_paid__c
        );
    }
}