force-app/main/default/objects/Periodic_touch_queries__c/Periodic_touch_queries__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Each record contains a query that returns a collection of records to be &quot;touched&quot; via scheduled apex.</description>
    <label>Periodic touch queries</label>
</CustomObject>

force-app/main/default/objects/Periodic_touch_queries__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, then the scheduler will touch the records returned by the query.</description>
    <inlineHelpText>If checked, then the scheduler will touch the records returned by the query.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periodic_touch_queries__c/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The batch size (number of records run at a time in a batch process) when touching the records</description>
    <inlineHelpText>The batch size (number of records run at a time in a batch process) when touching the records</inlineHelpText>
    <label>Batch size</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Periodic_touch_queries__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>The query returning records to be touched</description>
    <inlineHelpText>The query returning records to be touched</inlineHelpText>
    <label>Query</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TouchRecordsSchedulable.cls
/*
 * Touch collections of records determined by SOQL queries found in custom settings.
 * Run this on a regular basis, by using the Schedule button from the Setup/apex classes/ interface.
 */
global with sharing class TouchRecordsSchedulable implements Schedulable {
    global void execute(SchedulableContext scMain) {
        // Look for active queries to run from custom settings.
        // Note that the max length of a query is 255 characters.
        Map<String, Periodic_touch_queries__c> ptqs = Periodic_touch_queries__c.getAll();
        for (Periodic_touch_queries__c ptq : ptqs.values()) {
            if (ptq.Active__c) {
                Database.executeBatch(
                    new GenericTouchRecordsBatch(ptq.Query__c),
                    (Integer) ptq.Batch_size__c
                );
            }
        }
    }
}