force-app/main/default/objects/Form_Component__c/Form_Component__c.object-meta.xml
<CustomObject>
    <description>Component level in a hierarchically structured HTML form for online submissions</description>
    <label>Form Component</label>
    <nameField>
        <label>Form Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Component__c/fields/Form_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Form_Phrase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The (translatable) text phrase for this component</description>
    <inlineHelpText>The (translatable) text phrase for this component</inlineHelpText>
    <label>Form Phrase</label>
    <referenceTo>Form_Phrase__c</referenceTo>
    <relationshipLabel>Form Components</relationshipLabel>
    <relationshipName>Form_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Component__c/fields/Form_phrase_in_English__c.field-meta.xml
<CustomField>
    <fullName>Form_phrase_in_English__c</fullName>
    <description>The text of this component&apos;s form phrase in English</description>
    <inlineHelpText>The text of this component&apos;s form phrase in English</inlineHelpText>
    <label>Form phrase in English</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Phrase__c/Form_Phrase__c.object-meta.xml
<CustomObject>
    <description>Identifies a piece of text appearing one or more times in forms. The translations of that text, including English, are stored in a separate object.</description>
    <label>Form Phrase</label>
    <nameField>
        <label>Form Phrase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Phrases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Phrase__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this phrase is in active use in one or more forms</description>
    <inlineHelpText>Checked if this phrase is in active use in one or more forms</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Phrase__c/fields/Phrase_in_English__c.field-meta.xml
<CustomField>
    <fullName>Phrase_in_English__c</fullName>
    <description>The text of this phrase in English</description>
    <inlineHelpText>The text of this phrase in English</inlineHelpText>
    <label>Phrase in English</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Phrase__c/fields/Phrase_in_English_trimmed__c.field-meta.xml
<CustomField>
    <fullName>Phrase_in_English_trimmed__c</fullName>
    <description>First 255 characters of the &quot;Phrase in English&quot; field (auto-maintained)</description>
    <inlineHelpText>First 255 characters of the &quot;Phrase in English&quot; field (auto-maintained)</inlineHelpText>
    <label>Phrase in English (trimmed)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_Phrase_Translation__c/Form_Phrase_Translation__c.object-meta.xml
<CustomObject>
    <description>Translation of a phrase into a particular language</description>
    <label>Form Phrase Translation</label>
    <nameField>
        <displayFormat>PHRT-{0000}</displayFormat>
        <label>Form Phrase Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Phrase Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Phrase_Translation__c/fields/Form_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Form_Phrase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The phrase for which this is a translation</description>
    <inlineHelpText>The phrase for which this is a translation</inlineHelpText>
    <label>Form Phrase</label>
    <referenceTo>Form_Phrase__c</referenceTo>
    <relationshipLabel>Form Phrase Translations</relationshipLabel>
    <relationshipName>Form_Phrase_Translations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Phrase_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>The language of this phrase translation</description>
    <inlineHelpText>The language of this phrase translation</inlineHelpText>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Phrase_Translation__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>The text for this phrase in the given language</description>
    <inlineHelpText>The text for this phrase in the given language</inlineHelpText>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Phrase_Translation__c/fields/Text_in_English__c.field-meta.xml
<CustomField>
    <fullName>Text_in_English__c</fullName>
    <description>The text of this phrase in English</description>
    <inlineHelpText>The text of this phrase in English</inlineHelpText>
    <label>Text in English</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FormPhraseController.cls
public inherited sharing class FormPhraseController {

    /**********************************
    * For general use
    *********************************/
    
    // Update the phrase-in-English fields in form phrase, its form phrase translations, and referring form components.
    public static void updatePhraseInEnglish (Id phraseId) {
        // Fetch form phrase and its translations.
        Form_Phrase__c phr = [
            SELECT Phrase_in_English__c, Phrase_in_English_trimmed__c
            FROM Form_Phrase__c
            WHERE Id = : phraseId
        ];
        Form_Phrase_Translation__c[] trs = [
            SELECT Id, Language__c, Text__c, Text_in_English__c
            FROM Form_Phrase_Translation__c
            WHERE Form_Phrase__c = : phraseId            
        ];
        system.debug('updatePhraseInEnglish phr = ' +JSON.serialize(phr));
        system.debug('updatePhraseInEnglish trs = ' +JSON.serialize(trs));
        // Get the English text of the phrase if any.
        String textEng;
        for (Form_Phrase_Translation__c tr : trs) if (tr.Language__c == 'English') textEng = tr.Text__c;
        if (textEng == null) return; // Do nothing if there's no translation into English.
        String textEngTrimmed = textEng.left(255);
        // Update phrase and translations where necessary.
        if (phr.Phrase_in_English__c != textEng || phr.Phrase_in_English_trimmed__c != textEngTrimmed) {
            phr.Phrase_in_English__c = textEng;
            phr.Phrase_in_English_trimmed__c = textEngTrimmed;
            system.debug('updatePhraseInEnglish textEng = ' +textEng+ '; textEngTrimmed = ' +textEngTrimmed);
            update phr;
        }
        Form_Phrase_Translation__c[] trsToUpdate = new List<Form_Phrase_Translation__c> ();
        for (Form_Phrase_Translation__c tr : trs) {
            if (tr.Text_in_English__c != textEng) {
                tr.Text_in_English__c = textEng;
                trsToUpdate.add(tr);
            }
        }
        if (trsToUpdate.size() > 0) update trsToUpdate;
        // Check and update form components pointing to this phrase.
        Form_Component__c[] comps = [
            SELECT Form_phrase_in_English__c
            FROM Form_Component__c
            WHERE Form_Phrase__c = : phraseId
        ];
        Form_Component__c[] compsToUpdate = new List<Form_Component__c> ();
        for (Form_Component__c comp : comps) {
            if (comp.Form_phrase_in_English__c != textEng) {
                comp.Form_phrase_in_English__c = textEng;
                compsToUpdate.add(comp);
            }
        }
        if (compsToUpdate.size() > 0) update compsToUpdate;
    }

    // Form phrase translations for LWC 
    @AuraEnabled(cacheable=true)
    public static string getTranslations(){
        try {
            Form_Phrase_Translation__c[] translations = [
                SELECT Text__c, Text_in_English__c, Form_Phrase__c, Form_Phrase__r.Name, Language__c
                FROM Form_Phrase_Translation__c
                WHERE Form_Phrase__r.Active__c = true
            ];
            return JSON.serialize(translations);
        } catch (Exception e) {
            throw new GFW_Exception(e.getMessage());
        }
    }
    
}