force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account of the org responsible for this profile</description>
    <inlineHelpText>The account of the org responsible for this profile</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Date_declined__c.field-meta.xml
<CustomField>
    <fullName>Date_declined__c</fullName>
    <description>The date on which this profile was marked for definitive decline (ie. following internal review of initial decline decision).</description>
    <inlineHelpText>The date on which this profile was marked for definitive decline (ie. following internal review of initial decline decision).</inlineHelpText>
    <label>Date declined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Date_review_completed__c.field-meta.xml
<CustomField>
    <fullName>Date_review_completed__c</fullName>
    <description>The date on which profile review was completed</description>
    <inlineHelpText>The date on which profile review was completed</inlineHelpText>
    <label>Date review completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <description>Date on which this profile was submitted</description>
    <inlineHelpText>Date on which this profile was submitted</inlineHelpText>
    <label>Date submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this profile</description>
    <formula>IF ( NOT(ISBLANK(Date_declined__c)), &quot;0 Profile declined&quot;,
IF ( NOT(ISBLANK( Decline_reason__c )), &quot;2.9 Profile to decline&quot;,
IF ( AND(
      NOT(ISBLANK(Proposal_recent__c)), 
      NOT(ISBLANK(Date_review_completed__c))
   ), &quot;5 Proposal linked, Profile reviewed&quot;,
IF ( NOT(ISBLANK(Proposal_recent__c)), &quot;4.5 Proposal linked, Profile not reviewed&quot;,
IF ( AND(
      NOT(ISBLANK(Date_holdover_sent__c)), 
      NOT(ISBLANK(Date_review_completed__c))
   ), &quot;3.1 Holdover sent, Profile reviewed&quot;,
IF ( NOT(ISBLANK(Date_review_completed__c)), &quot;3 Profile reviewed&quot;,
IF ( AND(
      NOT(ISBLANK(Date_submitted__c)),
      NOT(ISBLANK(Date_holdover_sent__c))
   ), &quot;1.6 Holdover sent, Profile not reviewed&quot;,
IF ( NOT(ISBLANK(Date_submitted__c)), &quot;1.5 Profile submitted&quot;,
&quot;1 Profile pending&quot;
))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Status of this profile</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Status_external__c.field-meta.xml
<CustomField>
    <fullName>Status_external__c</fullName>
    <description>External status of this profile (the version that is viewed by applicant)</description>
    <formula>IF ( CONTAINS( LOWER(Status__c) , &quot;declined&quot; ), &quot;Declined&quot;,
IF ( NOT (ISBLANK ( Date_submitted__c )), &quot;Submitted&quot;,
&quot;Pending&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>External status of this profile (the version that is viewed by applicant)</inlineHelpText>
    <label>Status external</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/App_type__c.field-meta.xml
<CustomField>
    <fullName>App_type__c</fullName>
    <description>The type of application that led to this proposal</description>
    <inlineHelpText>The type of application that led to this proposal</inlineHelpText>
    <label>App type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Crisis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_awarded__c</fullName>
    <description>Date on which the proposal becomes a grant</description>
    <inlineHelpText>Date on which the proposal becomes a grant</inlineHelpText>
    <label>Date awarded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_declined__c.field-meta.xml
<CustomField>
    <fullName>Date_declined__c</fullName>
    <description>Date the proposal was declined</description>
    <inlineHelpText>Date the proposal was declined</inlineHelpText>
    <label>Date declined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_received__c.field-meta.xml
<CustomField>
    <fullName>Date_received__c</fullName>
    <description>Date the proposal arrives</description>
    <inlineHelpText>Date the proposal arrives</inlineHelpText>
    <label>Date received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_review_completed__c.field-meta.xml
<CustomField>
    <fullName>Date_review_completed__c</fullName>
    <description>Date on which this proposal&apos;s review was completed</description>
    <inlineHelpText>Date on which this proposal&apos;s review was completed</inlineHelpText>
    <label>Date review completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Grant_type__c.field-meta.xml
<CustomField>
    <fullName>Grant_type__c</fullName>
    <description>The type of this grant</description>
    <inlineHelpText>The type of this grant</inlineHelpText>
    <label>Grant type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this proposal is linked</description>
    <inlineHelpText>The profile to which this proposal is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this proposal (auto-maintained)</description>
    <inlineHelpText>Status of this proposal (auto-maintained)</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Status_external__c.field-meta.xml
<CustomField>
    <fullName>Status_external__c</fullName>
    <description>A version of this proposal&apos;s status suitable for viewing on the online apps site</description>
    <formula>IF (NOT (ISBLANK ( Date_declined__c )), &quot;Declined&quot;,
IF (NOT (ISBLANK ( Date_request_withdrawn__c )) &amp;&amp; TEXT(Request_withdrawn_reason__c) = &quot;AUTOMATED: Lack of online form activity&quot;,
&quot;Withdrawn_NoRecentActivity&quot;,
IF (NOT (ISBLANK ( Date_request_withdrawn__c )) || NOT(ISBLANK(Date_award_withdrawn__c)), &quot;Withdrawn&quot;,
IF ( Status_numeric__c &gt;= 6.2 , &quot;Awarded&quot;,
IF (NOT (ISBLANK ( Date_received__c )), &quot;Submitted&quot; ,

&quot;Pending&quot;
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A version of this proposal&apos;s status suitable for viewing on the online apps site</inlineHelpText>
    <label>Status external</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review_Form__c/Review_Form__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of components for field entry, used in review interfaces to populate fields in specified objects in the database.</description>
    <label>Review Form</label>
    <nameField>
        <label>Review Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Form__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this review form is in active use</description>
    <inlineHelpText>Checked if this review form is in active use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Grant_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <masterLabel>Grant type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InternalReview.cls
public with sharing class InternalReview extends Review{
    public String name;
    public Id accountId;
    public String accountName;
    public Date dateReceived;
    public String status;
    public String statusExternal;
    public String proposalAppType;
    public String proposalGrantType;
    public Boolean isWomensFund;
    public String granteeReportType;


    public InternalReview(Id recordId) {
        // is this a proposal review or a Grantee report review?
        String objName = Utilities.objectNameFromRecordId(recordId);
        System.debug('objName: '+objName);

        if (objName=='Proposal__c') {
            Proposal__c prop = [SELECT ID, Account__r.Name, Account__c, Status__c, Status_external__c, Date_approved__c, Date_declined__c, Date_awarded__c, Date_received__c, App_type__c FROM Proposal__c WHERE ID=:recordId];
            this.type = 'Proposal';
            this.accountId = prop.Account__c;
            this.accountName = prop.Account__r.Name;
            this.status = prop.Status__c;
            this.statusExternal = prop.Status_external__c;
            this.dateReceived = prop.Date_received__c;
            this.proposalAppType = prop.App_type__c;
            // Determine Review Form
            this.reviewFormId = getProposalReviewForm();
            System.debug('this.reviewFormId: '+this.reviewFormId);
            
            loadProposal(recordId);
            
        } else if (objName=='Grantee_Report__c') {
            Grantee_Report__c gReport = [SELECT ID, Name, Type__c, Date_received__c, Proposal__c, Proposal__r.Grant_type__c, Proposal__r.App_type__c, Proposal__r.Account__c, Proposal__r.Account__r.Name, Proposal__r.Account__r.Womens_Fund__c, Report_Spec__r.Form_reporting_Qs__r.Review_Form__c FROM Grantee_Report__c WHERE ID=:recordId];
            this.type = 'Grantee Report';
            this.accountId = gReport.Proposal__r.Account__c;
            this.accountName = gReport.Proposal__r.Account__r.Name;
            this.dateReceived = gReport.Date_received__c;
            this.granteeReportType = gReport.Type__c;
            this.isWomensFund = gReport.Proposal__r.Account__r.Womens_Fund__c;
            this.proposalGrantType = gReport.Proposal__r.Grant_type__c;
            this.proposalAppType = gReport.Proposal__r.App_type__c;
            // Determine Review Form
            this.reviewFormId = getGranteeReportReviewForm(gReport);
            loadGranteeReport(recordId);
            System.debug('this.reviewFormId: '+this.reviewFormId);
            
        } else if (objName=='Profile__c') {
            Profile__c prof = [SELECT ID, Account__c, Account__r.Name, Status__c, Status_external__c, Date_submitted__c, Date_declined__c, Date_review_completed__c FROM Profile__c WHERE ID=:recordId];
            List < Review_Form__c > profileReviewForm;
            try {
                profileReviewForm = [SELECT ID, Name FROM Review_Form__c WHERE Name='Profile' LIMIT 1];
            } catch (Exception e) {
                throw new GFW_Exception('InternalReview.Constructor', 'No Review Form named "Profile" found.  Cannot load Profile Review', e);
            }
            
            this.type = 'Profile';
            this.accountId = prof.Account__c;
            this.accountName = prof.Account__r.Name;
            this.status = prof.Status__c;
            this.statusExternal = prof.Status_external__c;
            this.dateReceived = prof.Date_submitted__c;
            this.reviewFormId = profileReviewForm[0].Id;
            loadProfile(recordId);
        }

        // Initialize Maps and lists
        formComponents = new List < FormComponent >();
        indicatorAssignMap = new Map < String, Map < String, IndicatorAssign > >();
        classificationAssignMap = new Map < String, List < ClassificationAssign > >();
        portfolioAssignments = new List < PortfolioAssign >();

        loadReviewFormComponents();
        loadPortfolioAssigns();
        loadProfilePortfolioAssigns();
        loadIndicatorAssigns();
        loadClassificationAssigns();
        finishFormComponentBuild();
       
    }

    public void submit() {
        try {
            Date today = System.today();

            // Update the Grantee Report or Proposal Review Completion Date if not already filled in
            if (this.type == 'Grantee Report') {
                if (this.linkedGranteeReport.Date_review_completed__c==null) {
                    Grantee_Report__c gr = new Grantee_Report__c (
                        Id=this.linkedGranteeReport.Id,
                        Date_review_completed__c = today
                    );
                    update gr;
                }
            } else if (this.type == 'Proposal') {
                if (this.linkedProposal.Date_review_completed__c==null) {
                    Proposal__c prop = new Proposal__c (
                        Id=this.linkedProposal.Id,
                        Date_review_completed__c = today
                    );
                    update prop;
                }
            } else if (this.type == 'Profile') {
                if (this.linkedProfile.Date_review_completed__c==null) {
                    Profile__c prof = new Profile__c (
                        Id=this.linkedProfile.Id,
                        Date_review_completed__c = today
                    );
                    update prof;
                }
            }
        } catch (Exception e) {
            throw new GFW_Exception('InternalReview.submit', 'Review Submit Failed, please refresh and try again.', e);
        }


    }

    //todo: default review form
    private ID getProposalReviewForm() {
        // First, get all the active review forms.
        Review_Form__c[] reviewForms = [SELECT Id, Name FROM Review_Form__c WHERE Active__c = true];
        

        Map<String, Review_Form__c> rfMap = new Map<String, Review_Form__c> ();
        for (Review_Form__c rf : reviewForms) rfMap.put(rf.Name, rf);
        System.debug('rfMap: '+rfMap);

        // Try first to find a review form for the proposal's app type, else use standard.
        String baseFormName = 'Proposal' + this.proposalAppType;
        System.debug('baseFormName: '+baseFormName);
        Id baseFormId;
        if (rfMap.containsKey(baseFormName)) {
            baseFormId = rfMap.get(baseFormName).Id;
        } else if (rfMap.containsKey('ProposalStandard')) {
            baseFormId = rfMap.get('ProposalStandard').Id;
        }    
        System.debug('baseFormId: '+baseFormId);  
        
        return baseFormId;
    }

    private ID getGranteeReportReviewForm(Grantee_Report__c granteeReport) {
        //First check and see if the form behind the grantee report links to a review form.  If so, use that form
        if (granteeReport.Report_Spec__r.Form_reporting_Qs__r.Review_Form__c !=null) {
            return granteeReport.Report_Spec__r.Form_reporting_Qs__r.Review_Form__c;
        } else {
            // First, get all the active review forms.
            Review_Form__c[] reviewForms = [SELECT Id, Name FROM Review_Form__c WHERE Active__c = true];
            Map<String, Review_Form__c> rfMap = new Map<String, Review_Form__c> ();
            for (Review_Form__c rf : reviewForms) rfMap.put(rf.Name, rf);

            // Find an appropriate review form based on app type, grant type, and whether the account is WF.
            Id baseFormId;

            String baseFormName = 'Report' + (this.proposalGrantType == 'Crisis' ? 'Crisis' : this.proposalAppType);

            Id formId = this.isWomensFund && rfMap.containsKey(baseFormName +this.granteeReportType +'WF') ? rfMap.get(baseFormName +this.granteeReportType +'WF').Id :
                    this.isWomensFund && rfMap.containsKey(baseFormName +'WF') ? rfMap.get(baseFormName +'WF').Id :
                    rfMap.containsKey(baseFormName +this.granteeReportType) ? rfMap.get(baseFormName +this.granteeReportType).Id :
                    rfMap.containsKey(baseFormName) ? rfMap.get(baseFormName).Id : 
                    rfMap.containsKey('ReportStandard' +this.granteeReportType) ? rfMap.get('ReportStandard' +this.granteeReportType).Id : 
                    rfMap.containsKey('ReportStandard') ? rfMap.get('ReportStandard').Id : 
                    null;

            return formId;
        }
        
    }
}