force-app/main/default/objects/Account/fields/Account_black_listed__c.field-meta.xml
<CustomField>
    <fullName>Account_black_listed__c</fullName>
    <description>Checked if this account has been marked with the Red flag &quot;Black list&quot; indicator</description>
    <formula>Red_flag_Black_list__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Checked if this account has been marked with the Red flag &quot;Black list&quot; indicator</inlineHelpText>
    <label>Account black-listed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this classification is in active use and may be assigned to profiles and proposals.</description>
    <inlineHelpText>If checked, this classification is in active use and may be assigned to profiles and proposals.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/Classification_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single classification to a profile</description>
    <label>Classification-Profile Assign</label>
    <nameField>
        <displayFormat>CA-Prof-{00000}</displayFormat>
        <label>Classification-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Decline_reason__c/Decline_reason__c.object-meta.xml
<CustomObject>
    <description>Official reasons for decline</description>
    <label>Decline reason</label>
    <nameField>
        <label>Decline reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decline reasons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Decline_reason__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, then this decline reason is considered active and may be used in profiles and/or proposals.</description>
    <inlineHelpText>If checked, then this decline reason is considered active and may be used in profiles and/or proposals.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile linked to this letter</description>
    <inlineHelpText>The profile linked to this letter</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this portfolio is in active use</description>
    <inlineHelpText>Checked if this portfolio is in active use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile_Assign__c/Portfolio_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a portfolio to a profile</description>
    <label>Portfolio-Profile Assign</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Portfolio-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Portfolio-Profile Assigns</relationshipLabel>
    <relationshipName>Portfolio_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account of the org responsible for this profile</description>
    <inlineHelpText>The account of the org responsible for this profile</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Account_black_listed__c.field-meta.xml
<CustomField>
    <fullName>Account_black_listed__c</fullName>
    <description>Checked if this profile&apos;s account has been marked with one of the three &quot;red flag&quot; indicators: Fraud with GFW, Fraud with peer orgs, or Other</description>
    <formula>Account__r.Account_black_listed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Checked if this profile&apos;s account has been marked with one of the three &quot;red flag&quot; indicators: Fraud with GFW, Fraud with peer orgs, or Other</inlineHelpText>
    <label>Account black-listed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <description>Date on which this profile was submitted</description>
    <inlineHelpText>Date on which this profile was submitted</inlineHelpText>
    <label>Date submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Decline_reason__c.field-meta.xml
<CustomField>
    <fullName>Decline_reason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reason that this profile is ineligible (restricted to one of the type 1 declines)</description>
    <inlineHelpText>Reason that this profile is ineligible (restricted to one of the type 1 declines)</inlineHelpText>
    <label>Not-eligible reason</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>May only select active decline reasons that are appropriate for profile declines.</errorMessage>
        <filterItems>
            <field>Decline_reason__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Decline_reason__c.For_profile__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>May only select active decline reasons that are appropriate for profile declines.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Decline_reason__c</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Next_profile__c.field-meta.xml
<CustomField>
    <fullName>Next_profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The subsequent profile, created after this one expires</description>
    <inlineHelpText>The subsequent profile, created after this one expires</inlineHelpText>
    <label>Next profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Prior profile</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Prior_profile__c.field-meta.xml
<CustomField>
    <fullName>Prior_profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The prior profile (if any) for this account</description>
    <inlineHelpText>The prior profile (if any) for this account</inlineHelpText>
    <label>Prior profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Profiles (Prior profile)</relationshipLabel>
    <relationshipName>Profiles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this profile</description>
    <formula>IF ( NOT(ISBLANK(Date_declined__c)), &quot;0 Profile declined&quot;,
IF ( NOT(ISBLANK( Decline_reason__c )), &quot;2.9 Profile to decline&quot;,
IF ( AND(
      NOT(ISBLANK(Proposal_recent__c)), 
      NOT(ISBLANK(Date_review_completed__c))
   ), &quot;5 Proposal linked, Profile reviewed&quot;,
IF ( NOT(ISBLANK(Proposal_recent__c)), &quot;4.5 Proposal linked, Profile not reviewed&quot;,
IF ( AND(
      NOT(ISBLANK(Date_holdover_sent__c)), 
      NOT(ISBLANK(Date_review_completed__c))
   ), &quot;3.1 Holdover sent, Profile reviewed&quot;,
IF ( NOT(ISBLANK(Date_review_completed__c)), &quot;3 Profile reviewed&quot;,
IF ( AND(
      NOT(ISBLANK(Date_submitted__c)),
      NOT(ISBLANK(Date_holdover_sent__c))
   ), &quot;1.6 Holdover sent, Profile not reviewed&quot;,
IF ( NOT(ISBLANK(Date_submitted__c)), &quot;1.5 Profile submitted&quot;,
&quot;1 Profile pending&quot;
))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Status of this profile</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review_Form__c/Review_Form__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of components for field entry, used in review interfaces to populate fields in specified objects in the database.</description>
    <label>Review Form</label>
    <nameField>
        <label>Review Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Form__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this review form is in active use</description>
    <inlineHelpText>Checked if this review form is in active use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Review_Form_Component__c/Review_Form_Component__c.object-meta.xml
<CustomObject>
    <description>Represents a component used by a review form for field entry</description>
    <label>Review Form Component</label>
    <nameField>
        <displayFormat>RFC-{000000}</displayFormat>
        <label>Review Form Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Form Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Form_Component__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this review form component is in use</description>
    <inlineHelpText>Checked if this review form component is in use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Review_Form_Component__c/fields/Review_Form__c.field-meta.xml
<CustomField>
    <fullName>Review_Form__c</fullName>
    <description>The review form to which this component belongs</description>
    <inlineHelpText>The review form to which this component belongs</inlineHelpText>
    <label>Review Form</label>
    <referenceTo>Review_Form__c</referenceTo>
    <relationshipLabel>Review Form Components</relationshipLabel>
    <relationshipName>Review_Form_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If template is active, it may be invoked (usually from letters).</description>
    <inlineHelpText>If template is active, it may be invoked (usually from letters).</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProfileController.cls
public class ProfileController {
    public static String notificationTemplateName = 'Request to submit Updated Profile';

    /**********************************
     * For use in Lightning components
     *********************************/

    @AuraEnabled
    public static Profile__c getProfile(Id profileId) {
        String objName = 'Profile__c';
        String[] fieldNames = Utilities.fieldNamesForObject(objName);
        fieldNames.add('Decline_reason__r.Name');
        fieldNames.add('Account__r.Account_black_listed__c');
        String q =
            'SELECT ' +
            String.join(fieldNames, ', ') +
            ' FROM ' +
            objName +
            ' WHERE Id = : profileId';
        system.debug('getProfile: q = ' + q);
        return Database.query(q);
    }

    @AuraEnabled
    public static Profile__c saveProfile(Profile__c profile) {
        //system.debug('saveProfile before update: status = ' +profile.Status__c);
        update profile;
        profile = getProfile(profile.Id);
        system.debug('saveProfile after update: status = ' + profile.Status__c);
        return profile;
    }

    // Clone a profile.
    // Set the original profile's Next Profile link to point to the new profile.
    public static Profile__c profileDeepClone(Id profileId) {
        Profile__c p = getProfile(profileId);
        Profile__c pNew = new Profile__c(
            Account__c = p.Account__c,
            Prior_profile__c = profileId
        );
        insert pNew;
        // Update link in original profile.
        p.Next_profile__c = pNew.Id;
        update p;
        return pNew;
    }

    // Send email notification to the group whose profile was cloned.
    public static void sendCloneNotificationEmails(Set<Id> pIds) {
        // Build and email letters for new profiles.
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            buildLetters0(pIds, notificationTemplateName, true)
        );
    }

    @AuraEnabled
    public static ProfileInfo getProfileInfo(Id profileId) {
        return new ProfileInfo(profileId);
    }

    // Object that packages profile information including profile object and picklists.
    public with sharing class ProfileInfo {
        @AuraEnabled
        public Profile__c profile,
            priorProfile;
        @AuraEnabled
        public Id gmDataId;
        @AuraEnabled
        public Map<String, List<String>> picklists;
        @AuraEnabled
        public String[] declineReasonNames,
            classificationNames,
            portfolioNames,
            selectedClassificationNames,
            selectedPortfolioNames,
            unselectedClassificationNames,
            unselectedPortfolioNames;
        @AuraEnabled
        public String selectedDeclineReasonName,
            selectedClassificationIdsPacked,
            selectedPortfolioIdsPacked;
        @AuraEnabled
        public Map<Id, String> declineReasonNameMap,
            classificationNameMap,
            portfolioNameMap;
        @AuraEnabled
        public List<Review_Form_Component__c> reviewComponents = new List<Review_Form_Component__c>();

        public ProfileInfo(Id profileId) {
            this.profile = getProfile(profileId);
            // Fetch the profile whose Next Profile link points at this profile.
            Profile__c[] priorProfs = [
                SELECT Id, Name, Date_submitted__c
                FROM Profile__c
                WHERE Next_profile__c = :profileId
            ];
            if (priorProfs.size() > 0)
                priorProfile = priorProfs[0];
            // Look up values in picklists at the time the record is created, so they're up to date.
            picklists = Utilities.getPicklists('Profile__c');

            setDeclineReasonFields();
            setPortfolioFields();
            // Stash the review form components for the profile review form.
            Review_Form__c[] reviewForms = (Review_Form__c[]) Utilities.fetchRecords(
                'Review_Form__c',
                'WHERE Name = \'Profile\' AND Active__c = true',
                new List<String>{
                    Utilities.buildChildSubQuery(
                        'Review_Form_Component__c',
                        'Review_Form_Components__r',
                        'WHERE Active__c = true ORDER BY Sort_number__c'
                    )
                }
            );
            if (reviewForms.size() > 0) {
                reviewComponents = reviewForms[0].Review_Form_Components__r;
            }
        }

        private void setDeclineReasonFields() {
            // Set fields for decline reason names and the currently selected decline reason name.
            Map<Id, Decline_Reason__c> drMap = new Map<Id, Decline_Reason__c>(
                [
                    SELECT Id, Name
                    FROM Decline_Reason__c
                    WHERE For_profile__c = true AND Active__c = true
                    ORDER BY Name
                ]
            );
            declineReasonNameMap = new Map<Id, String>();
            for (Decline_Reason__c dr : drMap.values())
                declineReasonNameMap.put(dr.Id, dr.Name);
            declineReasonNames = declineReasonNameMap.values();
            if (declineReasonNames.size() > 0)
                declineReasonNames.add(0, ''); // Add blank entry at the front.
            selectedDeclineReasonName = declineReasonNameMap.get(
                profile.Decline_reason__c
            );
        }

        private void setPortfolioFields() {
            // Fetch portfolio names and the currently selected ones.
            Map<Id, Portfolio__c> pMap = new Map<Id, Portfolio__c>(
                [
                    SELECT Id, Type__c, Name_with_type__c
                    FROM Portfolio__c
                    WHERE Type__c = 'Priority' AND Active__c = true
                    ORDER BY Name_with_type__c
                ]
            );
            portfolioNameMap = new Map<Id, String>();
            for (Portfolio__c p : pMap.values())
                portfolioNameMap.put(p.Id, p.Name_with_type__c);
            portfolioNames = portfolioNameMap.values();
            system.debug(
                'ProfileController.apxc setPortfolioFields: portfolioNameMap = ' +
                JSON.serialize(portfolioNameMap)
            );
            if (portfolioNames.size() > 0)
                portfolioNames.add(0, ''); // Add blank entry at the front.
            // Fetch and stash priority portfolios that have been assigned to this profile.
            Map<Id, Portfolio__c> pAssigned = new Map<Id, Portfolio__c>(
                [
                    SELECT Id
                    FROM Portfolio__c
                    WHERE
                        Id IN (
                            SELECT Portfolio__c
                            FROM Portfolio_Profile_Assign__c
                            WHERE
                                Profile__c = :profile.Id
                                AND Portfolio__r.Type__c = 'Priority'
                        )
                ]
            );
            // Stash selected names and ids.
            List<id> ids = new List<Id>();
            selectedPortfolioNames = new List<String>();
            for (Portfolio__c p : pAssigned.values()) {
                String pName = portfolioNameMap.get(p.Id);
                ids.add(p.Id);
                selectedPortfolioNames.add(pName);
            }
            selectedPortfolioIdsPacked = String.join(ids, ';');
            // Stash the unselected names.
            unselectedPortfolioNames = new List<String>();
            for (Id pId : portfolioNameMap.keySet()) {
                system.debug(
                    'pId = ' +
                    pId +
                    '; portfolioNameMap.get(pId) = ' +
                    portfolioNameMap.get(pId)
                );
                if (!pAssigned.containsKey(pId))
                    unselectedPortfolioNames.add(portfolioNameMap.get(pId));
            }
        }
    }

    @AuraEnabled
    public static ClassificationInfo getClassificationInfo(
        String cType,
        Id profId
    ) {
        ClassificationInfo result = new ClassificationInfo(cType, profId);
        return result;
    }

    // Object that packages information (Ids and names) regarding selected and unselected classifications
    public with sharing class ClassificationInfo {
        @AuraEnabled
        public String selectedIdsPacked;
        @AuraEnabled
        public String[] names,
            selectedNames,
            unselectedNames;
        @AuraEnabled
        public Map<Id, String> nameMap;
        public ClassificationInfo(String cType, Id pId) {
            // Fetch classification names of given type and the currently selected ones.
            Map<Id, Classification__c> cMap = new Map<Id, Classification__c>(
                [
                    SELECT Id, Name_with_prefix__c
                    FROM Classification__c
                    WHERE Type__c = :cType AND Active__c = true
                    ORDER BY Name_with_prefix__c
                ]
            );
            nameMap = new Map<Id, String>();
            for (Classification__c c : cMap.values())
                nameMap.put(c.Id, c.Name_with_prefix__c);
            names = nameMap.values();
            if (names.size() > 0)
                names.add(0, ''); // Add blank entry at the front.
            // Fetch and stash classifications that have been assigned to this profile.
            Map<Id, Classification__c> cAssigned = new Map<Id, Classification__c>(
                [
                    SELECT Id
                    FROM Classification__c
                    WHERE
                        Id IN (
                            SELECT Classification__c
                            FROM Classification_Profile_Assign__c
                            WHERE Profile__c = :pId
                        )
                        AND Type__c = :cType
                ]
            );
            // Stash selected names and ids.
            List<id> ids = new List<Id>();
            selectedNames = new List<String>();
            for (Classification__c c : cAssigned.values()) {
                String cName = nameMap.get(c.Id);
                ids.add(c.Id);
                selectedNames.add(cName);
            }
            selectedIdsPacked = String.join(ids, ';');
            // Stash the unselected names.
            unselectedNames = new List<String>();
            for (Id cId : nameMap.keySet()) {
                system.debug(
                    'cId = ' +
                    cId +
                    '; nameMap.get(cId) = ' +
                    nameMap.get(cId)
                );
                if (!cAssigned.containsKey(cId))
                    unselectedNames.add(nameMap.get(cId));
            }
        }
    }

    // This method has a "2" in the name, because the String parameters can't be passed if it
    // is just called "saveProfileInfo".  Is "saveProfileInfo" reserved because ProfileInfo is a class name?
    @AuraEnabled
    public static Profile__c saveProfileInfo2(
        Profile__c pr,
        String populationIdsPacked,
        String strategyIdsPacked,
        String issueIdsPacked,
        String portfolioIdsPacked
    ) {
        system.debug(
            'In saveProfileInfo2: pr = ' +
            JSON.serialize(pr) +
            '; issueIdsPacked = ' +
            issueIdsPacked +
            '; strategyIdsPacked = ' +
            strategyIdsPacked +
            '; populationIdsPacked = ' +
            populationIdsPacked +
            '; portfolioIdsPacked = ' +
            portfolioIdsPacked
        );
        saveClassificationAssigns(
            pr,
            'Population',
            populationIdsPacked == null ? '' : populationIdsPacked
        );
        saveClassificationAssigns(
            pr,
            'Issue',
            issueIdsPacked == null ? '' : issueIdsPacked
        );
        saveClassificationAssigns(
            pr,
            'Strategy',
            strategyIdsPacked == null ? '' : strategyIdsPacked
        );
        savePortfolioAssigns(pr, portfolioIdsPacked);
        // Save the profile part and return the result (possibly errors).
        return saveProfile(pr);
    }

    private static void saveClassificationAssigns(
        Profile__c pr,
        String cType,
        String selectedIdsPacked
    ) {
        system.debug(
            'In saveClassificationAssigns: pr = ' +
            JSON.serialize(pr) +
            '; selectedIdsPacked = ' +
            selectedIdsPacked
        );
        Id pId = pr.Id;
        // Add/remove joins to align with new selections.
        // Get current assignments.
        Map<Id, Classification_Profile_Assign__c> cJoins = new Map<Id, Classification_Profile_Assign__c>(
            [
                SELECT Id, Classification__c
                FROM Classification_Profile_Assign__c
                WHERE
                    Profile__c = :pId
                    AND Classification__r.Type__c = :cType
                    AND Classification__r.Active__c = true
            ]
        );
        system.debug(
            'In saveClassificationAssigns: cJoins = ' + JSON.serialize(cJoins)
        );
        // Stash current classification ids.
        Set<Id> currentIds = new Set<Id>();
        for (Classification_Profile_Assign__c ca : cJoins.values())
            currentIds.add(ca.Classification__c);
        // Get selected classifications.
        Set<String> setIds = new Set<String>(selectedIdsPacked.split(';', 0));
        system.debug(
            'In saveClassificationAssigns: setIds = ' + JSON.serialize(setIds)
        );
        // Build list of classifications to delete - they were assigned, but are no longer selected.
        List<Classification_Profile_Assign__c> toDelete = new List<Classification_Profile_Assign__c>();
        for (Classification_Profile_Assign__c ca : cJoins.values()) {
            if (!setIds.contains(String.valueof(ca.Classification__c)))
                toDelete.add(ca);
        }
        system.debug(
            'In saveClassificationAssigns: toDelete = ' +
            JSON.serialize(toDelete)
        );
        // Build list of classifications to insert - they weren't originally assigned, but are now selected.
        List<Classification_Profile_Assign__c> toInsert = new List<Classification_Profile_Assign__c>();
        for (String s : setIds) {
            if (String.isBlank(s))
                continue;
            Id i = Id.valueOf(s);
            if (!currentIds.contains(i))
                toInsert.add(
                    new Classification_Profile_Assign__c(
                        Classification__c = i,
                        Profile__c = pId
                    )
                );
        }
        system.debug(
            'In saveClassificationAssigns: toInsert = ' +
            JSON.serialize(toInsert)
        );
        if (toDelete.size() > 0)
            delete toDelete;
        if (toInsert.size() > 0)
            insert toInsert;
    }

    private static void savePortfolioAssigns(
        Profile__c pr,
        String selectedIdsPacked
    ) {
        system.debug(
            'In savePortfolioAssigns: pr = ' +
            JSON.serialize(pr) +
            '; selectedIdsPacked = ' +
            selectedIdsPacked
        );
        Id pId = pr.Id;
        // Add/remove priority portfolio joins to align with new selections.
        // Get current assignments.
        Map<Id, Portfolio_Profile_Assign__c> pJoins = new Map<Id, Portfolio_Profile_Assign__c>(
            [
                SELECT Id, Portfolio__c
                FROM Portfolio_Profile_Assign__c
                WHERE Profile__c = :pId AND Portfolio__r.Type__c = 'Priority'
            ]
        );
        system.debug(
            'In savePortfolioAssigns: pJoins = ' + JSON.serialize(pJoins)
        );
        // Stash current classification ids.
        Set<Id> currentIds = new Set<Id>();
        for (Portfolio_Profile_Assign__c pa : pJoins.values())
            currentIds.add(pa.Portfolio__c);
        // Get selected classifications.
        Set<String> setIds = new Set<String>(selectedIdsPacked.split(';', 0));
        system.debug(
            'In savePortfolioAssigns: setIds = ' + JSON.serialize(setIds)
        );
        // Build list of classifications to delete - they were assigned, but are no longer selected.
        List<Portfolio_Profile_Assign__c> toDelete = new List<Portfolio_Profile_Assign__c>();
        for (Portfolio_Profile_Assign__c pa : pJoins.values()) {
            if (!setIds.contains(String.valueof(pa.Portfolio__c)))
                toDelete.add(pa);
        }
        system.debug(
            'In savePortfolioAssigns: toDelete = ' + JSON.serialize(toDelete)
        );
        // Build list of portfolios to insert - they weren't originally assigned, but are now selected.
        List<Portfolio_Profile_Assign__c> toInsert = new List<Portfolio_Profile_Assign__c>();
        for (String s : setIds) {
            if (String.isBlank(s))
                continue;
            Id i = Id.valueOf(s);
            if (!currentIds.contains(i))
                toInsert.add(
                    new Portfolio_Profile_Assign__c(
                        Portfolio__c = i,
                        Profile__c = pId
                    )
                );
        }
        system.debug(
            'In savePortfolioAssigns: toInsert = ' + JSON.serialize(toInsert)
        );
        if (toDelete.size() > 0)
            delete toDelete;
        if (toInsert.size() > 0)
            insert toInsert;
    }

    /**********************************
     * For use in VisualForce pages
     *********************************/

    private ApexPages.StandardController standardController;
    private ApexPages.StandardSetController standardSetController;

    public ProfileController(ApexPages.StandardController standardController) {
        this.standardController = standardController;
        this.selRecs = fetchRecords(new Set<Id>{ standardController.getId() });
        this.templates = Utilities.templatesMenu(
            objectName,
            START,
            selRecs,
            statusFieldName
        );
    }

    public ProfileController(
        ApexPages.StandardSetController standardSetController
    ) {
        this.standardSetController = standardSetController;
        Map<Id, Profile__c> selMap = new Map<Id, Profile__c>(
            (List<Profile__c>) standardSetController.getSelected()
        );
        this.selRecs = fetchRecords(selMap.keySet());
        this.templates = Utilities.templatesMenu(
            objectName,
            START,
            selRecs,
            statusFieldName
        );
    }

    // Build the menu of admissible correspondence templates for this object.
    private static String objectName = 'Profile__c';
    private static final String START = '--Select Template--';
    private static String statusFieldName = 'Status_numeric__c';
    private List<Profile__c> selRecs;
    public List<selectOption> templates { get; private set; }
    public String selectedTemplate { get; set; }
    {
        selectedTemplate = START;
    }
    public List<Letter__c> newLetters = new List<Letter__c>();

    // Build and reset letters for selected records (VF context).
    public PageReference buildLetters() {
        // Generate error if no selected template - assign error to the templateType field.
        if (selectedTemplate == null || selectedTemplate == START) {
            ApexPages.AddMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR,
                    'Please select a template',
                    'Must select a template before building new letters'
                )
            );
            selectedTemplate = START; // If I don't reset to the START value, it gets set to one of the non-disabled values.
            return null;
        }
        Set<Id> selIds;
        if (standardSetController != null) {
            Map<Id, Profile__c> selMap = new Map<Id, Profile__c>(
                (List<Profile__c>) standardSetController.getSelected()
            );
            selIds = selMap.keySet();
        } else {
            selIds = new Set<Id>{ standardController.getId() };
        }
        newLetters = buildLetters0(selIds, selectedTemplate, false);
        // Changes have been saved; jump to the new letter if there's only one.
        if (standardController != null && newLetters.size() == 1)
            return Utilities.pageReferenceForRecord(newLetters[0]);
        else
            return doCancel(); // Stay in current layout.
    }

    // Build and reset letters for given profiles (non-VF context).
    // The shape with ids parameter is for external callers; with records parameter is called from VF.
    public static List<Letter__c> buildLetters0(
        Set<Id> selIds,
        String selectedTemplate,
        Boolean emailFlg
    ) {
        return buildLetters0(fetchRecords(selIds), selectedTemplate, emailFlg);
    }
    public static List<Letter__c> buildLetters0(
        Profile__c[] selRecs,
        String selectedTemplate,
        Boolean emailFlg
    ) {
        Set<Id> accIds = new Set<Id>();
        for (Profile__c p : selRecs) {
            Id accId = p.Account__c;
            if (accId != null)
                accIds.add(accId);
        }
        Map<Id, List<String>> emails = Utilities.emailsForAccounts(accIds);
        // Build new letters for selected records.
        Id templateId = Utilities.recordIdFromName(
            'Template__c',
            selectedTemplate
        );
        List<Letter__c> ls = new List<Letter__c>();
        for (Profile__c r : selRecs) {
            List<String> es = emails.get(r.Account__c);
            ls.add(
                new Letter__c(
                    Template__c = templateId,
                    Account__c = r.Account__c,
                    Account_owner__c = r.Account__r.OwnerId,
                    Letter_owner__c = UserInfo.getUserId(),
                    Profile__c = r.Id,
                    // Use account emails if any.
                    Emails__c = Utilities.stringJoinWithCharLimit(es, ',', 255)
                )
            );
        }
        if (ls.size() > 0) {
            insert ls;
            system.debug('buildLetters0: ls = ' + JSON.serialize(ls));
            // Reset the new letters.
            Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(ls);
            LetterController.resetLetters0(lMap.keySet(), emailFlg);
        }
        return ls;
    }

    // Get records for given ids.
    static private Profile__c[] fetchRecords(Set<Id> ids) {
        system.debug('fetchRecords: ids = ' + JSON.serialize(ids));
        return [
            SELECT
                Id,
                Status_numeric__c,
                Account__c,
                Account__r.OwnerId
            FROM Profile__c
            WHERE Id IN :ids
        ];
    }

    public PageReference doCancel() {
        return (standardSetController != null)
            ? standardSetController.cancel()
            : standardController.cancel();
    }
}