force-app/main/default/objects/Account/fields/Account_number__c.field-meta.xml
<CustomField>
    <fullName>Account_number__c</fullName>
    <description>Auto-generated number for account records</description>
    <displayFormat>A{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Auto-generated number for account records</inlineHelpText>
    <label>Account number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <description>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</description>
    <inlineHelpText>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</inlineHelpText>
    <label>Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The payment method (if any) linked to this letter</description>
    <inlineHelpText>The payment method (if any) linked to this letter</inlineHelpText>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this letter</description>
    <inlineHelpText>The proposal linked to this letter</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <description>The details of how the applicant should be paid; includes banking information</description>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Payment method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account linked to this payment method</description>
    <inlineHelpText>The account linked to this payment method</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Amount_to_pay__c.field-meta.xml
<CustomField>
    <fullName>Amount_to_pay__c</fullName>
    <description>The amount to be paid on the payment associated with this payment method</description>
    <inlineHelpText>The amount to be paid on the payment associated with this payment method</inlineHelpText>
    <label>Amount to pay</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Date_payment_info_confirmed__c.field-meta.xml
<CustomField>
    <fullName>Date_payment_info_confirmed__c</fullName>
    <description>The date on which the information in this payment method was confirmed by staff</description>
    <inlineHelpText>The date on which the information in this payment method was confirmed by staff</inlineHelpText>
    <label>Date payment info confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this payment method</description>
    <inlineHelpText>The proposal linked to this payment method</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of payment method</description>
    <inlineHelpText>The type of payment method</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Org account</fullName>
                <default>true</default>
                <label>Org account</label>
            </value>
            <value>
                <fullName>Joint account</fullName>
            </value>
            <value>
                <fullName>Fiscal sponsor</fullName>
            </value>
            <value>
                <fullName>Alternative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Unique_id__c.field-meta.xml
<CustomField>
    <fullName>Unique_id__c</fullName>
    <description>The id field used to represent this payment method at the vendor</description>
    <inlineHelpText>The id field used to represent this payment method at the vendor</inlineHelpText>
    <label>Unique id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Amount_awarded__c.field-meta.xml
<CustomField>
    <fullName>Amount_awarded__c</fullName>
    <description>Actual amount awarded to the group (possibly over multiple payments)</description>
    <inlineHelpText>Actual amount awarded to the group (possibly over multiple payments)</inlineHelpText>
    <label>Amount awarded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Source_object__c.field-meta.xml
<CustomField>
    <fullName>Source_object__c</fullName>
    <description>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</description>
    <inlineHelpText>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</inlineHelpText>
    <label>Source object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>GM_Data__c</fullName>
            </value>
            <value>
                <fullName>Milestone__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Payment__c</fullName>
            </value>
            <value>
                <fullName>Payment_Method__c</fullName>
            </value>
            <value>
                <fullName>Profile__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentMethodControllerTest.cls
@isTest
public class PaymentMethodControllerTest {
    static testMethod void PaymentMethodControllerTest1a() {
        // Build new payment methods, proposals and accounts
        InitTestObjects(1, 1);
        // Build new standard set controller and select the new payment methods.
        Map<Id, Payment_Method__c> pMap = new Map<Id, Payment_Method__c>(
            [SELECT Id FROM Payment_Method__c]
        );
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            pMap.values()
        );
        ssc.setSelected(pMap.values());

        Test.StartTest();
        // Build a new controller and use it to build new letters for the selected payment methods.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'Payment_Method__c'
        ));
        PaymentMethodController pc = new PaymentMethodController(ssc);
        pc.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', pc.selectedTemplate),
            null
        );
        pc.buildLetters();
        Test.StopTest();

        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );
        validate(lMap.keySet());
    }

    static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [
                SELECT Account__c, Account__r.Name, Emails__c, Payment_Method__c
                FROM Letter__c
                WHERE Id IN :lIds
            ]
        );
        Map<Id, Payment_Method__c> pMap = new Map<Id, Payment_Method__c>(
            [
                SELECT Id
                FROM Payment_Method__c
                WHERE
                    Id IN (
                        SELECT Payment_Method__c
                        FROM Letter__c
                        WHERE Id IN :lIds
                    )
            ]
        );
        // Should be a different letter for each payment method.
        system.assertEquals(lMap.size(), pMap.size());
        // Gather email addresses for contacts under the accounts.
        Map<Id, Account> aMap = new Map<Id, Account>([SELECT Id FROM Account]);
        Map<Id, List<String>> emailMap = Utilities.emailsForAccounts(
            aMap.keySet()
        );
        // The emails stored on the letter need to agree with the account's emails.
        for (Letter__c l : lMap.values()) {
            system.debug(
                'loop in validate: l.Account__r.Name= ' +
                l.Account__r.Name +
                '; l.Emails__c = ' +
                JSON.serialize(l.Emails__c)
            );
            system.assertEquals(
                l.Emails__c,
                String.join(emailMap.get(l.Account__c), ',')
            );
        }
    }

    static void InitTestObjects(
        Integer NumberOfPaymentMethods,
        Integer NumberOfAccounts
    ) {
        // Build proposals and accounts
        BuildTestProposals.InitTestObjects(
            NumberOfPaymentMethods,
            NumberOfAccounts
        );
        List<Proposal__c> ps = new List<Proposal__c>(
            [SELECT Id, Account__c FROM Proposal__c]
        );
        // Build and insert payment methods linked to the new proposals.
        List<Payment_Method__c> pas = new List<Payment_Method__c>();
        for (Integer x = 0; x < NumberOfPaymentMethods; x++) {
            pas.add(
                new Payment_Method__c(
                    Proposal__c = ps[x].Id,
                    Account__c = ps[x].Account__c
                    // Add other field assignments for payment methods
                )
            );
        }
        insert pas;
    }

    static testMethod void PaymentMethodControllerTest2a() {
        // Build records.
        BuildTestProposals.InitTestObjects(1, 1);
        Proposal__c p = [SELECT Id, Account__c FROM Proposal__c LIMIT 1];
        Account a = [
            SELECT Id, Account_number__c
            FROM Account
            WHERE Id = :p.Account__c
        ];
        insert new Payment_Method__c(
            Proposal__c = p.Id,
            Account__c = a.Id,
            Type__c = 'Org account'
        );
        Payment_Method__c pm = [
            SELECT Id
            FROM Payment_Method__c
            WHERE Type__c = 'Org account'
            LIMIT 1
        ];

        Test.StartTest();
        PaymentMethodUniqueIdInvocable.updateUniqueId(new List<Id>{ pm.Id });
        Test.StopTest();

        // Ensure that new unique ids were constructed from the appropriate account's Account Number.
        pm = [
            SELECT Id, Unique_id__c
            FROM Payment_Method__c
            WHERE Type__c = 'Org account'
            LIMIT 1
        ];
        system.assertEquals(a.Account_number__c + '-1', pm.Unique_id__c);
    }

    static testMethod void PaymentMethodControllerTest3() {
        // Build records.
        BuildTestProposals.InitTestObjects(1, 1);
        Proposal__c p = [SELECT Id, Account__c FROM Proposal__c LIMIT 1];
        Account a = [
            SELECT Id, Account_number__c
            FROM Account
            WHERE Id = :p.Account__c
        ];
        insert new Payment_Method__c(
            Proposal__c = p.Id,
            Account__c = a.Id,
            Unique_id__c = 'wu 1',
            Type__c = 'Org account'
        );
        Payment_Method__c pm = [
            SELECT Id
            FROM Payment_Method__c
            WHERE Type__c = 'Org account'
            LIMIT 1
        ];
        insert new Payment_Method__c(
            Proposal__c = p.Id,
            Account__c = a.Id,
            Type__c = 'Alternative'
        );
        Payment_Method__c pm1 = [
            SELECT Id
            FROM Payment_Method__c
            WHERE Type__c = 'Alternative'
            LIMIT 1
        ];

        Test.StartTest();
        PaymentMethodUniqueIdInvocable.updateUniqueId(new List<Id>{ pm1.Id });
        Test.StopTest();

        // Ensure that new Unique id was copied from the earlier payment method.
        pm1 = [
            SELECT Id, Unique_id__c
            FROM Payment_Method__c
            WHERE Type__c = 'Alternative'
            LIMIT 1
        ];
        system.assertEquals('wu 1', pm1.Unique_id__c);
    }

    // Test the newPaymentMethod code
    static testMethod void PaymentMethodControllerTest4() {
        // Build records.
        ProposalUpdateTest.buildTemplateMacros();
        BuildTestProposals.InitTestObjects(1, 1);
        Proposal__c p = [SELECT Id, Account__c FROM Proposal__c LIMIT 1];
        p.Amount_awarded__c = 100;
        update p;
        Account a = [
            SELECT Id, Account_number__c
            FROM Account
            WHERE Id = :p.Account__c
        ];

        Test.StartTest();
        // No existing payment method to clone, so this should build a new one.
        PaymentMethodNewInvocable.newPaymentMethod(new List<Id>{ p.Id });
        Payment_Method__c[] pms = [
            SELECT Id, Type__c, Proposal__c, Account__c, Amount_to_pay__c
            FROM Payment_Method__c
        ];
        system.assertEquals(1, pms.size());
        system.assertEquals(100, pms[0].Amount_to_pay__c);
        system.assertEquals('Org account', pms[0].Type__c);
        // Because the new one isn't yet confirmed, we won't be able to create another.
        PaymentMethodNewInvocable.newPaymentMethod(new List<Id>{ p.Id });
        pms = [
            SELECT Id, Type__c, Proposal__c, Account__c
            FROM Payment_Method__c
        ];
        system.assertEquals(1, pms.size());
        // Verify and clear prop lookup, to make it based on the account.
        pms[0].Date_payment_info_confirmed__c = Date.today();
        pms[0].Proposal__c = null;
        update pms[0];
        ProposalUpdate.updateProposal(p.Id, true);
        // This time we can create a new one, cloning, linking to the proposal, and clearing date fields.
        PaymentMethodNewInvocable.newPaymentMethod(new List<Id>{ p.Id });
        pms = [
            SELECT Id, Type__c, Proposal__c, Account__c
            FROM Payment_Method__c
        ];
        system.assertEquals(2, pms.size());
        pms = [
            SELECT Id, Type__c, Proposal__c, Date_payment_info_confirmed__c
            FROM Payment_Method__c
            WHERE Proposal__c != null
        ];
        system.assertEquals(1, pms.size());
        system.assertEquals(p.Id, pms[0].Proposal__c);
        system.assertEquals(null, pms[0].Date_payment_info_confirmed__c);
        Test.StopTest();
    }
}