force-app/main/default/objects/Account/fields/Contact_info_GM__c.field-meta.xml
<CustomField>
    <fullName>Contact_info_GM__c</fullName>
    <description>Contact info for this account based on primary contact, top-ranked linked address, and phones and emails</description>
    <inlineHelpText>Contact info for this account based on primary contact, top-ranked linked address, and phones and emails</inlineHelpText>
    <label>Contact info GM</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_primary__c.field-meta.xml
<CustomField>
    <fullName>Contact_primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact for this account - addressed in pre-contract, contract, and payment letters</description>
    <inlineHelpText>The primary contact for this account - addressed in pre-contract, contract, and payment letters</inlineHelpText>
    <label>Contact primary</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Primary contact must be one of the contacts linked to this account.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Primary contact must be one of the contacts linked to this account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Contact primary)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>An address linked to the account</description>
    <label>Address</label>
    <nameField>
        <displayFormat>a{0000000}</displayFormat>
        <label>Address name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An internal field used to link this address info to an Account.</description>
    <inlineHelpText>An internal field used to link this address info to an Account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city name related to the address.  This name can be the preferred city name or an acceptable city name. Free text of up to 50 characters.</description>
    <inlineHelpText>The City portion of the address.  Free text of up to 50 characters.</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Multiple street lines can be entered by simply hitting enter after each line.  A total of 255 characters can be entered.  This field, along with the Locality field, is for use in mail merges.</description>
    <inlineHelpText>Multiple street lines can be entered by simply hitting enter after each line.  A total of 255 characters can be entered.  This field, along with the Locality field, is for use in mail merges.</inlineHelpText>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <defaultValue>/* Default GM contacts to rank 1, Dev contacts to blank. */
IF(CONTAINS($RecordType.DeveloperName, &quot;GM&quot;), 1, null)</defaultValue>
    <description>Used to sort contacts within an account, for example, to pick the primary one</description>
    <inlineHelpText>Used to sort contacts within an account, for example, to pick the primary one</inlineHelpText>
    <label>Rank</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_GM.recordType-meta.xml
<RecordType>
    <fullName>Contact_GM</fullName>
    <active>true</active>
    <description>For grantmaking-related contact records, primarily staff at grantee/applicant orgs</description>
    <label>Contact GM</label>
</RecordType>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateAccountContactInfoTest.cls
@isTest
public class UpdateAccountContactInfoTest {
    static testMethod void UpdateAccountContactInfoTest1() {
        // Build data records
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'Test account',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'),
            Website = 'www.abc.org'
        );
        Account acc = [SELECT Id, Contact_primary__c FROM Account LIMIT 1];
        insert new Address__c(
            Account__c = acc.Id,
            Street__c = 'test street',
            City__c = 'test city'
        );
        insert new Contact(
            AccountId = acc.Id,
            LastName = 'Primary contact name',
            Rank__c = 1,
            RecordTypeId = Utilities.getRecTypeId('Contact', 'Contact_GM')
        );
        Id ctId = [SELECT Id FROM Contact LIMIT 1].Id;
        acc.Contact_primary__c = ctId;
        update acc;

        Test.StartTest();
        UpdateAccountContactInfo.UpdateAccountContactInfo(
            new List<Id>{ acc.Id }
        );
        acc = [
            SELECT Id, Name, Contact_info_GM__c
            FROM Account
            WHERE Id = :acc.Id
        ];
        system.assertEquals('Test account', acc.Name);
        // Run same request again in order to cover more code
        UpdateAccountContactInfo.UpdateAccountContactInfo(
            new List<Id>{ acc.Id }
        );
        Test.StopTest();
    }
}