force-app/main/default/objects/Account/fields/Contact_emails_GM__c.field-meta.xml
<CustomField>
    <fullName>Contact_emails_GM__c</fullName>
    <description>The email addresses to be used when contacting this group</description>
    <inlineHelpText>The email addresses to be used when contacting this group</inlineHelpText>
    <label>Contact emails GM</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_info_GM__c.field-meta.xml
<CustomField>
    <fullName>Contact_info_GM__c</fullName>
    <description>Contact info for this account based on primary contact, top-ranked linked address, and phones and emails</description>
    <inlineHelpText>Contact info for this account based on primary contact, top-ranked linked address, and phones and emails</inlineHelpText>
    <label>Contact info GM</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_primary__c.field-meta.xml
<CustomField>
    <fullName>Contact_primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact for this account - addressed in pre-contract, contract, and payment letters</description>
    <inlineHelpText>The primary contact for this account - addressed in pre-contract, contract, and payment letters</inlineHelpText>
    <label>Contact primary</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Primary contact must be one of the contacts linked to this account.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Primary contact must be one of the contacts linked to this account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Contact primary)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/LinkedAddress__c.field-meta.xml
<CustomField>
    <fullName>LinkedAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Click this link to edit the Default Address.</description>
    <inlineHelpText>Click this link to edit the Default Address.</inlineHelpText>
    <label>Mailing Address Link</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone2__c.field-meta.xml
<CustomField>
    <fullName>Phone2__c</fullName>
    <description>An optional second phone number for this account</description>
    <inlineHelpText>An optional second phone number for this account</inlineHelpText>
    <label>Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>An address linked to the account</description>
    <label>Address</label>
    <nameField>
        <displayFormat>a{0000000}</displayFormat>
        <label>Address name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An internal field used to link this address info to an Account.</description>
    <inlineHelpText>An internal field used to link this address info to an Account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_w_confidential__c.field-meta.xml
<CustomField>
    <fullName>Address_w_confidential__c</fullName>
    <description>Combined address except that Street is hidden for confidential accounts</description>
    <formula>IF( Account__r.Keep_confidential__c &amp;&amp; NOT(ISBLANK(Street__c)), &quot;[Street address CONFIDENTIAL]&quot;, Street__c) &amp;
        IF(NOT(ISBLANK(Street__c)), &apos;, &apos;, &apos;&apos;) &amp; 
        Street__c &amp;
        IF(NOT(ISBLANK(City__c)), &apos;, &apos;, &apos;&apos;) &amp; 
        City__c &amp;
        IF(NOT(ISBLANK(Province__c)), &apos;, &apos;, &apos;&apos;) &amp; 
        Province__c &amp;
        &apos; &apos; &amp; PostalCode__c &amp; &apos; &apos; &amp; Country__c</formula>
    <inlineHelpText>Combined address except that Street is hidden for confidential accounts</inlineHelpText>
    <label>Address (w/ confidential)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Full_address__c.field-meta.xml
<CustomField>
    <fullName>Full_address__c</fullName>
    <description>System-generated, using individual pieces of the address record.  This field contains the formatted address, which can be used for mailing purposes.</description>
    <formula>Street__c &amp;
IF(NOT(ISBLANK(Street__c)), &apos;, &apos;, &apos;&apos;)
&amp; City__c &amp;
IF(NOT(ISBLANK(City__c)), &apos;, &apos;, &apos;&apos;)
&amp; State__c &amp; &apos;  &apos; &amp;  PostalCode__c &amp; &apos;    &apos; &amp;  Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>System-generated, using individual pieces of the address record.  This field contains the formatted address, which can be used for mailing purposes.</inlineHelpText>
    <label>Full address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/IsCurrentActiveAddress__c.field-meta.xml
<CustomField>
    <fullName>IsCurrentActiveAddress__c</fullName>
    <formula>IF( ISBLANK(Contact__c), IF( Account__r.LinkedAddress__c =  Id , &quot;YES&quot;, &quot;No&quot;), IF ( Contact__r.LinkedAddress__c = Id , &quot;YES&quot;, &quot;No&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this address is currently the Active Address.</inlineHelpText>
    <label>Is Current Active Address:</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <description>City, State/Province, Postal Code and Country (if not USA) combined onto one line for use in reports, screen display, and mail merges. This field, along with the Street field, is for use in mail merges.</description>
    <formula>City__c &amp;
        IF(NOT(ISBLANK(State__c)), &apos;, &apos; &amp; State__c, &apos;&apos;) &amp;
        IF(NOT(ISBLANK(Province__c)), &apos;, &apos; &amp; Province__c, &apos;&apos;) &amp;
        &apos; &apos; &amp; PostalCode__c &amp; BR() &amp;
  Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>City, State/Province, Postal Code and Country (if not USA) combined onto one line for use in reports, screen display, and mail merges. This field, along with the Street field, is for use in mail merges.</inlineHelpText>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Multiple street lines can be entered by simply hitting enter after each line.  A total of 255 characters can be entered.  This field, along with the Locality field, is for use in mail merges.</description>
    <inlineHelpText>Multiple street lines can be entered by simply hitting enter after each line.  A total of 255 characters can be entered.  This field, along with the Locality field, is for use in mail merges.</inlineHelpText>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedAddress__c.field-meta.xml
<CustomField>
    <fullName>LinkedAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Click this link to edit the Primary Address.</inlineHelpText>
    <label>Alternate Address Link</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>LAContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateAccountContactInfo.cls
public class UpdateAccountContactInfo {
    public class myException extends Exception {
    }

    @InvocableMethod(
        label='Update account contact info'
        description='Update Contact Info GM field in account record.'
    )
    public static void UpdateAccountContactInfo(List<Id> accIds) {
        for (Id accId : accIds)
            handleRequest(accId);
    }

    // Look up emails, phones, address, and build (possibly new) contact info string.
    public static void handleRequest(Id accId) {
        system.debug('handleRequest: accId = ' + accId);
        // Get account info, including all necessary email- and contact info-related fields.
        Account acc = AccountController.fetchAccountsContactInfo(
            new Set<Id>{ accId }
        )[0];
        system.debug('handleRequest: acc = ' + JSON.serialize(acc));
        // Get linked addresses. Note that the current address (Yes) sorts ahead of others (No). If no current, then get most recent.
        List<Address__c> addrs = new List<Address__c>(
            [
                SELECT
                    Id,
                    Full_address__c,
                    Address_w_confidential__c,
                    IsCurrentActiveAddress__c,
                    LastModifiedDate,
                    Street__c,
                    Locality__c
                FROM Address__c
                WHERE
                    Account__c = :accId
                    AND (Street__c != null
                    OR Locality__c != null)
                ORDER BY IsCurrentActiveAddress__c DESC, LastModifiedDate DESC
            ]
        );
        system.debug('addrs = ' + JSON.serialize(addrs));
        Address__c addr = addrs.size() > 0 ? addrs[0] : null;
        List<String> emails = AccountController.emailsForAccount(acc);
        String contactInfo = buildContactInfoText(acc, emails, addr);
        String emailsStr = emails.size() > 0
            ? Utilities.stringJoinWithCharLimit(
                    new List<String>(emails),
                    ', ',
                    255
                )
            : null;
        // Update account if the new contact info is different from what was already there.
        system.debug('acc.Contact_info_GM__c = ' + acc.Contact_info_GM__c);
        system.debug('contactInfo = ' + contactInfo);
        system.debug('emailsStr = ' + emailsStr);
        if (
            contactInfo != acc.Contact_info_GM__c ||
            emailsStr != acc.Contact_emails_GM__c
        ) {
            acc.Contact_info_GM__c = contactInfo;
            acc.Contact_emails_GM__c = emailsStr;
            if (addr != null)
                acc.LinkedAddress__c = addr.Id;
            update acc;
            system.debug(
                'After update: acc.Contact_info_GM__c = ' +
                acc.Contact_info_GM__c
            );
        }
    }

    // Return contact info string for given account based on given applicant and address.
    // Pass address rather than fetching, because the record may not yet have been saved in database.
    public static String buildContactInfoText(
        Account acc,
        List<String> emails,
        Address__c addr
    ) {
        system.debug('buildContactInfoText...');
        system.debug('acc = ' + JSON.serialize(acc));
        system.debug('addr = ' + JSON.serialize(addr));
        // Gather phones.
        Set<String> phones = new Set<String>();
        if (acc.Phone != null)
            phones.add(acc.Phone);
        if (acc.Phone2__c != null)
            phones.add(acc.Phone2__c);
        // Build multi-line contact info string.
        List<String> lines = new List<String>();
        system.debug('acc.Contact_primary__c = ' + acc.Contact_primary__c);
        if (
            acc.Contact_primary__c != null &&
            acc.Contact_primary__r.Name != null
        )
            lines.add(acc.Contact_primary__r.Name);
        if (addr != null && addr.Address_w_confidential__c != null)
            lines.add(addr.Address_w_confidential__c.replace('<br>', '\n'));
        else if (acc.BillingAddress != null) {
            String[] lastAddrBits = Utilities.removeNulls(
                new List<String>{
                    acc.BillingState,
                    acc.BillingPostalCode,
                    acc.BillingCountry
                }
            );
            String endOfAddr = lastAddrBits != null
                ? String.join(lastAddrBits, ' ')
                : null;
            lines.add(
                String.join(
                    Utilities.removeNulls(
                        new List<String>{
                            acc.BillingStreet,
                            acc.BillingCity,
                            endOfAddr
                        }
                    ),
                    ', '
                )
            );
        }
        if (acc.Website != null)
            lines.add(acc.Website);
        if (emails.size() > 0)
            lines.add(String.join(emails, ', '));
        if (phones.size() > 0)
            lines.add(String.join(new List<String>(phones), ', '));
        return String.join(lines, '\n');
    }
}