force-app/main/default/objects/Account/fields/Contact_emails_GM__c.field-meta.xml
<CustomField>
    <fullName>Contact_emails_GM__c</fullName>
    <description>The email addresses to be used when contacting this group</description>
    <inlineHelpText>The email addresses to be used when contacting this group</inlineHelpText>
    <label>Contact emails GM</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_info_GM__c.field-meta.xml
<CustomField>
    <fullName>Contact_info_GM__c</fullName>
    <description>Contact info for this account based on primary contact, top-ranked linked address, and phones and emails</description>
    <inlineHelpText>Contact info for this account based on primary contact, top-ranked linked address, and phones and emails</inlineHelpText>
    <label>Contact info GM</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_primary__c.field-meta.xml
<CustomField>
    <fullName>Contact_primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact for this account - addressed in pre-contract, contract, and payment letters</description>
    <inlineHelpText>The primary contact for this account - addressed in pre-contract, contract, and payment letters</inlineHelpText>
    <label>Contact primary</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Primary contact must be one of the contacts linked to this account.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Primary contact must be one of the contacts linked to this account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Contact primary)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GM_Email2__c.field-meta.xml
<CustomField>
    <fullName>GM_Email2__c</fullName>
    <description>Secondary email address for this account (for grantmaking-related correspondence)</description>
    <inlineHelpText>Secondary email address for this account (for grantmaking-related correspondence)</inlineHelpText>
    <label>GM Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/GM_Email__c.field-meta.xml
<CustomField>
    <fullName>GM_Email__c</fullName>
    <description>Primary email address for this account (for grantmaking-related correspondence)</description>
    <externalId>true</externalId>
    <inlineHelpText>Primary email address for this account (for grantmaking-related correspondence)</inlineHelpText>
    <label>GM Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Org_name_GM__c.field-meta.xml
<CustomField>
    <fullName>Org_name_GM__c</fullName>
    <description>The original org name as it came over from the grantmaking db in FileMaker (possibly longer than 80 characters)</description>
    <inlineHelpText>The original org name as it came over from the grantmaking db in FileMaker (possibly longer than 80 characters)</inlineHelpText>
    <label>Org name GM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone2__c.field-meta.xml
<CustomField>
    <fullName>Phone2__c</fullName>
    <description>An optional second phone number for this account</description>
    <inlineHelpText>An optional second phone number for this account</inlineHelpText>
    <label>Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>Alternate email address</description>
    <inlineHelpText>Alternate email address</inlineHelpText>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <defaultValue>/* Default GM contacts to rank 1, Dev contacts to blank. */
IF(CONTAINS($RecordType.DeveloperName, &quot;GM&quot;), 1, null)</defaultValue>
    <description>Used to sort contacts within an account, for example, to pick the primary one</description>
    <inlineHelpText>Used to sort contacts within an account, for example, to pick the primary one</inlineHelpText>
    <label>Rank</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rank_non_blank__c.field-meta.xml
<CustomField>
    <fullName>Rank_non_blank__c</fullName>
    <description>The value of Rank if non-blank, else 90</description>
    <formula>BLANKVALUE(Rank__c, 90)</formula>
    <inlineHelpText>The value of Rank if non-blank, else 90</inlineHelpText>
    <label>Rank non blank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Account_owner__c.field-meta.xml
<CustomField>
    <fullName>Account_owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cached lookup relationship to the account owner. Necessary because can&apos;t reach through the polymorphic Account.Owner link.</description>
    <inlineHelpText>Cached lookup relationship to the account owner. Necessary because can&apos;t reach through the polymorphic Account.Owner link.</inlineHelpText>
    <label>Account owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <description>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</description>
    <inlineHelpText>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</inlineHelpText>
    <label>Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Letter_owner__c.field-meta.xml
<CustomField>
    <fullName>Letter_owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cached lookup relationship to the letter owner. Necessary because can&apos;t reach through the polymorphic Letter.Owner link.</description>
    <inlineHelpText>Cached lookup relationship to the letter owner. Necessary because can&apos;t reach through the polymorphic Letter.Owner link.</inlineHelpText>
    <label>Letter owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Letters1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region record linked to this letter</description>
    <inlineHelpText>Region record linked to this letter</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountController.cls
public class AccountController {
    private ApexPages.StandardController standardController;
    private ApexPages.StandardSetController standardSetController;

    public AccountController(ApexPages.StandardController standardController) {
        this.standardController = standardController;
    }

    public AccountController(
        ApexPages.StandardSetController standardSetController
    ) {
        this.standardSetController = standardSetController;
    }

    // Build the menu of admissible correspondence templates for this object.
    private static String objectName = 'Account';
    private static final String START = '--Select Template--';
    public List<selectOption> templates { get; private set; }
    {
        templates = Utilities.templatesForObject(objectName, START);
    }
    public String selectedTemplate { get; set; }

    {
        selectedTemplate = START;
    }

    // Build and reset letters for selected records.
    public PageReference buildLetters() {
        // Generate error if no selected template - assign error to the templateType field.
        if (selectedTemplate == null || selectedTemplate == START) {
            ApexPages.AddMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR,
                    'Please select a template',
                    'Must select a template before building new letters'
                )
            );
            selectedTemplate = START; // If I don't reset to the START value, it gets set to one of the non-disabled values.
            return null;
        }
        Set<Id> selIds = getSelectedIds();
        Map<Id, Account> selMap = new Map<Id, Account>(
            [SELECT Id, OwnerId, GM_Region__c FROM Account WHERE Id IN :selIds]
        );
        Map<Id, List<String>> emails = emailsForAccounts(selMap.keySet());
        // Build new letters for selected records.
        Id templateId = Utilities.recordIdFromName(
            'Template__c',
            selectedTemplate
        );
        List<Letter__c> ls = new List<Letter__c>();
        for (Account r : selMap.values()) {
            List<String> es = emails.get(r.Id);
            ls.add(
                new Letter__c(
                    Template__c = templateId,
                    Account__c = r.Id,
                    Account_owner__c = r.OwnerId,
                    Letter_owner__c = UserInfo.getUserId(),
                    Region__c = r.GM_Region__c,
                    Emails__c = Utilities.stringJoinWithCharLimit(es, ',', 255)
                )
            );
        }
        insert ls;
        Map<Id, Letter__c> lsMap = new Map<Id, Letter__c>(ls);
        // Reset the new letters.
        LetterController.resetLetters0(lsMap.keySet(), false);
        // Changes have been saved; jump to the new letter if there's only one.
        if (standardController != null && ls.size() == 1)
            return Utilities.pageReferenceForRecord(ls[0]);
        else
            return doCancel(); // Stay in current layout.
    }

    public PageReference doCancel() {
        return (standardSetController != null)
            ? standardSetController.cancel()
            : standardController.cancel();
    }

    private Set<Id> getSelectedIds() {
        Set<Id> selIds;
        if (standardSetController != null) {
            Map<Id, Account> selMap = new Map<Id, Account>(
                (List<Account>) standardSetController.getSelected()
            );
            selIds = selMap.keySet();
        } else {
            selIds = new Set<Id>{ standardController.getId() };
        }
        return selIds;
    }

    /**********************************
     * For general use
     *********************************/

    // Fetch account records with given ids, grabbing all contact info fields.
    public static List<Account> fetchAccountsContactInfo(Set<Id> accIds) {
        return [
            SELECT
                Name,
                Org_name_GM__c,
                Website,
                Contact_info_GM__c,
                Contact_emails_GM__c,
                Phone,
                Phone2__c,
                GM_Email__c,
                GM_Email2__c,
                Contact_primary__c,
                Contact_primary__r.Name,
                RecordType.DeveloperName,
                BillingAddress,
                BillingStreet,
                BillingCity,
                BillingState,
                BillingPostalCode,
                BillingCountry,
                (
                    SELECT Email, Email2__c, Rank__c
                    FROM Contacts
                    WHERE Email != null
                    ORDER BY Rank_non_blank__c
                )
            FROM Account
            WHERE Id IN :accIds
        ];
    }

    // Return a map of emails for given accounts; results depend on account record type.
    public static Map<Id, List<String>> emailsForAccounts(Set<Id> aIds) {
        Map<ID, List<String>> eMap = new Map<Id, List<String>>();
        List<Account> accts = fetchAccountsContactInfo(aIds);
        //system.debug('accts = ' +JSON.serialize(accts));
        // Gather emails for each account.
        for (Account a : accts) {
            eMap.put(a.Id, emailsForAccount(a));
        }
        return eMap;
    }

    // Return the unique email addresses that haven't been marked invalid for the given account.
    // Use Email and Email2 fields plus emails of rank 1 contacts.  If none of those, use linked emails.
    // NOTE: The caller should have fetched all necessary contact info fields into given account.
    public static List<String> emailsForAccount(Account a) {
        Set<String> uniqueEmails = new Set<String>();
        List<String> orderedEmails = new List<String>(); // Used for contact emails of Dev accounts
        if (
            a.RecordType.DeveloperName != null &&
            a.RecordType.DeveloperName.contains('GM')
        ) {
            // Gather emails for a GM account.
            // Grab emails from fields and from contacts.
            if (a.GM_Email__c != null)
                uniqueEmails.add(a.GM_Email__c);
            if (a.GM_Email2__c != null)
                uniqueEmails.add(a.GM_Email2__c);
            // For GM accounts, only add emails from rank 1 contacts.
            for (Contact c : a.Contacts) {
                if (c.Rank__c == 1) {
                    uniqueEmails.add(c.Email);
                }
            }
            system.debug(
                'emailsForAccount: uniqueEmails (GM) = ' +
                JSON.serialize(uniqueEmails)
            );
            return new List<String>(uniqueEmails);
        } else {
            // For Dev accounts, gather unique contact emails, preserving the original rank order.
            for (Contact c : a.Contacts)
                if (!uniqueEmails.contains(c.Email)) {
                    uniqueEmails.add(c.Email);
                    orderedEmails.add(c.Email);
                }
            system.debug(
                'emailsForAccount: orderedEmails (Dev) = ' +
                JSON.serialize(orderedEmails)
            );
            return orderedEmails;
        }
    }

    // Update a GM account's contact info by "touching" the orgContactInfo form instance's Submit form log entry (which triggers invocation of apex code).
    public static Boolean updateContactInfo(Id accountId) {
        UpdateAccountContactInfo.UpdateAccountContactInfo(
            new List<Id>{ accountId }
        );
        return true;
    }

    /**********************************
     * For use in Lightning components
     *********************************/
}