force-app/main/default/objects/Account/fields/Date_of_first_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_first_grant__c</fullName>
    <description>Earliest date awarded for a grantee group (does not include &quot;award withdrawn&quot; grants)</description>
    <inlineHelpText>Earliest date awarded for a grantee group (does not include &quot;award withdrawn&quot; grants)</inlineHelpText>
    <label>Date of first grant</label>
    <summarizedField>Proposal__c.Date_awarded__c</summarizedField>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_of_last_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_last_grant__c</fullName>
    <description>Most recent date awarded for a grantee group (does not include &quot;award withdrawn&quot; grants)</description>
    <inlineHelpText>Most recent date awarded for a grantee group (does not include &quot;award withdrawn&quot; grants)</inlineHelpText>
    <label>Date of last grant</label>
    <summarizedField>Proposal__c.Date_awarded__c</summarizedField>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/GM_country__c.field-meta.xml
<CustomField>
    <fullName>GM_country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country where this organization does its work (not necessarily its mailing country)</description>
    <inlineHelpText>The country where this organization does its work (not necessarily its mailing country)</inlineHelpText>
    <label>GM country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_grants__c.field-meta.xml
<CustomField>
    <fullName>Num_grants__c</fullName>
    <description>The number of grants linked to this account</description>
    <inlineHelpText>The number of grants linked to this account</inlineHelpText>
    <label>Num grants</label>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_proposals__c.field-meta.xml
<CustomField>
    <fullName>Num_proposals__c</fullName>
    <description>The number of proposals linked to this account</description>
    <inlineHelpText>The number of proposals linked to this account</inlineHelpText>
    <label>Num proposals</label>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_awarded__c.field-meta.xml
<CustomField>
    <fullName>Total_awarded__c</fullName>
    <description>The total of grants awarded to this group</description>
    <inlineHelpText>The total of grants awarded to this group</inlineHelpText>
    <label>Total awarded</label>
    <summarizedField>Proposal__c.Amount_awarded__c</summarizedField>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Represents a single country and grantmaking within that country.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Date_of_first_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_first_grant__c</fullName>
    <description>The date on which the first grant was awarded in this country</description>
    <inlineHelpText>The date on which the first grant was awarded in this country</inlineHelpText>
    <label>Date of first grant</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Date_of_last_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_last_grant__c</fullName>
    <description>The date on which the latest grant was awarded in this country</description>
    <inlineHelpText>The date on which the latest grant was awarded in this country</inlineHelpText>
    <label>Date of last grant</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Num_grants__c.field-meta.xml
<CustomField>
    <fullName>Num_grants__c</fullName>
    <description>The number of grants awarded in this country</description>
    <inlineHelpText>The number of grants awarded in this country</inlineHelpText>
    <label>Num grants</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Num_profiles__c.field-meta.xml
<CustomField>
    <fullName>Num_profiles__c</fullName>
    <description>The number of profiles received from this country</description>
    <inlineHelpText>The number of profiles received from this country</inlineHelpText>
    <label>Num profiles</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Num_proposals__c.field-meta.xml
<CustomField>
    <fullName>Num_proposals__c</fullName>
    <description>The number of proposals received from this country</description>
    <inlineHelpText>The number of proposals received from this country</inlineHelpText>
    <label>Num proposals</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Enclosing region for this country</description>
    <inlineHelpText>Enclosing region for this country</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Countries</relationshipLabel>
    <relationshipName>Countries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Total_awarded__c.field-meta.xml
<CustomField>
    <fullName>Total_awarded__c</fullName>
    <description>The total amount in USD of grants awarded in this country</description>
    <inlineHelpText>The total amount in USD of grants awarded in this country</inlineHelpText>
    <label>Total awarded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account of the org responsible for this profile</description>
    <inlineHelpText>The account of the org responsible for this profile</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Group&apos;s country</description>
    <inlineHelpText>Group&apos;s country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Date_of_last_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_last_grant__c</fullName>
    <formula>Account__r.Date_of_last_grant__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of last grant</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Amount_awarded__c.field-meta.xml
<CustomField>
    <fullName>Amount_awarded__c</fullName>
    <description>Actual amount awarded to the group (possibly over multiple payments)</description>
    <inlineHelpText>Actual amount awarded to the group (possibly over multiple payments)</inlineHelpText>
    <label>Amount awarded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The country where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_awarded__c</fullName>
    <description>Date on which the proposal becomes a grant</description>
    <inlineHelpText>Date on which the proposal becomes a grant</inlineHelpText>
    <label>Date awarded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this proposal is linked</description>
    <inlineHelpText>The profile to which this proposal is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CountryControllerTest.cls
@isTest
public class CountryControllerTest {
    static testMethod void CountryControllerTest() {
        // Build new records
        ProposalUpdateTest.buildTemplateMacros();
        insert new Region__c(Name = 'test region');
        Id rId = [SELECT Id FROM Region__c LIMIT 1].Id;
        insert new Country__c(Name = 'test country', Region__c = rId);
        Id cId = [SELECT Id FROM Country__c LIMIT 1].Id;
        insert new Account(
            Name = 'test account',
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'),
            GM_country__c = cId,
            GM_region__c = rId
        );
        Id aId = [SELECT Id FROM Account LIMIT 1].Id;
        Date date1 = Date.today();
        Date date2 = date1.addDays(1);
        insert new Proposal__c(
            Account__c = aId,
            Date_awarded__c = date1,
            Amount_awarded__c = 100
        );
        insert new Proposal__c(
            Account__c = aId,
            Date_awarded__c = date2,
            Amount_awarded__c = 50
        );
        Proposal__c[] ps = [SELECT Id, Country__c FROM Proposal__c];
        //system.debug('CountryControllerTest: ps = ' + JSON.serialize(ps));
        ProposalUpdate.updateProposal(ps[0].Id, true);
        ProposalUpdate.updateProposal(ps[1].Id, true);
        insert new Profile__c();

        Test.StartTest();
        CountryController.updateStatsFields(new List<Id>{ cId });
        Country__c c = [
            SELECT
                Id,
                Num_proposals__c,
                Num_grants__c,
                Num_profiles__c,
                Date_of_first_grant__c,
                Date_of_last_grant__c,
                Total_awarded__c
            FROM Country__c
            WHERE Id = :cId
            LIMIT 1
        ];
        system.assertEquals(2, c.Num_proposals__c);
        system.assertEquals(2, c.Num_grants__c);
        system.assertEquals(date1, c.Date_of_first_grant__c);
        system.assertEquals(date2, c.Date_of_last_grant__c);
        system.assertEquals(150, c.Total_awarded__c);

        // Schedule test of country stats update.
        String cronExp = '0 0 0 15 3 ?';
        String jobId = System.schedule(
            'ScheduleApexClassTest',
            cronExp,
            new CountryStatsSchedule()
        );

        Test.StopTest();
    }
}