force-app/main/default/objects/Account/fields/Date_of_first_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_first_grant__c</fullName>
    <description>Earliest date awarded for a grantee group (does not include &quot;award withdrawn&quot; grants)</description>
    <inlineHelpText>Earliest date awarded for a grantee group (does not include &quot;award withdrawn&quot; grants)</inlineHelpText>
    <label>Date of first grant</label>
    <summarizedField>Proposal__c.Date_awarded__c</summarizedField>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_of_last_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_last_grant__c</fullName>
    <description>Most recent date awarded for a grantee group (does not include &quot;award withdrawn&quot; grants)</description>
    <inlineHelpText>Most recent date awarded for a grantee group (does not include &quot;award withdrawn&quot; grants)</inlineHelpText>
    <label>Date of last grant</label>
    <summarizedField>Proposal__c.Date_awarded__c</summarizedField>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_grants__c.field-meta.xml
<CustomField>
    <fullName>Num_grants__c</fullName>
    <description>The number of grants linked to this account</description>
    <inlineHelpText>The number of grants linked to this account</inlineHelpText>
    <label>Num grants</label>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_proposals__c.field-meta.xml
<CustomField>
    <fullName>Num_proposals__c</fullName>
    <description>The number of proposals linked to this account</description>
    <inlineHelpText>The number of proposals linked to this account</inlineHelpText>
    <label>Num proposals</label>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_awarded__c.field-meta.xml
<CustomField>
    <fullName>Total_awarded__c</fullName>
    <description>The total of grants awarded to this group</description>
    <inlineHelpText>The total of grants awarded to this group</inlineHelpText>
    <label>Total awarded</label>
    <summarizedField>Proposal__c.Amount_awarded__c</summarizedField>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Represents a single country and grantmaking within that country.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Date_of_first_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_first_grant__c</fullName>
    <description>The date on which the first grant was awarded in this country</description>
    <inlineHelpText>The date on which the first grant was awarded in this country</inlineHelpText>
    <label>Date of first grant</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Date_of_last_grant__c.field-meta.xml
<CustomField>
    <fullName>Date_of_last_grant__c</fullName>
    <description>The date on which the latest grant was awarded in this country</description>
    <inlineHelpText>The date on which the latest grant was awarded in this country</inlineHelpText>
    <label>Date of last grant</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Num_grants__c.field-meta.xml
<CustomField>
    <fullName>Num_grants__c</fullName>
    <description>The number of grants awarded in this country</description>
    <inlineHelpText>The number of grants awarded in this country</inlineHelpText>
    <label>Num grants</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Num_profiles__c.field-meta.xml
<CustomField>
    <fullName>Num_profiles__c</fullName>
    <description>The number of profiles received from this country</description>
    <inlineHelpText>The number of profiles received from this country</inlineHelpText>
    <label>Num profiles</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Num_proposals__c.field-meta.xml
<CustomField>
    <fullName>Num_proposals__c</fullName>
    <description>The number of proposals received from this country</description>
    <inlineHelpText>The number of proposals received from this country</inlineHelpText>
    <label>Num proposals</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Total_awarded__c.field-meta.xml
<CustomField>
    <fullName>Total_awarded__c</fullName>
    <description>The total amount in USD of grants awarded in this country</description>
    <inlineHelpText>The total amount in USD of grants awarded in this country</inlineHelpText>
    <label>Total awarded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Amount_awarded__c.field-meta.xml
<CustomField>
    <fullName>Amount_awarded__c</fullName>
    <description>Actual amount awarded to the group (possibly over multiple payments)</description>
    <inlineHelpText>Actual amount awarded to the group (possibly over multiple payments)</inlineHelpText>
    <label>Amount awarded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The country where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_awarded__c</fullName>
    <description>Date on which the proposal becomes a grant</description>
    <inlineHelpText>Date on which the proposal becomes a grant</inlineHelpText>
    <label>Date awarded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <description>Checked if this proposal has been granted and hasn&apos;t been withdrawn</description>
    <formula>AND(
 NOT(ISBLANK(Date_awarded__c)), 
 ISBLANK(Date_award_withdrawn__c), 
 ISBLANK(Date_request_withdrawn__c), 
 ISBLANK(Date_declined__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Checked if this proposal has been granted and hasn&apos;t been withdrawn</inlineHelpText>
    <label>Grant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Payment_dependent_on_prior_grant__c.field-meta.xml
<CustomField>
    <fullName>Payment_dependent_on_prior_grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This proposal/grant can&apos;t be paid until the given prior grant has its milestone completed and approved.</description>
    <inlineHelpText>This proposal/grant can&apos;t be paid until the given prior grant has its milestone completed and approved.</inlineHelpText>
    <label>Payment dependent on prior grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Proposal__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Proposal__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Select a prior grant from the same account as this grant.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Proposals (dependency)</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CountryController.cls
public class CountryController {
    
    // Update grantmaking stats fields for given countries.
    public static void updateStatsFields (List<Id> countryIds) {
        Map<Id, Country__c> cMap = new Map<Id, Country__c> ([
            SELECT Id, Name, Date_of_first_grant__c, Date_of_last_grant__c, 
            Num_grants__c, Num_proposals__c, Num_profiles__c, Total_awarded__c,
            (SELECT Id, Date_awarded__c, Grant__c, Amount_awarded__c, Account__r.Name FROM Proposals__r)
            FROM Country__c
            WHERE Id IN : countryIds
        ]);
        
        // Loop through countries, assigning stats fields.
        for(Country__c c : cMap.values()) {
            c.Date_of_first_grant__c = null;
            c.Date_of_last_grant__c = null;
            c.Num_grants__c = 0;
            c.Num_proposals__c = 0;
            c.Total_awarded__c = 0;
            // Gather stats from child proposals.
            for(Proposal__c p : c.Proposals__r) {
                if(p.Account__r.Name.containsIgnoreCase('DONOTUSE')) continue;
                c.Num_proposals__c += 1;
                if(p.Grant__c && p.Amount_awarded__c != null && p.Date_awarded__c != null) {
                    c.Num_grants__c += 1;
                    c.Total_awarded__c += p.Amount_awarded__c;
                    system.debug('updateStatsFields props loop: before: c.Date_of_first_grant__c = ' +c.Date_of_first_grant__c+ '; c.Date_of_last_grant__c = ' +c.Date_of_last_grant__c+ '; p.Date_awarded__c = ' +p.Date_awarded__c);
                    if(c.Date_of_first_grant__c == null || p.Date_awarded__c < c.Date_of_first_grant__c)
                    	c.Date_of_first_grant__c = p.Date_awarded__c;
                    if(c.Date_of_last_grant__c == null || p.Date_awarded__c > c.Date_of_last_grant__c)
                    	c.Date_of_last_grant__c = p.Date_awarded__c;
                    system.debug('updateStatsFields props loop: after: c.Date_of_first_grant__c = ' +c.Date_of_first_grant__c+ '; c.Date_of_last_grant__c = ' +c.Date_of_last_grant__c);
                }
            }
        }
        if (cMap.size() > 0) update cMap.values();
    }

}