force-app/main/default/objects/Account/fields/FS_Group__c.field-meta.xml
<CustomField>
    <fullName>FS_Group__c</fullName>
    <description>FS Group to which this Account belongs based on Owner.</description>
    <formula>TEXT(Owner.FS_Group_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>FS Group to which this Account belongs based on Owner.</inlineHelpText>
    <label>FS Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GFW_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>GFW_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The GFW Account ID</description>
    <externalId>true</externalId>
    <label>GFW Account ID</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Log_Record__c.field-meta.xml
<CustomField>
    <fullName>Sync_Log_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sync Log Record created from sync that brought over source record from GFW.</description>
    <label>Sync Log Record</label>
    <referenceTo>Sync_Log_Record__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>false</active>
    <description>Entity made up of individuals.</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/FS_Group_Settings__mdt/FS_Group_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Settings for each FS group</description>
    <label>FS Group Settings</label>
    <pluralLabel>FS Group Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if this is an active FS group.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Designated_Role_for_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Designated_Role_for_Ownership__c</fullName>
    <description>Name of Role to use for assigning ownership of records for this FS group.</description>
    <label>Designated Role for Ownership</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/GFW_COA_Name__c.field-meta.xml
<CustomField>
    <fullName>GFW_COA_Name__c</fullName>
    <description>Name of relevant Chart of Account record in GFW db.</description>
    <label>GFW COA Name</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sync_Log__c/Sync_Log__c.object-meta.xml
<CustomObject>
    <description>Logging of Sync results</description>
    <label>Sync Log</label>
    <nameField>
        <displayFormat>SL-{0000}</displayFormat>
        <label>Sync Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Log__c/fields/FS_Group__c.field-meta.xml
<CustomField>
    <fullName>FS_Group__c</fullName>
    <description>Name of FS group</description>
    <label>FS Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of sync operation</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of sync operation</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/Sync_Log_Record__c.object-meta.xml
<CustomObject>
    <label>Sync Log Record</label>
    <nameField>
        <displayFormat>SLR-{0000}</displayFormat>
        <label>Sync Log Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Log Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Log_Record__c/fields/FS_Group__c.field-meta.xml
<CustomField>
    <fullName>FS_Group__c</fullName>
    <description>Name of fiscally sponsored group</description>
    <label>FS Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/fields/FSGroupOwnerId__c.field-meta.xml
<CustomField>
    <fullName>FSGroupOwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field for setting OwnerId of new records so they belong to FS Group.</description>
    <label>FSGroupOwnerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sync_Log_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/fields/RecordInfo__c.field-meta.xml
<CustomField>
    <fullName>RecordInfo__c</fullName>
    <description>Stores json of record from GFW</description>
    <label>Record Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of sync log record: Pending, Success or Error</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/fields/Sync_Log__c.field-meta.xml
<CustomField>
    <fullName>Sync_Log__c</fullName>
    <description>Parent Sync Log record</description>
    <label>Sync Log</label>
    <referenceTo>Sync_Log__c</referenceTo>
    <relationshipLabel>Sync Log Records</relationshipLabel>
    <relationshipName>Sync_Log_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Set to custom metadata type object mapping name</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Sync_BatchableUpsertTest.cls
@isTest
public without sharing class Sync_BatchableUpsertTest {

    @TestSetup
    static void makeData(){
        // Create user for owner
        String emluname = 'user@name.org';
        Id pId = [SELECT Id FROM Profile WHERE Name =  'System Administrator' LIMIT 1].Id;
        User u = new User(
            Username = emluname,
            Email = emluname,
            CommunityNickname = emluname.left(4),
            LastName = 'testOwner',
            FirstName = 'testOwner',
            Alias = emluname.left(4),
            ProfileId = pId,
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'GMT'
        );
        insert u;
        
        // Set up Sync Log and Sync Log Records
        List<FS_Group_Settings__mdt> fsGroups = [SELECT GFW_COA_Name__c, Designated_Role_for_Ownership__c
        FROM FS_Group_Settings__mdt WHERE Active__c = TRUE];
        String json = '' +
        '{"Name":"Jane Doe","RecordType":{' +
        '"DeveloperName":"Household","attributes":{' +
        '"url":"/services/data/v48.0/sobjects/RecordType/012i0000000HNlOAAW","type":"RecordType"}},' +
        '"AQB__AccountType__c":"Household","Id":"0011Y00002LvEcKQAV","attributes":'+
        '{"url":"/services/data/v48.0/sobjects/Account/0011Y00002LvEcKQAV","type":"Account"}}';

        Sync_Log__c sLog = new Sync_Log__c(
            Type__c = 'GFW to FSDB',
            Status__c = 'Launched'
        );
        insert sLog;

        Sync_Log_Record__c slRec = new Sync_Log_Record__c(
            RecordInfo__c = json,
            Sync_Log__c = sLog.Id,
            Status__c = 'Pending',
            Type__c = 'Account',
            FSGroupOwnerId__c = u.Id,
            FS_Group__c = fsGroups[0].GFW_COA_Name__c
        );
        insert slRec;
    }

    @isTest
    static void Sync_BatchableUpsertTest() {
        
        Test.startTest();

        // Execute batch for Account
        List<String> objNames = new List<String>{'Account'};
        Id batchInstanceId = Database.executeBatch(new Sync_BatchableUpsert(objNames), 5);
        System.debug('batchInstanceId: ' + batchInstanceId);

        Test.stopTest();

        List<Sync_Log_Record__c> logRecs = [SELECT Id, Name FROM Sync_Log_Record__c WHERE Status__c = 'Success' AND Type__c = 'Account'];
        system.assertEquals(logRecs.size(), 1);
        List<Account> accts = [SELECT Id, Name, GFW_Account_ID__c, RecordType.Name FROM Account];
        system.debug('acct name: ' + accts[0].Name);
        system.assertEquals(logRecs.size(), accts.size());
        system.assertEquals('Household Account', accts[0].RecordType.Name);
        system.assertEquals('0011Y00002LvEcKQAV', accts[0].GFW_Account_ID__c);

    }
}