force-app/main/default/objects/Account/fields/GFW_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>GFW_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The GFW Account ID</description>
    <externalId>true</externalId>
    <label>GFW Account ID</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Log_Record__c.field-meta.xml
<CustomField>
    <fullName>Sync_Log_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sync Log Record created from sync that brought over source record from GFW.</description>
    <label>Sync Log Record</label>
    <referenceTo>Sync_Log_Record__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/FS_Group_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Settings for each FS group</description>
    <label>FS Group Settings</label>
    <pluralLabel>FS Group Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if this is an active FS group.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/Designated_Role_for_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Designated_Role_for_Ownership__c</fullName>
    <description>Name of Role to use for assigning ownership of records for this FS group.</description>
    <label>Designated Role for Ownership</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Group_Settings__mdt/fields/GFW_COA_Name__c.field-meta.xml
<CustomField>
    <fullName>GFW_COA_Name__c</fullName>
    <description>Name of relevant Chart of Account record in GFW db.</description>
    <label>GFW COA Name</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/Sync_Log_Record__c.object-meta.xml
<CustomObject>
    <label>Sync Log Record</label>
    <nameField>
        <displayFormat>SLR-{0000}</displayFormat>
        <label>Sync Log Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Log Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Log_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of sync log record: Pending, Success or Error</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Set to custom metadata type object mapping name</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Sync_QueueableTest.cls
@isTest
public without sharing class Sync_QueueableTest {

    @isTest
    static void QueueableTest() {
        
        Test.setMock(HttpCalloutMock.class, new SyncMock());

        Test.startTest();

        List<FS_Group_Settings__mdt> fsGroups = [SELECT GFW_COA_Name__c, Designated_Role_for_Ownership__c
        FROM FS_Group_Settings__mdt WHERE Active__c = TRUE LIMIT 1];

        // Runs first part of Queueable that launches sync
        System.enqueueJob(new Sync_Queueable(fsGroups));

        // Runs second part of Queueable that upserts Accounts when running tests 
        System.enqueueJob(new Sync_Queueable(null));

        Test.stopTest();

        List<Sync_Log_Record__c> logRecs = [SELECT Id, Name FROM Sync_Log_Record__c WHERE Status__c = 'Success' AND Type__c = 'Account'];
        system.assert(logRecs.size()>0);
        List<Account> accts = [SELECT Id, Name, GFW_Account_ID__c FROM Account];
        system.assert(accts.size()>0);
        system.assertEquals(logRecs.size(), accts.size());
    }
}