force-app/main/default/objects/Account/fields/GM_country__c.field-meta.xml
<CustomField>
    <fullName>GM_country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country where this organization does its work (not necessarily its mailing country)</description>
    <inlineHelpText>The country where this organization does its work (not necessarily its mailing country)</inlineHelpText>
    <label>GM country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GM_Email__c.field-meta.xml
<CustomField>
    <fullName>GM_Email__c</fullName>
    <description>Primary email address for this account (for grantmaking-related correspondence)</description>
    <externalId>true</externalId>
    <inlineHelpText>Primary email address for this account (for grantmaking-related correspondence)</inlineHelpText>
    <label>GM Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>false</active>
    <description>Entity made up of individuals.</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>Alternate email address</description>
    <inlineHelpText>Alternate email address</inlineHelpText>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <defaultValue>/* Default GM contacts to rank 1, Dev contacts to blank. */
IF(CONTAINS($RecordType.DeveloperName, &quot;GM&quot;), 1, null)</defaultValue>
    <description>Used to sort contacts within an account, for example, to pick the primary one</description>
    <inlineHelpText>Used to sort contacts within an account, for example, to pick the primary one</inlineHelpText>
    <label>Rank</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_GM.recordType-meta.xml
<RecordType>
    <fullName>Contact_GM</fullName>
    <active>true</active>
    <description>For grantmaking-related contact records, primarily staff at grantee/applicant orgs</description>
    <label>Contact GM</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Represents a single country and grantmaking within that country.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Enclosing region for this country</description>
    <inlineHelpText>Enclosing region for this country</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Countries</relationshipLabel>
    <relationshipName>Countries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The country where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the request/grant</description>
    <inlineHelpText>Description of the request/grant</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BuildTestProposals.cls
public with sharing class BuildTestProposals {
    // Grab account record type Ids.
    public static Id householdRtId = Utilities.getRecTypeId(
        'Account',
        'Household'
    );
    public static Id organizationRtId = Utilities.getRecTypeId(
        'Account',
        'Organization_GM'
    );

    // Prepare the specified number of proposals and accounts.  Include one contact per account.
    // The proposals are distributed evenly among the number of accounts specified.
    public static void InitTestObjects(
        Integer NumberOfProposals,
        Integer NumberOfAccounts
    ) {
        insert new Region__c(Name = 'test region');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Country__c(Name = 'test country', Region__c = reg.Id);
        Country__c cnt = [SELECT Id FROM Country__c LIMIT 1];
        List<Account> accts = new List<Account>();
        for (Integer x = 0; x < NumberOfAccounts; x++) {
            accts.add(
                new Account(
                    Name = 'ptest_acct_' + String.valueOf(x),
                    GM_Country__c = cnt.Id,
                    GM_email__c = 'ptestAcct' +
                        String.valueOf(x) +
                        '@ptest.org',
                    RecordTypeId = organizationRtId
                )
            );
        }
        insert accts;
        List<Account> accounts = new List<Account>(
            [SELECT Id, Name FROM Account]
        );

        List<Contact> cts = new List<Contact>();
        for (Integer x = 0; x < NumberOfAccounts; x++) {
            cts.add(
                new Contact(
                    LastName = 'ptest_' + String.valueOf(x),
                    AccountId = accounts[x].Id,
                    Rank__c = 1,
                    Email = 'ptest_' + String.valueOf(x) + '@ptest.org',
                    Email2__c = 'ptest_' + String.valueOf(x) + '@ptest.org',
                    RecordTypeId = Utilities.getRecTypeId('Contact', 'Contact_GM')
                )
            );
        }
        insert cts;
        List<Contact> contacts = new List<Contact>(
            [SELECT AccountId, LastName FROM Contact]
        );

        // Build and insert proposals linked to appropriate accounts.
        List<Proposal__c> ps = new List<Proposal__c>();
        Integer acctnumber = 0;
        for (Integer x = 0; x < NumberOfProposals; x++) {
            ps.add(
                new Proposal__c(
                    Account__c = accounts[acctnumber].Id,
                    Description__c = 'Description: ' + x
                    // Add other field assignments for proposals
                )
            );
            acctnumber++;
            if (acctnumber >= NumberOfAccounts)
                acctnumber = 0;
        }
        insert ps;
    }
}