force-app/main/default/objects/Account/fields/GM_country__c.field-meta.xml
<CustomField>
    <fullName>GM_country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country where this organization does its work (not necessarily its mailing country)</description>
    <inlineHelpText>The country where this organization does its work (not necessarily its mailing country)</inlineHelpText>
    <label>GM country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>false</active>
    <description>Entity made up of individuals.</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Household_GM_Advisor.recordType-meta.xml
<RecordType>
    <fullName>Household_GM_Advisor</fullName>
    <active>true</active>
    <description>Household account record used for Advisors</description>
    <label>Household GM Advisor</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Advisor__c/Advisor__c.object-meta.xml
<CustomObject>
    <description>Holds information about an advisor&apos;s interests, region of expertise.  Links from letters, endorsements and advisor terms.</description>
    <label>Advisor</label>
    <nameField>
        <label>Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The account, either household or organization, containing mailing information for this advisor</description>
    <inlineHelpText>The account, either household or organization, containing mailing information for this advisor</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact record with contact information for this advisor</description>
    <inlineHelpText>The contact record with contact information for this advisor</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <description>Old email address(es) from Filemaker. Do not use. Emails should be entered in the linked contact record (for indivs) or at the Org level (for &quot;Org advisors&quot;).</description>
    <inlineHelpText>Old email address(es) from Filemaker. Do not use. Emails should be entered in the linked contact record (for indivs) or at the Org level (for &quot;Org advisors&quot;).</inlineHelpText>
    <label>Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/Global__c.field-meta.xml
<CustomField>
    <fullName>Global__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if this advisor has global expertise/interests</description>
    <inlineHelpText>Checked if this advisor has global expertise/interests</inlineHelpText>
    <label>Global</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>The language prefered by this advisor (for correspondence)</description>
    <inlineHelpText>The language prefered by this advisor (for correspondence)</inlineHelpText>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program of expertise of this advisor</description>
    <inlineHelpText>Program of expertise of this advisor</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of advisor (including official, informal, reference)</description>
    <inlineHelpText>Type of advisor (including official, informal, reference)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Official</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/Advisor_Term__c.object-meta.xml
<CustomObject>
    <description>Represents a term of an official GFW advisor</description>
    <label>Advisor Term</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Advisor Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisor Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor_Term__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <description>Parent advisor of this advisor term</description>
    <inlineHelpText>Parent advisor of this advisor term</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>Advisor__c</referenceTo>
    <relationshipLabel>Advisor Terms</relationshipLabel>
    <relationshipName>Advisor_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this advisor term, that is, the role of the advisor for the duration of this advisor term. Normally populated on acceptance.</description>
    <inlineHelpText>The type of this advisor term, that is, the role of the advisor for the duration of this advisor term. Normally populated on acceptance.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Advisor_term_types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/recordTypes/Endorser.recordType-meta.xml
<RecordType>
    <fullName>Endorser</fullName>
    <active>true</active>
    <description>An advisor term during which endorsements may be requested from the advisor</description>
    <label>Endorser</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <defaultValue>/* Default GM contacts to rank 1, Dev contacts to blank. */
IF(CONTAINS($RecordType.DeveloperName, &quot;GM&quot;), 1, null)</defaultValue>
    <description>Used to sort contacts within an account, for example, to pick the primary one</description>
    <inlineHelpText>Used to sort contacts within an account, for example, to pick the primary one</inlineHelpText>
    <label>Rank</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>A picklist of the highest level categorization of this contact. The category can be further described in the Secondary Type field.</inlineHelpText>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Friend</fullName>
                <default>true</default>
                <label>Friend</label>
            </value>
            <value>
                <fullName>Corporate Contact</fullName>
            </value>
            <value>
                <fullName>Alumnus</fullName>
            </value>
            <value>
                <fullName>Institutional Proxy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_GM.recordType-meta.xml
<RecordType>
    <fullName>Contact_GM</fullName>
    <active>true</active>
    <description>For grantmaking-related contact records, primarily staff at grantee/applicant orgs</description>
    <label>Contact GM</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact_GM_Advisor.recordType-meta.xml
<RecordType>
    <fullName>Contact_GM_Advisor</fullName>
    <active>true</active>
    <description>For contact records of advisors</description>
    <label>Contact GM Advisor</label>
</RecordType>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Account_owner__c.field-meta.xml
<CustomField>
    <fullName>Account_owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cached lookup relationship to the account owner. Necessary because can&apos;t reach through the polymorphic Account.Owner link.</description>
    <inlineHelpText>Cached lookup relationship to the account owner. Necessary because can&apos;t reach through the polymorphic Account.Owner link.</inlineHelpText>
    <label>Account owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advisor to which this letter is linked</description>
    <inlineHelpText>Advisor to which this letter is linked</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>Advisor__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact linked to this letter</description>
    <inlineHelpText>Contact linked to this letter</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <description>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</description>
    <inlineHelpText>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</inlineHelpText>
    <label>Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language in which this letter is written</description>
    <formula>IF (NOT(ISBLANK(TEXT( Account__r.Correspondence_language__c ))), 
  TEXT(Account__r.Correspondence_language__c),
IF (NOT(ISBLANK(TEXT( Profile__r.Language__c ))), 
  TEXT(Profile__r.Language__c),
&quot;English&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Language in which this letter is written</inlineHelpText>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Letter_owner__c.field-meta.xml
<CustomField>
    <fullName>Letter_owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cached lookup relationship to the letter owner. Necessary because can&apos;t reach through the polymorphic Letter.Owner link.</description>
    <inlineHelpText>Cached lookup relationship to the letter owner. Necessary because can&apos;t reach through the polymorphic Letter.Owner link.</inlineHelpText>
    <label>Letter owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Letters1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</description>
    <inlineHelpText>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Advisor assignments</fullName>
            </value>
            <value>
                <fullName>Saved Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Advisor_term_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Expert</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>Assessor</fullName>
    </customValue>
    <customValue>
        <fullName>View forms</fullName>
    </customValue>
    <description>The types of advisor terms</description>
    <masterLabel>Advisor term types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AdvisorController.cls
public class AdvisorController {

    private ApexPages.StandardController standardController;
    private ApexPages.StandardSetController standardSetController;
 
    public AdvisorController(ApexPages.StandardController standardController) {
        this.standardController = standardController;
    }
 
    public AdvisorController(ApexPages.StandardSetController standardSetController) {
        this.standardSetController = standardSetController;
    }
    
    // Build the menu of admissible correspondence templates for this object. 
    private static String objectName = 'Advisor__c';
    private static final String START = '--Select Template--';
    public List<selectOption> templates { get; private set; } { templates = Utilities.templatesForObject(objectName, START); }
    public String selectedTemplate {get; set;} { selectedTemplate = START; }


    // Get selected records, then build and reset letters for them.
    public PageReference buildLetters() {
        // Generate error if no selected template - assign error to the templateType field.
        if (selectedTemplate == null || selectedTemplate == START) {
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a template', 'Must select a template before building new letters'));
            selectedTemplate = START; // If I don't reset to the START value, it gets set to one of the non-disabled values. 
            return null;
        }
        // Get Selected Record IDs from Controller
        Set<Id> selIds;
        if (standardSetController != null) {
            Map<Id, Advisor__c> selMap = new Map<Id, Advisor__c> ((List<Advisor__c>) standardSetController.getSelected());
            selIds = selMap.keySet();
        } else {
            selIds = new Set<Id> {standardController.getId()};
        }

        // Pass selections to the letter builder
        Map < String, String > customParams = new Map < String, String >{'isEmail'=>'false'};
        List<Letter__c> ls = buildLetters0(selIds, selectedTemplate, customParams); //Not emails
        
        // Changes have been saved; jump to the new letter if there's only one.
        if(standardController != null && ls.size() == 1) return Utilities.pageReferenceForRecord(ls[0]);
        else return doCancel(); // Stay in current layout.
    }


    public static List<Letter__c> buildLetters0(Set<Id> selIds, ID templateId, Map < String, String > customParams) {

        //Set email flag from params
        Boolean emailFlg = false;
        if (customParams.containsKey('isEmail') && customParams.get('isEmail')=='true') {
            emailFlg = true;
        }
                
        // Query for data to build the letters
        Map<Id, Advisor__c> selMap = new Map<Id, Advisor__c> ([
            SELECT Id, Account__c, Account__r.OwnerId, Contact__c,
            Program__c, Emails__c, Contact__r.Email, Contact__r.AQB__OtherEmail__c
            FROM Advisor__c
            WHERE Id IN : selIds
        ]);
        // Gather email addresses from the advisor accounts.
        Set<Id> accIds = new Set<Id> ();
        for (Advisor__c adv : selMap.values()) accIds.add(adv.Account__c);
        Map<Id, List<String>> accEmails = Utilities.emailsForAccounts(accIds);
        system.debug('buildLetters: accEmails = ' +JSON.serialize(accEmails));
        // Build new letters for selected records.
        List<Letter__c> ls = new List<Letter__c>();
        for (Advisor__c r : selMap.values()) {
            Id accId = r.Account__c;
            String emails = accId != null && accEmails.get(accId) != null ? String.join(Utilities.removeNulls(accEmails.get(accId)), ',') : null;
            Letter__c let = new Letter__c (
                Template__c = templateId,
                Account__c = r.Account__c,
                Account_owner__c = r.Account__r.OwnerId,
                Letter_owner__c = UserInfo.getUserId(),
                Advisor__c = r.Id,
                Contact__c = r.Contact__c,
                Program__c = r.Program__c,
                Emails__c = emails
            );
            // update any additional values from the map
            let = LetterController.updateWithParams(let, customParams);
            ls.add(let);
        }
        System.debug('letters:'+JSON.serialize(ls));
        insert ls;
        Map<Id, Letter__c> lsMap = new Map<Id, Letter__c> (ls);
        // Reset the new letters.
        LetterController.resetLetters0(lsMap.keySet(), emailFlg);
        return ls;
    }
    
    // Build a new endorsement request and join records for selected advisors.
    public PageReference buildEndorseRequest() {
        Set<Id> selIds = getSelectedIds();
        Map<Id, Advisor__c> selMap = new Map<Id, Advisor__c> ([
            SELECT Id
            FROM Advisor__c
            WHERE Id IN : selIds
        ]);
        // Build empty endorse request record.
        Endorse_Request__c er = new Endorse_Request__c();
        insert er;
        // Build a join record for each advisor.
        List<Endorse_Request_Advisor__c> erjs = new List<Endorse_Request_Advisor__c>();
        for (Advisor__c a : selMap.values()){
            erjs.add(new Endorse_Request_Advisor__c (
                Advisor__c = a.Id,
                Endorse_Request__c = er.Id
            ));
        }
        insert erjs;
        // Changes have been saved; jump to the new endorse request record.
        return Utilities.pageReferenceForRecord(er);
    }
    
    private Set<Id> getSelectedIds() {
        Set<Id> selIds;
        if (standardSetController != null) {
            Map<Id, Advisor__c> selMap = new Map<Id, Advisor__c> ((List<Advisor__c>) standardSetController.getSelected());
            selIds = selMap.keySet();
        } else {
            selIds = new Set<Id> {standardController.getId()};
        }
        return selIds;
    }
    
    public PageReference doCancel() {       
        return (standardSetController != null) ? standardSetController.cancel() : standardController.cancel();   
    }
    
    /**********************************
     * For use in Lightning components
     *********************************/
    
    public class AdvException extends Exception {}
    public static Id recTypeIdContactGM = Utilities.getRecTypeId('Contact', 'Contact_GM');
    public static Id recTypeIdContactAdv = Utilities.getRecTypeId('Contact', 'Contact_GM_Advisor');
    public static Id recTypeIdAcctHouseholdAdv = Utilities.getRecTypeId('Account', 'Household_GM_Advisor');
    public static Id recTypeIdAcctOrgGM = Utilities.getRecTypeId('Account', 'Organization_GM');
    public static String communityAccountName = 'GFW Community Members Advisors';
    public static String grantCommunityProfileName = 'GFW community member';
    public static String advisorCommunityProfileName = 'GFW community member Advisor';
    public static String standardUserGMProfileName = 'Standard User GM';
    public static String advisorCommunityPermSetName = 'Community: Advisors';
    
    // Build three interlinked records: Advisor, Contact, Account (household), Advisor Term, and optionally a GM Org account for org affiliation.
    @AuraEnabled
    public static String buildAdvisorRecs(String jsonString) {
        strike_responseData responseData = new strike_responseData();
        try {
            system.debug('buildAdvisorRecs: jsonString = ' +jsonString);
            Map<String, Object> jsonMap = (Map<String, Object>)JSON.deserializeUntyped(jsonString);
            String firstName = (String)jsonMap.get('firstName');
            String lastName = (String)jsonMap.get('lastName');
            String termRecordType = (String)jsonMap.get('advisorTermRecordType');
            String termType = (String)jsonMap.get('advisorTermType');
            Date advisorTermStartDate = jsonMap.get('advisorTermStartDate') != null ? Date.valueOf((String)jsonMap.get('advisorTermStartDate')) : null;
            Date advisorTermEndDate = jsonMap.get('advisorTermEndDate') != null ? Date.valueOf((String)jsonMap.get('advisorTermEndDate')) : null;
            system.debug('buildAdvisorRecs: advisorTermStartDate = ' +advisorTermStartDate+ '; advisorTermEndDate = ' +advisorTermEndDate);
            String advName = firstName +' '+ lastName;
            Account advAcct = new Account (
                RecordTypeId = recTypeIdAcctHouseholdAdv,
                Name = advName
            );
            insert advAcct;
            system.debug('buildAdvisorRecs: advAcct = ' +JSON.serialize(advAcct));
            // Build org affiliation account if necessary.
            Account orgAffilAcct;
            Id orgAffilAcctId = idFromJSON(jsonMap, 'orgAffilAcctId');
            String orgAffilName = (String)jsonMap.get('orgAffilName');
            system.debug('buildAdvisorRecs: orgAffilAcctId = ' +orgAffilAcctId+ '; orgAffilName = ' +orgAffilName);
            if (orgAffilAcctId == null && orgAffilName != null) {
                orgAffilAcct = new Account (
                    RecordTypeId = recTypeIdAcctOrgGM,
                    Name = orgAffilName,
                    GM_country__c = idFromJSON(jsonMap, 'countryId')                    
                );
                insert orgAffilAcct;
                orgAffilAcctId = orgAffilAcct.Id;
            } else if (orgAffilAcctId != null && orgAffilName == null) {
                orgAffilAcct = [SELECT Name FROM Account WHERE Id = : orgAffilAcctId];
                orgAffilName = orgAffilAcct.Name;
            }
            system.debug('buildAdvisorRecs: orgAffilAcct = ' +JSON.serialize(orgAffilAcct));
            Contact advCon = new Contact (
                RecordTypeId = recTypeIdContactAdv,
                AccountId = advAcct.Id,
                FirstName = firstName,
                LastName = lastName,
                Email = (String)jsonMap.get('email'),
                Title = (String)jsonMap.get('title'),
                Rank__c = 1
            );
            insert advCon;
            system.debug('buildAdvisorRecs: advCon = ' +JSON.serialize(advCon));
            // 2/7/20: Note that Type__c field of Advisor will be retired or significantly modified at some point.
            Advisor__c adv = new Advisor__c (
                Name = advName,
                Type__c = termType == 'Strategic' ? 'Official' : termType == 'Expert' ? 'Informal' : termType,
                Language__c = (String)jsonMap.get('language'),
                Program__c = idFromJSON(jsonMap, 'programId'),
                Global__c = (String)jsonMap.get('global') == 'true' ? true : false,
                Account__c = advAcct.Id,
                Contact__c = advCon.Id,
                GM_org_affiliation__c = orgAffilAcctId
            );
            insert adv;
            system.debug('buildAdvisorRecs: adv = ' +JSON.serialize(adv));
            Advisor_Term__c advt = new Advisor_Term__c (
                RecordTypeId = Utilities.getRecTypeId('Advisor_Term__c', termRecordType),
                Advisor__c = adv.Id,
                Type__c = termRecordType == 'Endorser' && termType == 'Reference' ? 'Reference' : null,
                Type_invited__c = termRecordType == 'Endorser' && termType != 'Reference' ? termType : null,
                Date_term_begins__c = advisorTermStartDate != null ? advisorTermStartDate : Date.today(),
                Date_term_ends__c = termRecordType == 'Endorser' && termType == 'Reference' ? null : advisorTermEndDate,
                Portfolio__c = idFromJSON(jsonMap, 'portfolioId')
            );
            insert advt;
            system.debug('buildAdvisorRecs: advt = ' +JSON.serialize(advt));
            advt = [SELECT Id, Name FROM Advisor_Term__c WHERE Id = :advt.Id];
            responseData.results = new Map<String, Object> {
                'advisorId' => adv.Id,
                'accountId' => advAcct.Id,
                'contactId' => advCon.Id,
                'orgAffilAcctId' => orgAffilAcctId,
                'orgAffilName' => orgAffilName,
                'name' => advName,
                'advisorTermId' => advt.Id,
                'advisorTermName' => advt.Name
            };
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        
        return responseData.getJsonString();
    }

    // Test for empty string (as opposed to null) so casting to id doesn't break.
    private static Id idFromJSON (Map<String, Object> jsonMap, String attr) {
        if (jsonMap.get(attr) == null) return null;
        String valStr = (String) jsonMap.get(attr);
        return valStr == '' ? null : Id.valueOf(valStr); 
    }

    // Fetch profile and permission sets of current user.
    @AuraEnabled
    public static String fetchProfileAndPermissionSets() {
        strike_responseData responseData = new strike_responseData();
        try {
            responseData.results = new Map<String, Object> {
                'profile' => Utilities.currentUserProfileName(),
                'permissionSets' => Utilities.currentUserPermissionSetNames()
            };
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        system.debug('fetchProfileAndPermissionSets: responseData = ' +JSON.serialize(responseData));
        return responseData.getJsonString();
    }

    // Add given advisor to the Advisors community.
    @AuraEnabled
    public static String addAdvisorToCommunity(String jsonString) {
        strike_responseData responseData = new strike_responseData();
        try {
            system.debug('addAdvisorToCommunity: jsonString = ' +jsonString);
            Map<String, Object> jsonMap = (Map<String, Object>)JSON.deserializeUntyped(jsonString);
            Id advId = Id.valueOf((String)jsonMap.get('advisorId'));
            Advisor__c adv = [
                SELECT Id, Name, Contact__c, Contact__r.Email, Contact__r.FirstName, Contact__r.LastName, Community_contact__c
                FROM Advisor__c
                WHERE Id = : advId
            ];
            system.debug('addAdvisorToCommunity: adv = ' +JSON.serialize(adv));
            // Currently, this only works for individual advisors whose contact records have emails and who aren't already online.
            if (advId == null || adv.Community_contact__c != null || adv.Contact__c == null || adv.Contact__r.Email == null) 
                throw new AdvException ('Advisor already in community or not individual or has blank email');
            // Look up community profile/account.
            Id commAccId = [SELECT Id FROM Account WHERE Name = : communityAccountName LIMIT 1].Id;
            Id pIdGrnt = [SELECT Id FROM Profile WHERE Name = : grantCommunityProfileName LIMIT 1].Id;
            Id pIdAdv = [SELECT Id FROM Profile WHERE Name = : advisorCommunityProfileName LIMIT 1].Id;
            Id psIdAdv = [SELECT Id FROM PermissionSet WHERE Label = : advisorCommunityPermSetName LIMIT 1].Id;
            String email = adv.Contact__r.Email;
            String username = advisorUsernameFromEmail(email);
            // User/Contact will either already exist or be created here.
            User u; 
            Contact c;
            // See if there's already a user with that email as username. (There should be at most one.)
            User[] users = [SELECT Id, ContactId, ProfileId, Username FROM User WHERE Username = : username];
            if (users.size() > 0) u = users[0];
            system.debug('addAdvisorToCommunity: u = ' +JSON.serialize(u));
            if (u != null) { // Don't allow reuse of existing username
                // Username already belongs to a community.
                if (u.ProfileId == pIdAdv) throw new AdvException ('Advisor contact username (' +username+ ') is already a username in advisor community.');
                if (u.ProfileId == pIdGrnt) throw new AdvException ('Advisor contact username (' +username+ ') is a username in grantmaking community.');
                if (u.ContactId != null) throw new AdvException ('Advisor contact username (' +username+ ') is a username linked to a community contact.');
                throw new AdvException ('Advisor contact username (' +username+ ') is the username of an existing user record.');
            } else {
                // Build the new user with advisor community profile.
                u = new User(
                    Username = username,
                    Email = email,
                    //CompanyName = orgName.left(80),
                    CommunityNickname = username.left(40),
                    LastName = adv.Contact__r.LastName != null ? adv.Contact__r.LastName.left(40) : null,
                    FirstName = adv.Contact__r.FirstName != null ? adv.Contact__r.FirstName.left(40) : null,
                    Alias = email.toLowerCase().left(4),
                    ProfileId = pIdAdv,
                    EmailEncodingKey = 'UTF-8',
                    LanguageLocaleKey = 'en_US',
                    LocaleSidKey = 'en_US',
                    TimeZoneSidKey = 'GMT'
                );
                system.debug('addAdvisorToCommunity: u = ' +JSON.serialize(u));
            }
            // If no contact, then build a new one in the community account.
            if (c == null) {
                c = new Contact(
                    RecordTypeId = recTypeIdContactGM,
                    AccountId = commAccId,
                    AQB__Type__c = 'Friend',
                    Email = email,
                    Online_email__c = email,
                    AQB__EmailPreference__c = 'Online Email',
                    LastName = adv.Contact__r.LastName,
                    FirstName = adv.Contact__r.FirstName
                );
                system.debug('addAdvisorToCommunity: c = ' +JSON.serialize(c));
                insert c;
            }
            // Insert new user or update existing one.
            if (u.ContactId != c.Id) {
                u.ContactId = c.Id; // Link user to new community contact.
                if (u.Id == null) insert u;
                else update u; // Not sure if it's actually possible to hit this else clause, given conditions on u and c above.
            } 
            if (u.ProfileId == pIdGrnt) {
                // User is in grants community profile, so assign the advisors community permission set (so user is in both communities).
                assignPermissionSet(u.Id, psIdAdv);
            }
            // Link advisor to community contact.
            adv.Community_contact__c = c.Id;
            adv.Community_contact_username__c = username;
            update adv;
            responseData.results = new Map<String, Object> {
                // Note that we can't return id of new user, if any, since it was created in a separate transaction.
                'userName' => u.Username
            };
        } catch (Exception e) {
            if (e.getMessage() != 'SUCCESS') responseData.addError(e.getMessage());
        }
        system.debug('addAdvisorToCommunity: responseData = ' +JSON.serialize(responseData));
        return responseData.getJsonString();
    }
    
    // Future method to assign user to a permission set (future is to avoid Mixed DML operations error).
    @future
    public static void assignPermissionSet(Id userId, Id permSetId) {
        system.debug('assignPermissionSet: userId = ' +userId+ '; permSetId = ' +permSetId);
        insert new PermissionSetAssignment (PermissionSetId = permSetId, AssigneeId = userId);
    }

    // Fetch org advisors linked to account, if any.
    @AuraEnabled(cacheable=true)
    public static Advisor__c[] advisorsFromAccount(Id accountId) {
        Advisor__c[] advs = [SELECT Id, Name FROM Advisor__c WHERE Account__c = : accountId];
        system.debug('advisorsFromAccount: advs = ' +JSON.serialize(advs));
        return advs;
    }
    
    /**********************************
     * For general use
     *********************************/
    
    // Ensure that the Current Endorser Term lookup field is up to date. 
    public static void updateLookups (Id advisorId) {
        Id currentEndorserTermId;
        Date today = Date.today();
        Advisor__c adv = [
            SELECT Current_endorser_term__c, Active__c, 
            (SELECT Id, Status__c 
            FROM Advisor_Terms__r 
            WHERE RecordType.Name = 'Endorser' 
            )
            FROM Advisor__c
            WHERE Id = :advisorId
        ];
        system.debug('updateLookups: adv = ' +JSON.serialize(adv));
        // If advisor is active, look for an active endorser advisor term.  There should be at most one!
        if (adv.Active__c) {
            for (Advisor_Term__c advt : adv.Advisor_Terms__r) {
                if (advt.Status__c.toLowerCase().contains('active')) currentEndorserTermId = advt.Id;
            }
        }
        if (adv.Current_endorser_term__c != currentEndorserTermId) {
            adv.Current_endorser_term__c = currentEndorserTermId;
            update adv;
        }
    }
    
    // The advisor's username is their email with the prefix ADV-.
    public static String advisorUsernameFromEmail (String email) {
        return 'ADV-' + email;
    }

    //Only call when in the context of an Advisor Experience Site User
    public static String getRunningUserAdvisorId() {
        try {
            ID userId = UserInfo.getUserId();
            User u = [SELECT Id, FirstName, LastName, Email, ContactId FROM User WHERE Id=:userId];
            Advisor__c runningAdvisor = [SELECT ID FROM Advisor__c WHERE Community_contact__c =:u.ContactId LIMIT 1];
            return runningAdvisor.Id;
        } catch (Exception e) {
            throw new GFW_Exception('AdvisorController.getRunningUserAdvisorId', 'Could not load Advisor Record', e);
        }
        
    }

}