force-app/main/default/objects/Account/fields/GM_country__c.field-meta.xml
<CustomField>
    <fullName>GM_country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country where this organization does its work (not necessarily its mailing country)</description>
    <inlineHelpText>The country where this organization does its work (not necessarily its mailing country)</inlineHelpText>
    <label>GM country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organization_GM_FS.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM_FS</fullName>
    <active>true</active>
    <description>Organizations that act as fiscal sponsors for our grants</description>
    <label>Organization GM FS</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <defaultValue>/* Default GM contacts to rank 1, Dev contacts to blank. */
IF(CONTAINS($RecordType.DeveloperName, &quot;GM&quot;), 1, null)</defaultValue>
    <description>Used to sort contacts within an account, for example, to pick the primary one</description>
    <inlineHelpText>Used to sort contacts within an account, for example, to pick the primary one</inlineHelpText>
    <label>Rank</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_GM.recordType-meta.xml
<RecordType>
    <fullName>Contact_GM</fullName>
    <active>true</active>
    <description>For grantmaking-related contact records, primarily staff at grantee/applicant orgs</description>
    <label>Contact GM</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Represents a single country and grantmaking within that country.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Enclosing region for this country</description>
    <inlineHelpText>Enclosing region for this country</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Countries</relationshipLabel>
    <relationshipName>Countries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OFAC_search_SDN__c/OFAC_search_SDN__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Search for a name using the OFAC SDN API.</description>
    <label>OFAC search SDN</label>
</CustomObject>

force-app/main/default/objects/OFAC_search_SDN__c/fields/API_key__c.field-meta.xml
<CustomField>
    <fullName>API_key__c</fullName>
    <description>Special key for calls from Global Fund for Women</description>
    <inlineHelpText>Special key for calls from Global Fund for Women</inlineHelpText>
    <label>API key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OFAC_search_SDN__c/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <description>The base URL for the api call</description>
    <inlineHelpText>The base URL for the api call</inlineHelpText>
    <label>Base URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OFAC_search_SDN__c/fields/Min_score__c.field-meta.xml
<CustomField>
    <fullName>Min_score__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The minimum score required to get a match for the SDN search api call</description>
    <inlineHelpText>The minimum score required to get a match for the SDN search api call</inlineHelpText>
    <label>Min score</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OFAC_search_SDN__c/fields/Recipient_email__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email__c</fullName>
    <description>The email address(es) of folks who should receive notification of any hits at OFAC</description>
    <inlineHelpText>The email address(es) of folks who should receive notification of any hits at OFAC</inlineHelpText>
    <label>Recipient email</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <description>The details of how the applicant should be paid; includes banking information</description>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Payment method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account linked to this payment method</description>
    <inlineHelpText>The account linked to this payment method</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Fiscal_sponsor__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account corresponding to the fiscal sponsor (if any) for this payment method</description>
    <inlineHelpText>The account corresponding to the fiscal sponsor (if any) for this payment method</inlineHelpText>
    <label>Fiscal sponsor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods (Fiscal sponsor)</relationshipLabel>
    <relationshipName>Payment_Methods1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this payment method</description>
    <inlineHelpText>The proposal linked to this payment method</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The country where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OFACLookupTest.cls
@isTest
public class OFACLookupTest {
    static testMethod void OFACLookupTest() {
        // Set mock callout class and build custom settings.
        Test.setMock(HttpCalloutMock.class, new OFACLookupMock());
        buildCustomSettings();
        // Build data records
        insert new Region__c(Name = 'East Africa');
        Id regionId = [SELECT Id FROM Region__c LIMIT 1].Id;
        insert new Country__c(Name = 'Zimbabwe', Region__c = regionId);
        Id countryId = [SELECT Id FROM Country__c LIMIT 1].Id;
        // Two accounts, one grantee and one fiscal sponsor, each with a contact.
        insert new Account(
            Name = 'Test account',
            GM_Country__c = countryId,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Id accId1 = [SELECT Id FROM Account LIMIT 1].Id;
        insert new Account(
            Name = 'Test fiscal sponsor account',
            GM_Country__c = countryId,
            // Record type Organization_GM_FS is currently (10/8/20) hidden for FFDB
            RecordTypeId = Utilities.getRecTypeId(
                'Account',
                'Organization_GM' // 'Organization_GM_FS'
            )
        );
        Id accId2 = [
            SELECT Id
            FROM Account
            WHERE Name = 'Test fiscal sponsor account'
            LIMIT 1
        ]
        .Id;
        insert new Contact(
            LastName = 'Doe',
            FirstName = 'John',
            Rank__c = 1,
            Email = 'abc1@def.org',
            AccountId = accId1,
            RecordTypeId = Utilities.getRecTypeId('Contact', 'Contact_GM')
        );
        insert new Contact(
            LastName = 'Doe',
            FirstName = 'John',
            Rank__c = 1,
            Email = 'abc2@def.org',
            AccountId = accId2,
            RecordTypeId = Utilities.getRecTypeId('Contact', 'Contact_GM')
        );
        // Build proposal under the grantee account.
        insert new Proposal__c(Account__c = accId1);
        Id propId = [SELECT Id FROM Proposal__c LIMIT 1].Id;
        // Build a payment method linked to a fiscal sponsor
        insert new Payment_Method__c(
            Proposal__c = propId,
            Account__c = accId1,
            Fiscal_sponsor__c = accId2
        );

        Test.StartTest();
        //String results = OFACLookup.OFACLookupInStatusRange();
        String results = OFACLookup.lookupProposals(new Set<Id>{ propId });
        system.debug('OFACLookupTest: results = ' + results);
        system.assert(results != null);
        system.assert(results.contains('(FS)')); // The results should include an FS hit.
        OFACLookup.OFACLookupNotificationEmail(results);
        Test.StopTest();
    }

    // Build custom setting instance with dummy data for OFAC search.
    public static void buildCustomSettings() {
        insert (new OFAC_search_SDN__c(
            Name = 'OFACSearchSDN',
            Base_URL__c = 'http://search.ofac-api.com/api/v1',
            API_key__c = '2f74fbc7-78c3-4ccd-8b1f-34b3ced7cc84-yJEXM',
            Min_score__c = 100,
            Recipient_email__c = 'abc@def.org'
        ));
    }
}