force-app/main/default/objects/Account/fields/GM_Email__c.field-meta.xml
<CustomField>
    <fullName>GM_Email__c</fullName>
    <description>Primary email address for this account (for grantmaking-related correspondence)</description>
    <externalId>true</externalId>
    <inlineHelpText>Primary email address for this account (for grantmaking-related correspondence)</inlineHelpText>
    <label>GM Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_grants__c.field-meta.xml
<CustomField>
    <fullName>Num_grants__c</fullName>
    <description>The number of grants linked to this account</description>
    <inlineHelpText>The number of grants linked to this account</inlineHelpText>
    <label>Num grants</label>
    <summaryFilterItems>
        <field>Proposal__c.Grant__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Proposal__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Staff_responsible__c.field-meta.xml
<CustomField>
    <fullName>Staff_responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The staff member who is responsible for this account</description>
    <inlineHelpText>The staff member who is responsible for this account</inlineHelpText>
    <label>Staff responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Specifies information about profiles to be invited and grants to be made under this allocation&apos;s parent fund.</description>
    <label>Allocation</label>
    <nameField>
        <displayFormat>ALLOC-{000000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <description>The parent fund of this allocation</description>
    <inlineHelpText>The parent fund of this allocation</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/Grant_size__c.field-meta.xml
<CustomField>
    <fullName>Grant_size__c</fullName>
    <description>The planned amount of a grant to be awarded under this allocation</description>
    <inlineHelpText>The planned amount of a grant to be awarded under this allocation</inlineHelpText>
    <label>Grant size</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/Num_grants__c.field-meta.xml
<CustomField>
    <fullName>Num_grants__c</fullName>
    <description>The planned number of grants to be awarded under this allocation</description>
    <inlineHelpText>The planned number of grants to be awarded under this allocation</inlineHelpText>
    <label>Num grants</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/Staff_responsible__c.field-meta.xml
<CustomField>
    <fullName>Staff_responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The staff member who is associated with this allocation</description>
    <inlineHelpText>The staff member who is associated with this allocation</inlineHelpText>
    <label>Staff responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <description>Representations an allocation of all or part of a grant to a fund (funding source)</description>
    <label>Charge</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <description>The fund to which this charge applies</description>
    <inlineHelpText>The fund to which this charge applies</inlineHelpText>
    <label>Fund</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>May only charge to active funds.</errorMessage>
        <filterItems>
            <field>Fund__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>May only charge to active funds.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Represents an amount of restricted funding</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this fund is currently active (usually means that there are still funds left to charge)</description>
    <inlineHelpText>True if this fund is currently active (usually means that there are still funds left to charge)</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Amount_funded__c.field-meta.xml
<CustomField>
    <fullName>Amount_funded__c</fullName>
    <description>Amount in dollars of fund not including overhead</description>
    <inlineHelpText>Amount in dollars of fund not including overhead</inlineHelpText>
    <label>Amount funded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region to which this fund applies (if any)</description>
    <inlineHelpText>Region to which this fund applies (if any)</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Staff_responsible__c.field-meta.xml
<CustomField>
    <fullName>Staff_responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The staff member who is associated with this fund</description>
    <inlineHelpText>The staff member who is associated with this fund</inlineHelpText>
    <label>Staff responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Standard funds represent an amount of restricted funding to be allocated for grantmaking.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Invite__c/Invite__c.object-meta.xml
<CustomObject>
    <description>Tracks the invitation process for a given fund from profile to proposal</description>
    <label>Invite</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invite__c/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <description>The parent allocation of this invite</description>
    <inlineHelpText>The parent allocation of this invite</inlineHelpText>
    <label>Allocation</label>
    <referenceTo>Allocation__c</referenceTo>
    <relationshipLabel>Invites</relationshipLabel>
    <relationshipName>Invites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The fund to which this letter is linked</description>
    <inlineHelpText>The fund to which this letter is linked</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region record linked to this letter</description>
    <inlineHelpText>Region record linked to this letter</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Staff_responsible__c.field-meta.xml
<CustomField>
    <fullName>Staff_responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The member of staff responsible for this proposal/grant</description>
    <inlineHelpText>The member of staff responsible for this proposal/grant</inlineHelpText>
    <label>Staff responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If template is active, it may be invoked (usually from letters).</description>
    <inlineHelpText>If template is active, it may be invoked (usually from letters).</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InviteControllerTest.cls
@isTest
public class InviteControllerTest {
    public static Id organizationRtId = Utilities.getRecTypeId(
        'Account',
        'Organization_GM'
    );
    public static Id fundRtId = Utilities.getRecTypeId('Fund__c', 'Standard');
    static testMethod void InviteControllerTest1() {
        // Build new records.
        Id userId = UserInfo.getUserId();
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'invtest_acct_1',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'),
            GM_email__c = 'abc@def.org'
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Fund__c(
            Name = 'test fund',
            Amount_funded__c = 100,
            Active__c = true,
            RecordTypeId = fundRtId
        );
        Fund__c fund = [SELECT Id FROM Fund__c LIMIT 1];
        insert new Allocation__c(
            Fund__c = fund.Id,
            Grant_size__c = 10,
            Num_grants__c = 1,
            Staff_responsible__c = userId
        );
        Allocation__c alloc = [SELECT Id FROM Allocation__c LIMIT 1];
        insert new Invite__c(Account__c = acc.Id, Allocation__c = alloc.Id);
        Map<Id, Invite__c> invMap = new Map<Id, Invite__c>(
            [SELECT Id FROM Invite__c]
        );
        // Build new standard set controller and select the new invite.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            invMap.values()
        );
        ssc.setSelected(invMap.values());

        Test.StartTest();
        // Build a new invite controller and use it to build new letters for the selected invites.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'Invite__c'
        ));
        InviteController ic1 = new InviteController(ssc);
        ic1.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', ic1.selectedTemplate),
            null
        );
        ic1.buildLetters();
        // These last bits are for code coverage.
        ApexPages.StandardController sc = new ApexPages.StandardController(
            invMap.values()[0]
        );
        InviteController ic2 = new InviteController(sc);
        ic2.buildLetters();
        ic2.selectedTemplate = 'Test template';
        ic2.buildLetters();
        ic2.doCancel();
        Test.StopTest();

        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );
        validate(lMap.keySet());
    }

    static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [
                SELECT Account__c, Emails__c, Invite__c
                FROM Letter__c
                WHERE Id IN :lIds
            ]
        );
        Map<Id, Invite__c> invMap = new Map<Id, Invite__c>(
            [
                SELECT Id
                FROM Invite__c
                WHERE Id IN (SELECT Invite__c FROM Letter__c WHERE Id IN :lIds)
            ]
        );
        system.debug(
            'InviteController validate: lMap = ' + JSON.serialize(lMap)
        );
        system.assertNotEquals(invMap.size(), lMap.size());
        // Gather email addresses for the accounts of these invites.
        Map<Id, Account> aMap = new Map<Id, Account>(
            [
                SELECT Id
                FROM Account
                WHERE
                    Id IN (
                        SELECT Account__c
                        FROM Invite__c
                        WHERE Id IN :invMap.keySet()
                    )
            ]
        );
        Map<Id, List<String>> emailMap = AccountController.emailsForAccounts(
            aMap.keySet()
        );
        system.debug(
            'InviteController validate: emailMap = ' + JSON.serialize(emailMap)
        );
        // The emails stored on the letter need to agree with the account's emails.
        for (Letter__c l : lMap.values()) {
            system.assertEquals(
                l.Emails__c,
                String.join(emailMap.get(l.Account__c), ',')
            );
        }
    }

    // Test functionality to build new invites/allocations for charges on a fund.
    static testMethod void InviteControllerTest2() {
        // Build new records.
        Id userId = UserInfo.getUserId();
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'invtest_acct_1',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'),
            GM_email__c = 'abc@def.org'
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Fund__c(
            Name = 'test fund',
            Amount_funded__c = 100,
            Active__c = true,
            RecordTypeId = fundRtId
        );
        Fund__c fund = [SELECT Id FROM Fund__c LIMIT 1];
        insert new Proposal__c(
            Account__c = acc.Id,
            Amount_awarded__c = 50,
            Date_awarded__c = Date.today()
        );
        Proposal__c prop = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new Charge__c(Fund__c = fund.Id, Proposal__c = prop.Id);

        Test.startTest();
        InvitesAllocationsForRstInvocable.NewInvsAllocsRequest req = new InvitesAllocationsForRstInvocable.NewInvsAllocsRequest();
        req.fundId = fund.Id;
        InvitesAllocationsForRstInvocable.newInvitesAllocations(
            new List<InvitesAllocationsForRstInvocable.NewInvsAllocsRequest>{
                req
            }
        );
        Test.stopTest();

        Allocation__c[] allocs = [SELECT Id FROM Allocation__c];
        Invite__c[] invs = [SELECT Id, Allocation__c FROM Invite__c];
        system.assert(allocs.size() > 0);
        system.assert(invs.size() > 0);
        system.assertEquals(allocs[0].Id, invs[0].Allocation__c);
    }

    // Test functionality to build new invites/allocations for charged proposals.
    static testMethod void InviteControllerTest3() {
        // Build new records.
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'invtest_acct_1',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'),
            GM_email__c = 'abc@def.org'
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Fund__c(
            Name = 'test fund',
            Amount_funded__c = 100,
            Active__c = true,
            RecordTypeId = fundRtId
        );
        Fund__c fund = [SELECT Id FROM Fund__c LIMIT 1];
        insert new Proposal__c(
            Account__c = acc.Id,
            Amount_awarded__c = 50,
            Date_awarded__c = Date.today()
        );
        Proposal__c prop = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new Charge__c(
            Fund__c = fund.Id,
            Proposal__c = prop.Id,
            Amount_charged__c = 20
        );
        Charge__c c1 = [
            SELECT Id
            FROM Charge__c
            WHERE Amount_charged__c = 20
            LIMIT 1
        ];
        insert new Charge__c(
            Fund__c = fund.Id,
            Proposal__c = prop.Id,
            Amount_charged__c = 30
        );
        Charge__c c2 = [
            SELECT Id
            FROM Charge__c
            WHERE Amount_charged__c = 30
            LIMIT 1
        ];

        Test.startTest();
        // First ensure that we skip props with split charges.
        InviteController.newAllocationsInvitesForProps(new Set<Id>{ prop.Id });
        Invite__c[] invs = [SELECT Id FROM Invite__c];
        system.assertEquals(0, invs.size());
        // Now delete the charge and test again via the batch process.
        delete c2;
        Database.executeBatch(
            new InvitesAllocationsForPropsBatch('SELECT Id FROM Proposal__c'),
            5
        );
        Test.stopTest();

        Allocation__c[] allocs = [SELECT Id FROM Allocation__c];
        invs = [SELECT Id, Allocation__c FROM Invite__c];
        system.assert(allocs.size() > 0);
        system.assert(invs.size() > 0);
        system.assertEquals(allocs[0].Id, invs[0].Allocation__c);
    }

    // Test the cloneProposal method.
    static testMethod void InviteControllerTest4() {
        // Build new records.
        Id userId = UserInfo.getUserId();
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'invtest_acct_1',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'),
            GM_email__c = 'abc@def.org'
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Proposal__c(
            Account__c = acc.Id,
            Amount_awarded__c = 50,
            Date_awarded__c = Date.today()
        );
        Proposal__c p = [SELECT Id, Account__c FROM Proposal__c LIMIT 1];
        insert new Fund__c(
            Name = 'test fund',
            Amount_funded__c = 100,
            Active__c = true,
            RecordTypeId = fundRtId
        );
        Fund__c fund = [SELECT Id FROM Fund__c LIMIT 1];
        insert new Allocation__c(
            Fund__c = fund.Id,
            Grant_size__c = 10,
            Num_grants__c = 1,
            Staff_responsible__c = userId
        );
        Allocation__c alloc = [SELECT Id FROM Allocation__c LIMIT 1];
        insert new Invite__c(
            Account__c = acc.Id,
            Allocation__c = alloc.Id,
            Proposal_to_clone__c = p.Id
        );
        Invite__c i = [SELECT Id FROM Invite__c LIMIT 1];

        Test.StartTest();
        InviteCloneProposalInvocable.cloneProposal(new List<Id>{ i.Id });
        Test.StopTest();

        Proposal__c pNew = [
            SELECT Id, Account__c, Amount_awarded__c
            FROM Proposal__c
            WHERE Prior_proposal__c != null
            LIMIT 1
        ];
        system.assertNotEquals(p.Id, pNew.Id);
        system.assertEquals(p.Account__c, pNew.Account__c);
        system.assertEquals(null, pNew.Amount_awarded__c);
        GM_Data__c[] gmds = [SELECT Id FROM GM_Data__c];
        system.assertEquals(2, gmds.size());
    }

    // Test the aura enabled method for creating new proposal from invite.
    static testMethod void InviteControllerTest5() {
        // Build new records.
        Id userId = UserInfo.getUserId();
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'invtest_acct_1',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'),
            GM_email__c = 'abc@def.org'
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Profile__c(Account__c = acc.Id, Language__c = 'English');
        Profile__c prof = [SELECT Id FROM Profile__c LIMIT 1];
        insert new Fund__c(
            Name = 'test fund',
            Amount_funded__c = 100,
            Active__c = true,
            RecordTypeId = fundRtId
        );
        Fund__c fund = [SELECT Id FROM Fund__c LIMIT 1];
        insert new Allocation__c(
            Fund__c = fund.Id,
            Grant_size__c = 10,
            Num_grants__c = 1,
            Staff_responsible__c = userId
        );
        Allocation__c alloc = [SELECT Id FROM Allocation__c LIMIT 1];
        insert new Invite__c(
            Account__c = acc.Id,
            Profile__c = prof.Id,
            Allocation__c = alloc.Id
        );
        Invite__c i = [SELECT Id FROM Invite__c LIMIT 1];

        Test.StartTest();
        String jsonString = JSON.serialize(
            new Map<String, Object>{
                'inviteId' => i.Id,
                'invitationDeadline' => Date.today().addDays(100),
                'awardNotificationDeadline' => Date.today().addDays(200)
            }
        );
        String returnJSON = InviteController.newProposal(jsonString);
        Test.StopTest();

        // Check that records were created, and that they're inter-linked.
        Proposal__c prop = [
            SELECT Id, GM_Data__c, Invite__c
            FROM Proposal__c
            LIMIT 1
        ];
        GM_Data__c gmd = [SELECT Id, Proposal__c FROM GM_Data__c LIMIT 1];
        i = [SELECT Id, Proposal__c FROM Invite__c LIMIT 1];
        system.assertNotEquals(null, prop);
        system.assertNotEquals(null, gmd);
        system.assertEquals(prop.Id, i.Proposal__c);
        system.assertEquals(prop.Id, gmd.Proposal__c);
        system.assertEquals(gmd.Id, prop.GM_Data__c);
        system.assertEquals(i.Id, prop.Invite__c);
    }
}