force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs (if any) linked to the proposal/grant behind this letter</description>
    <inlineHelpText>The custom reqs (if any) linked to the proposal/grant behind this letter</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region record linked to this letter</description>
    <inlineHelpText>Region record linked to this letter</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Represents a milestone (report, payment, site visit, etc.) due or received for this grant</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Date_due__c.field-meta.xml
<CustomField>
    <fullName>Date_due__c</fullName>
    <description>The date by which we should receive the milestone</description>
    <inlineHelpText>The date by which we should receive the milestone</inlineHelpText>
    <label>Date due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Milestone_Spec__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Spec__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The milestone spec part of the proposal&apos;s custom req, if any, that is linked to this milestone</description>
    <inlineHelpText>The milestone spec part of the proposal&apos;s custom req, if any, that is linked to this milestone</inlineHelpText>
    <label>Milestone Spec</label>
    <referenceTo>Milestone_Spec__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of milestone</description>
    <inlineHelpText>The type of milestone</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/Milestone_Spec__c.object-meta.xml
<CustomObject>
    <description>Specification of a milestone including type, date due, etc.</description>
    <label>Milestone Spec</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Milestone Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Spec__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <description>The custom reporting reqs record for this milestone spec record</description>
    <inlineHelpText>The custom reporting reqs record for this milestone spec record</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Milestone Specs</relationshipLabel>
    <relationshipName>Milestone_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/fields/Date_due__c.field-meta.xml
<CustomField>
    <fullName>Date_due__c</fullName>
    <description>Due date for milestone
Note: Overrides Num months due</description>
    <inlineHelpText>Due date for milestone
Note: Overrides Num months due</inlineHelpText>
    <label>Date due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/fields/Review_form__c.field-meta.xml
<CustomField>
    <fullName>Review_form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The review form used for milestones linked to this milestone spec</description>
    <inlineHelpText>The review form used for milestones linked to this milestone spec</inlineHelpText>
    <label>Review form</label>
    <referenceTo>Review_Form__c</referenceTo>
    <relationshipLabel>Milestone Specs</relationshipLabel>
    <relationshipName>Milestone_Specs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this milestone</description>
    <inlineHelpText>The type of this milestone</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs for this proposal (if any)</description>
    <inlineHelpText>The custom reqs for this proposal (if any)</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review_Form_Component__c/Review_Form_Component__c.object-meta.xml
<CustomObject>
    <description>Represents a component used by a review form for field entry</description>
    <label>Review Form Component</label>
    <nameField>
        <displayFormat>RFC-{000000}</displayFormat>
        <label>Review Form Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Form Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Form_Component__c/fields/Lightning_component_name__c.field-meta.xml
<CustomField>
    <fullName>Lightning_component_name__c</fullName>
    <description>The name of the lightning component used to instantiate this field in a review interface</description>
    <inlineHelpText>The name of the lightning component used to instantiate this field in a review interface</inlineHelpText>
    <label>Lightning component name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HeadingMedium</fullName>
            </value>
            <value>
                <fullName>HeadingSmall</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>InputCheckbox</fullName>
            </value>
            <value>
                <fullName>InputSelect</fullName>
            </value>
            <value>
                <fullName>InputSelectLookup</fullName>
            </value>
            <value>
                <fullName>InputSelectMulti</fullName>
            </value>
            <value>
                <fullName>InputSelectMulti1</fullName>
            </value>
            <value>
                <fullName>InputTextarea</fullName>
            </value>
            <value>
                <fullName>InputText</fullName>
            </value>
            <value>
                <fullName>InputTextReadonly</fullName>
            </value>
            <value>
                <fullName>InputNumber</fullName>
            </value>
            <value>
                <fullName>IndicatorGroup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review_Form_Component__c/fields/Review_Form__c.field-meta.xml
<CustomField>
    <fullName>Review_Form__c</fullName>
    <description>The review form to which this component belongs</description>
    <inlineHelpText>The review form to which this component belongs</inlineHelpText>
    <label>Review Form</label>
    <referenceTo>Review_Form__c</referenceTo>
    <relationshipLabel>Review Form Components</relationshipLabel>
    <relationshipName>Review_Form_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review_Form_Component__c/fields/Sort_number__c.field-meta.xml
<CustomField>
    <fullName>Sort_number__c</fullName>
    <description>This number determines where this component is inserted in the overall form</description>
    <inlineHelpText>This number determines where this component is inserted in the overall form</inlineHelpText>
    <label>Sort number</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Milestone_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Report</fullName>
    </customValue>
    <customValue>
        <fullName>Report narrative</fullName>
    </customValue>
    <customValue>
        <fullName>Report financial</fullName>
    </customValue>
    <customValue>
        <fullName>Report activities</fullName>
    </customValue>
    <customValue>
        <fullName>Site visit</fullName>
    </customValue>
    <description>Milestone types</description>
    <masterLabel>Milestone type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MilestoneControllerTest.cls
@isTest
public class MilestoneControllerTest {
    /**********************************
     * Test the component-related methods
     * *******************************/

    static testMethod void MilestoneControllerTest1() {
        // Build new records
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'test account',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Account a = [SELECT Id FROM Account LIMIT 1];
        insert new Review_Form__c(Name = 'test milestone review form');
        Review_Form__c rf = [SELECT Id FROM Review_Form__c LIMIT 1];
        insert new Review_Form__c(Name = 'ReportStandard_WF');
        insert new Review_Form_Component__c(
            Review_Form__c = rf.Id,
            Lightning_component_name__c = 'InputCheckbox',
            Sort_number__c = 1
        );
        insert new Custom_Reqs__c(Name = 'test custom reqs');
        Custom_Reqs__c cr = [SELECT Id FROM Custom_Reqs__c LIMIT 1];
        insert new Milestone_Spec__c(
            Custom_Reqs__c = cr.Id,
            Type__c = 'Report',
            Date_due__c = Date.today(),
            Review_form__c = rf.Id
        );
        Milestone_Spec__c ms = [SELECT Id FROM Milestone_Spec__c LIMIT 1];
        insert new Profile__c();
        Profile__c pr = [SELECT Id FROM Profile__c LIMIT 1];
        insert new Proposal__c(
            Account__c = a.Id,
            Profile__c = pr.Id,
            Custom_Reqs__c = cr.Id
        );
        Proposal__c p = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new Milestone__c(
            Proposal__c = p.Id,
            Type__c = 'Report',
            Milestone_Spec__c = ms.Id
        );
        Milestone__c m = [SELECT Id FROM Milestone__c LIMIT 1];
        Test.StartTest();
        MilestoneController.MilestoneInfo mInfo = MilestoneController.getMilestoneInfo(
            m.Id
        );
        GM_Data__c d = [SELECT Id FROM GM_Data__c WHERE Proposal__c = :p.Id];
        MilestoneController.saveMilestoneInfo(m, d);
        Test.StopTest();
    }

    /**********************************
     * Test the VF-related methods
     * *******************************/

    static testMethod void MilestoneControllerTest2a() {
        // Build new milestones, proposals and accounts
        InitTestObjects(1, 1);
        Map<Id, Milestone__c> mMap = new Map<Id, Milestone__c>(
            [SELECT Id FROM Milestone__c]
        );
        // Build new standard set controller and select the new records.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            mMap.values()
        );
        ssc.setSelected(mMap.values());

        Test.StartTest();
        // Build a new milestone controller and use it to build new letters for the selected milestones.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'Milestone__c'
        ));
        MilestoneController gc = new MilestoneController(ssc);
        gc.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', gc.selectedTemplate),
            null
        );
        gc.buildLetters();
        Test.StopTest();

        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );
        validate(lMap.keySet());
    }

    static testMethod void MilestoneControllerTest2b() {
        // Build new milestones, proposals and accounts
        InitTestObjects(1, 1);
        Map<Id, Milestone__c> mMap = new Map<Id, Milestone__c>(
            [SELECT Id FROM Milestone__c]
        );
        // Build new standard controller and select the new record.
        ApexPages.StandardController sc = new ApexPages.StandardController(
            mMap.values()[0]
        );

        Test.StartTest();
        // Build a new milestone controller and use it to build new letters for the selected milestones.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'Milestone__c'
        ));
        MilestoneController gc = new MilestoneController(sc);
        gc.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', gc.selectedTemplate),
            null
        );
        gc.buildLetters();
        Test.StopTest();

        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );
        validate(lMap.keySet());
    }

    static testMethod void MilestoneControllerTest3() {
        // Build 1 new milestone/proposal/account
        InitTestObjects(1, 1);
        Milestone__c m = [SELECT Id FROM Milestone__c LIMIT 1];
        Test.StartTest();
        String templateName = 'Test template';
        insert (new Template__c(
            Name = templateName,
            Source_object__c = 'Milestone__c'
        ));
        Template__c template = [
            SELECT Id
            FROM Template__c
            WHERE Name = :templateName
            LIMIT 1
        ];
        // Use invocable class to build and email letter.
        MilestoneEmailLetterInvocable.EmailLetterRequest req = new MilestoneEmailLetterInvocable.EmailLetterRequest();
        req.mId = m.Id;
        req.templateId = template.Id;
        MilestoneEmailLetterInvocable.buildAndEmailLetter(
            new List<MilestoneEmailLetterInvocable.EmailLetterRequest>{ req }
        );
        Test.StopTest();
    }

    static testMethod void MilestoneControllerTest4() {
        // Build 1 new milestone/proposal/account
        InitTestObjects(1, 1);
        Milestone__c m = [SELECT Id FROM Milestone__c LIMIT 1];
        Test.StartTest();
        insert (new Template__c(
            Name = 'Milestone reminder letter',
            Source_object__c = 'Milestone__c'
        ));
        Template__c t = [SELECT Id FROM Template__c LIMIT 1];
        insert new Letter__c(
            Milestone__c = m.Id,
            Template__c = t.Id,
            Date_emailed__c = Date.today()
        );
        Letter__c l = [SELECT Id FROM Letter__c LIMIT 1];
        // Use invocable class to run the letter sent actions.
        MilestoneLetterSentInvocable.MilestoneLetterSentRequest req = new MilestoneLetterSentInvocable.MilestoneLetterSentRequest();
        req.letterId = l.Id;
        // Test each of four letter templates.
        MilestoneLetterSentInvocable.letterSent(
            new List<MilestoneLetterSentInvocable.MilestoneLetterSentRequest>{
                req
            }
        );
        m = [
            SELECT Id, Num_overdue_notices_sent__c, Num_reminders_sent__c
            FROM Milestone__c
            LIMIT 1
        ];
        system.assertEquals(1, m.Num_reminders_sent__c);
        t.Name = 'Milestone overdue letter';
        update t;
        MilestoneLetterSentInvocable.letterSent(
            new List<MilestoneLetterSentInvocable.MilestoneLetterSentRequest>{
                req
            }
        );
        m = [
            SELECT Id, Num_overdue_notices_sent__c, Num_reminders_sent__c
            FROM Milestone__c
            LIMIT 1
        ];
        system.assertEquals(1, m.Num_overdue_notices_sent__c);
        t.Name = 'Milestone acknowledgement letter';
        update t;
        MilestoneLetterSentInvocable.letterSent(
            new List<MilestoneLetterSentInvocable.MilestoneLetterSentRequest>{
                req
            }
        );
        t.Name = 'Milestone follow up letter';
        update t;
        MilestoneLetterSentInvocable.letterSent(
            new List<MilestoneLetterSentInvocable.MilestoneLetterSentRequest>{
                req
            }
        );
        Test.StopTest();
    }

    static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [
                SELECT Account__c, Emails__c, Milestone__c
                FROM Letter__c
                WHERE Id IN :lIds
            ]
        );
        Map<Id, Milestone__c> mMap = new Map<Id, Milestone__c>(
            [
                SELECT Id
                FROM Milestone__c
                WHERE
                    Id IN (SELECT Milestone__c FROM Letter__c WHERE Id IN :lIds)
            ]
        );
        // Should be a different letter for each proposal.
        system.assertEquals(lMap.size(), mMap.size());
        // Gather email addresses for contacts under the accounts.
        Map<Id, Account> aMap = new Map<Id, Account>([SELECT Id FROM Account]);
        Map<Id, List<String>> emailMap = AccountController.emailsForAccounts(
            aMap.keySet()
        );
        // The emails stored on the letter need to agree with the account's emails.
        for (Letter__c l : lMap.values()) {
            system.assertEquals(
                l.Emails__c,
                String.join(emailMap.get(l.Account__c), ',')
            );
        }
    }

    static void InitTestObjects(
        Integer NumberOfGranteeReports,
        Integer NumberOfAccounts
    ) {
        // Build proposals and accounts
        BuildTestProposals.InitTestObjects(
            NumberOfGranteeReports,
            NumberOfAccounts
        );
        List<Proposal__c> ps = new List<Proposal__c>(
            [SELECT Id, Account__c FROM Proposal__c]
        );
        // Build and insert milestones linked to the new proposals.
        List<Milestone__c> ms = new List<Milestone__c>();
        for (Integer x = 0; x < NumberOfGranteeReports; x++) {
            ms.add(
                new Milestone__c(
                    Proposal__c = ps[x].Id
                    // Add other field assignments for milestones
                )
            );
        }
        insert ms;
    }

    // Test code to build new milestones for awarded proposals.
    static testMethod void MilestoneControllerTest5() {
        // Build new proposals, accounts, milestone specs.
        BuildTestProposals.InitTestObjects(1, 1);
        insert new Custom_Reqs__c(Name = 'test reporting reqs');
        Custom_Reqs__c custReqs = [SELECT Id FROM Custom_Reqs__c LIMIT 1];
        insert new Milestone_Spec__c(
            Custom_Reqs__c = custReqs.Id,
            Date_due__c = Date.today().addDays(100),
            Type__c = 'Report'
        );
        insert new Milestone_Spec__c(
            Custom_Reqs__c = custReqs.Id,
            Num_months_due__c = 12,
            Type__c = 'Report'
        );
        // Push the proposal to award stage.
        Proposal__c p = [SELECT Id, Account__c FROM Proposal__c LIMIT 1];
        p.Amount_awarded__c = 100;
        p.Custom_Reqs__c = custReqs.Id;
        update p;
        // Have to update date awarded separately because of a validation rule on changes to amount/date awarded fields.
        p.Date_awarded__c = Date.today();
        update p;

        Test.StartTest();
        // Insert a report milestone.
        insert new Milestone__c(Proposal__c = p.Id, Type__c = 'Report');
        Milestone__c m1 = [SELECT Id FROM Milestone__c LIMIT 1];
        MilestoneController.buildMilestones(p.Id);
        Test.StopTest();

        // Insert a new milestone.  Because it isn't linked to a milestone spec, date due is not updated.
        Milestone__c[] ms = [SELECT Id, Date_due__c FROM Milestone__c];
        for (Milestone__c m : ms) {
            system.assertEquals(null, m.Date_due__c);
        }
    }
}