force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>Group other than a corporation or household.</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Periodic_delete_queries__c/Periodic_delete_queries__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>NOTE: Check with IM before editing, as this can mass delete records without saving in the recycle bin! Each record contains a query that returns a collection of records to be deleted via scheduled apex.</description>
    <label>Periodic delete queries</label>
</CustomObject>

force-app/main/default/objects/Periodic_delete_queries__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this delete query is active</description>
    <inlineHelpText>Checked if this delete query is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periodic_delete_queries__c/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <defaultValue>10000</defaultValue>
    <description>The size of the batch used by the batch apex to make the deletes.  Default is 10,000.</description>
    <inlineHelpText>The size of the batch used by the batch apex to make the deletes.  Default is 10,000.</inlineHelpText>
    <label>Batch size</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Periodic_delete_queries__c/fields/Hard_delete__c.field-meta.xml
<CustomField>
    <fullName>Hard_delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, then do a hard delete - that is, remove from the recycle bin immediately after deleting.</description>
    <inlineHelpText>If checked, then do a hard delete - that is, remove from the recycle bin immediately after deleting.</inlineHelpText>
    <label>Hard delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periodic_delete_queries__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>The query used to find records to delete</description>
    <inlineHelpText>The query used to find records to delete</inlineHelpText>
    <label>Query</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteRecordsSchedulableTest.cls
@isTest
public with sharing class DeleteRecordsSchedulableTest {
    // Test the batch apex class.
    static testMethod void DeleteRecordsSchedulableTest1() {
        // Build records to delete.
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'acc test',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        insert (new Account(
            Name = 'test 2',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        ));
        insert (new Account(
            Name = 'test 3',
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization')
        ));
        String q = 'SELECT Id FROM Account WHERE RecordType.DeveloperName = \'Organization_GM\'';
        Account[] accts = [
            SELECT Id
            FROM Account
            WHERE RecordType.DeveloperName = 'Organization'
        ];
        Test.StartTest();
        Database.executeBatch(new DeleteRecordsBatch(q, true), 3);
        Database.executeBatch(new DeleteRecordsBatch(accts, true), 3);
        Test.StopTest();
        Account[] acctResults = [SELECT Id FROM Account];
        system.assertEquals(0, acctResults.size());
    }

    // Test the schedulable class.
    static testMethod void DeleteRecordsSchedulableTest2() {
        // Build records to delete.
        insert (new Account(Name = 'test 1'));
        insert (new Account(Name = 'test 2'));
        // Build custom setting instance with dummy data.
        insert (new Periodic_delete_queries__c(
            Name = 'pdq1',
            Active__c = true,
            Query__c = 'SELECT Id FROM Account',
            Hard_delete__c = true,
            Batch_size__c = 3
        ));
        // The schedule time isn't actually used; it just runs after Test.StopTest().
        String CRON_EXP = '0 0 0 15 3 ?';
        Test.StartTest();
        String jobId = System.schedule(
            'Delete records',
            CRON_EXP,
            new DeleteRecordsSchedulable()
        );
        Test.StopTest();
        // Not validating after schedulable class test, because it doesn't work for some reason.
    }
}