force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this classification: Population, Strategy, or Issue</description>
    <inlineHelpText>Type of this classification: Population, Strategy, or Issue</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Population</fullName>
            </value>
            <value>
                <fullName>Strategy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/Classification_Assign__c.object-meta.xml
<CustomObject>
    <description>Assignment of a single classification to a proposal</description>
    <label>Classification Assign</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Classification Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification assigned to the proposal</description>
    <inlineHelpText>The classification assigned to the proposal</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal to which the classification is assigned</description>
    <inlineHelpText>The proposal to which the classification is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/Classification_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single classification to a profile</description>
    <label>Classification-Profile Assign</label>
    <nameField>
        <displayFormat>CA-Prof-{00000}</displayFormat>
        <label>Classification-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification linked from this join record</description>
    <inlineHelpText>The classification linked from this join record</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account of the org responsible for this profile</description>
    <inlineHelpText>The account of the org responsible for this profile</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this proposal is linked</description>
    <inlineHelpText>The profile to which this proposal is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ClassificationControllerTest.cls
@isTest
public class ClassificationControllerTest {
    static testmethod void ClassificationControllerTest () {
        // Build new records
        insert new Region__c (Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account (
            Name = 'test account', 
            GM_Region__c = reg.Id, 
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
            );
        Account a = [SELECT Id FROM Account LIMIT 1];
        insert new Profile__c (Account__c = a.Id);
        Profile__c pr = [SELECT Id FROM Profile__c LIMIT 1];
        insert new Proposal__c (Account__c = a.Id, Profile__c = pr.Id);
        Proposal__c p = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new Classification__c (Name = 'Test Issue 1', Type__c = 'Issue');
        Classification__c ci1 = [SELECT Id FROM Classification__c WHERE Name = 'Test Issue 1' LIMIT 1];
        insert new Classification__c (Name = 'Test Issue 2', Type__c = 'Issue');
        Classification__c ci2 = [SELECT Id FROM Classification__c WHERE Name = 'Test Issue 2' LIMIT 1];
        insert new Classification__c (Name = 'Test Issue 3', Type__c = 'Issue');
        Classification__c ci3 = [SELECT Id FROM Classification__c WHERE Name = 'Test Issue 3' LIMIT 1];
        insert new Classification_Assign__c (Proposal__c = p.Id, Classification__c = ci1.Id);
        insert new Classification_Profile_Assign__c (Profile__c = pr.Id, Classification__c = ci1.Id);
        insert new Classification_Profile_Assign__c (Profile__c = pr.Id, Classification__c = ci2.Id);
        insert new Classification_Profile_Assign__c (Profile__c = pr.Id, Classification__c = ci3.Id);

        Test.StartTest();
        ClassificationController.updateClassificationAssigns(p.Id, 'Issue', new List<String>{'Test Issue 1', 'Test Issue 2'});
        ClassificationController.updateClassificationAssigns(pr.Id, 'Issue', new List<String>());
        Test.stopTest();

        // Check that only one new assign added to proposal.
        Classification_Assign__c[] propClassAssigns = [SELECT Id FROM Classification_Assign__c];
        system.assertEquals(2, propClassAssigns.size());
        // Check that all assigns for the profile are removed.
        Classification_Profile_Assign__c[] profClassAssigns = [SELECT Id FROM Classification_Profile_Assign__c];
        system.assertEquals(0, profClassAssigns.size());
    }

}