force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SavedSetNames__c.field-meta.xml
<CustomField>
    <fullName>SavedSetNames__c</fullName>
    <description>Temporary field for retrieving saved sets</description>
    <inlineHelpText>Temporary field for retrieving saved sets</inlineHelpText>
    <label>SavedSetNames</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ReportUtilitiesTest.cls
@isTest
private class ReportUtilitiesTest {
    

    @isTest
    static void getAvailableObjectsTest() {
        String jsonReturnList = ReportUtilities.getAvailableObjects();
        List < ReportUtilities.Option > options = (List < ReportUtilities.Option >)JSON.deserialize(jsonReturnList, List < ReportUtilities.Option>.class);
        Set < String > optionSet = new Set < String >();
        for (ReportUtilities.Option opt: options) {
            optionSet.add(opt.value);
        }
        System.assertEquals(true, optionSet.contains('Account'));

    }   

    //https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_analytics_test_reports.htm
    @isTest(SeeAllData='true') //SeeAllData gives us access to reports & report runs use seealldata=true regardless of this setting
    static void getReportListTest() {
        
        List <Report> reportList = [SELECT Id, DeveloperName FROM Report WHERE DeveloperName LIKE 'Accounts_GM_TEMPLATE%'];
        String reportId = (String)reportList.get(0).get('Id');
      
        // Create Account/Proposal
        insert new Region__c (Name = 'test region');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account (Name = 'test account', GM_region__c = reg.Id, RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'));
        Account a = [SELECT Id FROM Account LIMIT 1];
        insert new Proposal__c (Account__c = a.Id);
        Proposal__c p = [SELECT Id FROM Proposal__c LIMIT 1];

        // Get Report Metadata
        Reports.ReportMetadata reportMetadata = Reports.ReportManager.describeReport(reportId).getReportMetadata();
        
        // Since report runs in test mode ALWAYS uses seealldata=true, apply a filter
        List<Reports.ReportFilter> filters = new List<Reports.ReportFilter>(); 
        Reports.ReportFilter newFilter = new Reports.ReportFilter();
        newFilter.setColumn('Account.GM_region__c');
        newFilter.setOperator('equals');
        newFilter.setValue(reg.Id);
        filters.add(newFilter);
        reportMetadata.setReportFilters(filters);

        Test.startTest();
       
        Reports.ReportInstance instanceObj = Reports.ReportManager.runAsyncReport(reportId,reportMetadata,false);
        String instanceId = instanceObj.getId();
        
        // Report instance is not available yet.
        Test.stopTest();
        // After the stopTest method, the report has finished executing and should be avail in ReportUtilities
        String returnReportList = ReportUtilities.getReportList('Account');
        List < ReportUtilities.Option > reportOptions = (List < ReportUtilities.Option >)JSON.deserialize(returnReportList, List < ReportUtilities.Option >.class);
  
    }

    @isTest(SeeAllData='true') //SeeAllData gives us access to reports & report runs use seealldata=true regardless of this setting
    static void getTabularRealReportDataTest() {
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName LIKE 'Accounts_GM_TEMPLATE%'];
        String reportId = (String)reportList.get(0).get('Id');
      
        // Create Account/Proposal
        insert new Region__c (Name = 'test region');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account (Name = 'test account', GM_region__c = reg.Id, RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'));
        Account a = [SELECT Id FROM Account LIMIT 1];
        insert new Proposal__c (Account__c = a.Id);
        Proposal__c p = [SELECT Id FROM Proposal__c LIMIT 1];


        Reports.ReportMetadata reportMetadata = Reports.ReportManager.describeReport(reportId).getReportMetadata();
        
        List < String > columns = reportMetadata.getDetailColumns();
        System.debug('columns: '+columns);

        // Since report runs in test mode ALWAYS use seealldata=true, apply a filter
        List<Reports.ReportFilter> filters = new List<Reports.ReportFilter>(); 
        Reports.ReportFilter newFilter = new Reports.ReportFilter();
        newFilter.setColumn('Account.GM_region__c');
        newFilter.setOperator('equals');
        newFilter.setValue(String.valueOf(reg.Id));
        filters.add(newFilter);
        reportMetadata.setReportFilters(filters);

        Test.startTest();
       
        Reports.ReportInstance instanceObj = Reports.ReportManager.runAsyncReport(reportId,reportMetadata,false);
        String instanceId = instanceObj.getId();
        
        // Report instance is not available yet.
        Test.stopTest();
        // After the stopTest method, the report has finished executing and should be avail in ReportUtilities
        ReportUtilities.getRecordIdsFromTabularReport (reportId, 'Account');


    }


    @isTest(SeeAllData='true') //SeeAllData gives us access to reports & report runs use seealldata=true regardless of this setting
    static void getSummaryRealReportDataTest() {
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName LIKE 'Proposals_TEMPLATE%'];
        String reportId = (String)reportList.get(0).get('Id');
      
        // Create Account/Proposal
        insert new Region__c (Name = 'test region');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account (Name = 'test account', GM_region__c = reg.Id, RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM'));
        Account a = [SELECT Id FROM Account LIMIT 1];
        insert new Proposal__c (Account__c = a.Id, SavedSetNames__c = 'test savedsetname');
        Proposal__c p = [SELECT Id, SavedSetNames__c FROM Proposal__c LIMIT 1];


        Reports.ReportMetadata reportMetadata = Reports.ReportManager.describeReport(reportId).getReportMetadata();
        
        List < String > columns = reportMetadata.getDetailColumns();
        System.debug('columns: '+columns);

        // Since report runs in test mode ALWAYS use seealldata=true, apply a filter
        List<Reports.ReportFilter> filters = new List<Reports.ReportFilter>(); 
        Reports.ReportFilter newFilter = new Reports.ReportFilter();
        newFilter.setColumn('Proposal__c.SavedSetNames__c');
        newFilter.setOperator('equals');
        newFilter.setValue('test savedsetname');
        filters.add(newFilter);
        reportMetadata.setReportFilters(filters);

        Test.startTest();
       
        Reports.ReportInstance instanceObj = Reports.ReportManager.runAsyncReport(reportId,reportMetadata,false);
        String instanceId = instanceObj.getId();
        
        // Report instance is not available yet.
        Test.stopTest();
        // After the stopTest method, the report has finished executing and should be avail in ReportUtilities
        ReportUtilities.getRecordIdsFromSummaryReport (reportId, 'Proposal__c');

    }

    @isTest(SeeAllData='true') //SeeAllData gives us access to reports & report runs use seealldata=true regardless of this setting
    static void getRowCountTest() {
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName LIKE 'Accounts_GM_TEMPLATE%'];
        String reportId = (String)reportList.get(0).get('Id');

        // test the row Count method-- Because the report will always run with seealldata=true, we can't know how many rows there will be
        //https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_analytics_test_reports.htm
        Integer rowCount = ReportUtilities.getRowCount(reportId);
        System.assertEquals(true, rowCount>0);
        
    }

}