force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this classification: Population, Strategy, or Issue</description>
    <inlineHelpText>Type of this classification: Population, Strategy, or Issue</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Population</fullName>
            </value>
            <value>
                <fullName>Strategy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/Classification_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single classification to a profile</description>
    <label>Classification-Profile Assign</label>
    <nameField>
        <displayFormat>CA-Prof-{00000}</displayFormat>
        <label>Classification-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile linked to this letter</description>
    <inlineHelpText>The profile linked to this letter</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region record linked to this letter</description>
    <inlineHelpText>Region record linked to this letter</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</description>
    <inlineHelpText>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Advisor assignments</fullName>
            </value>
            <value>
                <fullName>Saved Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portfolio_Profile_Assign__c/Portfolio_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a portfolio to a profile</description>
    <label>Portfolio-Profile Assign</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Portfolio-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Profile_Assign__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <description>The portfolio linked from this join record</description>
    <inlineHelpText>The portfolio linked from this join record</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Portfolio-Profile Assigns</relationshipLabel>
    <relationshipName>Portfolio_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Portfolio-Profile Assigns</relationshipLabel>
    <relationshipName>Portfolio_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date on which this profile will &quot;expire&quot;, at which point the applicant needs to complete a new one</description>
    <inlineHelpText>Date on which this profile will &quot;expire&quot;, at which point the applicant needs to complete a new one</inlineHelpText>
    <label>Expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Restricted_Classification_Portfolio__c/Restricted_Classification_Portfolio__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single restricted classification to a portfolio</description>
    <label>Restricted Classification-Portfolio</label>
    <nameField>
        <displayFormat>RCP-{000000}</displayFormat>
        <label>Restricted Classification-Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restricted Classifications-Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Restricted_Classification_Portfolio__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <description>The portfolio to which this &quot;join&quot; record assigns a restricted classification</description>
    <inlineHelpText>The portfolio to which this &quot;join&quot; record assigns a restricted classification</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Restricted Classifications</relationshipLabel>
    <relationshipName>Restricted_Classifications_Portfolios</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review_Form_Component__c/Review_Form_Component__c.object-meta.xml
<CustomObject>
    <description>Represents a component used by a review form for field entry</description>
    <label>Review Form Component</label>
    <nameField>
        <displayFormat>RFC-{000000}</displayFormat>
        <label>Review Form Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Form Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Form_Component__c/fields/Lightning_component_name__c.field-meta.xml
<CustomField>
    <fullName>Lightning_component_name__c</fullName>
    <description>The name of the lightning component used to instantiate this field in a review interface</description>
    <inlineHelpText>The name of the lightning component used to instantiate this field in a review interface</inlineHelpText>
    <label>Lightning component name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HeadingMedium</fullName>
            </value>
            <value>
                <fullName>HeadingSmall</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>InputCheckbox</fullName>
            </value>
            <value>
                <fullName>InputSelect</fullName>
            </value>
            <value>
                <fullName>InputSelectLookup</fullName>
            </value>
            <value>
                <fullName>InputSelectMulti</fullName>
            </value>
            <value>
                <fullName>InputSelectMulti1</fullName>
            </value>
            <value>
                <fullName>InputTextarea</fullName>
            </value>
            <value>
                <fullName>InputText</fullName>
            </value>
            <value>
                <fullName>InputTextReadonly</fullName>
            </value>
            <value>
                <fullName>InputNumber</fullName>
            </value>
            <value>
                <fullName>IndicatorGroup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review_Form_Component__c/fields/Review_Form__c.field-meta.xml
<CustomField>
    <fullName>Review_Form__c</fullName>
    <description>The review form to which this component belongs</description>
    <inlineHelpText>The review form to which this component belongs</inlineHelpText>
    <label>Review Form</label>
    <referenceTo>Review_Form__c</referenceTo>
    <relationshipLabel>Review Form Components</relationshipLabel>
    <relationshipName>Review_Form_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review_Form_Component__c/fields/Sort_number__c.field-meta.xml
<CustomField>
    <fullName>Sort_number__c</fullName>
    <description>This number determines where this component is inserted in the overall form</description>
    <inlineHelpText>This number determines where this component is inserted in the overall form</inlineHelpText>
    <label>Sort number</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProfileControllerTest.cls
@isTest
public with sharing class ProfileControllerTest {
    /**********************************
     * Test the component-related methods
     * *******************************/

    static testMethod void ProfileControllerTest1() {
        // Build new records
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'test account',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Id aId = [SELECT Id FROM Account LIMIT 1].Id;
        insert new Review_Form__c(Name = 'Profile');
        Id rfId = [SELECT Id FROM Review_Form__c LIMIT 1].Id;
        insert new Review_Form_Component__c(
            Review_Form__c = rfId,
            Lightning_component_name__c = 'InputCheckbox',
            Sort_number__c = 1
        );
        insert new Profile__c(
            Expiration_date__c = Date.newInstance(1960, 2, 17)
        );
        Profile__c p = [SELECT Id FROM Profile__c LIMIT 1];
        Id pId = p.Id;
        insert new Portfolio__c(Name = 'Test portfolio', Type__c = 'Priority');
        Id portId = [SELECT Id FROM Portfolio__c LIMIT 1].Id;
        insert new Portfolio_Profile_Assign__c(
            Profile__c = pId,
            Portfolio__c = portId
        );
        insert new Classification__c(
            Name = 'Test classification',
            Type__c = 'Population'
        );
        Id cpId = [SELECT Id FROM Classification__c LIMIT 1].Id;
        insert new Classification__c(
            Name = 'Test classification',
            Type__c = 'Strategy'
        );
        Id csId = [SELECT Id FROM Classification__c LIMIT 1].Id;
        insert new Classification__c(
            Name = 'Test classification',
            Type__c = 'Issue'
        );
        Id ciId = [SELECT Id FROM Classification__c LIMIT 1].Id;
        insert new Classification__c(
            Name = 'Test pop classification',
            Type__c = 'Population'
        );
        Id cId = [SELECT Id FROM Classification__c LIMIT 1].Id;
        insert new Classification_Profile_Assign__c(
            Profile__c = pId,
            Classification__c = cId
        );
        insert new Restricted_Classification__c(
            Name = 'Test restr classification',
            Type__c = 'Outcome'
        );
        Id rcId = [SELECT Id FROM Restricted_Classification__c LIMIT 1].Id;
        insert new Restricted_Classification_Portfolio__c(
            Portfolio__c = portId,
            Restricted_Classification__c = rcId
        );

        Test.StartTest();
        ProfileController.getProfile(pId);
        ProfileController.saveProfile(p);
        ProfileController.getProfileInfo(pId);
        ProfileController.saveProfileInfo2(
            p,
            String.valueOf(cId),
            String.valueOf(csId),
            String.valueOf(ciId),
            String.valueOf(portId)
        );
        ProfileController.getClassificationInfo('Issue', pId);
        Test.StopTest();
    }

    static testMethod void ProfileControllerTest2() {
        // Build new records
        insert new Profile__c(
            Expiration_date__c = Date.newInstance(1960, 2, 17)
        );
        Profile__c p = [SELECT Id FROM Profile__c LIMIT 1];
        Id pId = p.Id;
        insert new Template__c(Name = 'Request to submit Updated Profile');

        Test.StartTest();
        // Test profile clone batch class.  Check results after test.stopTest().
        String q =
            'SELECT Id, Decline_reason__c, Decline_reason__r.Name FROM Profile__c ' +
            ' WHERE Expiration_date__c <> null ' +
            ' AND Expiration_date__c <= TODAY ' +
            ' AND Next_profile__c = null';
        Database.executeBatch(new ProfileCloneBatch(q), 10);
        Test.StopTest();
        p = [SELECT Id, Next_profile__c FROM Profile__c WHERE Id = :pId];
        system.assertNotEquals(null, p);
        system.assertNotEquals(null, p.Next_profile__c);
        Profile__c pClone = [
            SELECT Id
            FROM Profile__c
            WHERE Id = :p.Next_profile__c
        ];
        system.assertNotEquals(null, pClone);
    }

    static testMethod void ProfileControllerTest3() {
        // Build new records
        insert new Profile__c(
            Expiration_date__c = Date.newInstance(1960, 2, 17)
        );
        Profile__c p = [SELECT Id FROM Profile__c LIMIT 1];
        Id pId = p.Id;
        insert new Template__c(Name = 'Request to submit Updated Profile');

        Test.StartTest();
        // Schedule test of profile clone.  Check results after test.stopTest().
        String cronExp = '0 0 0 15 3 ?';
        String jobId = System.schedule(
            'ScheduleApexClassTest',
            cronExp,
            new ProfileCloneSchedule()
        );
        Test.StopTest();
    }

    /**********************************
     * Test the VF-related methods
     * *******************************/

    static testMethod void ProfileControllerTestVF() {
        // Build new records
        InitTestObjects(10);
        Map<Id, Profile__c> pMap = new Map<Id, Profile__c>(
            [SELECT Id FROM Profile__c]
        );
        // Build new standard set controller and select the new profiles.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            pMap.values()
        );
        ssc.setSelected(pMap.values());

        Test.StartTest();
        // Build a new profile controller and use it to build new letters for the selected profiles.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'Profile__c'
        ));
        ProfileController pc = new ProfileController(ssc);
        pc.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', pc.selectedTemplate),
            null
        );
        pc.buildLetters();
        Test.StopTest();

        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );
        validate(lMap.keySet());
    }

    static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [
                SELECT Emails__c, Profile__c
                FROM Letter__c
                WHERE Id IN :lIds
            ]
        );
        Map<Id, Profile__c> pMap = new Map<Id, Profile__c>(
            [
                SELECT Id
                FROM Profile__c
                WHERE Id IN (SELECT Profile__c FROM Letter__c WHERE Id IN :lIds)
            ]
        );
        // Should be a different letter for each profile.
        system.assertEquals(lMap.size(), pMap.size());
    }

    // NOTE: Not providing email address for these profiles, because we'd have to create linked contacts and accounts.
    static void InitTestObjects(Integer NumberOfProfiles) {
        List<Profile__c> pas = new List<Profile__c>();
        for (Integer x = 0; x < NumberOfProfiles; x++) {
            pas.add(new Profile__c());
        }
        insert pas;
    }
}