force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/GM_Data__c/GM_Data__c.object-meta.xml
<CustomObject>
    <description>Contains grant-related data and indicators stemming from the group&apos;s grant application and their milestones</description>
    <label>GM Data</label>
    <nameField>
        <displayFormat>GMD-{0000000}</displayFormat>
        <label>GM Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GM Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GM_Data__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The portfolio (if any) providing the context for restricted and eligibility-related fields in this GM Data record</description>
    <inlineHelpText>The portfolio (if any) providing the context for restricted and eligibility-related fields in this GM Data record</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GM_Data__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile record, if any, to which this GM data is linked</description>
    <inlineHelpText>The profile record, if any, to which this GM data is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Indicator__c/Indicator__c.object-meta.xml
<CustomObject>
    <description>Represents an indicator for LEI grantmaking analysis</description>
    <label>Indicator</label>
    <nameField>
        <label>Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this indicator.  This field is used to group indicators in review forms.</description>
    <inlineHelpText>The type of this indicator.  This field is used to group indicators in review forms.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Indicator_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile linked to this letter</description>
    <inlineHelpText>The profile linked to this letter</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region record linked to this letter</description>
    <inlineHelpText>Region record linked to this letter</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Represents a milestone (report, payment, site visit, etc.) due or received for this grant</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of milestone</description>
    <inlineHelpText>The type of milestone</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</description>
    <inlineHelpText>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Advisor assignments</fullName>
            </value>
            <value>
                <fullName>Saved Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portfolio_Profile_Assign__c/Portfolio_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a portfolio to a profile</description>
    <label>Portfolio-Profile Assign</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Portfolio-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Profile_Assign__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <description>The portfolio linked from this join record</description>
    <inlineHelpText>The portfolio linked from this join record</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Portfolio-Profile Assigns</relationshipLabel>
    <relationshipName>Portfolio_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Portfolio-Profile Assigns</relationshipLabel>
    <relationshipName>Portfolio_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date on which this profile will &quot;expire&quot;, at which point the applicant needs to complete a new one</description>
    <inlineHelpText>Date on which this profile will &quot;expire&quot;, at which point the applicant needs to complete a new one</inlineHelpText>
    <label>Expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this proposal is linked</description>
    <inlineHelpText>The profile to which this proposal is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Restricted_Classification_Portfolio__c/Restricted_Classification_Portfolio__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single restricted classification to a portfolio</description>
    <label>Restricted Classification-Portfolio</label>
    <nameField>
        <displayFormat>RCP-{000000}</displayFormat>
        <label>Restricted Classification-Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restricted Classifications-Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Restricted_Classification_Portfolio__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <description>The portfolio to which this &quot;join&quot; record assigns a restricted classification</description>
    <inlineHelpText>The portfolio to which this &quot;join&quot; record assigns a restricted classification</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Restricted Classifications</relationshipLabel>
    <relationshipName>Restricted_Classifications_Portfolios</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Indicator_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Change Matrix</fullName>
    </customValue>
    <customValue>
        <fullName>Movement Building</fullName>
    </customValue>
    <customValue>
        <fullName>Crisis Response</fullName>
    </customValue>
    <customValue>
        <fullName>Initiative A</fullName>
    </customValue>
    <description>Indicator types</description>
    <masterLabel>Indicator type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Milestone_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Report</fullName>
    </customValue>
    <customValue>
        <fullName>Report narrative</fullName>
    </customValue>
    <customValue>
        <fullName>Report financial</fullName>
    </customValue>
    <customValue>
        <fullName>Report activities</fullName>
    </customValue>
    <customValue>
        <fullName>Site visit</fullName>
    </customValue>
    <description>Milestone types</description>
    <masterLabel>Milestone type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GMDataControllerTest.cls
@isTest
public class GMDataControllerTest {
    /**********************************
     * Test the component-related methods
     * *******************************/

    static testMethod void GMDataControllerTest1() {
        // Build new records
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'acc test',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Id aId = [SELECT Id FROM Account LIMIT 1].Id;
        insert new Profile__c(
            Expiration_date__c = Date.newInstance(1960, 2, 17)
        );
        Profile__c p = [SELECT Id FROM Profile__c LIMIT 1];
        Id pId = p.Id;
        insert new Portfolio__c(Name = 'Test portfolio', Type__c = 'Priority');
        Id portId = [SELECT Id FROM Portfolio__c LIMIT 1].Id;
        insert new Portfolio_Profile_Assign__c(
            Profile__c = pId,
            Portfolio__c = portId
        );
        insert new GM_Data__c(Account__c = aId, Portfolio__c = portId);
        Id gId = [SELECT Id FROM GM_Data__c LIMIT 1].Id;
        insert new Restricted_Classification__c(
            Name = 'Test restr class 1',
            Type__c = 'Outcome'
        );
        insert new Restricted_Classification__c(
            Name = 'Test restr class 2',
            Type__c = 'Outcome'
        );
        Id rcId1 = [
            SELECT Id
            FROM Restricted_Classification__c
            WHERE Name = 'Test restr class 1'
            LIMIT 1
        ]
        .Id;
        Id rcId2 = [
            SELECT Id
            FROM Restricted_Classification__c
            WHERE Name = 'Test restr class 2'
            LIMIT 1
        ]
        .Id;
        insert new Restricted_Classification_Portfolio__c(
            Portfolio__c = portId,
            Restricted_Classification__c = rcId1
        );
        insert new Restricted_Classification_GM_Data__c(
            GM_Data__c = gId,
            Restricted_Classification__c = rcId1
        );

        insert new Indicator__c(
            Name = 'test indicator 1',
            GM_Data_field_name__c = 'Test_indicator_tracking__c'
        );
        insert new Indicator__c(
            Name = 'test indicator 2',
            GM_Data_field_name__c = 'Test_indicator_tracking__c'
        );
        insert new Indicator__c(
            Name = 'test indicator 3',
            GM_Data_field_name__c = 'Test_indicator_tracking__c'
        );
        Id indId1 = [
            SELECT Id
            FROM Indicator__c
            WHERE Name = 'test indicator 1'
            LIMIT 1
        ]
        .Id;
        Id indId2 = [
            SELECT Id
            FROM Indicator__c
            WHERE Name = 'test indicator 2'
            LIMIT 1
        ]
        .Id;
        Id indId3 = [
            SELECT Id
            FROM Indicator__c
            WHERE Name = 'test indicator 3'
            LIMIT 1
        ]
        .Id;
        insert new Indicator_Assign__c(
            Indicator__c = indId1,
            GM_Data__c = gId,
            Quantity__c = 13
        );
        insert new Indicator_Assign__c(
            Indicator__c = indId2,
            GM_Data__c = gId,
            Quantity__c = 14
        );

        Test.StartTest();
        GMDataController.GMDataInfo gm = GMDataController.getGMDataInfo(gId);
        gm.indicatorAssignInfo.put(indId1, '15;'); // Update an existing indicator assign.
        gm.indicatorAssignInfo.put(indId3, '111;abc'); // Insert a new indicator assign.
        system.debug('gm = ' + JSON.serialize(gm));
        GMDataController.saveGMDataInfo(JSON.serialize(gm));
        gm = GMDataController.getGMDataInfo(gId);
        gm.selectedIdsPacked.put(gId, (String) rcId2);
        GMDataController.saveGMDataInfo(JSON.serialize(gm));
        Test.StopTest();
    }

    /**********************************
     * Test the VF-related methods
     * *******************************/

    static testMethod void GMDataControllerTestVF() {
        // Build new records
        InitTestObjects(10);
        Map<Id, GM_Data__c> gMap = new Map<Id, GM_Data__c>(
            [SELECT Id FROM GM_Data__c]
        );
        // Build new standard set controller and select the new profiles.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            gMap.values()
        );
        ssc.setSelected(gMap.values());

        Test.StartTest();
        // Build a new profile controller and use it to build new letters for the selected profiles.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'GM_Data__c'
        ));
        GMDataController pc = new GMDataController(ssc);
        pc.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', pc.selectedTemplate),
            null
        );
        pc.buildLetters();
        Test.StopTest();

        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );
        validate(lMap.keySet());
    }

    static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Emails__c, GM_Data__c FROM Letter__c WHERE Id IN :lIds]
        );
        Map<Id, GM_Data__c> gMap = new Map<Id, GM_Data__c>(
            [
                SELECT Id
                FROM GM_Data__c
                WHERE Id IN (SELECT GM_Data__c FROM Letter__c WHERE Id IN :lIds)
            ]
        );
        // Should be a different letter for each profile.
        system.assertEquals(lMap.size(), gMap.size());
    }

    // NOTE: Not providing email addresses, because we'd have to create linked contacts and accounts.
    static void InitTestObjects(Integer NumberOfRecords) {
        // Build and insert GM data records.
        List<GM_Data__c> gas = new List<GM_Data__c>();
        for (Integer x = 0; x < NumberOfRecords; x++) {
            gas.add(new GM_Data__c());
        }
        insert gas;
    }

    // Test the code that updates risk fields.
    static testMethod void GMDataControllerTest2() {
        // Build records
        BuildTestProposals.InitTestObjects(1, 1);
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Proposal__c prop = [SELECT Id FROM Proposal__c LIMIT 1];
        // Build two grants with milestones on that account.
        // NOTE: Uncomment out the following lines to get more coverage from the test.  But they must be
        // commented out when deploying to avoid "Too many SOQL" errors.
        /*
        insert new Proposal__c (Account__c = acc.Id, Date_awarded__c = Date.today().addDays(-100), Amount_awarded__c = 100);
        Proposal__c prop2 = [SELECT Id FROM Proposal__c WHERE Amount_awarded__c = 100 LIMIT 1];
        insert new Milestone__c (Proposal__c = prop2.Id, Type__c = 'Report', Date_due__c = Date.today().addDays(-30));
        insert new Proposal__c (Account__c = acc.Id, Date_awarded__c = Date.today().addDays(-100), Amount_awarded__c = 200);
        Proposal__c prop3 = [SELECT Id FROM Proposal__c WHERE Amount_awarded__c = 200 LIMIT 1];
        insert new Milestone__c (Proposal__c = prop3.Id, Type__c = 'Report', Date_due__c = Date.today().addDays(-60));
        */

        Test.StartTest();
        String cronExp = '0 0 0 15 3 ?';
        System.schedule(
            'GMDataUpdateSchedule',
            cronExp,
            new GMDataUpdateSchedule()
        );
        Test.StopTest();
    }
}