force-app/main/default/objects/Account/fields/GM_region__c.field-meta.xml
<CustomField>
    <fullName>GM_region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</description>
    <inlineHelpText>The region where this organization does its work.  NOTE: field will AutoUpdate upon Saving</inlineHelpText>
    <label>GM region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>Group other than a corporation or household.</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>An address linked to the account</description>
    <label>Address</label>
    <nameField>
        <displayFormat>a{0000000}</displayFormat>
        <label>Address name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An internal field used to link this address info to an Account.</description>
    <inlineHelpText>An internal field used to link this address info to an Account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks if this address is being used as account address.</description>
    <inlineHelpText>Checks if this address is being used as account address.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Multiple street lines can be entered by simply hitting enter after each line.  A total of 255 characters can be entered.  This field, along with the Locality field, is for use in mail merges.</description>
    <inlineHelpText>Multiple street lines can be entered by simply hitting enter after each line.  A total of 255 characters can be entered.  This field, along with the Locality field, is for use in mail merges.</inlineHelpText>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>Alternate email address</description>
    <inlineHelpText>Alternate email address</inlineHelpText>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <defaultValue>/* Default GM contacts to rank 1, Dev contacts to blank. */
IF(CONTAINS($RecordType.DeveloperName, &quot;GM&quot;), 1, null)</defaultValue>
    <description>Used to sort contacts within an account, for example, to pick the primary one</description>
    <inlineHelpText>Used to sort contacts within an account, for example, to pick the primary one</inlineHelpText>
    <label>Rank</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_Dev.recordType-meta.xml
<RecordType>
    <fullName>Contact_Dev</fullName>
    <active>true</active>
    <description>Record type for Dev&apos;s contact records (including individual donors and prospects)</description>
    <label>Contact Dev</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact_GM.recordType-meta.xml
<RecordType>
    <fullName>Contact_GM</fullName>
    <active>true</active>
    <description>For grantmaking-related contact records, primarily staff at grantee/applicant orgs</description>
    <label>Contact GM</label>
</RecordType>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <description>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</description>
    <inlineHelpText>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</inlineHelpText>
    <label>Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region record linked to this letter</description>
    <inlineHelpText>Region record linked to this letter</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Source_object__c.field-meta.xml
<CustomField>
    <fullName>Source_object__c</fullName>
    <description>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</description>
    <inlineHelpText>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</inlineHelpText>
    <label>Source object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>GM_Data__c</fullName>
            </value>
            <value>
                <fullName>Milestone__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Payment__c</fullName>
            </value>
            <value>
                <fullName>Payment_Method__c</fullName>
            </value>
            <value>
                <fullName>Profile__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountControllerTest.cls
@isTest
public with sharing class AccountControllerTest {
    static testMethod void AccountControllerTest1() {
        // Build new proposals and accounts
        BuildTestProposals.InitTestObjects(2, 2);
        // Build a dev account with a contact.
        insert new Account(
            Name = 'test dev account',
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization')
        );
        Account acc1 = [
            SELECT Id
            FROM Account
            WHERE Name = 'test dev account'
            LIMIT 1
        ];
        insert new Contact(
            LastName = 'test last name',
            AccountId = acc1.Id,
            Rank__c = 1,
            Email = 'abc1@def.org',
            Email2__c = 'abc1@def.org',
            RecordTypeId = Utilities.getRecTypeId('Contact', 'Contact_Dev')
        );
        Map<Id, Account> aMap = new Map<Id, Account>([SELECT Id FROM Account]);
        // Build new standard set controller and select the new accounts.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(
            aMap.values()
        );
        ssc.setSelected(aMap.values());

        Test.StartTest();
        // Build a new controller and use it to build new letters for the selected accounts.
        insert (new Template__c(
            Name = 'Test template',
            Source_object__c = 'Account'
        ));
        AccountController ac = new AccountController(ssc);
        ac.selectedTemplate = 'Test template';
        system.assertNotEquals(
            Utilities.recordIdFromName('Template__c', ac.selectedTemplate),
            null
        );
        ac.buildLetters();
        Test.StopTest();

        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );
        validate(lMap.keySet());
    }

    static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Account__c, Emails__c FROM Letter__c WHERE Id IN :lIds]
        );
        system.debug('validate: lMap = ' + JSON.serialize(lMap));
        // Gather accounts and their contacts' email addresses.
        Map<Id, Account> aMap = new Map<Id, Account>(
            [
                SELECT Id
                FROM Account
                WHERE Id IN (SELECT Account__c FROM Letter__c WHERE Id IN :lIds)
            ]
        );
        system.debug('validate: aMap = ' + JSON.serialize(aMap));
        // Should be a different letter for each account.
        system.assertEquals(lMap.size(), aMap.size());
        Map<Id, List<String>> emailMap = AccountController.emailsForAccounts(
            aMap.keySet()
        );
        system.debug('validate: emailMap = ' + JSON.serialize(emailMap));
        // The emails stored on the letter need to agree with the account's emails.
        for (Letter__c l : lMap.values()) {
            system.assertEquals(
                l.Emails__c,
                Utilities.stringJoinWithCharLimit(emailMap.get(l.Account__c), ',', 255)
            );
        }
    }

    // Test the update contact info code.
    static testMethod void AccountControllerTest4() {
        // Build records.
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'acc test',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Address__c(
            Account__c = acc.Id,
            IsActive__c = true,
            Street__c = 'aaa'
        );
        insert new Contact(
            AccountId = acc.Id,
            LastName = 'Test contact',
            Rank__c = 1,
            Email = 'testing@applicant.org',
            RecordTypeId = Utilities.getRecTypeId('Contact', 'Contact_GM')
        );

        Test.startTest();
        AccountUpdateContactInfoInvocable.updateContactInfo(
            new List<Id>{ acc.Id }
        );
        Test.stopTest();
    }
}