force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <description>Representations an allocation of all or part of a grant to a fund (funding source)</description>
    <label>Charge</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Distribution__c.field-meta.xml
<CustomField>
    <fullName>Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The distribution within the charge&apos;s fund against which this charge is released</description>
    <inlineHelpText>The distribution within the charge&apos;s fund against which this charge is released</inlineHelpText>
    <label>Distribution</label>
    <referenceTo>Distribution__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <description>The fund to which this charge applies</description>
    <inlineHelpText>The fund to which this charge applies</inlineHelpText>
    <label>Fund</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>May only charge to active funds.</errorMessage>
        <filterItems>
            <field>Fund__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>May only charge to active funds.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Projection__c.field-meta.xml
<CustomField>
    <fullName>Projection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The projection within the charge&apos;s fund against which this charge is released</description>
    <inlineHelpText>The projection within the charge&apos;s fund against which this charge is released</inlineHelpText>
    <label>Projection</label>
    <referenceTo>Projection__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distribution__c/Distribution__c.object-meta.xml
<CustomObject>
    <description>A Distribution record is a link from a Pending fund to a Standard one.  The specified amount of funds (usually unrestricted by the donor) is considered to be &quot;moved&quot; from the pending fund to the standard fund where it is available for grantmaking.</description>
    <label>Distribution</label>
    <nameField>
        <displayFormat>DIST-{000000}</displayFormat>
        <label>Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of this distribution</description>
    <inlineHelpText>The amount of this distribution</inlineHelpText>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Distribution__c/fields/ChartofAccounts__c.field-meta.xml
<CustomField>
    <fullName>ChartofAccounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This distribution&apos;s chart of accounts record</description>
    <inlineHelpText>This distribution&apos;s chart of accounts record</inlineHelpText>
    <label>ChartofAccounts</label>
    <referenceTo>ChartofAccounts__c</referenceTo>
    <relationshipLabel>Distributions</relationshipLabel>
    <relationshipName>Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distribution__c/fields/Fiscal_year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_year__c</fullName>
    <description>The fiscal year to which this distribution applies</description>
    <inlineHelpText>The fiscal year to which this distribution applies</inlineHelpText>
    <label>Fiscal year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Distribution__c/fields/Source_fund__c.field-meta.xml
<CustomField>
    <fullName>Source_fund__c</fullName>
    <description>The pending fund that is the source of this distribution of funds</description>
    <inlineHelpText>The pending fund that is the source of this distribution of funds</inlineHelpText>
    <label>Source fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Distributions</relationshipLabel>
    <relationshipName>Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Distribution__c/fields/Target_fund__c.field-meta.xml
<CustomField>
    <fullName>Target_fund__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The standard fund that is the target of this distribution of funds for grantmaking</description>
    <inlineHelpText>The standard fund that is the target of this distribution of funds for grantmaking</inlineHelpText>
    <label>Target fund</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Target fund must have the record type = Standard.</errorMessage>
        <filterItems>
            <field>Fund__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Choose from among Standard funds</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Distributions (Target fund)</relationshipLabel>
    <relationshipName>Distributions1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Represents an amount of restricted funding</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/Amount_funded__c.field-meta.xml
<CustomField>
    <fullName>Amount_funded__c</fullName>
    <description>Amount in dollars of fund not including overhead</description>
    <inlineHelpText>Amount in dollars of fund not including overhead</inlineHelpText>
    <label>Amount funded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/ChartofAccounts__c.field-meta.xml
<CustomField>
    <fullName>ChartofAccounts__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This fund&apos;s chart of accounts record</description>
    <inlineHelpText>This fund&apos;s chart of accounts record</inlineHelpText>
    <label>Chart of Accounts</label>
    <referenceTo>ChartofAccounts__c</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Fiscal_year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_year__c</fullName>
    <description>The fiscal year of this fund</description>
    <inlineHelpText>The fiscal year of this fund</inlineHelpText>
    <label>Fiscal year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region to which this fund applies (if any)</description>
    <inlineHelpText>Region to which this fund applies (if any)</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Total_available__c.field-meta.xml
<CustomField>
    <fullName>Total_available__c</fullName>
    <description>The total amount of any linked projections and distributions.  Note that Standard and Pending funds only sum the grantmaking part of linked projections.</description>
    <inlineHelpText>The total amount of any linked projections and distributions.  Note that Standard and Pending funds only sum the grantmaking part of linked projections.</inlineHelpText>
    <label>Total available</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/recordTypes/Overhead.recordType-meta.xml
<RecordType>
    <fullName>Overhead</fullName>
    <active>false</active>
    <description>Captures total &quot;overhead&quot;, that is, the non-grantmaking amount, from projections linked to grantmaking (non-revenue) funds.  The total is maintained by a nightly script.</description>
    <label>Overhead</label>
</RecordType>

force-app/main/default/objects/Fund__c/recordTypes/Pending.recordType-meta.xml
<RecordType>
    <fullName>Pending</fullName>
    <active>true</active>
    <description>Record type for &quot;pending&quot; fund records, holding funds (usually unrestricted) awaiting distribution into standard funds</description>
    <label>Pending</label>
</RecordType>

force-app/main/default/objects/Fund__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Standard funds represent an amount of restricted funding to be allocated for grantmaking.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Projection__c/Projection__c.object-meta.xml
<CustomObject>
    <description>Projections are used to log and track a high-level breakdown of the amounts expected from a particular opportunity or gift in a particular fiscal year.</description>
    <label>Projection</label>
    <nameField>
        <displayFormat>PROJ-{000000}</displayFormat>
        <label>Projection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Projection__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount allocated for this projection - if blank, then total amount is calculated by adding grantmaking and non-grantmaking amounts.</description>
    <inlineHelpText>The amount allocated for this projection - if blank, then total amount is calculated by adding grantmaking and non-grantmaking amounts.</inlineHelpText>
    <label>Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/ChartofAccounts__c.field-meta.xml
<CustomField>
    <fullName>ChartofAccounts__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This projection&apos;s chart of accounts record</description>
    <inlineHelpText>This projection&apos;s chart of accounts record</inlineHelpText>
    <label>Chart of Accounts</label>
    <referenceTo>ChartofAccounts__c</referenceTo>
    <relationshipLabel>Projections</relationshipLabel>
    <relationshipName>Projections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Fiscal_year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_year__c</fullName>
    <description>The fiscal year to which this projection applies</description>
    <inlineHelpText>The fiscal year to which this projection applies</inlineHelpText>
    <label>Fiscal year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The fund that specifies and tracks how the grantmaking part of this projection is spent</description>
    <inlineHelpText>The fund that specifies and tracks how the grantmaking part of this projection is spent</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Projections</relationshipLabel>
    <relationshipName>Projections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Grantmaking_amount__c.field-meta.xml
<CustomField>
    <fullName>Grantmaking_amount__c</fullName>
    <description>Specific amount allocated for grantmaking - if blank, then grantmaking amount is calculated using the grantmaking percent field</description>
    <inlineHelpText>Specific amount allocated for grantmaking - if blank, then grantmaking amount is calculated using the grantmaking percent field</inlineHelpText>
    <label>Grantmaking amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Non_grantmaking_amount__c.field-meta.xml
<CustomField>
    <fullName>Non_grantmaking_amount__c</fullName>
    <description>Specific amount allocated for non-grantmaking purposes - if blank, then non-grantmaking amount is calculated using the grantmaking percent field</description>
    <inlineHelpText>Specific amount allocated for non-grantmaking purposes - if blank, then non-grantmaking amount is calculated using the grantmaking percent field</inlineHelpText>
    <label>Non-grantmaking amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FundControllerTest.cls
@isTest
public class FundControllerTest {
    static testMethod void FundControllerTest1() {
        // Build new records.
        insert new ChartofAccounts__c(Name = 'Test c-of-a');
        ChartofAccounts__c cOfA = [
            SELECT Id
            FROM ChartofAccounts__c
            WHERE Name = 'Test c-of-a'
            LIMIT 1
        ];
        String fy = String.valueOf(Date.today().year());
        insert new Fund__c(
            // Record type Overhead is currently (10/14/20) hidden for FFDB
            RecordTypeId = Utilities.getRecTypeId(
                'Fund__c',
                'Standard' // 'Overhead'
            ),
            Name = 'Testfundoverhead',
            Amount_funded__c = 0,
            Fiscal_year__c = fy
        );
        insert new Fund__c(
            RecordTypeId = Utilities.getRecTypeId('Fund__c', 'Standard'),
            Name = 'Testfundstandard',
            Amount_funded__c = 100,
            Fiscal_year__c = fy
        );
        Fund__c fund1 = [
            SELECT Id
            FROM Fund__c
            WHERE Name = 'Testfundstandard'
            LIMIT 1
        ];
        insert new Fund__c(
            // Record type Pending is currently (10/14/20) hidden for FFDB
            RecordTypeId = Utilities.getRecTypeId(
                'Fund__c',
                'Standard' // 'Pending'
            ),
            Name = 'Testfundpending',
            Amount_funded__c = 100,
            Fiscal_year__c = fy
        );
        Fund__c fund2 = [
            SELECT Id
            FROM Fund__c
            WHERE Name = 'Testfundpending'
            LIMIT 1
        ];
        insert new Projection__c(
            ChartofAccounts__c = cOfA.Id,
            Fiscal_year__c = fy,
            Fund__c = fund1.Id,
            Grantmaking_amount__c = 100,
            Non_grantmaking_amount__c = 10
        );
        insert new Distribution__c(
            Source_fund__c = fund2.Id,
            Target_fund__c = fund1.Id,
            Fiscal_year__c = fy,
            Amount__c = 200
        );
        // Build a fund with no projections/distributions whose total amount projected needs to be zeroed out.
        insert new Fund__c(
            RecordTypeId = Utilities.getRecTypeId('Fund__c', 'Standard'),
            Name = 'Testfundstandard 3',
            Amount_funded__c = 100,
            Total_available__c = 10
        );

        Test.StartTest();
        FundController.updateTotals(null);
        Test.StopTest();
        Fund__c fund0 = [
            SELECT Id, Total_available__c
            FROM Fund__c
            WHERE Name = 'Testfundoverhead'
            LIMIT 1
        ];
        fund1 = [
            SELECT Id, Total_available__c
            FROM Fund__c
            WHERE Name = 'Testfundstandard'
            LIMIT 1
        ];
        fund2 = [
            SELECT Id, Total_available__c
            FROM Fund__c
            WHERE Name = 'Testfundpending'
            LIMIT 1
        ];
        Fund__c fund3 = [
            SELECT Id, Total_available__c
            FROM Fund__c
            WHERE Name = 'Testfundstandard 3'
            LIMIT 1
        ];
        // Asserts temporarily commented out (10/14/20). Bring them back when fund record types are reactivated.
        /*
        system.assertEquals(10, fund0.Total_available__c);
        system.assertEquals(300, fund1.Total_available__c);
        system.assertEquals(null, fund2.Total_available__c);
        system.assertEquals(0, fund3.Total_available__c);
        */
        // Update total via invocable and schedule for code coverage.
        FundUpdateTotalInvocable.updateTotal(new List<Id>{ fund1.Id });
        System.schedule(
            'UpdateTotals test',
            '0 0 0 15 3 ?',
            new FundUpdateTotalsSchedule()
        );
    }

    static testMethod void FundControllerTest2() {
        // Build new records.
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'acc test',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Proposal__c(Account__c = acc.Id);
        Proposal__c prop = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new ChartofAccounts__c(Name = 'Test c-of-a');
        ChartofAccounts__c cOfA = [
            SELECT Id
            FROM ChartofAccounts__c
            WHERE Name = 'Test c-of-a'
            LIMIT 1
        ];
        String fy = String.valueOf(Date.today().year());
        insert new Fund__c(
            RecordTypeId = Utilities.getRecTypeId('Fund__c', 'Standard'),
            Name = 'Testfundstandard',
            Amount_funded__c = 100,
            Active__c = true
        );
        Fund__c fund1 = [
            SELECT Id
            FROM Fund__c
            WHERE Name = 'Testfundstandard'
            LIMIT 1
        ];
        insert new Fund__c(
            // Record type Pending is currently (10/14/20) hidden for FFDB
            RecordTypeId = Utilities.getRecTypeId(
                'Fund__c',
                'Standard' // 'Pending'
            ),
            Name = 'Testfundpending',
            Amount_funded__c = 100,
            Active__c = true
        );
        Fund__c fund2 = [
            SELECT Id
            FROM Fund__c
            WHERE Name = 'Testfundpending'
            LIMIT 1
        ];
        insert new Projection__c(
            ChartofAccounts__c = cOfA.Id,
            Fiscal_year__c = fy,
            Fund__c = fund1.Id,
            Grantmaking_amount__c = 100,
            Non_grantmaking_amount__c = 0
        );
        Projection__c proj = [SELECT Id FROM Projection__c LIMIT 1];
        insert new Distribution__c(
            Source_fund__c = fund2.Id,
            Target_fund__c = fund1.Id,
            Fiscal_year__c = fy,
            Amount__c = 200
        );
        insert new Charge__c(
            Proposal__c = prop.Id,
            Projection__c = proj.Id,
            Fund__c = fund1.Id,
            Amount_charged__c = 100
        );
        Charge__c chg = [SELECT Id FROM Charge__c LIMIT 1];
        String jsonString = JSON.serialize(
            new Map<String, Object>{
                'chargeIds' => new List<String>{ chg.Id },
                'projectionId' => proj.Id,
                'distributionId' => null,
                'dateReleased' => Date.today()
            }
        );

        Test.StartTest();
        FundController.getRecordsForReleasing(fund1.Id);
        Test.StopTest();

        proj = [SELECT Id, Amount_released__c FROM Projection__c LIMIT 1];
        system.assertEquals(100, proj.Amount_released__c);
    }

    static testMethod void FundControllerTest3() {
        // Build new records.
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'acc test',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Proposal__c(Account__c = acc.Id);
        Proposal__c prop = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new ChartofAccounts__c(Name = 'Test c-of-a');
        ChartofAccounts__c cOfA = [
            SELECT Id
            FROM ChartofAccounts__c
            WHERE Name = 'Test c-of-a'
            LIMIT 1
        ];
        String fy = String.valueOf(Date.today().year());
        insert new Fund__c(
            RecordTypeId = Utilities.getRecTypeId('Fund__c', 'Standard'),
            Name = 'Testfundstandard',
            Amount_funded__c = 100,
            Active__c = true
        );
        Fund__c fund1 = [
            SELECT Id
            FROM Fund__c
            WHERE Name = 'Testfundstandard'
            LIMIT 1
        ];
        insert new Fund__c(
            // Record type Pending is currently (10/14/20) hidden for FFDB
            RecordTypeId = Utilities.getRecTypeId(
                'Fund__c',
                'Standard' // 'Pending'
            ),
            Name = 'Testfundpending',
            Amount_funded__c = 100,
            Active__c = true
        );
        Fund__c fund2 = [
            SELECT Id
            FROM Fund__c
            WHERE Name = 'Testfundpending'
            LIMIT 1
        ];
        insert new Projection__c(
            ChartofAccounts__c = cOfA.Id,
            Fiscal_year__c = fy,
            Fund__c = fund1.Id,
            Grantmaking_amount__c = 100,
            Non_grantmaking_amount__c = 0
        );
        Projection__c proj = [SELECT Id FROM Projection__c LIMIT 1];
        insert new Distribution__c(
            Source_fund__c = fund2.Id,
            Target_fund__c = fund1.Id,
            Fiscal_year__c = fy,
            Amount__c = 200
        );
        insert new Charge__c(
            Proposal__c = prop.Id,
            Projection__c = proj.Id,
            Fund__c = fund1.Id,
            Amount_charged__c = 100
        );
        Charge__c chg = [SELECT Id FROM Charge__c LIMIT 1];
        String jsonString = JSON.serialize(
            new Map<String, Object>{
                'chargeIds' => new List<String>{ chg.Id },
                'projectionId' => proj.Id,
                'distributionId' => null,
                'dateReleased' => Date.today()
            }
        );

        Test.StartTest();
        // Unrelease that single charge.
        String responseString = FundController.unreleaseCharges(jsonString);
        system.debug('responseString = ' + responseString);
        chg = [
            SELECT Id, Date_released__c, Projection__c
            FROM Charge__c
            LIMIT 1
        ];
        system.assertEquals(null, chg.Projection__c);
        system.assertEquals(null, chg.Date_released__c);
        // Reset the projection's released amount.
        FundController.updateProjsDistsReleasing(fund1.Id);
        Test.StopTest();
    }

    // Release a charge that is more than the projection, forcing clone/split of the charge.
    static testMethod void FundControllerTest4() {
        // Build new records.
        insert new Region__c(Name = 'Region test');
        Region__c reg = [SELECT Id FROM Region__c LIMIT 1];
        insert new Account(
            Name = 'acc test',
            GM_Region__c = reg.Id,
            RecordTypeId = Utilities.getRecTypeId('Account', 'Organization_GM')
        );
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Proposal__c(Account__c = acc.Id);
        Proposal__c prop = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new ChartofAccounts__c(Name = 'Test c-of-a');
        ChartofAccounts__c cOfA = [
            SELECT Id
            FROM ChartofAccounts__c
            WHERE Name = 'Test c-of-a'
            LIMIT 1
        ];
        String fy = String.valueOf(Date.today().year());
        insert new Fund__c(
            RecordTypeId = Utilities.getRecTypeId('Fund__c', 'Standard'),
            Name = 'Testfundstandard',
            Amount_funded__c = 100,
            Active__c = true
        );
        Fund__c fund1 = [
            SELECT Id
            FROM Fund__c
            WHERE Name = 'Testfundstandard'
            LIMIT 1
        ];
        insert new Fund__c(
            // Record type Pending is currently (10/14/20) hidden for FFDB
            RecordTypeId = Utilities.getRecTypeId(
                'Fund__c',
                'Standard' // 'Pending'
            ),
            Name = 'Testfundpending',
            Amount_funded__c = 100,
            Active__c = true
        );
        Fund__c fund2 = [
            SELECT Id
            FROM Fund__c
            WHERE Name = 'Testfundpending'
            LIMIT 1
        ];
        insert new Projection__c(
            ChartofAccounts__c = cOfA.Id,
            Fiscal_year__c = fy,
            Fund__c = fund1.Id,
            Grantmaking_amount__c = 100,
            Non_grantmaking_amount__c = 0
        );
        Projection__c proj = [SELECT Id FROM Projection__c LIMIT 1];
        insert new Distribution__c(
            Source_fund__c = fund2.Id,
            Target_fund__c = fund1.Id,
            Fiscal_year__c = fy,
            Amount__c = 200
        );
        insert new Charge__c(
            Proposal__c = prop.Id,
            Fund__c = fund1.Id,
            Amount_charged__c = 130
        );
        Charge__c chg = [SELECT Id FROM Charge__c LIMIT 1];
        String jsonString = JSON.serialize(
            new Map<String, Object>{
                'chargeIds' => new List<String>{ chg.Id },
                'projectionId' => proj.Id,
                'distributionId' => null,
                'dateReleased' => Date.today()
            }
        );

        Test.StartTest();
        FundController.releaseCharges(jsonString);
        Test.StopTest();

        Charge__c[] chgs = [
            SELECT Id, Date_released__c, Projection__c, Amount_charged__c
            FROM Charge__c
            ORDER BY CreatedDate
        ];
        // There should be two charges; the original is released, the new one still not released.
        system.assertEquals(2, chgs.size());
        system.assertEquals(100, chgs[0].Amount_charged__c);
        system.assertEquals(proj.Id, chgs[0].Projection__c);
        system.assertNotEquals(null, chgs[0].Date_released__c);
        system.assertEquals(30, chgs[1].Amount_charged__c);
        system.assertEquals(null, chgs[1].Projection__c);
        system.assertEquals(null, chgs[1].Date_released__c);
    }
}