force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>Group other than a corporation or household.</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organization_GM.recordType-meta.xml
<RecordType>
    <fullName>Organization_GM</fullName>
    <active>true</active>
    <description>Organizations that are grantees or applicants</description>
    <label>Organization GM</label>
</RecordType>

force-app/main/default/objects/Advisor__c/Advisor__c.object-meta.xml
<CustomObject>
    <description>Holds information about an advisor&apos;s interests, region of expertise.  Links from letters, endorsements and advisor terms.</description>
    <label>Advisor</label>
    <nameField>
        <label>Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The account, either household or organization, containing mailing information for this advisor</description>
    <inlineHelpText>The account, either household or organization, containing mailing information for this advisor</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/GM_org_affiliation__c.field-meta.xml
<CustomField>
    <fullName>GM_org_affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The GM organization (if any) with which this advisor is affiliated (employee, consultant, board member, etc.)</description>
    <inlineHelpText>The GM organization (if any) with which this advisor is affiliated (employee, consultant, board member, etc.)</inlineHelpText>
    <label>GM org affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated advisors</relationshipLabel>
    <relationshipName>Advisors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of advisor (including official, informal, reference)</description>
    <inlineHelpText>Type of advisor (including official, informal, reference)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Official</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/Advisor_Term__c.object-meta.xml
<CustomObject>
    <description>Represents a term of an official GFW advisor</description>
    <label>Advisor Term</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Advisor Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisor Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisor_Term__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <description>Parent advisor of this advisor term</description>
    <inlineHelpText>Parent advisor of this advisor term</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>Advisor__c</referenceTo>
    <relationshipLabel>Advisor Terms</relationshipLabel>
    <relationshipName>Advisor_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Date_accepted__c.field-meta.xml
<CustomField>
    <fullName>Date_accepted__c</fullName>
    <description>The date on which the invitation to serve the given advisor term was accepted</description>
    <inlineHelpText>The date on which the invitation to serve the given advisor term was accepted</inlineHelpText>
    <label>Date accepted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Date_term_begins__c.field-meta.xml
<CustomField>
    <fullName>Date_term_begins__c</fullName>
    <description>For official advisors, when their term begins</description>
    <inlineHelpText>For official advisors, when their term begins</inlineHelpText>
    <label>Date term begins</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For &quot;View Forms&quot; advisor terms, this portfolio contains the proposals/accounts to be shared with the advisor</description>
    <inlineHelpText>For &quot;View Forms&quot; advisor terms, this portfolio contains the proposals/accounts to be shared with the advisor</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Advisor Terms</relationshipLabel>
    <relationshipName>Advisor_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this advisor term, that is, the role of the advisor for the duration of this advisor term. Normally populated on acceptance.</description>
    <inlineHelpText>The type of this advisor term, that is, the role of the advisor for the duration of this advisor term. Normally populated on acceptance.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Advisor_term_types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisor_Term__c/recordTypes/Assessor.recordType-meta.xml
<RecordType>
    <fullName>Assessor</fullName>
    <active>true</active>
    <description>An advisor term during which assessments may be requested from the advisor</description>
    <label>Assessor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>A picklist of the highest level categorization of this contact. The category can be further described in the Secondary Type field.</inlineHelpText>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Friend</fullName>
                <default>true</default>
                <label>Friend</label>
            </value>
            <value>
                <fullName>Corporate Contact</fullName>
            </value>
            <value>
                <fullName>Alumnus</fullName>
            </value>
            <value>
                <fullName>Institutional Proxy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_GM_Advisor.recordType-meta.xml
<RecordType>
    <fullName>Contact_GM_Advisor</fullName>
    <active>true</active>
    <description>For contact records of advisors</description>
    <label>Contact GM Advisor</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Represents a single country and grantmaking within that country.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Enclosing region for this country</description>
    <inlineHelpText>Enclosing region for this country</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Countries</relationshipLabel>
    <relationshipName>Countries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advisor to which this letter is linked</description>
    <inlineHelpText>Advisor to which this letter is linked</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>Advisor__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Advisor_Term__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advisor term to which this letter is linked</description>
    <inlineHelpText>Advisor term to which this letter is linked</inlineHelpText>
    <label>Advisor Term</label>
    <referenceTo>Advisor_Term__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region record linked to this letter</description>
    <inlineHelpText>Region record linked to this letter</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</description>
    <inlineHelpText>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Advisor assignments</fullName>
            </value>
            <value>
                <fullName>Saved Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Source_object__c.field-meta.xml
<CustomField>
    <fullName>Source_object__c</fullName>
    <description>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</description>
    <inlineHelpText>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</inlineHelpText>
    <label>Source object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>GM_Data__c</fullName>
            </value>
            <value>
                <fullName>Milestone__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Payment__c</fullName>
            </value>
            <value>
                <fullName>Payment_Method__c</fullName>
            </value>
            <value>
                <fullName>Profile__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Advisor_term_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Expert</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>Assessor</fullName>
    </customValue>
    <customValue>
        <fullName>View forms</fullName>
    </customValue>
    <description>The types of advisor terms</description>
    <masterLabel>Advisor term types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AdvisorControllerTest.cls
@isTest
public with sharing class AdvisorControllerTest {
    public static Id organizationRtId = Utilities.getRecTypeId('Account', 'Organization');
    public static Id ctAdvRecTypeId = Utilities.getRecTypeId('Contact', 'Contact_GM_Advisor');
    public static Id orgGMRtId = Utilities.getRecTypeId('Account', 'Organization_GM');
    
    static testmethod void AdvisorControllerTest1 () {
        // Build new advisors
        InitTestObjects(2);
        Map<Id, Advisor__c> advMap = new Map<Id, Advisor__c> ([SELECT Id FROM Advisor__c]);
        // Build new standard set controller and select the new advisors.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(advMap.values());
        ssc.setSelected(advMap.values());        
        
        Test.StartTest();
        // Test code to build advisor records.
        Country__c country = [SELECT Id, Region__r.Name FROM Country__c LIMIT 1];
        insert new Portfolio__c (Name = 'test portfolio', Type__c = 'Saved Set');
        Portfolio__c port = [SELECT Id FROM Portfolio__c LIMIT 1];
        String jsonString = JSON.serialize(new Map<String, Object> {
            'type' => 'Reference', 
            'firstName' => 'Josephine', 
            'lastName' => 'Sprat', 
            'email' => 'abc@def.org', 
            'countryId' => country.Id,
            'orgAffilName' => 'org1',
            'advisorTermRecordType' => 'Assessor',
            'advisorTermType' => 'Strategic',
            'advisorTermStartDate' => Date.today().addDays(-10),
            'portfolioId' => port.Id
        });
        String responseString = AdvisorController.buildAdvisorRecs(jsonString);
        system.debug('responseString = ' +responseString);
        Advisor_Term__c advt = [SELECT Id, Advisor__c FROM Advisor_Term__c WHERE Advisor__r.GM_org_affiliation__r.Name = 'org1' LIMIT 1];
        // Force type to be non-blank, as though we've successfully invited them to be a strategic advisor.
        advt.Date_term_begins__c = Date.today().addDays(-100);
        advt.Date_accepted__c = Date.today();
        advt.Type__c = 'Strategic'; 
        update advt;
        AdvisorUpdateLookupsInvocable.updateLookups(new List<Id> {advt.Advisor__c});
        Advisor__c adv = [SELECT Id, Current_assessor_term__c FROM Advisor__c WHERE Id = : advt.Advisor__c];
        system.assertEquals(advt.Id, adv.Current_assessor_term__c);
        // Build a new advisor controller and use it to build new letters for the selected advisors.
        Template__c temp = new Template__c (Name = 'Test template', Source_object__c = 'Advisor__c');
        insert temp;
        AdvisorController pc = new AdvisorController (ssc);
        pc.selectedTemplate = temp.Id;
        system.assertNotEquals(pc.selectedTemplate, null);
        pc.buildLetters();
        Test.StopTest();
        
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c> ([SELECT Id FROM Letter__c]);
        validate(lMap.keySet());
        // Check that build new records succeeded.
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(responseString);
        Map<string, Object> results = (Map<String, Object>)response.get('results');
        system.debug('results: ' +results);
        system.debug('errMsg: ' +response.get('errMsg'));
        System.assertEquals(true, response.get('isSuccess'));
    }
    
    public static void validate(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c> ([
            SELECT Account__c, Advisor__c, Emails__c
            FROM Letter__c
            WHERE Id IN : lIds
        ]);
        Map<Id, Advisor__c> advMap = new Map<Id, Advisor__c> ([
            SELECT Id, Contact__c, Contact__r.Email
            FROM Advisor__c
            WHERE Id IN (SELECT Advisor__c FROM Letter__c WHERE Id IN : lIds)
        ]);
        // Should be a different letter for each advisor.
        system.assertEquals(lMap.size(), advMap.size());
        // The emails stored on the letter need to agree with the advisor's emails.
        for (Letter__c l : lMap.values()) {
            system.assertEquals(l.Emails__c, advMap.get(l.Advisor__c).Contact__r.Email);
        }
    }
    // Prepare the specified number of advisors.  Include one contact per advisor.
    public static void InitTestObjects(Integer NumberOfAdvisors) {
        // Build a country record.
        Region__c reg = new Region__c (Name = 'test region');
        insert reg;
        Country__c country = new Country__c (Name = 'test country', Region__c = reg.Id);
        insert country;
        Account advAcct = new Account (
            Name = AdvisorController.advisorContactsAccountName, 
            GM_country__c = country.Id,
            RecordTypeId = orgGMRtId
            );
        insert advAcct;
        system.debug('InitTestObjects: advAcct = ' +JSON.serialize(advAcct));
		List<Contact>cts = new List<Contact>();
		for(Integer x=0;x<NumberOfAdvisors;x++) {      
			cts.add(new Contact(
				LastName = 'ptest_' + String.valueOf(x),
				AccountId = advAcct.Id,
                Email = 'ptest_' + String.valueOf(x) + '@ptest.org',
                RecordTypeId = ctAdvRecTypeId,
                Rank__c = 1
				));
		}
		insert cts;
        // Use record type filter in SOQL call to ensure that we're not picking up random contacts from non-advisor InitTestObjects calls.
		List<Contact> contacts = new List<Contact> ([SELECT AccountId, LastName, RecordType.Name FROM Contact WHERE RecordTypeId = : ctAdvRecTypeId]);
        system.debug('InitTestObjects: contacts = ' +JSON.serialize(contacts));

		// Build and insert advisors.  
		List<Advisor__c> advs = new List<Advisor__c>();    
		for(Contact ct : cts) {      
			advs.add(new Advisor__c(
				Contact__c = ct.Id, Name = 'Test advisor ' + ct.LastName, Global__c = true
                // Add other field assignments for advisors
				));
		}
        insert advs;
        system.debug('InitTestObjects: advs = ' +JSON.serialize(advs));
        // Build an advisor term for each advisor.
		List<Advisor_Term__c> advTs = new List<Advisor_Term__c>();    
		for(Advisor__c adv : advs) {      
			advTs.add(new Advisor_Term__c(
                Advisor__c = adv.Id,
                RecordTypeId = Utilities.getRecTypeId('Advisor_Term__c', 'Assessor'),
                Date_term_begins__c = Date.today().addDays(-100),
                Type__c = 'Assessor'
				));
		}
        system.debug('InitTestObjects: advTs = ' +JSON.serialize(advTs));
        insert advTs;
    }

    static testmethod void AdvisorControllerTest2 () {
        // Build new advisors and contacts
        InitTestObjects(2);
        Advisor__c[] advs = [SELECT Id FROM Advisor__c];
        Map<Id, List<String>> emails = AdvisorController.emailsForAdvisors(new Set<Id> {advs[0].Id, advs[1].Id});
        system.assert(emails.size() > 0);
        
        Test.StartTest();
        system.assertEquals(1, advs.size());
        String profPerms = AdvisorController.fetchProfileAndPermissionSets();
        // Test code to add advisor to a community.
        Account acc1 = [SELECT Id, Name FROM Account WHERE Name = : AdvisorController.advisorContactsAccountName LIMIT 1];
        String jsonString = JSON.serialize(new Map<String, Object> {
            'advisorId' => advs[0].Id
        });
        String responseString = AdvisorController.addAdvisorToCommunity(jsonString);
        system.debug('responseString = ' +responseString);
        Test.StopTest();
        
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(responseString);
        Map<string, Object> results = (Map<String, Object>)response.get('results');
        String userName;
        if (results.get('userName') != null) userName = (String)results.get('userName');
        List<String> errors = (List<String>)results.get('errors');
        system.debug('AdvisorControllerTest2: userName = ' +userName+ '; errors = ' +JSON.serialize(errors));
        system.assertNotEquals(null, userName);
        User u = [SELECT Username, ProfileId, ContactId FROM User WHERE Username = : userName];
        Id pIdAdv = [SELECT Id FROM Profile WHERE Name = : AdvisorController.advisorCommunityProfileName LIMIT 1].Id;
        system.assertEquals(pIdAdv, u.ProfileId);
        Contact c = [SELECT Id, AccountId FROM Contact WHERE Id = : u.ContactId];
        system.assertEquals(acc1.Id, c.AccountId);
        Advisor__c adv = [SELECT Id, Community_contact__c FROM Advisor__c WHERE Id = : advs[0].Id];
        system.assertEquals(u.ContactId, adv.Community_contact__c);
    }
    
    static testmethod void AdvisorControllerTest3 () {
        UserRole r = [SELECT ID FROM UserRole WHERE Name='Top Level'];
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        thisUser.UserRoleId = r.Id;
        update thisUser;

        // System.runAs avoids the Mixed DML Operations error.  (Can't update setup object like User in same context as non-setup object.)
        System.runAs(thisUser) {
            // Build new advisors and accounts
            InitTestObjects(1);
            Advisor__c adv = [SELECT Id, Contact__c, Contact__r.LastName, Contact__r.FirstName, Contact__r.Email FROM Advisor__c][0];
            String email = adv.Contact__r.Email;
            Id pIdAdv = [SELECT Id FROM Profile WHERE Name = : AdvisorController.advisorCommunityProfileName LIMIT 1].Id;
            Account acc = [SELECT Id, Name FROM Account WHERE Name = : AdvisorController.advisorContactsAccountName LIMIT 1];
            insert new Contact (AccountId = acc.Id, LastName = 'test contact');
            Contact c = [SELECT Id FROM Contact WHERE LastName = 'test contact' LIMIT 1];
            
            // Pre-build user record with advisor's email (to force exception to be thrown).
            insert new User(
                Username = AdvisorController.advisorUsernameFromEmail(email),
                Email = email,
                CommunityNickname = email.left(40),
                LastName = adv.Contact__r.LastName != null ? adv.Contact__r.LastName.left(40) : null,
                FirstName = adv.Contact__r.FirstName != null ? adv.Contact__r.FirstName.left(40) : null,
                Alias = email.toLowerCase().left(4),
                ProfileId = pIdAdv,
                ContactId = c.Id,
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'GMT'
            );
            User u = [
                SELECT Id, Username, Email, CommunityNickname, LastName, FirstName, Alias, 
                ProfileId, ContactId, EmailEncodingKey, LanguageLocaleKey, LocaleSidKey, TimeZoneSidKey
                FROM User 
                WHERE Email = : email 
                LIMIT 1
            ];
            
            Test.StartTest();
            String profPerms = AdvisorController.fetchProfileAndPermissionSets();
            // Assign permission set for code coverage.
            Id psIdAdv = [SELECT Id FROM PermissionSet WHERE Label = : AdvisorController.advisorCommunityPermSetName LIMIT 1].Id;
            AdvisorController.assignPermissionSet(u.Id, psIdAdv);
            // Test code to add advisor to a community.
            String jsonString = JSON.serialize(new Map<String, Object> {
                'advisorId' => adv.Id
                    });
            String responseString = AdvisorController.addAdvisorToCommunity(jsonString);
            system.debug('responseString = ' +responseString);
            Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(responseString);
            Map<string, Object> results = (Map<String, Object>)response.get('results');
            String userName;
            if (results.get('userName') != null) userName = (String)results.get('userName');
            // Expect to get an error as that username is already in the advisor community.
            system.assertEquals(null, userName);
            system.assert(!(Boolean)response.get('isSuccess'));
            system.assert(((String)response.get('errMsg')).contains('Advisor contact username'));
            
            // Try again where the clash is with a user without a linked contact (for code coverage).
            User uNew = u.clone(false, true);
            String emailNew = 'dontuser@abc.org';
            u.Username = AdvisorController.advisorUsernameFromEmail(emailNew); // Tweak username on original user to avoid conflict.
            u.Email = emailNew;
            u.CommunityNickname = emailNew.left(40);
            update u;
            uNew.ProfileId = [SELECT Id FROM Profile WHERE Name = : AdvisorController.standardUserGMProfileName LIMIT 1].Id;
            uNew.ContactId = null;
            insert uNew;
            responseString = AdvisorController.addAdvisorToCommunity(jsonString);
            
            Test.StopTest();
        }
    }

    @IsTest
    static void getRunningUserAdvisorIdTest(){
        //Setup test data
        UserRole r = [SELECT ID FROM UserRole WHERE Name='Top Level'];
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        thisUser.UserRoleId = r.Id;
        update thisUser;

        // System.runAs avoids the Mixed DML Operations error.  (Can't update setup object like User in same context as non-setup object.)
        System.runAs(thisUser) {
            // Build new advisors and accounts
            InitTestObjects(1);
            Advisor__c adv = [SELECT Id, Contact__c, Contact__r.LastName, Contact__r.FirstName, Contact__r.Email FROM Advisor__c][0];
            String email = adv.Contact__r.Email;
            Id pIdAdv = [SELECT Id FROM Profile WHERE Name = : AdvisorController.advisorCommunityProfileName LIMIT 1].Id;
            Account acc = [SELECT Id, Name FROM Account WHERE Name = : AdvisorController.advisorContactsAccountName LIMIT 1];
            insert new Contact (AccountId = acc.Id, LastName = 'test contact');
            Contact c = [SELECT Id FROM Contact WHERE LastName = 'test contact' LIMIT 1];
            
            // Pre-build user record with advisor's email (to force exception to be thrown).
            insert new User(
                Username = AdvisorController.advisorUsernameFromEmail(email),
                Email = email,
                CommunityNickname = email.left(40),
                LastName = adv.Contact__r.LastName != null ? adv.Contact__r.LastName.left(40) : null,
                FirstName = adv.Contact__r.FirstName != null ? adv.Contact__r.FirstName.left(40) : null,
                Alias = email.toLowerCase().left(4),
                ProfileId = pIdAdv,
                ContactId = c.Id,
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'GMT'
            );
            User u = [
                SELECT Id, Username, Email, CommunityNickname, LastName, FirstName, Alias, 
                ProfileId, ContactId, EmailEncodingKey, LanguageLocaleKey, LocaleSidKey, TimeZoneSidKey
                FROM User 
                WHERE Email = : email 
                LIMIT 1
            ];
            //Done with test data setup
        }
        Test.startTest();
        String advisorId;
        System.runAs(thisUser){
            advisorId = AdvisorController.getRunningUserAdvisorId();
            System.debug('advisorId: '+advisorId);
        }
        Test.stopTest();

        //load the advisor record
        Advisor__c advisor = [SELECT Id, Contact__c, Contact__r.LastName, Contact__r.FirstName, Contact__r.Email FROM Advisor__c][0];
        System.assertEquals(advisor.Id, advisorId);
        
    }
    
}