force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Sets Region field with East or West depending on State</description>
    <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HI:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY:ND:SD:NE:MN:IA:MO:AR:LA&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT:AL:AR:DC:DE:FL:GA:KY:MD:MS:NC:NJ:SC:TN:VA:WV:IL:IN:MI:NE:OH:WI&quot;, BillingState), &quot;East&quot;, &quot;Unknown&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Region of Donor Account set off Address State - US only</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Reqs__c/Custom_Reqs__c.object-meta.xml
<CustomObject>
    <description>Represents the custom requirements imposed by restricted funds that apply to the linked proposals</description>
    <label>Custom Reqs</label>
    <nameField>
        <label>Custom Reqs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Reqs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Account_owner__c.field-meta.xml
<CustomField>
    <fullName>Account_owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cached lookup relationship to the account owner. Necessary because can&apos;t reach through the polymorphic Account.Owner link.</description>
    <inlineHelpText>Cached lookup relationship to the account owner. Necessary because can&apos;t reach through the polymorphic Account.Owner link.</inlineHelpText>
    <label>Account owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs (if any) linked to the proposal/grant behind this letter</description>
    <inlineHelpText>The custom reqs (if any) linked to the proposal/grant behind this letter</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <description>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</description>
    <inlineHelpText>Comma-separated email addresses for this letter, usually the emails of the account&apos;s contact records</inlineHelpText>
    <label>Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Letter_owner__c.field-meta.xml
<CustomField>
    <fullName>Letter_owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cached lookup relationship to the letter owner. Necessary because can&apos;t reach through the polymorphic Letter.Owner link.</description>
    <inlineHelpText>Cached lookup relationship to the letter owner. Necessary because can&apos;t reach through the polymorphic Letter.Owner link.</inlineHelpText>
    <label>Letter owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Letters1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The payment linked to this letter</description>
    <inlineHelpText>The payment linked to this letter</inlineHelpText>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this letter</description>
    <inlineHelpText>The proposal linked to this letter</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region record linked to this letter</description>
    <inlineHelpText>Region record linked to this letter</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Represents a payment made for a grant</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal to which this payment belongs</description>
    <inlineHelpText>The proposal to which this payment belongs</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs for this proposal (if any)</description>
    <inlineHelpText>The custom reqs for this proposal (if any)</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The region where this proposal&apos;s parent organization does its work</description>
    <inlineHelpText>The region where this proposal&apos;s parent organization does its work</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Status_numeric__c.field-meta.xml
<CustomField>
    <fullName>Status_numeric__c</fullName>
    <description>A numeric version of this proposal&apos;s status, suitable for sorting</description>
    <formula>VALUE( LEFT( Status__c, FIND(&quot; &quot;, Status__c) - 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A numeric version of this proposal&apos;s status, suitable for sorting</inlineHelpText>
    <label>Status numeric</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Geographic regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentController.cls
public with sharing class PaymentController {
    private ApexPages.StandardController standardController;
    private ApexPages.StandardSetController standardSetController;

    public PaymentController(ApexPages.StandardController standardController) {
        this.standardController = standardController;
        this.selRecs = fetchRecords(new Set<Id>{ standardController.getId() });
        this.templates = Utilities.templatesMenu(
            objectName,
            START,
            selRecs,
            statusFieldName
        );
    }

    public PaymentController(
        ApexPages.StandardSetController standardSetController
    ) {
        this.standardSetController = standardSetController;
        Map<Id, Payment__c> selMap = new Map<Id, Payment__c>(
            (List<Payment__c>) standardSetController.getSelected()
        );
        this.selRecs = fetchRecords(selMap.keySet());
        this.templates = Utilities.templatesMenu(
            objectName,
            START,
            selRecs,
            statusFieldName
        );
    }

    // Build the menu of admissible correspondence templates for this object.
    private static String objectName = 'Payment__c';
    private static final String START = '--Select Template--';
    private static String statusFieldName = 'Proposal__r.Status_numeric__c';
    private List<Payment__c> selRecs;
    public List<selectOption> templates { get; private set; }
    public String selectedTemplate { get; set; }

    {
        selectedTemplate = START;
    }

    // Get selected records, then build and reset letters for them.
    public PageReference buildLetters() {
        // Generate error if no selected template - assign error to the templateType field.
        if (selectedTemplate == null || selectedTemplate == START) {
            ApexPages.AddMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR,
                    'Please select a template',
                    'Must select a template before building new letters'
                )
            );
            selectedTemplate = START; // If I don't reset to the START value, it gets set to one of the non-disabled values.
            return null;
        }
        // Gather email addresses from the related accounts.
        Set<Id> accIds = new Set<Id>();
        for (Payment__c p : selRecs)
            accIds.add(p.Proposal__r.Account__c);
        Map<Id, List<String>> emails = AccountController.emailsForAccounts(accIds);
        // Build new letters for selected records.
        Id templateId = Utilities.recordIdFromName(
            'Template__c',
            selectedTemplate
        );
        List<Letter__c> ls = new List<Letter__c>();
        for (Payment__c r : selRecs) {
            List<String> es = emails.get(r.Proposal__r.Account__c);
            ls.add(
                new Letter__c(
                    Template__c = templateId,
                    Account__c = r.Proposal__r.Account__c,
                    Account_owner__c = r.Proposal__r.Account__r.OwnerId,
                    Letter_owner__c = UserInfo.getUserId(),
                    Payment__c = r.Id,
                    Proposal__c = r.Proposal__c,
                    Region__c = r.Proposal__r.Region__c,
                    Custom_Reqs__c = r.Proposal__r.Custom_Reqs__c,
                    Emails__c = (es == null)
                        ? ''
                        : Utilities.stringJoinWithCharLimit(es, ',', 255)
                )
            );
        }
        insert ls;
        Map<Id, Letter__c> lsMap = new Map<Id, Letter__c>(ls);
        // Reset the new letters.
        LetterController.resetLetters0(lsMap.keySet(), false);
        // Changes have been saved; jump to the new letter if there's only one.
        if (standardController != null && ls.size() == 1)
            return Utilities.pageReferenceForRecord(ls[0]);
        else
            return doCancel(); // Stay in current layout.
    }

    // Get records for given ids.
    static private Payment__c[] fetchRecords(Set<Id> ids) {
        system.debug('fetchRecords: ids = ' + JSON.serialize(ids));
        return [
            SELECT
                Id,
                Proposal__c,
                Proposal__r.Account__c,
                Proposal__r.Status_numeric__c,
                Proposal__r.Account__r.OwnerId,
                Proposal__r.Region__c,
                Proposal__r.Custom_Reqs__c
            FROM Payment__c
            WHERE Id IN :ids
        ];
    }

    public PageReference doCancel() {
        return (standardSetController != null)
            ? standardSetController.cancel()
            : standardController.cancel();
    }

    /**********************************
     * For general use
     *********************************/
}