force-app/main/default/objects/Custom_Reqs__c/Custom_Reqs__c.object-meta.xml
<CustomObject>
    <description>Represents the custom requirements imposed by restricted funds that apply to the linked proposals</description>
    <label>Custom Reqs</label>
    <nameField>
        <label>Custom Reqs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Reqs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Spec__c/Milestone_Spec__c.object-meta.xml
<CustomObject>
    <description>Specification of a milestone including type, date due, etc.</description>
    <label>Milestone Spec</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Milestone Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Spec__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <description>The custom reporting reqs record for this milestone spec record</description>
    <inlineHelpText>The custom reporting reqs record for this milestone spec record</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Milestone Specs</relationshipLabel>
    <relationshipName>Milestone_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/fields/Num_months_due__c.field-meta.xml
<CustomField>
    <fullName>Num_months_due__c</fullName>
    <description>The number of months after the date awarded on which the milestone is due</description>
    <inlineHelpText>The number of months after the date awarded on which the milestone is due</inlineHelpText>
    <label>Num months due</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone_Spec__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this milestone</description>
    <inlineHelpText>The type of this milestone</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template_piece__c/Template_piece__c.object-meta.xml
<CustomObject>
    <description>Contains a piece of text used to instantiate a template.</description>
    <label>Template piece</label>
    <nameField>
        <label>Template piece</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template pieces</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_piece__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs to which this template piece is assigned</description>
    <inlineHelpText>The custom reqs to which this template piece is assigned</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Template pieces</relationshipLabel>
    <relationshipName>Template_pieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_piece__c/fields/Revise__c.field-meta.xml
<CustomField>
    <fullName>Revise__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this template piece should be revised before use.</description>
    <inlineHelpText>If checked, this template piece should be revised before use.</inlineHelpText>
    <label>Revise</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Template_piece__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template parent of this template piece (blank if this is a generic template piece)</description>
    <inlineHelpText>The template parent of this template piece (blank if this is a generic template piece)</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template pieces</relationshipLabel>
    <relationshipName>Template_pieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Milestone_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Report</fullName>
    </customValue>
    <customValue>
        <fullName>Report narrative</fullName>
    </customValue>
    <customValue>
        <fullName>Report financial</fullName>
    </customValue>
    <customValue>
        <fullName>Report activities</fullName>
    </customValue>
    <customValue>
        <fullName>Site visit</fullName>
    </customValue>
    <description>Milestone types</description>
    <masterLabel>Milestone type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomReqsControllerTest.cls
@isTest
public class CustomReqsControllerTest {
    static testMethod void CustomReqsControllerTest1() {
        insert new Custom_Reqs__c(Name = 'test custom reqs');
        Custom_Reqs__c cr = [SELECT Id FROM Custom_Reqs__c LIMIT 1];
        insert new Milestone_Spec__c(
            Custom_Reqs__c = cr.Id,
            Type__c = 'Report',
            Num_months_due__c = 12
        );
        Milestone_Spec__c r = [SELECT Id FROM Milestone_Spec__c LIMIT 1];
        insert new Template__c(Name = 'test template');
        Template__c t = [SELECT Id FROM Template__c LIMIT 1];
        insert new Template_Piece__c(
            Name = 'test template piece',
            Custom_Reqs__c = cr.Id,
            Template__c = t.Id
        );
        Template_Piece__c tp = [SELECT Id FROM Template_Piece__c LIMIT 1];

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(cr);
        customReqsController crc = new customReqsController(sc);
        crc.deepClone();
        crc.doCancel();
        Test.stopTest();

        Custom_Reqs__c crNew = [
            SELECT Id
            FROM Custom_Reqs__c
            WHERE Name = 'test custom reqs (Copy)'
            LIMIT 1
        ];
        system.assertNotEquals(null, crNew);
        system.assertNotEquals(cr.Id, crNew.Id);
        Milestone_Spec__c[] rsNew = [
            SELECT Id
            FROM Milestone_Spec__c
            WHERE Custom_Reqs__c = :crNew.Id
        ];
        system.assertEquals(1, rsNew.size());
        system.assertNotEquals(r.Id, rsNew[0].Id);
        Template_Piece__c[] tpsNew = [
            SELECT Id, Revise__c
            FROM Template_Piece__c
            WHERE Custom_Reqs__c = :crNew.Id
        ];
        system.assertEquals(1, tpsNew.size());
        system.assertNotEquals(tp.Id, tpsNew[0].Id);
        system.assert(tpsNew[0].Revise__c);
    }
}