force-app/main/default/objects/Custom_Reqs__c/Custom_Reqs__c.object-meta.xml
<CustomObject>
    <description>Represents the custom requirements imposed by restricted funds that apply to the linked proposals</description>
    <label>Custom Reqs</label>
    <nameField>
        <label>Custom Reqs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Reqs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Spec__c/Milestone_Spec__c.object-meta.xml
<CustomObject>
    <description>Specification of a milestone including type, date due, etc.</description>
    <label>Milestone Spec</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Milestone Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Spec__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <description>The custom reporting reqs record for this milestone spec record</description>
    <inlineHelpText>The custom reporting reqs record for this milestone spec record</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Milestone Specs</relationshipLabel>
    <relationshipName>Milestone_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Template_piece__c/Template_piece__c.object-meta.xml
<CustomObject>
    <description>Contains a piece of text used to instantiate a template.</description>
    <label>Template piece</label>
    <nameField>
        <label>Template piece</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template pieces</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_piece__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs to which this template piece is assigned</description>
    <inlineHelpText>The custom reqs to which this template piece is assigned</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Template pieces</relationshipLabel>
    <relationshipName>Template_pieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_piece__c/fields/Revise__c.field-meta.xml
<CustomField>
    <fullName>Revise__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this template piece should be revised before use.</description>
    <inlineHelpText>If checked, this template piece should be revised before use.</inlineHelpText>
    <label>Revise</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomReqsController.cls
public class CustomReqsController {
    private String recordId;
    private ApexPages.StandardController standardController;

    public CustomReqsController(ApexPages.StandardController controller) {
        this.standardController = controller;
        recordId = controller.getRecord().Id;
    }

    public PageReference deepClone() {
        // Invoke the custom reqs deep clone code.
        Id cloneId = cloneCustomReqs(recordId);
        // Navigate to the cloned form record, or stay here if no clone.
        Id destId = cloneId != null ? cloneId : recordId;
        PageReference p = new PageReference('/' + destId);
        p.setRedirect(true);
        return p;
    }

    public PageReference doCancel() {
        return standardController.cancel();
    }

    /**********************************
     * For general use
     *********************************/

    // Clone a custom reqs record together with its milestone specs and template pieces.
    // Return the Id of the clone or null if operation failed.
    public static Id cloneCustomReqs(Id cReqsId) {
        // Fetch all fields from custom reqs record and its children to facilitate cloning.
        Custom_reqs__c cReqs = (Custom_reqs__c) Utilities.fetchRecord(
            'Custom_reqs__c',
            cReqsId,
            null
        );
        if (cReqs == null)
            return null;
        String reportSpecQ =
            'SELECT ' +
            String.join(
                Utilities.fieldNamesForObject('Milestone_spec__c'),
                ', '
            ) +
            ' FROM Milestone_spec__c' +
            ' WHERE Custom_reqs__c = : cReqsId';
        Milestone_spec__c[] ms = Database.query(reportSpecQ);
        String templatePieceQ =
            'SELECT ' +
            String.join(
                Utilities.fieldNamesForObject('Template_Piece__c'),
                ', '
            ) +
            ' FROM Template_Piece__c' +
            ' WHERE Custom_reqs__c = : cReqsId';
        Template_Piece__c[] tps = Database.query(templatePieceQ);
        sObject[] toInsert = new List<sObject>();
        // Clone custom reqs, change name.
        Custom_reqs__c cReqsNew = cReqs.clone(false, true);
        if (cReqsNew == null)
            return null;
        cReqsNew.Name = cReqs.Name + ' (Copy)';
        insert cReqsNew;
        // Clone child milestone specs and template pieces, and link to new custom reqs.
        for (Milestone_spec__c m : ms) {
            Milestone_spec__c mNew = m.clone(false, false);
            mNew.Custom_reqs__c = cReqsNew.Id;
            toInsert.add(mNew);
        }
        for (Template_Piece__c tp : tps) {
            Template_Piece__c tpNew = tp.clone(false, false);
            tpNew.Custom_reqs__c = cReqsNew.Id;
            tpNew.Revise__c = true; // Every cloned template piece defaults to needing to be checked.
            toInsert.add(tpNew);
        }
        if (toInsert.size() > 0)
            insert toInsert;
        return cReqsNew.Id;
    }
}