force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <description>Representations an allocation of all or part of a grant to a fund (funding source)</description>
    <label>Charge</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Amount_charged__c.field-meta.xml
<CustomField>
    <fullName>Amount_charged__c</fullName>
    <description>The amount of the linked grant that is being charged to the linked fund</description>
    <inlineHelpText>The amount of the linked grant that is being charged to the linked fund</inlineHelpText>
    <label>Amount charged</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Distribution__c.field-meta.xml
<CustomField>
    <fullName>Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The distribution within the charge&apos;s fund against which this charge is released</description>
    <inlineHelpText>The distribution within the charge&apos;s fund against which this charge is released</inlineHelpText>
    <label>Distribution</label>
    <referenceTo>Distribution__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <description>The fund to which this charge applies</description>
    <inlineHelpText>The fund to which this charge applies</inlineHelpText>
    <label>Fund</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>May only charge to active funds.</errorMessage>
        <filterItems>
            <field>Fund__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>May only charge to active funds.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Projection__c.field-meta.xml
<CustomField>
    <fullName>Projection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The projection within the charge&apos;s fund against which this charge is released</description>
    <inlineHelpText>The projection within the charge&apos;s fund against which this charge is released</inlineHelpText>
    <label>Projection</label>
    <referenceTo>Projection__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distribution__c/Distribution__c.object-meta.xml
<CustomObject>
    <description>A Distribution record is a link from a Pending fund to a Standard one.  The specified amount of funds (usually unrestricted by the donor) is considered to be &quot;moved&quot; from the pending fund to the standard fund where it is available for grantmaking.</description>
    <label>Distribution</label>
    <nameField>
        <displayFormat>DIST-{000000}</displayFormat>
        <label>Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of this distribution</description>
    <inlineHelpText>The amount of this distribution</inlineHelpText>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Distribution__c/fields/Amount_released__c.field-meta.xml
<CustomField>
    <fullName>Amount_released__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The amount of this distribution that has so far been released, that is, the sum of linked charges</description>
    <inlineHelpText>The amount of this distribution that has so far been released, that is, the sum of linked charges</inlineHelpText>
    <label>Amount released</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Distribution__c/fields/Fiscal_year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_year__c</fullName>
    <description>The fiscal year to which this distribution applies</description>
    <inlineHelpText>The fiscal year to which this distribution applies</inlineHelpText>
    <label>Fiscal year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Distribution__c/fields/Target_fund__c.field-meta.xml
<CustomField>
    <fullName>Target_fund__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The standard fund that is the target of this distribution of funds for grantmaking</description>
    <inlineHelpText>The standard fund that is the target of this distribution of funds for grantmaking</inlineHelpText>
    <label>Target fund</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Target fund must have the record type = Standard.</errorMessage>
        <filterItems>
            <field>Fund__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Choose from among Standard funds</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Distributions (Target fund)</relationshipLabel>
    <relationshipName>Distributions1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Represents an amount of restricted funding</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/Fiscal_year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_year__c</fullName>
    <description>The fiscal year of this fund</description>
    <inlineHelpText>The fiscal year of this fund</inlineHelpText>
    <label>Fiscal year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Total_available__c.field-meta.xml
<CustomField>
    <fullName>Total_available__c</fullName>
    <description>The total amount of any linked projections and distributions.  Note that Standard and Pending funds only sum the grantmaking part of linked projections.</description>
    <inlineHelpText>The total amount of any linked projections and distributions.  Note that Standard and Pending funds only sum the grantmaking part of linked projections.</inlineHelpText>
    <label>Total available</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/recordTypes/Overhead.recordType-meta.xml
<RecordType>
    <fullName>Overhead</fullName>
    <active>false</active>
    <description>Captures total &quot;overhead&quot;, that is, the non-grantmaking amount, from projections linked to grantmaking (non-revenue) funds.  The total is maintained by a nightly script.</description>
    <label>Overhead</label>
</RecordType>

force-app/main/default/objects/Fund__c/recordTypes/Pending.recordType-meta.xml
<RecordType>
    <fullName>Pending</fullName>
    <active>true</active>
    <description>Record type for &quot;pending&quot; fund records, holding funds (usually unrestricted) awaiting distribution into standard funds</description>
    <label>Pending</label>
</RecordType>

force-app/main/default/objects/Fund__c/recordTypes/Revenue.recordType-meta.xml
<RecordType>
    <fullName>Revenue</fullName>
    <active>false</active>
    <description>This &quot;fund&quot; is a gathering place for revenue coming primarily from small gifts and opportunities that aren&apos;t linked to standard or pending funds.  Primary use is for gathering unrestricted funds (chart of accounts = #Unrestricted).</description>
    <label>Revenue</label>
</RecordType>

force-app/main/default/objects/Fund__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Standard funds represent an amount of restricted funding to be allocated for grantmaking.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Projection__c/Projection__c.object-meta.xml
<CustomObject>
    <description>Projections are used to log and track a high-level breakdown of the amounts expected from a particular opportunity or gift in a particular fiscal year.</description>
    <label>Projection</label>
    <nameField>
        <displayFormat>PROJ-{000000}</displayFormat>
        <label>Projection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Projection__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount allocated for this projection - if blank, then total amount is calculated by adding grantmaking and non-grantmaking amounts.</description>
    <inlineHelpText>The amount allocated for this projection - if blank, then total amount is calculated by adding grantmaking and non-grantmaking amounts.</inlineHelpText>
    <label>Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Amount_released__c.field-meta.xml
<CustomField>
    <fullName>Amount_released__c</fullName>
    <description>The amount of this projection that has so far been released, that is, the sum of linked charges</description>
    <inlineHelpText>The amount of this projection that has so far been released, that is, the sum of linked charges</inlineHelpText>
    <label>Amount released</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Fiscal_year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_year__c</fullName>
    <description>The fiscal year to which this projection applies</description>
    <inlineHelpText>The fiscal year to which this projection applies</inlineHelpText>
    <label>Fiscal year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The fund that specifies and tracks how the grantmaking part of this projection is spent</description>
    <inlineHelpText>The fund that specifies and tracks how the grantmaking part of this projection is spent</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Projections</relationshipLabel>
    <relationshipName>Projections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <description>This formula field equals total gathered if this is a gatherer projection, else Amount if non-blank, else grantmaking amount plus non-grantmaking amount.</description>
    <formula>IF(Total_received_pooled__c &gt; 0 &amp;&amp; ISBLANK(Carryover__c) &amp;&amp; ISBLANK(Grantmaking_amount__c) &amp;&amp; ISBLANK(Amount__c),
  Total_received_pooled__c,
IF(Amount__c &gt; 0.0, Amount__c,
 Grantmaking_amount__c + Non_grantmaking_amount__c
))</formula>
    <inlineHelpText>This formula field equals total gathered if this is a gatherer projection, else Amount if non-blank, else grantmaking amount plus non-grantmaking amount.</inlineHelpText>
    <label>Total amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Total_grantmaking__c.field-meta.xml
<CustomField>
    <fullName>Total_grantmaking__c</fullName>
    <description>If this is a gatherer projection then the grantmaking amount is the total gathered times the grantmaking fraction.  If not a gatherer, then the Amount field times the grantmaking fraction.  If no Amount, then just grantmaking amount.</description>
    <formula>IF(Total_received_pooled__c &gt; 0 &amp;&amp; ISBLANK(Carryover__c) &amp;&amp; ISBLANK(Grantmaking_amount__c) &amp;&amp; ISBLANK(Amount__c),
 IF(NOT(ISBLANK( Grantmaking_fraction__c )), ROUND(Total_received_pooled__c * Grantmaking_fraction__c, 0), null),

 IF(Amount__c &gt; 0,
  IF(NOT(ISBLANK( Grantmaking_fraction__c )), Amount__c * Grantmaking_fraction__c, null),
  Grantmaking_amount__c
))</formula>
    <inlineHelpText>If this is a gatherer projection then the grantmaking amount is the total gathered times the grantmaking fraction.  If not a gatherer, then the Amount field times the grantmaking fraction.  If no Amount, then just grantmaking amount.</inlineHelpText>
    <label>Total grantmaking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Total_grantmaking_converted__c.field-meta.xml
<CustomField>
    <fullName>Total_grantmaking_converted__c</fullName>
    <description>The total grantmaking amount converted to the target currency, if any</description>
    <formula>IF(NOT(ISBLANK(TEXT(Target_currency__c))),
 ROUND(Total_grantmaking__c * Exchange_rate_to_target_currency__c, 2),
 Total_grantmaking__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The total grantmaking amount converted to the target currency, if any</inlineHelpText>
    <label>Total grantmaking converted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Projection__c/fields/Total_non_grantmaking__c.field-meta.xml
<CustomField>
    <fullName>Total_non_grantmaking__c</fullName>
    <description>If this projection is a gatherer, then total gathered times 1 - grantmaking fraction.  If not a gatherer, then product of Amount field with 1 - grantmaking fraction.  If both are blank, then it&apos;s non-grantmaking amount.</description>
    <formula>IF(Total_received_pooled__c &gt; 0 &amp;&amp; ISBLANK(Carryover__c) &amp;&amp; ISBLANK(Grantmaking_amount__c) &amp;&amp; ISBLANK(Amount__c),
 IF(NOT(ISBLANK( Grantmaking_fraction__c )), Total_received_pooled__c - Total_grantmaking__c , null),

 IF(Amount__c &gt; 0,
  IF(NOT(ISBLANK( Grantmaking_fraction__c )), Amount__c * (1 - Grantmaking_fraction__c), null),
  Non_grantmaking_amount__c
))</formula>
    <inlineHelpText>If this projection is a gatherer, then total gathered times 1 - grantmaking fraction.  If not a gatherer, then product of Amount field with 1 - grantmaking fraction.  If both are blank, then it&apos;s non-grantmaking amount.</inlineHelpText>
    <label>Total non-grantmaking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FundController.cls
public with sharing class FundController {
    /**********************************
     * For general use
     *********************************/

    // Update totals for all funds.
    // The fund with given id (if non-null) is updated immediately, the others are updated in a batch process.
    public static void updateTotals(Id fundId) {
        // Get all funds.
        Map<Id, Fund__c> funds = new Map<Id, Fund__c>(
            [
                SELECT
                    Total_available__c,
                    RecordType.DeveloperName,
                    Fiscal_year__c
                FROM Fund__c
            ]
        );
        Integer batchSize = 100;
        Map<Id, Fund__c> fundsToUpdate = new Map<Id, Fund__c>();
        // Gather the overhead funds for updating based on non-grantmaking amounts of non-revenue projections.
        List<Fund__c> overheadFunds = [
            SELECT Fiscal_year__c
            FROM Fund__c
            WHERE RecordType.DeveloperName = 'Overhead'
        ];
        // Total overhead by fiscal year
        Map<String, Decimal> overheadTotals = new Map<String, Decimal>();
        for (Fund__c f : overheadFunds)
            overheadTotals.put(f.Fiscal_year__c, 0);
        // Total projection amounts by fund.
        List<AggregateResult> projGrouped = [
            SELECT
                SUM(Total_grantmaking__c) sumGM,
                SUM(Total_grantmaking_converted__c) sumGMConv,
                SUM(Total_non_grantmaking__c) sumNonGM,
                SUM(Total_amount__c) sum,
                Fund__c
            FROM Projection__c
            WHERE
                Fund__c != null
                AND Fund__c IN :funds.keySet()
                AND Total_amount__c > 0
            GROUP BY Fund__c
        ];
        // Total distribution amounts by fund.
        List<AggregateResult> distGrouped = [
            SELECT SUM(Amount__c) sum, Target_fund__c
            FROM Distribution__c
            WHERE
                Target_fund__c != null
                AND Target_fund__c IN :funds.keySet()
                AND Amount__c > 0
            GROUP BY Target_fund__c
        ];
        // Sum projections and distributions into lookup table of totals for the fund's auto-totaling field.
        Map<Id, Decimal> fundTotals = new Map<Id, Decimal>();
        for (AggregateResult t : projGrouped) {
            Fund__c f = funds.get((Id) t.get('Fund__c'));
            // Standard and Pending funds sum the grantmaking part of the projection.
            Decimal tot = (f.RecordType.DeveloperName == 'Standard' ||
                f.RecordType.DeveloperName == 'Pending')
                ? (Decimal) t.get('sumGMConv') // Use converted amounts, in case projections do currency conversion
                : (Decimal) t.get('sum');
            system.debug(
                'UpdateTotals: tot = ' +
                tot +
                '; f = ' +
                JSON.serialize(f)
            );
            fundTotals.put(
                f.Id,
                tot + (fundTotals.containsKey(f.Id) ? fundTotals.get(f.Id) : 0)
            );
            // Sum up the non-grantmaking into overhead.
            if (
                f.RecordType.DeveloperName != 'Revenue' &&
                f.RecordType.DeveloperName != 'Overhead' &&
                overheadTotals.containsKey(f.Fiscal_year__c)
            )
                overheadTotals.put(
                    f.Fiscal_year__c,
                    (Decimal) t.get('sumNonGM') +
                    overheadTotals.get(f.Fiscal_year__c)
                );
        }
        for (AggregateResult t : distGrouped) {
            Fund__c f = funds.get((Id) t.get('Target_fund__c'));
            fundTotals.put(
                f.Id,
                (Decimal) t.get('sum') +
                (fundTotals.containsKey(f.Id) ? fundTotals.get(f.Id) : 0)
            );
        }
        // Update totaling field in the affected funds.
        for (Fund__c f : funds.values()) {
            // If fund is for overhead, take accumulated total for the FY.
            if (f.RecordType.DeveloperName == 'Overhead') {
                String fy = f.Fiscal_year__c;
                if (
                    overheadTotals.containsKey(fy) &&
                    f.Total_available__c != overheadTotals.get(fy)
                ) {
                    f.Total_available__c = overheadTotals.get(fy);
                    fundsToUpdate.put(f.Id, f);
                }
            } else {
                // Non-overhead fund
                // Handle case where fund has projections/distributions and the total needs updating.
                if (
                    fundTotals.containsKey(f.Id) &&
                    f.Total_available__c != fundTotals.get(f.Id)
                ) {
                    f.Total_available__c = fundTotals.get(f.Id);
                    fundsToUpdate.put(f.Id, f);
                }
                // Handle case where fund has no projection/distributions, and total needs to be reset to zero.
                if (!fundTotals.containsKey(f.Id) && f.Total_available__c > 0) {
                    f.Total_available__c = 0;
                    fundsToUpdate.put(f.Id, f);
                }
            }
        }
        // If given fund needs updating, do it immediately.  Then do others in a batch process.
        Fund__c fund = fundId != null ? fundsToUpdate.remove(fundId) : null;
        if (fund != null)
            update fund;
        if (fundsToUpdate.size() > 0)
            Database.executeBatch(
                new GenericUpdateRecordsBatch(fundsToUpdate.values()),
                batchSize
            );
    }

    /**********************************
     * For use in Lightning components
     *********************************/

    // Fetch the fund's charges, projections, and distributions, after ensuring that totals released are up to date.
    // Include names of current user's permission sets, so lightning code can restrict permission to release/unrelease.
    @AuraEnabled
    public static String getRecordsForReleasing(String fundIdStr) {
        Id fundId = Id.valueOf(fundIdStr);
        strike_responseData responseData = new strike_responseData();
        try {
            updateProjsDistsReleasing(fundId);
            responseData.results = new Map<String, Object>{
                'charges' => getCharges(fundId),
                'projections' => getProjections(fundId),
                'distributions' => getDistributions(fundId),
                'permissionSets' => Utilities.currentUserPermissionSetNames()
            };
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        system.debug(
            'getRecordsForReleasing: responseData = ' +
            JSON.serialize(responseData)
        );
        return responseData.getJsonString();
    }

    // Ensure that the amount released fields in the fund's projections and distributions are up to date.
    public static void updateProjsDistsReleasing(Id fundId) {
        sObject[] toUpdate = new List<sObject>();
        Map<Id, Decimal> projTotals = new Map<Id, Decimal>();
        Map<Id, Decimal> distTotals = new Map<Id, Decimal>();
        Map<Id, Projection__c> projs = new Map<Id, Projection__c>(
            [
                SELECT Amount_released__c
                FROM Projection__c
                WHERE Fund__c = :fundId
            ]
        );
        Map<Id, Distribution__c> dists = new Map<Id, Distribution__c>(
            [
                SELECT Amount_released__c
                FROM Distribution__c
                WHERE Target_fund__c = :fundId
            ]
        );
        Charge__c[] charges = new List<Charge__c>(
            [
                SELECT Projection__c, Distribution__c, Amount_charged__c
                FROM Charge__c
                WHERE
                    Fund__c = :fundId
                    AND (Projection__c != null
                    OR Distribution__c != null)
            ]
        );
        // Total up charges linked to projections or distributions.
        for (Id pId : projs.keySet())
            projTotals.put(pId, 0);
        for (Id dId : dists.keySet())
            distTotals.put(dId, 0);
        for (Charge__c c : charges) {
            Id pId = c.Projection__c;
            Id dId = c.Distribution__c;
            if (pId != null)
                projTotals.put(pId, c.Amount_charged__c + projTotals.get(pId));
            else if (dId != null)
                distTotals.put(dId, c.Amount_charged__c + distTotals.get(dId));
        }
        // Gather projections/distributions whose releasing totals need updating.
        for (Projection__c p : projs.values()) {
            Decimal total = projTotals.get(p.Id);
            if (p.Amount_released__c != total) {
                p.Amount_released__c = total;
                toUpdate.add(p);
            }
        }
        for (Distribution__c d : dists.values()) {
            Decimal total = distTotals.get(d.Id);
            if (d.Amount_released__c != total) {
                d.Amount_released__c = total;
                toUpdate.add(d);
            }
        }
        if (toUpdate.size() > 0)
            update toUpdate;
    }

    public static List<Charge__c> getCharges(Id fundId) {
        String objName = 'Charge__c';
        String[] fieldNames = Utilities.fieldNamesForObject(objName);
        fieldNames.addAll(
            new List<String>{
                'Projection__r.Name',
                'Distribution__r.Name',
                'Proposal__r.Name',
                'Proposal__r.Account__c',
                'Proposal__r.Account__r.Name',
                'Proposal__r.Date_awarded__c'
            }
        );
        String q =
            'SELECT ' +
            String.join(fieldNames, ', ') +
            ' FROM ' +
            objName +
            ' WHERE Fund__c = : fundId';
        system.debug('getCharges: fundId = ' + fundId + '; q = ' + q);
        return Database.query(q);
    }

    public static List<Projection__c> getProjections(Id fundId) {
        String objName = 'Projection__c';
        String[] fieldNames = Utilities.fieldNamesForObject(objName);
        fieldNames.addAll(
            new List<String>{ 'Opportunity__r.Name', 'ChartofAccounts__r.Name' }
        );
        String q =
            'SELECT ' +
            String.join(fieldNames, ', ') +
            ' FROM ' +
            objName +
            ' WHERE Fund__c = : fundId';
        system.debug('getProjections: q = ' + q);
        return Database.query(q);
    }

    public static List<Distribution__c> getDistributions(Id fundId) {
        String objName = 'Distribution__c';
        String[] fieldNames = Utilities.fieldNamesForObject(objName);
        fieldNames.addAll(
            new List<String>{ 'Source_fund__r.Name', 'ChartofAccounts__r.Name' }
        );
        String q =
            'SELECT ' +
            String.join(fieldNames, ', ') +
            ' FROM ' +
            objName +
            ' WHERE Target_fund__c = : fundId';
        system.debug('getDistributions: q = ' + q);
        return Database.query(q);
    }

    // Release the charges selected in the lightning component app against given projection/distribution on given date.
    @AuraEnabled
    public static String releaseCharges(String jsonString) {
        sObject[] toUpdate = new List<sObject>();
        sObject[] toInsert = new List<sObject>();
        strike_responseData responseData = new strike_responseData();
        try {
            system.debug('releaseCharges: jsonString = ' + jsonString);
            Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(
                jsonString
            );
            system.debug(
                'releaseCharges: jsonMap = ' + JSON.serialize(jsonMap)
            );
            List<Object> chargeObjs = (List<Object>) jsonMap.get('chargeIds');
            List<String> chargeIds = new List<String>();
            for (Object cObj : chargeObjs)
                chargeIds.add(String.valueOf(cObj));
            system.debug('releaseCharges: chargeIds = ' + chargeIds);
            Id projId = jsonMap.get('projectionId') != null
                ? Id.valueOf((String) jsonMap.get('projectionId'))
                : null;
            Id distId = jsonMap.get('distributionId') != null
                ? Id.valueOf((String) jsonMap.get('distributionId'))
                : null;
            system.debug(
                'releaseCharges: projId = ' +
                projId +
                '; distId = ' +
                distId
            );
            Date dateReleased = Date.valueOf(
                (String) jsonMap.get('dateReleased')
            );
            // Fetch records
            Charge__c[] charges = new List<Charge__c>(
                [
                    SELECT
                        Amount_charged__c,
                        Projection__c,
                        Distribution__c,
                        Date_released__c,
                        Fund__c,
                        Proposal__c
                    FROM Charge__c
                    WHERE Id IN :chargeIds
                ]
            );
            Projection__c proj;
            Distribution__c dist;
            if (projId != null)
                proj = [
                    SELECT Amount_released__c, To_be_released__c
                    FROM Projection__c
                    WHERE Id = :projId
                ];
            else if (distId != null)
                dist = [
                    SELECT Amount_released__c, To_be_released__c
                    FROM Distribution__c
                    WHERE Id = :distId
                ];
            Decimal toBeRel = proj != null
                ? proj.To_be_released__c
                : dist != null ? dist.To_be_released__c : 0;
            Decimal total = 0;
            // Release charges until the total released passes the amount left to be released in the projection/distribution.
            for (Charge__c c : charges) {
                Decimal chgAmt = c.Amount_charged__c;
                if (c.Date_released__c != null)
                    continue; // Skip charges that have already been released.
                if (total + chgAmt > toBeRel) {
                    // This charge would overflow proj/dist.
                    // "Split" the charge by cloning so we fully release the proj/dist.
                    Charge__c newChg = c.clone(false, false, false, false);
                    // New charge holds the extra amount, and will not be released.
                    newChg.Amount_charged__c = total + chgAmt - toBeRel;
                    toInsert.add(newChg);
                    system.debug(
                        'releaseCharges cloning charge: total = ' +
                        total +
                        '; chgAmt = ' +
                        chgAmt +
                        '; toBeRel = ' +
                        toBeRel
                    );
                    system.debug(
                        'releaseCharges cloning charge: newChg = ' +
                        JSON.serialize(newChg)
                    );
                    // Reduce amount of original charge.
                    chgAmt = toBeRel - total;
                    c.Amount_charged__c = chgAmt;
                }
                // Release the charge.
                if (proj != null)
                    c.Projection__c = proj.Id;
                else if (dist != null)
                    c.Distribution__c = dist.Id;
                c.Date_released__c = dateReleased;
                toUpdate.add(c);
                total += chgAmt;
                if (total >= toBeRel)
                    break; // Bail if we've hit the proj/dist's limit.
            }
            if (toUpdate.size() > 0)
                update toUpdate;
            if (toInsert.size() > 0)
                insert toInsert;
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        system.debug(
            'getRecordsForReleasing: responseData = ' +
            JSON.serialize(responseData)
        );
        return responseData.getJsonString();
    }

    // Unrelease the charges selected in the lightning component app.
    @AuraEnabled
    public static String unreleaseCharges(String jsonString) {
        sObject[] toUpdate = new List<sObject>();
        strike_responseData responseData = new strike_responseData();
        try {
            system.debug('unreleaseCharges: jsonString = ' + jsonString);
            Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(
                jsonString
            );
            system.debug(
                'unreleaseCharges: jsonMap = ' + JSON.serialize(jsonMap)
            );
            List<Object> chargeObjs = (List<Object>) jsonMap.get('chargeIds');
            List<String> chargeIds = new List<String>();
            for (Object cObj : chargeObjs)
                chargeIds.add(String.valueOf(cObj));
            system.debug('unreleaseCharges: chargeIds = ' + chargeIds);
            // Fetch records
            Charge__c[] charges = new List<Charge__c>(
                [
                    SELECT
                        Amount_charged__c,
                        Projection__c,
                        Distribution__c,
                        Date_released__c
                    FROM Charge__c
                    WHERE Id IN :chargeIds
                ]
            );
            // Unrelease charges by clearing date released and the projection/distribution lookups.
            for (Charge__c c : charges) {
                // Skip charges that have already been released.
                if (
                    c.Date_released__c == null &&
                    c.Projection__c == null &&
                    c.Distribution__c == null
                )
                    continue;
                c.Projection__c = null;
                c.Distribution__c = null;
                c.Date_released__c = null;
                toUpdate.add(c);
            }
            if (toUpdate.size() > 0)
                update toUpdate;
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        system.debug(
            'getRecordsForReleasing: responseData = ' +
            JSON.serialize(responseData)
        );
        return responseData.getJsonString();
    }
}