force-app/main/default/objects/GM_Data__c/GM_Data__c.object-meta.xml
<CustomObject>
    <description>Contains grant-related data and indicators stemming from the group&apos;s grant application and their milestones</description>
    <label>GM Data</label>
    <nameField>
        <displayFormat>GMD-{0000000}</displayFormat>
        <label>GM Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GM Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GM_Data__c/fields/Date_awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_awarded__c</fullName>
    <description>Date awarded from linked proposal</description>
    <formula>Proposal__r.Date_awarded__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Date awarded from linked proposal</inlineHelpText>
    <label>Date awarded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GM_Data__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this GM data</description>
    <inlineHelpText>The proposal linked to this GM data</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Date_award_withdrawn__c.field-meta.xml
<CustomField>
    <fullName>Date_award_withdrawn__c</fullName>
    <description>Date the grant award was withdrawn (usually by us)</description>
    <inlineHelpText>Date the grant award was withdrawn (usually by us)</inlineHelpText>
    <label>Date award withdrawn</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_awarded__c</fullName>
    <description>Date on which the proposal becomes a grant</description>
    <inlineHelpText>Date on which the proposal becomes a grant</inlineHelpText>
    <label>Date awarded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_declined__c.field-meta.xml
<CustomField>
    <fullName>Date_declined__c</fullName>
    <description>Date the proposal was declined</description>
    <inlineHelpText>Date the proposal was declined</inlineHelpText>
    <label>Date declined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_request_withdrawn__c.field-meta.xml
<CustomField>
    <fullName>Date_request_withdrawn__c</fullName>
    <description>Date the proposal was withdrawn (usually by applicant)</description>
    <inlineHelpText>Date the proposal was withdrawn (usually by applicant)</inlineHelpText>
    <label>Date request withdrawn</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/GM_Data__c.field-meta.xml
<CustomField>
    <fullName>GM_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the GM Data record holding information for this proposal/grant</description>
    <inlineHelpText>Link to the GM Data record holding information for this proposal/grant</inlineHelpText>
    <label>GM Data</label>
    <referenceTo>GM_Data__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GMDataUpdateSchedule.cls
/*
 * Update the risk fields in gm data for under review props.
 */
global class GMDataUpdateSchedule implements Schedulable {
    global void execute(SchedulableContext scMain) {
        Map<Id, GM_Data__c> gmDatas = new Map<Id, GM_Data__c>(
            [
                SELECT Id
                FROM GM_Data__c
                WHERE
                    Proposal__c != null
                    AND Proposal__r.Date_declined__c = null
                    AND Proposal__r.Date_awarded__c = null
                    AND Proposal__r.Date_request_withdrawn__c = null
                    AND Proposal__r.Date_award_withdrawn__c = null
            ]
        );
        GMDataController.updateGMData(gmDatas.keySet());
    }
}