force-app/main/default/objects/GM_Data__c/GM_Data__c.object-meta.xml
<CustomObject>
    <description>Contains grant-related data and indicators stemming from the group&apos;s grant application and their milestones</description>
    <label>GM Data</label>
    <nameField>
        <displayFormat>GMD-{0000000}</displayFormat>
        <label>GM Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GM Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GM_Data__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The portfolio (if any) providing the context for restricted and eligibility-related fields in this GM Data record</description>
    <inlineHelpText>The portfolio (if any) providing the context for restricted and eligibility-related fields in this GM Data record</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Indicator__c/Indicator__c.object-meta.xml
<CustomObject>
    <description>Represents an indicator for LEI grantmaking analysis</description>
    <label>Indicator</label>
    <nameField>
        <label>Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this indicator is in active use</description>
    <inlineHelpText>Checked if this indicator is in active use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Indicator__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>The code associated with this indicator</description>
    <inlineHelpText>The code associated with this indicator</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indicator__c/fields/GM_Data_field_name__c.field-meta.xml
<CustomField>
    <fullName>GM_Data_field_name__c</fullName>
    <description>If non-blank, then update this field in GM Data when assignments to this indicator are made.</description>
    <inlineHelpText>If non-blank, then update this field in GM Data when assignments to this indicator are made.</inlineHelpText>
    <label>GM Data field name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indicator__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this indicator.  This field is used to group indicators in review forms.</description>
    <inlineHelpText>The type of this indicator.  This field is used to group indicators in review forms.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Indicator_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Assign__c/Indicator_Assign__c.object-meta.xml
<CustomObject>
    <description>Assignment of a single indicator to a GM Data record</description>
    <label>Indicator Assign</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Indicator Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Assign__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>The comment (if any) associated with this indicator assignment</description>
    <inlineHelpText>The comment (if any) associated with this indicator assignment</inlineHelpText>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Indicator_Assign__c/fields/GM_Data__c.field-meta.xml
<CustomField>
    <fullName>GM_Data__c</fullName>
    <description>The GM Data to which this indicator assign record is linked</description>
    <inlineHelpText>The GM Data to which this indicator assign record is linked</inlineHelpText>
    <label>GM Data</label>
    <referenceTo>GM_Data__c</referenceTo>
    <relationshipLabel>Indicator Assigns</relationshipLabel>
    <relationshipName>Indicator_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Indicator_Assign__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>The indicator to which this indicator assign record is linked</description>
    <inlineHelpText>The indicator to which this indicator assign record is linked</inlineHelpText>
    <label>Indicator</label>
    <referenceTo>Indicator__c</referenceTo>
    <relationshipLabel>Indicator Assigns</relationshipLabel>
    <relationshipName>Indicator_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Indicator_Assign__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>The quantity (if any) associated with this indicator assignment</description>
    <inlineHelpText>The quantity (if any) associated with this indicator assignment</inlineHelpText>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/GM_Data__c.field-meta.xml
<CustomField>
    <fullName>GM_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The GM Data record linked to this letter</description>
    <inlineHelpText>The GM Data record linked to this letter</inlineHelpText>
    <label>GM Data</label>
    <referenceTo>GM_Data__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this portfolio is in active use</description>
    <inlineHelpText>Checked if this portfolio is in active use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</description>
    <inlineHelpText>Type of portfolio (i.e., grantmaking, general fundraising, grantee initiative, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Advisor assignments</fullName>
            </value>
            <value>
                <fullName>Saved Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restricted_Classification__c/Restricted_Classification__c.object-meta.xml
<CustomObject>
    <description>Classifications associated with donor restricted funds.  These classifications represent concepts specified by external entities (donors) rather than by Global Fund for Women.  Each restricted classification has a type, like Outcome or Location.</description>
    <label>Restricted Classification</label>
    <nameField>
        <label>Restricted Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restricted Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Restricted_Classification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this restricted classification</description>
    <inlineHelpText>The type of this restricted classification</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outcome</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Target population</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restricted_Classification_GM_Data__c/Restricted_Classification_GM_Data__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single restricted classification to a GM Data record</description>
    <label>Restricted Classification-GM Data</label>
    <nameField>
        <displayFormat>RCG-{000000}</displayFormat>
        <label>Restricted Classification-GM Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restricted Classifications-GM Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Restricted_Classification_GM_Data__c/fields/GM_Data__c.field-meta.xml
<CustomField>
    <fullName>GM_Data__c</fullName>
    <description>The GM Data record to which this &quot;join&quot; record assigns a restricted classification</description>
    <inlineHelpText>The GM Data record to which this &quot;join&quot; record assigns a restricted classification</inlineHelpText>
    <label>GM Data</label>
    <referenceTo>GM_Data__c</referenceTo>
    <relationshipLabel>Restricted Classifications</relationshipLabel>
    <relationshipName>Restricted_Classifications_GM_Data</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restricted_Classification_GM_Data__c/fields/Restricted_Classification__c.field-meta.xml
<CustomField>
    <fullName>Restricted_Classification__c</fullName>
    <description>The restricted classification assigned by this &quot;join&quot; record</description>
    <inlineHelpText>The restricted classification assigned by this &quot;join&quot; record</inlineHelpText>
    <label>Restricted Classification</label>
    <referenceTo>Restricted_Classification__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>Restricted_Classifications_GM_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restricted_Classification_Portfolio__c/Restricted_Classification_Portfolio__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single restricted classification to a portfolio</description>
    <label>Restricted Classification-Portfolio</label>
    <nameField>
        <displayFormat>RCP-{000000}</displayFormat>
        <label>Restricted Classification-Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restricted Classifications-Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Restricted_Classification_Portfolio__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <description>The portfolio to which this &quot;join&quot; record assigns a restricted classification</description>
    <inlineHelpText>The portfolio to which this &quot;join&quot; record assigns a restricted classification</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Restricted Classifications</relationshipLabel>
    <relationshipName>Restricted_Classifications_Portfolios</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restricted_Classification_Portfolio__c/fields/Restricted_Classification__c.field-meta.xml
<CustomField>
    <fullName>Restricted_Classification__c</fullName>
    <description>The restricted classification assigned by this &quot;join&quot; record</description>
    <inlineHelpText>The restricted classification assigned by this &quot;join&quot; record</inlineHelpText>
    <label>Restricted Classification</label>
    <referenceTo>Restricted_Classification__c</referenceTo>
    <relationshipLabel>Portfolios</relationshipLabel>
    <relationshipName>Restricted_Classifications_Portfolios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If template is active, it may be invoked (usually from letters).</description>
    <inlineHelpText>If template is active, it may be invoked (usually from letters).</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Indicator_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Change Matrix</fullName>
    </customValue>
    <customValue>
        <fullName>Movement Building</fullName>
    </customValue>
    <customValue>
        <fullName>Crisis Response</fullName>
    </customValue>
    <customValue>
        <fullName>Initiative A</fullName>
    </customValue>
    <description>Indicator types</description>
    <masterLabel>Indicator type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GMDataController.cls
public class GMDataController {
    /**********************************
     * For use in Lightning components
     *********************************/

    // Build structure for a gmData record.
    @AuraEnabled
    public static GMDataInfo getGMDataInfo(Id gmDataId) {
        return new GMDataInfo(gmDataId);
    }

    // Object that packages GM Data information including restricted classifications and picklists.
    public with sharing class GMDataInfo {
        @AuraEnabled
        public GM_Data__c gmData;
        @AuraEnabled
        public Map<String, String[]> picklists;
        @AuraEnabled
        public Portfolio__c portfolio;
        @AuraEnabled
        public Map<String, String> selectedIdsPacked = new Map<String, String>();
        @AuraEnabled
        public Map<String, String[]> selectedNames = new Map<String, List<String>>(),
            unselectedNames = new Map<String, List<String>>();
        @AuraEnabled
        public Map<Id, String> nameMap;
        @AuraEnabled
        public Map<String, List<Indicator__c>> indicatorMap = new Map<String, List<Indicator__c>>();
        @AuraEnabled
        public Map<Id, Indicator_Assign__c> indicatorAssignMap = new Map<Id, Indicator_Assign__c>();
        @AuraEnabled
        // New/changed indicator assignments in review form
        public Map<String, String> indicatorAssignInfo = new Map<String, String>();

        public GMDataInfo(Id gmDataId) {
            if (gmDataId == null)
                return;
            // Get the GM Data record.
            gmData = (GM_Data__c) Utilities.fetchRecord(
                'GM_Data__c',
                gmDataId,
                null
            );
            // Look up values in picklists at the time the GMDataInfo record is created, so they're up to date.
            picklists = Utilities.getPicklists('GM_Data__c');
            // Fetch portfolio if one is linked from the gm data.
            Id portId = gmData.Portfolio__c;
            if (portId != null) {
                portfolio = [
                    SELECT Id, Name
                    FROM Portfolio__c
                    WHERE Id = :portId
                ];

                // Fetch legal restricted classification names, i.e. the ones specified in the portfolio.
                Map<Id, Restricted_Classification_Portfolio__c> rcpMap = new Map<Id, Restricted_Classification_Portfolio__c>(
                    [
                        SELECT
                            Id,
                            Restricted_Classification__c,
                            Restricted_Classification__r.Name,
                            Restricted_Classification__r.Type__c
                        FROM Restricted_Classification_Portfolio__c
                        WHERE Portfolio__c = :portId
                        ORDER BY Restricted_Classification__r.Name
                    ]
                );
                nameMap = new Map<Id, String>();
                for (Restricted_Classification_Portfolio__c c : rcpMap.values())
                    nameMap.put(
                        c.Restricted_Classification__c,
                        c.Restricted_Classification__r.Name
                    );
                // Fetch and stash restricted classifications that have been assigned to this gm data.
                Map<Id, Restricted_Classification__c> cAssigned = new Map<Id, Restricted_Classification__c>(
                    [
                        SELECT Id, Type__c
                        FROM Restricted_Classification__c
                        WHERE
                            Id IN (
                                SELECT Restricted_Classification__c
                                FROM Restricted_Classification_GM_Data__c
                                WHERE GM_Data__c = :gmDataId
                            )
                    ]
                );
                // Stash the names from the portfolio's legal ones that haven't been selected.
                for (
                    Restricted_Classification_Portfolio__c rcp : rcpMap.values()
                ) {
                    Id cId = rcp.Restricted_Classification__c;
                    String type = rcp.Restricted_Classification__r.Type__c;
                    system.debug(
                        'cId = ' +
                        cId +
                        '; nameMap.get(cId) = ' +
                        nameMap.get(cId)
                    );
                    // Ensure that unselected and selected maps have values for each type.
                    if (!unselectedNames.containsKey(type))
                        unselectedNames.put(type, new List<String>());
                    if (!selectedNames.containsKey(type))
                        selectedNames.put(type, new List<String>());
                    if (!cAssigned.containsKey(cId))
                        unselectedNames.get(type).add(nameMap.get(cId));
                }
                // Stash selected names and ids.
                for (Restricted_Classification__c c : cAssigned.values()) {
                    String cName = nameMap.get(c.Id);
                    if (!selectedIdsPacked.containsKey(c.Type__c))
                        selectedIdsPacked.put(c.Type__c, c.Id);
                    else
                        selectedIdsPacked.put(
                            c.Type__c,
                            selectedIdsPacked.get(c.Type__c) +
                            ';' +
                            c.Id
                        );
                    selectedNames.get(c.Type__c).add(cName);
                }
            }
            // Stash indicators in a map indexed by the Type field.
            for (
                Indicator__c i : (Indicator__c[]) Utilities.fetchRecords(
                    'Indicator__c',
                    'WHERE Active__c = true ORDER BY Code__c',
                    null
                )
            ) {
                String fName = i.Type__c;
                if (fName != null) {
                    if (!indicatorMap.containsKey(fName))
                        indicatorMap.put(fName, new List<Indicator__c>());
                    indicatorMap.get(fName).add(i);
                }
            }
            system.debug(
                'GMDataInfo: indicatorMap = ' + JSON.serialize(indicatorMap)
            );
            // Stash indicator assigns in a map indexed by the indicator Id.
            for (
                Indicator_Assign__c ia : (Indicator_Assign__c[]) Utilities.fetchRecords(
                    'Indicator_Assign__c',
                    'WHERE GM_Data__c =  \'' +
                    gmDataId +
                    '\'',
                    null
                )
            )
                indicatorAssignMap.put(ia.Indicator__c, ia);
            system.debug(
                'GMDataInfo: indicatorAssignMap = ' +
                JSON.serialize(indicatorAssignMap)
            );
        }
    }

    // Save a GMDataInfo record, including its restricted classification joins.
    @AuraEnabled
    public static GM_Data__c saveGMDataInfo(String gmDataInfoSerialized) {
        system.debug(
            'saveGMDataInfo: gmDataInfoSerialized = ' +
            JSON.serialize(gmDataInfoSerialized)
        );
        // Deserialize the gmDataInfo record.
        GMDataInfo gmDataInfo = (GMDataInfo) JSON.deserialize(
            gmDataInfoSerialized,
            GMDataInfo.class
        );
        system.debug(
            'saveGMDataInfo: gmDataInfo = ' + JSON.serialize(gmDataInfo)
        );
        GM_Data__c gmData = gmDataInfo.gmData;
        system.debug('saveGMDataInfo: gmData = ' + JSON.serialize(gmData));
        // Get current assignments.
        Map<Id, Restricted_Classification_GM_Data__c> cJoins = new Map<Id, Restricted_Classification_GM_Data__c>(
            [
                SELECT Id, GM_Data__c, Restricted_Classification__c
                FROM Restricted_Classification_GM_Data__c
                WHERE GM_Data__c = :gmData.Id
            ]
        );
        system.debug('saveGMDataInfo: cJoins = ' + JSON.serialize(cJoins));
        // Stash current classification ids.
        Set<Id> currentIds = new Set<Id>();
        for (Restricted_Classification_GM_Data__c j : cJoins.values())
            currentIds.add(j.Restricted_Classification__c);
        // Get selected classification ids after initializing map.
        Set<Id> selIds = new Set<Id>();
        if (gmDataInfo.selectedIdsPacked != null) {
            for (String idsPacked : gmDataInfo.selectedIdsPacked.values())
                for (String s : idsPacked.split(';', 0))
                    if (s.trim().length() > 0)
                        selIds.add(Id.valueOf(s.trim()));
        }
        system.debug('saveGMDataInfo: selIds = ' + JSON.serialize(selIds));
        // Build list of classifications to delete - they were assigned, but are no longer selected.
        List<Restricted_Classification_GM_Data__c> toDelete = new List<Restricted_Classification_GM_Data__c>();
        for (Restricted_Classification_GM_Data__c j : cJoins.values()) {
            Id cId = j.Restricted_Classification__c;
            if (!selIds.contains(cId))
                toDelete.add(j);
        }
        system.debug(
            'In saveGMDataInfo: toDelete = ' + JSON.serialize(toDelete)
        );
        // Build list of classifications to insert - they weren't originally assigned, but are now selected.
        List<Restricted_Classification_GM_Data__c> toInsert = new List<Restricted_Classification_GM_Data__c>();
        for (Id cId : new List<Id>(selIds)) {
            if (!currentIds.contains(cId))
                toInsert.add(
                    new Restricted_Classification_GM_Data__c(
                        Restricted_Classification__c = cId,
                        GM_Data__c = gmData.Id
                    )
                );
        }
        system.debug(
            'In saveGMDataInfo: toInsert = ' + JSON.serialize(toInsert)
        );
        if (toDelete.size() > 0)
            delete toDelete;
        if (toInsert.size() > 0)
            insert toInsert;
        // Update any indicator assigns that have changed.
        updateIndicatorAssigns(gmDataInfo);
        // Save and return the GM Data record.
        update gmData;
        return gmData;
    }

    // Make changes to the current indicator assignments for given GM Data record.
    private static void updateIndicatorAssigns(GMDataInfo gmDataInfo) {
        Indicator_Assign__c[] toInsert = new List<Indicator_Assign__c>(),
            toUpdate = new List<Indicator_Assign__c>(),
            toDelete = new List<Indicator_Assign__c>();
        // Get indicator Ids.
        Map<Id, Indicator__c> inds = new Map<Id, Indicator__c>(
            [
                SELECT Id, GM_Data_field_name__c, Type__c
                FROM Indicator__c
                WHERE Active__c = true
            ]
        );
        Id gmDataId = gmDataInfo.gmData.Id;
        // Gather current indicator assigns.
        List<Indicator_Assign__c> ias = [
            SELECT Id, Indicator__c, GM_Data__c, Quantity__c, Comment__c
            FROM Indicator_Assign__c
            WHERE GM_Data__c = :gmDataId
        ];
        // Gather indicator assigns needing updating.
        Map<Id, Indicator_Assign__c> indAssignsOld = new Map<Id, Indicator_Assign__c>();
        for (Indicator_Assign__c ia : ias)
            indAssignsOld.put(ia.Indicator__c, ia);
        // Convert new assignments to a Map by indicator id.
        Map<String, String> indAssignInfo = gmDataInfo.indicatorAssignInfo;
        Map<Id, String> indAssignsNew = new Map<Id, String>();
        for (String indIdString : indAssignInfo.keySet())
            indAssignsNew.put(
                Id.valueof(indIdString),
                indAssignInfo.get(indIdString)
            );
        system.debug(
            'updateIndicatorAssigns: gmDataId = ' +
            gmDataId +
            '; indAssignsOld = ' +
            JSON.serialize(indAssignsOld) +
            '; indAssignsNew = ' +
            JSON.serialize(indAssignsNew)
        );
        // Track which checkboxes in GM Data need to be set/unset to align with assigned indicators.
        Map<String, Boolean> checkboxesAssigned = new Map<String, Boolean>();
        // Initialize the checkbox values to false.
        for (Id indId : indAssignsNew.keySet())
            checkboxesAssigned.put(
                inds.get(indId).GM_Data_field_name__c,
                false
            );
        // For each indicator, determine whether there's an assign to delete, update, or insert.
        for (Indicator__c ind : inds.values()) {
            Indicator_Assign__c iaOld = indAssignsOld.get(ind.Id);
            String q, comment;
            Integer sepIndex, quantity;
            String iaNewInfo = indAssignsNew.get(ind.Id);
            if (iaNewInfo == '')
                iaNewInfo = null;
            if (iaNewInfo != null) {
                sepIndex = iaNewInfo.indexOf(';');
                if (sepIndex > -1) {
                    q = iaNewInfo.left(sepIndex);
                    if (q != null && q.length() > 0)
                        quantity = Integer.valueOf(q);
                    comment = iaNewInfo.right(
                        iaNewInfo.length() -
                        sepIndex -
                        1
                    );
                }
                // Indicate that checkbox in GM Data should be set for this indicator group.
                checkboxesAssigned.put(
                    inds.get(ind.Id).GM_Data_field_name__c,
                    true
                );
            }
            // Check if existing indicator assign should be deleted.
            if (iaOld != null && iaNewInfo == null)
                toDelete.add(iaOld);
            else if (iaOld == null && iaNewInfo != null)
                // Build a new indicator assign record.
                toInsert.add(
                    new Indicator_Assign__c(
                        Indicator__c = ind.Id,
                        GM_Data__c = gmDataId,
                        Quantity__c = quantity,
                        Comment__c = comment
                    )
                );
            else if (iaOld != null && iaNewInfo != null) {
                if (
                    quantity != iaOld.Quantity__c ||
                    comment != iaOld.Comment__c
                ) {
                    // Update an existing indicator assign record.
                    iaOld.Quantity__c = quantity;
                    iaOld.Comment__c = comment;
                    toUpdate.add(iaOld);
                }
            }
        }
        // Update the checkboxes in the GM Data record.
        for (Indicator__c ind : inds.values()) {
            String fName = ind.GM_Data_field_name__c;
            if (fName != null && checkboxesAssigned.containsKey(fName))
                gmDataInfo.gmData.put(fName, checkboxesAssigned.get(fName));
        }
        if (toInsert.size() > 0)
            insert toInsert;
        if (toUpdate.size() > 0)
            update toUpdate;
        if (toDelete.size() > 0)
            delete toDelete;
    }

    /**********************************
     * For use in VisualForce pages
     *********************************/

    private ApexPages.StandardController standardController;
    private ApexPages.StandardSetController standardSetController;

    public GMDataController(ApexPages.StandardController standardController) {
        this.standardController = standardController;
    }

    public GMDataController(
        ApexPages.StandardSetController standardSetController
    ) {
        this.standardSetController = standardSetController;
    }

    // Build the menu of admissible correspondence templates for this object.
    private static String objectName = 'GM_Data__c';
    private static final String START = '--Select Template--';
    public List<selectOption> templates { get; private set; }
    {
        templates = Utilities.templatesForObject(objectName, START);
    }
    public String selectedTemplate { get; set; }
    {
        selectedTemplate = START;
    }
    public List<Letter__c> newLetters = new List<Letter__c>();

    // Get selected records, then build and reset letters for them.
    public PageReference buildLetters() {
        // Generate error if no selected template - assign error to the templateType field.
        if (selectedTemplate == null || selectedTemplate == START) {
            ApexPages.AddMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR,
                    'Please select a template',
                    'Must select a template before building new letters'
                )
            );
            selectedTemplate = START; // If I don't reset to the START value, it gets set to one of the non-disabled values.
            return null;
        }
        Set<Id> selIds;
        if (standardSetController != null) {
            Map<Id, GM_Data__c> selMap = new Map<Id, GM_Data__c>(
                (List<GM_Data__c>) standardSetController.getSelected()
            );
            selIds = selMap.keySet();
        } else {
            selIds = new Set<Id>{ standardController.getId() };
        }
        Map<Id, GM_Data__c> selMap = new Map<Id, GM_Data__c>(
            [
                SELECT
                    Id,
                    Account__c,
                    Account__r.OwnerId,
                    Account__r.GM_email__c,
                    Profile__c
                FROM GM_Data__c
                WHERE Id IN :selIds
            ]
        );
        // Get account emails.
        Map<Id, Account> aMap = new Map<Id, Account>(
            [
                SELECT Id
                FROM Account
                WHERE
                    Id IN (
                        SELECT Account__c
                        FROM GM_Data__c
                        WHERE Id IN :selMap.keySet()
                    )
            ]
        );
        Map<Id, List<String>> emails = AccountController.emailsForAccounts(
            aMap.keySet()
        );
        // Build new letters for selected records.
        Id templateId = Utilities.recordIdFromName(
            'Template__c',
            selectedTemplate
        );
        for (GM_Data__c r : selMap.values()) {
            List<String> es = emails.get(r.Account__c);
            newLetters.add(
                new Letter__c(
                    Template__c = templateId,
                    Account__c = r.Account__c,
                    Account_owner__c = r.Account__r.OwnerId,
                    Letter_owner__c = UserInfo.getUserId(),
                    GM_Data__c = r.Id,
                    Profile__c = r.Profile__c,
                    // Use account emails.
                    Emails__c = Utilities.stringJoinWithCharLimit(es, ',', 255)
                )
            );
        }
        insert newLetters;
        // Reset the new letters.
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(newLetters);
        LetterController.resetLetters0(lMap.keySet(), false);
        // Changes have been saved; jump to the new letter if there's only one.
        if (standardController != null && newLetters.size() == 1)
            return Utilities.pageReferenceForRecord(newLetters[0]);
        else
            return doCancel(); // Stay in current layout.
    }

    public PageReference doCancel() {
        return (standardSetController != null)
            ? standardSetController.cancel()
            : standardController.cancel();
    }

    /**********************************
     * For general use
     *********************************/

    // Update GM Data record(s).
    public static void updateGMData(Set<Id> gmDataIds) {
    }
}