force-app/main/default/objects/Advisor_Term__c/Advisor_Term__c.object-meta.xml
<CustomObject>
    <description>Represents a term of an official GFW advisor</description>
    <label>Advisor Term</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Advisor Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisor Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>An assessment created by an advisor for a particular account/proposal/profile/portfolio</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Advisor_Term__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The advisor term record linked to this assessment</description>
    <inlineHelpText>The advisor term record linked to this assessment</inlineHelpText>
    <label>Advisor Term</label>
    <referenceTo>Advisor_Term__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Advisor_Term__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advisor term to which this letter is linked</description>
    <inlineHelpText>Advisor term to which this letter is linked</inlineHelpText>
    <label>Advisor Term</label>
    <referenceTo>Advisor_Term__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The assessment linked to this letter</description>
    <inlineHelpText>The assessment linked to this letter</inlineHelpText>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Source_object__c.field-meta.xml
<CustomField>
    <fullName>Source_object__c</fullName>
    <description>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</description>
    <inlineHelpText>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</inlineHelpText>
    <label>Source object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>GM_Data__c</fullName>
            </value>
            <value>
                <fullName>Milestone__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Payment__c</fullName>
            </value>
            <value>
                <fullName>Payment_Method__c</fullName>
            </value>
            <value>
                <fullName>Profile__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdvisorTermControllerTest.cls
@isTest
public with sharing class AdvisorTermControllerTest {
    
    static testmethod void AdvisorTermControllerTest1a () {
        // Build new advisors and accounts and advisor terms.
        AdvisorControllerTest.InitTestObjects(2);
        Map<Id, Advisor_Term__c> atMap = new Map<Id, Advisor_Term__c> ([SELECT Id FROM Advisor_Term__c]);
        // Build new standard set controller and select the new advisor terms.
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(atMap.values());
        ssc.setSelected(atMap.values());        
        
        Test.StartTest();
        // Build a new advisor term controller and use it to build new letters for the selected advisor terms.
        Template__c temp = new Template__c (Name = 'Test template', Source_object__c = 'Assessment__c');
        insert temp;
        AdvisorTermController pc = new AdvisorTermController (ssc);
        pc.selectedTemplate = temp.Id;
        system.assertNotEquals(pc.selectedTemplate, null);
        pc.buildLetters();
        Test.StopTest();
        
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c> ([SELECT Id FROM Letter__c]);
        AdvisorControllerTest.validate(lMap.keySet());
    }
    
    static testmethod void AdvisorTermControllerTest1b () {
        // Build new advisors and accounts and advisor terms.
        AdvisorControllerTest.InitTestObjects(2);
        Map<Id, Advisor_Term__c> atMap = new Map<Id, Advisor_Term__c> ([SELECT Id FROM Advisor_Term__c]);
        // Build new standard controller and select the new advisor term.
        ApexPages.StandardController sc = new ApexPages.StandardController(atMap.values()[0]);
        
        Test.StartTest();
        // Build a new advisor term controller and use it to build new letter for the advisor term.
        Template__c temp = new Template__c (Name = 'Test template', Source_object__c = 'Assessment__c');
        insert temp;
        AdvisorTermController pc = new AdvisorTermController (sc);
        pc.selectedTemplate = temp.Id;
        system.assertNotEquals(pc.selectedTemplate, null);
        pc.buildLetters();
        Test.StopTest();
        
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c> ([SELECT Id FROM Letter__c]);
        AdvisorControllerTest.validate(lMap.keySet());
    }
    
    static testmethod void AdvisorTermControllerTest2 () {
        // Build new advisors and accounts and advisor terms.
        AdvisorControllerTest.InitTestObjects(1);
        insert new Template__c (Name = AdvisorTermController.reminderTemplateName, Source_object__c = 'Advisor_Term__c');
        Test.StartTest();
        // Test emailing reminders via the schedulable class.
        String CRON_EXP = '0 0 0 15 3 ?';    
        String jobId = System.schedule('Email reminders', CRON_EXP, new AdvisorTermRemindersSchedule());
        Test.StopTest();
    }
    
}