force-app/main/default/objects/ChartofAccounts__c/ChartofAccounts__c.object-meta.xml
<CustomObject>
    <description>Chart of accounts information including departments and CAE code.</description>
    <label>Chart of Accounts</label>
    <nameField>
        <label>Designation Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ChartofAccounts__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Any free text information you wish to associated with this item in the Chart of Accounts.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ChartofAccounts__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ChartofAccounts__c.field-meta.xml
<CustomField>
    <fullName>ChartofAccounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to broadly categorize the donor’s intended use of their gift.  The list is organized in the follow manner:
#Unrestricted: Gifts for general support.
CF = Crisis Funds:  Gifts restricted for established crisis funding.  Followed by the location/description of the crisis.
FS = Fiscal Sponsorship:  Gifts for our fiscal sponsored grantee partners.  Followed by the acronym of the group.
GM = Grantmaking:  Gifts restricted for activities that include grantmaking.  Followed by the region/issue as applicable.  Gifts that are restricted to more than one region should use CR (Cross Regional.)
PF = Pooled Fund:  Gifts from multiple donors for a specific initiative.  Followed by the description of the initiative.
Prog = Program:  Gifts restricted for activities that do not include any grantmaking.  Followed by a description of the department/activity.
Temp-Time =  Time-restricted general support donations.</description>
    <inlineHelpText>The chart of accounts are used to broadly categorize the donor’s intent.  Please note:

#Unrestricted: General Support
CF: Crisis Funds
FS: Fiscal Sponsorship
GM: Grantmaking
PF: Pooled Fund
Prog: Program
Temp-Time: Time-restricted General Support</inlineHelpText>
    <label>Chart of Accounts</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The linked chart of accounts record must be marked Active.</errorMessage>
        <filterItems>
            <field>ChartofAccounts__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>The linked chart of accounts record must be marked Active.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ChartofAccounts__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Soft_ask__c.field-meta.xml
<CustomField>
    <fullName>Soft_ask__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use a &quot;soft ask&quot; for this opportunity.</description>
    <inlineHelpText>Use a &quot;soft ask&quot; for this opportunity.</inlineHelpText>
    <label>Soft ask</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/Task_spec__c.object-meta.xml
<CustomObject>
    <description>The specification or template for a single task - linked to a task spec group</description>
    <label>Task spec</label>
    <nameField>
        <displayFormat>TSpec-{000000}</displayFormat>
        <label>Task spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_spec__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this task spec is active</description>
    <inlineHelpText>Checked if this task spec is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The subject of tasks created from this task spec</description>
    <inlineHelpText>The subject of tasks created from this task spec</inlineHelpText>
    <label>Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/fields/Task_spec_group__c.field-meta.xml
<CustomField>
    <fullName>Task_spec_group__c</fullName>
    <description>This parent task spec group of this task spec</description>
    <inlineHelpText>This parent task spec group of this task spec</inlineHelpText>
    <label>Task spec group</label>
    <referenceTo>Task_spec_group__c</referenceTo>
    <relationshipLabel>Task specs</relationshipLabel>
    <relationshipName>Task_specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Populates the Type field of tasks built from this task spec</description>
    <inlineHelpText>Populates the Type field of tasks built from this task spec</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Report/interim</fullName>
            </value>
            <value>
                <fullName>Financial Report</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_spec_group__c/Task_spec_group__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of task specs for a particular object (e.g. Opportunity), used to create a set of actual tasks</description>
    <label>Task spec group</label>
    <nameField>
        <label>Task spec group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task spec groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_spec_group__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this task spec group is active</description>
    <inlineHelpText>Checked if this task spec group is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_spec_group__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of this task spec group</description>
    <inlineHelpText>Description of this task spec group</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task_spec_group__c/fields/Object_name__c.field-meta.xml
<CustomField>
    <fullName>Object_name__c</fullName>
    <description>The name of the Salesforce object to which this task spec group applies</description>
    <inlineHelpText>The name of the Salesforce object to which this task spec group applies</inlineHelpText>
    <label>Object name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Fund__c</fullName>
            </value>
            <value>
                <fullName>Allocation__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_spec_group__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this task spec group</description>
    <inlineHelpText>The type of this task spec group</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object_name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restricted Fund Checklist - option</fullName>
            </value>
            <value>
                <fullName>Restricted Fund Checklist - required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityController.cls
public class OpportunityController {
    /**********************************
     * For use in Lightning components
     *********************************/

    // Look up the active task spec groups for opportunities.
    @AuraEnabled
    public static Task_Spec_Group__c[] getTaskSpecGroups(String type) {
        return [
            SELECT Id, Name, Description__c
            FROM Task_Spec_Group__c
            WHERE
                Object_name__c = 'Opportunity'
                AND Type__c = :type
                AND Active__c = true
            ORDER BY Name
        ];
    }

    // Fetch all local fields of the tasks belonging to the given opportunity.
    @AuraEnabled
    public static Task[] getTasks(Id oppId) {
        return Utilities.fetchChildRecords('Task', oppId, 'WhatId', null);
    }

    // Build the RFC tasks for given opportunity from given task spec group.
    @AuraEnabled
    public static void buildTasksFromTSG(
        String oppId,
        String tsgId,
        String reportTaskAssignedToOverrideId
    ) {
        system.debug(
            'buildTasksFromTSG: oppId = ' +
            oppId +
            '; tsgId = ' +
            tsgId +
            '; reportTaskAssignedToOverrideId = ' +
            reportTaskAssignedToOverrideId
        );
        // Build tasks from selected task spec group.
        Utilities.instantiateTaskSpecs(
            (Id) oppId,
            (Id) tsgId,
            (Id) reportTaskAssignedToOverrideId,
            null
        );
    }

    // Build the RFC tasks for given opportunity from task spec groups with given type.
    @AuraEnabled
    public static void buildTasksFromTSGType(
        String oppId,
        String tsgType,
        String reportTaskAssignedToOverrideId
    ) {
        system.debug(
            'buildTasksFromTSGType: oppId = ' +
            oppId +
            '; tsgType = ' +
            tsgType +
            '; reportTaskAssignedToOverrideId = ' +
            reportTaskAssignedToOverrideId
        );
        Task_Spec_Group__c[] tsgs = getTaskSpecGroups(tsgType);
        for (Task_Spec_Group__c tsg : tsgs)
            Utilities.instantiateTaskSpecs(
                (Id) oppId,
                (Id) tsg.Id,
                (Id) reportTaskAssignedToOverrideId,
                null
            );
    }

    // Build tasks for given opportunity from given task spec group using JSON parameter.
    @AuraEnabled
    public static String instantiateTaskSpecGroup(String jsonString) {
        strike_responseData responseData = new strike_responseData();
        try {
            Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(
                jsonString
            );
            Id oppId = jsonMap.get('oppId') != null
                ? Id.valueOf((String) jsonMap.get('oppId'))
                : null;
            Id taskSpecGroupId = jsonMap.get('taskSpecGroupId') != null
                ? Id.valueOf((String) jsonMap.get('taskSpecGroupId'))
                : null;
            Id reportTaskAssignedToOverrideId = jsonMap.get(
                    'reportTaskAssignedToOverrideId'
                ) != null
                ? Id.valueOf(
                        (String) jsonMap.get('reportTaskAssignedToOverrideId')
                    )
                : null;
            Date baseDate = jsonMap.get('baseDate') != null
                ? Date.valueOf((String) jsonMap.get('baseDate'))
                : null;
            system.debug(
                'instantiateTaskSpecGroup: oppId = ' +
                oppId +
                '; taskSpecGroupId = ' +
                taskSpecGroupId +
                '; reportTaskAssignedToOverrideId = ' +
                reportTaskAssignedToOverrideId +
                '; baseDate = ' +
                baseDate
            );
            // Build tasks from selected task spec group.
            Utilities.instantiateTaskSpecs(
                oppId,
                taskSpecGroupId,
                reportTaskAssignedToOverrideId,
                baseDate
            );
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        system.debug(
            'instantiateTaskSpecGroup: responseData = ' +
            JSON.serialize(responseData)
        );
        return responseData.getJsonString();
    }

    // Build task for given opportunity from given task spec.
    @AuraEnabled
    public static String instantiateTaskSpec(String jsonString) {
        strike_responseData responseData = new strike_responseData();
        try {
            Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(
                jsonString
            );
            system.debug(
                'instantiateTaskSpec: jsonMap = ' + JSON.serialize(jsonMap)
            );
            Id oppId = jsonMap.get('oppId') != null
                ? Id.valueOf((String) jsonMap.get('oppId'))
                : null;
            Id taskSpecId = jsonMap.get('taskSpecId') != null
                ? Id.valueOf((String) jsonMap.get('taskSpecId'))
                : null;
            Id reportTaskAssignedToOverrideId = jsonMap.get(
                    'reportTaskAssignedToOverrideId'
                ) != null
                ? Id.valueOf(
                        (String) jsonMap.get('reportTaskAssignedToOverrideId')
                    )
                : null;
            Date baseDate = jsonMap.get('baseDate') != null
                ? Date.valueOf((String) jsonMap.get('baseDate'))
                : null;
            system.debug(
                'instantiateTaskSpec: oppId = ' +
                oppId +
                '; taskSpecId = ' +
                taskSpecId +
                '; reportTaskAssignedToOverrideId = ' +
                reportTaskAssignedToOverrideId +
                '; baseDate = ' +
                baseDate
            );
            // Build task from selected task spec.
            Task t = Utilities.instantiateTaskSpec(
                oppId,
                taskSpecId,
                reportTaskAssignedToOverrideId,
                baseDate
            );
            if (t != null)
                insert t;
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        system.debug(
            'instantiateTaskSpec: responseData = ' +
            JSON.serialize(responseData)
        );
        return responseData.getJsonString();
    }

    // Fetch tasks for given opportunity, plus first gift date and task specs and task spec groups.
    @AuraEnabled
    public static String getTasksPlus(Id oppId) {
        strike_responseData responseData = new strike_responseData();
        // Skip the Miscellaneous group - those are grabbed in the task spec search.
        Task_Spec_Group__c[] tsgs = [
            SELECT Id, Name, Description__c
            FROM Task_Spec_Group__c
            WHERE
                Object_name__c = 'Opportunity'
                AND Active__c = true
                AND Name != 'Miscellaneous'
            ORDER BY Name
        ];
        // Only grab task specs in the Miscellaneous group - the others are included in task spec groups.
        Task_spec__c[] tss = [
            SELECT Id, Name, Subject__c
            FROM Task_Spec__c
            WHERE Active__c = true AND Task_Spec_Group__r.Name = 'Miscellaneous'
            ORDER BY Name
        ];
        try {
            responseData.results = new Map<String, Object>{
                'tasks' => Utilities.fetchChildRecords(
                    'Task',
                    oppId,
                    'WhatId',
                    new List<String>{ 'Owner.Name', 'CreatedBy.Name' }
                ),
                'taskSpecs' => tss,
                'taskSpecGroups' => tsgs
            };
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        system.debug(
            'getTasksPlus: responseData = ' + JSON.serialize(responseData)
        );
        return responseData.getJsonString();
    }

    // Update task records as specified in the updateSpec JSON (list of records, each of which lists fields to change plus Id).
    @AuraEnabled
    public static String updateTasks(String tasksJSON) {
        strike_responseData responseData = new strike_responseData();
        try {
            List<Task> tasks = (List<Task>) JSON.deserialize(
                tasksJSON,
                List<Task>.class
            );
            update tasks;
        } catch (Exception e) {
            responseData.addError(e.getMessage());
        }
        return responseData.getJsonString();
    }

    /**********************************
     * For general use
     *********************************/

    /*
     * Assume that caller is ensuring that opp's stage just changed to Closed Won.  That is, we
     * shouldn't later re-clone if they delete the clone that was created when the opp was closed.
     * Conditions for cloning:
     * (1) the current stage is closed-won,
     * (2) the current type is "Major Gift Opportunity: Annual Gift",
     * (3) there's no open opportunity for this account with
     * type = "Major Gift Opportunity: Annual Gift" and
     * close date after the closed opp's close date (check with Renee on that last one!).
     */
    public static void opportunityClone(Id oppId) {
        // Constrain that opp is closed-won and of the correct type
        Opportunity opp = [
            SELECT
                CloseDate,
                StageName,
                Type,
                OwnerId,
                Amount,
                AccountId,
                Name,
                Notes__c,
                ChartofAccounts__c,
                ChartofAccounts__r.Name,
                Soft_ask__c,
                Account.Name,
                CampaignId
            FROM Opportunity
            WHERE
                Id = :oppId
                AND StageName = 'Closed Won'
                AND Type = 'Major Gift Opportunity: Annual Gift'
                AND AccountId != null
        ];
        if (opp == null)
            return; // Bail if inappropriate to do an auto-clone.

        // Build a pattern that matches strings like "FY2013-2014" in opportunity names.
        Pattern fyPat = Pattern.compile('FY(\\d{4})-(\\d{4})');

        // Fetch all open opportunities for the opp's account.
        Account acc = [
            SELECT
                Id,
                OwnerId,
                (
                    SELECT Id, AccountId, CloseDate, StageName
                    FROM Opportunities
                    WHERE
                        (NOT StageName LIKE '%Closed%')
                        AND Type = 'Major Gift Opportunity: Annual Gift'
                    ORDER BY CloseDate DESC
                    LIMIT 1
                )
            FROM Account
            WHERE Id = :opp.AccountId
        ];
        system.debug('OpportunityClone: acc = ' + JSON.serialize(acc));
        List<Opportunity> openOpps = acc.Opportunities;
        Opportunity newOpp;
        // Skip unless there's an open opp for the account with more recent close date.
        system.debug(
            'OpportunityClone before if: openOpps = ' + JSON.serialize(openOpps)
        );
        if (
            openOpps.size() == 0 ||
            openOpps[0].CloseDate == null ||
            openOpps[0].CloseDate < opp.CloseDate
        ) {
            // Look for an FY pattern in the closed opp's name.
            Matcher pm = fyPat.matcher(opp.Name);
            integer fyYear1, fyYear2;
            if (pm.find()) {
                fyYear1 = integer.valueof(pm.group(1));
                fyYear2 = integer.valueof(pm.group(2));
            }
            date newCloseDate = opp.CloseDate.addYears(1);
            string newCloseDateFY = Utilities.FYfromDate(newCloseDate);
            // Designation description is based on closed opp's chart-of-accounts.
            string designationDesc = (opp.ChartofAccounts__c == null ||
                opp.ChartofAccounts__r.Name.toLowerCase()
                    .contains('unrestricted'))
                ? 'General Support'
                : opp.ChartofAccounts__r.Name;
            // The FY for the new opp name is based on close date, unless this is a multi-year opp,
            // in which case base it on the FY pattern in the closed opp's name.
            string fyNew = (pm.find() &&
                fyYear2 > integer.valueOf(newCloseDateFY.Right(4)))
                ? Utilities.FYfromDate(date.newInstance(fyYear2 + 1, 1, 1))
                : newCloseDateFY;
            // Build the new opp name by string replace of the FY in the closed opp's name.
            // If it doesn't contain an FY pattern, then build a new name from scratch.
            string newOppName = (pm.matches())
                ? opp.Name.replace(
                        'FY' +
                        pm.group(1) +
                        '-' +
                        pm.group(2),
                        fyNew
                    )
                : fyNew + ' ' + designationDesc + ': ' + opp.Account.Name;

            // Now clone the closed opportunity.
            newOpp = new Opportunity(
                Amount = opp.Amount,
                AccountId = opp.AccountId,
                Type = opp.Type,
                ChartofAccounts__c = opp.ChartofAccounts__c,
                Soft_ask__c = opp.Soft_ask__c,
                OwnerId = opp.OwnerId,
                CampaignId = opp.CampaignId,
                StageName = 'Identification',
                Notes__c = 'Auto-cloned from prior closed opportunity, ' +
                    opp.Name,
                CloseDate = newCloseDate,
                Name = newOppName
            );
        }
        if (newOpp <> null)
            insert newOpp;
    }
}