force-app/main/default/objects/ChartofAccounts__c/ChartofAccounts__c.object-meta.xml
<CustomObject>
    <description>Chart of accounts information including departments and CAE code.</description>
    <label>Chart of Accounts</label>
    <nameField>
        <label>Designation Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/ChartofAccounts__c.field-meta.xml
<CustomField>
    <fullName>ChartofAccounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to broadly categorize the donor’s intended use of their gift.  The list is organized in the follow manner:
#Unrestricted: Gifts for general support.
CF = Crisis Funds:  Gifts restricted for established crisis funding.  Followed by the location/description of the crisis.
FS = Fiscal Sponsorship:  Gifts for our fiscal sponsored grantee partners.  Followed by the acronym of the group.
GM = Grantmaking:  Gifts restricted for activities that include grantmaking.  Followed by the region/issue as applicable.  Gifts that are restricted to more than one region should use CR (Cross Regional.)
PF = Pooled Fund:  Gifts from multiple donors for a specific initiative.  Followed by the description of the initiative.
Prog = Program:  Gifts restricted for activities that do not include any grantmaking.  Followed by a description of the department/activity.
Temp-Time =  Time-restricted general support donations.</description>
    <inlineHelpText>The chart of accounts are used to broadly categorize the donor’s intent.  Please note:

#Unrestricted: General Support
CF: Crisis Funds
FS: Fiscal Sponsorship
GM: Grantmaking
PF: Pooled Fund
Prog: Program
Temp-Time: Time-restricted General Support</inlineHelpText>
    <label>Chart of Accounts</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The linked chart of accounts record must be marked Active.</errorMessage>
        <filterItems>
            <field>ChartofAccounts__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>The linked chart of accounts record must be marked Active.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ChartofAccounts__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/Task_spec__c.object-meta.xml
<CustomObject>
    <description>The specification or template for a single task - linked to a task spec group</description>
    <label>Task spec</label>
    <nameField>
        <displayFormat>TSpec-{000000}</displayFormat>
        <label>Task spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_spec__c/fields/Assigned_to__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user to whom tasks based on this task spec should be assigned</description>
    <inlineHelpText>The user to whom tasks based on this task spec should be assigned</inlineHelpText>
    <label>Assigned to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Task_specs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Populates the Comments field of tasks built from this task spec</description>
    <inlineHelpText>Populates the Comments field of tasks built from this task spec</inlineHelpText>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/fields/Days_after__c.field-meta.xml
<CustomField>
    <fullName>Days_after__c</fullName>
    <description>If Due date is blank, then calculate the task&apos;s due date from this field, by adding this number of days to the date on which the task is created.</description>
    <inlineHelpText>If Due date is blank, then calculate the task&apos;s due date from this field, by adding this number of days to the date on which the task is created.</inlineHelpText>
    <label>Days after</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The subject of tasks created from this task spec</description>
    <inlineHelpText>The subject of tasks created from this task spec</inlineHelpText>
    <label>Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/fields/Task_spec_group__c.field-meta.xml
<CustomField>
    <fullName>Task_spec_group__c</fullName>
    <description>This parent task spec group of this task spec</description>
    <inlineHelpText>This parent task spec group of this task spec</inlineHelpText>
    <label>Task spec group</label>
    <referenceTo>Task_spec_group__c</referenceTo>
    <relationshipLabel>Task specs</relationshipLabel>
    <relationshipName>Task_specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_spec__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Populates the Type field of tasks built from this task spec</description>
    <inlineHelpText>Populates the Type field of tasks built from this task spec</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Report/interim</fullName>
            </value>
            <value>
                <fullName>Financial Report</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_spec_group__c/Task_spec_group__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of task specs for a particular object (e.g. Opportunity), used to create a set of actual tasks</description>
    <label>Task spec group</label>
    <nameField>
        <label>Task spec group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task spec groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_spec_group__c/fields/Object_name__c.field-meta.xml
<CustomField>
    <fullName>Object_name__c</fullName>
    <description>The name of the Salesforce object to which this task spec group applies</description>
    <inlineHelpText>The name of the Salesforce object to which this task spec group applies</inlineHelpText>
    <label>Object name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Fund__c</fullName>
            </value>
            <value>
                <fullName>Allocation__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_spec_group__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this task spec group</description>
    <inlineHelpText>The type of this task spec group</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object_name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restricted Fund Checklist - option</fullName>
            </value>
            <value>
                <fullName>Restricted Fund Checklist - required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityControllerTest.cls
@isTest
public class OpportunityControllerTest {
    static testMethod void OpportunityControllerTest1() {
        User u = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        insert new Opportunity(
            Name = 'test opportunity 1',
            StageName = 'Closed Won',
            CloseDate = Date.today()
        );
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        String typeVal = Utilities.picklistValues(
            'Task_Spec_Group__c',
            'Type__c'
        )[0];
        insert new Task_Spec_Group__c(
            Name = 'task spec group 1',
            Object_name__c = 'Opportunity',
            Type__c = typeVal
        );
        Task_Spec_Group__c tsg = [SELECT Id FROM Task_Spec_Group__c LIMIT 1];
        insert new Task_Spec__c(
            Task_Spec_Group__c = tsg.Id,
            Assigned_to__c = u.Id,
            Subject__c = 'sss',
            Type__c = Utilities.picklistValues('Task_Spec__c', 'Type__c')[0],
            Comments__c = 'ccc',
            Days_after__c = 2
        );
        Task_Spec__c taskSpec = [SELECT Id FROM Task_Spec__c LIMIT 1];
        String jsonString1 = JSON.serialize(
            new Map<String, Object>{
                'oppId' => opp.Id,
                'taskSpecId' => taskSpec.Id,
                'reportTaskAssignedToOverrideId' => u.Id,
                'baseDate' => null
            }
        );
        String jsonString2 = JSON.serialize(
            new Map<String, Object>{
                'oppId' => opp.Id,
                'taskSpecGroupId' => tsg.Id,
                'reportTaskAssignedToOverrideId' => u.Id,
                'baseDate' => null
            }
        );

        test.startTest();
        String jsonStr = OpportunityController.getTasksPlus(opp.Id);
        Task_Spec_Group__c[] tsgs = OpportunityController.getTaskSpecGroups(
            typeVal
        );
        system.assertNotEquals(tsgs, null);
        OpportunityController.buildTasksFromTSG(opp.Id, tsgs[0].Id, u.Id);
        OpportunityController.buildTasksFromTSGType(opp.Id, typeVal, u.Id);
        OpportunityController.instantiateTaskSpec(jsonString1);
        OpportunityController.instantiateTaskSpecGroup(jsonString2);
        test.stopTest();
        Task[] ts = OpportunityController.getTasks(opp.Id);
        system.assert(ts.size() > 0);
        Task t = ts[0];
        Date origDueDate = t.ActivityDate;
        Date newDueDate = t.ActivityDate.addDays(100);
        t.ActivityDate = newDueDate;
        String tasksJSON = JSON.serialize(new List<Task>{ t });
        OpportunityController.updateTasks(tasksJSON);
        t = [SELECT Id, ActivityDate FROM Task WHERE Id = :t.Id];
        system.assertNotEquals(origDueDate, t.ActivityDate);
    }

    static testMethod void OpportunityControllerTest2() {
        // Build new Opportunity records
        InitTestOpportunities();
        Map<Id, Opportunity> oppsMap = new Map<Id, Opportunity>(
            [
                SELECT Name, AccountId, Amount, StageName, CloseDate
                FROM Opportunity
            ]
        );

        Test.StartTest();
        Opportunity oppToClose;
        // Close the opportunity with StageName = Negotiation, causing it to be cloned.
        for (Opportunity opp : oppsMap.values()) {
            if (opp.StageName == 'Negotiation') {
                opp.StageName = 'Closed Won';
                opp.CloseDate = date.today();
                oppToClose = opp;
                break;
            }
        }
        update oppsMap.values();
        // If process that calls invocable class is in place and active, then clone should be triggered.  In case it's not,
        // call invocable class explicitly.
        OpportunityCloneInvocable.opportunityClone(
            new List<Id>{ oppToClose.Id }
        );
        Test.StopTest();

        // Get the opportunities (new and old) and validate.
        Map<Id, Opportunity> allOppsMap = new Map<Id, Opportunity>(
            [SELECT Id FROM Opportunity]
        );
        Validate(allOppsMap.keyset());
    }

    // Build two opportunities under an account.
    static void InitTestOpportunities() {
        ChartofAccounts__c objChartOfAccounts = new ChartofAccounts__c(
            Name = '#Unrestricted'
        );
        insert objChartOfAccounts;

        insert new Account(Name = 'opptest_acct_' + datetime.now());
        Account acc = [SELECT Id, Name FROM Account LIMIT 1];

        // Build opportunities linked to appropriate account.
        List<Opportunity> opps = new List<Opportunity>();
        // The first opp will be forced to close during the test.
        string fyForOppToBeClosed = Utilities.FYfromDate(Date.today());
        opps.add(
            new Opportunity(
                Name = fyForOppToBeClosed + ': Opp for ' + acc.Name,
                Type = 'Major Gift Opportunity: Annual Gift',
                StageName = 'Negotiation',
                CloseDate = Date.Today().addDays(-1),
                AccountId = acc.Id,
                Amount = 10,
                ChartofAccounts__c = objChartOfAccounts.Id
            )
        );
        // Second and third opps will stay open during the test.
        opps.add(
            new Opportunity(
                Name = fyForOppToBeClosed + ': Open opp #1 for ' + acc.Name,
                Type = 'Major Gift Opportunity: Annual Gift',
                StageName = 'Cultivation',
                CloseDate = Date.Today().addMonths(-2), // Closes in the past
                AccountId = acc.Id,
                Amount = 20,
                ChartofAccounts__c = objChartOfAccounts.Id
            )
        );
        opps.add(
            new Opportunity(
                Name = fyForOppToBeClosed + ': Open opp #2 for ' + acc.Name,
                Type = 'Major Gift Opportunity: Annual Gift',
                StageName = 'Cultivation',
                CloseDate = Date.Today().addDays(-2), // Closes in the future
                AccountId = acc.Id,
                Amount = 21,
                ChartofAccounts__c = objChartOfAccounts.Id
            )
        );
        system.debug('InitTestOpportunities: opps = ' + JSON.serialize(opps));
        if (opps.size() > 0)
            insert opps;
    }

    // Validate the new opportunities against the old opportunities (now closed).
    public static void Validate(Set<ID> oppsIds) {
        // Grab info from accounts and linked opportunities.
        Account acc = [
            SELECT
                Id,
                OwnerId,
                Name,
                (
                    SELECT Id, AccountId, CloseDate, StageName, Amount, Name
                    FROM Opportunities
                )
            FROM Account
            WHERE Id IN (SELECT AccountId FROM Opportunity WHERE Id IN :oppsIds)
            ORDER BY Name
        ];

        // Not doing Assert statements, instead just displaying account and its linked opps for eyeballing.
        system.debug('Account: ' + acc.Name);
        for (Opportunity o : acc.Opportunities) {
            system.debug(
                'Validate: Opportunity: ' +
                o.Name +
                '; Stage: ' +
                o.StageName +
                '; CloseDate: ' +
                o.CloseDate +
                '; Amount: ' +
                o.Amount
            );
        }
    }
}