force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template_macro__c/Template_macro__c.object-meta.xml
<CustomObject>
    <description>Contains a macro used when instantiating a template - the macro computes the name of a template piece using fields in the context of a letter record.</description>
    <label>Template macro</label>
    <nameField>
        <label>Template macro Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template macros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_macro__c/fields/Macro_text__c.field-meta.xml
<CustomField>
    <fullName>Macro_text__c</fullName>
    <description>The text of this template macro</description>
    <inlineHelpText>The text of this template macro</inlineHelpText>
    <label>Macro text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_macro__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template parent of this template macro. If blank, then the macro is &quot;generic&quot;.</description>
    <inlineHelpText>The template parent of this template macro. If blank, then the macro is &quot;generic&quot;.</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template macros</relationshipLabel>
    <relationshipName>Template_macros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TemplateControllerTest.cls
@isTest
public class TemplateControllerTest {
    // Test of TemplateMacros class
    static testMethod void TemplateControllerTest1() {
        // Build new accounts, template macros, templates
        BuildTestProposals.InitTestObjects(2, 2);
        insert new Template__c(Name = 'test template', Type__c = 'Grantmaking');
        Template__c t = [SELECT Id FROM Template__c LIMIT 1];
        insert new Template_macro__c(
            Template__c = t.Id,
            Name = 'TRUE MACRO',
            Macro_text__c = 'true'
        );
        insert new Template_macro__c( // Evals to non-null in this test.
            Template__c = t.Id,
            Name = 'ACCOUNT NAME',
            Macro_text__c = 'Account__c.Name'
        );
        insert new Template_macro__c( // Includes test of embedded macro call.
            Template__c = t.Id,
            Name = 'TEST MACRO',
            Macro_text__c = 'if(RIGHT([[ACCOUNT NAME]], 1) == "0" && [[TRUE MACRO]], "0th account: " & [[ACCOUNT NAME]], "1th account " & [[ACCOUNT NAME]])'
        );
        insert new Template_macro__c( // Should eval to blank, and not try to eval the DATEVALUE call.
            Template__c = t.Id,
            Name = 'TEST IF',
            Macro_text__c = 'IF(ISBLANK(Account__c.Site), "", CONCATENATE(" (", DATEVALUE(Account__c.LastModifiedDate), ")"))'
        );
        insert new Template_macro__c(
            Template__c = t.Id,
            Name = 'TEST FLOOR',
            Macro_text__c = 'TEXT(FLOOR(15.5))'
        );
        insert new Template_macro__c(
            Template__c = t.Id,
            Name = 'Macro with unknown field',
            Macro_text__c = 'abcdefg'
        );

        Test.StartTest();
        Proposal__c[] props = [
            SELECT Id, Account__r.Name, Account__r.Site
            FROM Proposal__c
        ];
        TemplateController.TemplateMacros tm = new TemplateController.TemplateMacros(
            t.Id
        );
        system.assertEquals(2, props.size());
        tm.initialize(props[0]);
        system.assert(
            ((String) tm.evaluate('TEST MACRO')).contains('0th account')
        );
        system.assertEquals('', (String) tm.evaluate('TEST IF'));
        system.assertEquals('15', (String) tm.evaluate('TEST FLOOR'));
        tm.initialize(props[1]);
        system.assert(
            ((String) tm.evaluate('TEST MACRO')).contains('1th account')
        );
        Test.StopTest();
    }
}