force-app/main/default/objects/GFW_Sync_Object_Mapping__mdt/GFW_Sync_Object_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Used for GFW Sync to map GFW object to FSDB object.</description>
    <label>GFW Sync Object Mapping</label>
    <pluralLabel>GFW Sync Object Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/GFW_Sync_Object_Mapping__mdt/fields/SyncLogRecordLookupFieldName__c.field-meta.xml
<CustomField>
    <fullName>SyncLogRecordLookupFieldName__c</fullName>
    <description>Name in Sync Log Record of lookup field to FSDB Object.</description>
    <label>SyncLogRecordLookupFieldName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/Sync_Log_Record__c.object-meta.xml
<CustomObject>
    <label>Sync Log Record</label>
    <nameField>
        <displayFormat>SLR-{0000}</displayFormat>
        <label>Sync Log Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Log Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Log_Record__c/fields/Results__c.field-meta.xml
<CustomField>
    <fullName>Results__c</fullName>
    <description>Outcome: error message or id of newly created record.</description>
    <label>Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sync_Log_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of sync log record: Pending, Success or Error</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Sync_LogRecords.cls
public class Sync_LogRecords {
    // Performs callouts to GFW and stashes json results in Sync Log Records

    // Class variables set in start method and used in execute
    // Database.Stateful allows instance member variables to retain their values between transactions. 

    List<String> coaNames;
    /*
    GFW_Sync_Object_Mapping__mdt objMap;
    String mdtObjName;
    Schema.SObjectField extIdFieldReference;
    */

    public Sync_BatchableLog(List<String> strListParam) {
        coaNames = strListParam;
        system.debug('parameter: ' + coaNames);
    }

    public Iterable<sObject> start(Database.BatchableContext bc) {
        // Instantiates new SyncController to build records of type mdtObjName
        // Returns records to execute method for upserting
        
        
        
        /*List<sObject> recs;
        if (mdtObjNames.size() > 0) {
            System.debug('Batch START top mdtObjNames: ' + mdtObjNames);
            mdtObjName = mdtObjNames.remove(0);
            SyncController scThisFS = new SyncController();
            recs = new List<sObject>(scThisFS.buildRecsToUpsert(mdtObjName));
            extIdFieldReference = scThisFS.extIdFieldReference;
            // syncLogRecIds = scThisFS.syncLogRecIds;
            objMap = scThisFS.getObjectMapping(mdtObjName);
            system.debug('Batch START this mdtObjName: ' + mdtObjName);
            System.debug('Batch START bottom mdtObjNames: ' + mdtObjNames);
        }
        return recs; 
        */
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> recs) {
        String resultMsg;
        String status;
        Id slRecId;
        List<Sync_Log_Record__c> upSLRs = new List<Sync_Log_Record__c>();
        String slrLookupFieldName;
        // Loop through results to update Sync Log Records.
        if (recs != null && recs.size() > 0) {
            slrLookupFieldName = objMap.SyncLogRecordLookupFieldName__c;
            Database.UpsertResult[] upsResults = Database.upsert( recs, extIdFieldReference, false);
            System.debug('upsResults: ' + upsResults);
            // Upsert results are in the same order as original list of records. 
            for(Integer index = 0, size = upsResults.size(); index < size; index++) {
                Sync_Log_Record__c slrecUpdate = new Sync_Log_Record__c();
                slrecUpdate.Id = (Id)recs[index].get('Sync_Log_Record__c');
                if(upsResults[index].isSuccess()) {
                    status = 'Success';
                    resultMsg = upsResults[index].isCreated() ? 
                        (String)upsResults[index].getid() + ' was created' : 
                        (String)upsResults[index].getid() + ' was updated';
                    slrecUpdate.put(slrLookupFieldName, upsResults[index].getid());
                } else {
                    status = 'Error';
                    resultMsg = String.join(upsResults[index].getErrors(), ';');
                }
                slrecUpdate.Status__c = status;
                slrecUpdate.Results__c = resultMsg;
                upSLRs.add(slrecUpdate);
            }
            if (upSLRs != null && !upSLRs.IsEmpty()) {
                update upSLRs;
            }
        }
    }

    public void finish(Database.BatchableContext bc) {
        // Cycle thru list and check for empty - do nothing. Otherwise we're in a loop!
        system.debug('Batch FINISH before if');
        if (mdtObjNames.size() > 0) {
            system.debug('Batch FINISH inside if. mdtObjNames: ' + mdtObjNames);
            Id batchInstanceId = Database.executeBatch(new Sync_BatchableUpsert(mdtObjNames), 15);
            System.debug('batchInstanceId: ' + batchInstanceId);
        }
    }

    
}