force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>A picklist of the highest level categorization of this contact. The category can be further described in the Secondary Type field.</inlineHelpText>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Friend</fullName>
                <default>true</default>
                <label>Friend</label>
            </value>
            <value>
                <fullName>Corporate Contact</fullName>
            </value>
            <value>
                <fullName>Alumnus</fullName>
            </value>
            <value>
                <fullName>Institutional Proxy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_Dev.recordType-meta.xml
<RecordType>
    <fullName>Contact_Dev</fullName>
    <active>true</active>
    <description>Record type for Dev&apos;s contact records (including individual donors and prospects)</description>
    <label>Contact Dev</label>
</RecordType>

force-app/main/default/objects/Custom_Reqs__c/Custom_Reqs__c.object-meta.xml
<CustomObject>
    <description>Represents the custom requirements imposed by restricted funds that apply to the linked proposals</description>
    <label>Custom Reqs</label>
    <nameField>
        <label>Custom Reqs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Reqs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Reqs__c/fields/Short_name__c.field-meta.xml
<CustomField>
    <fullName>Short_name__c</fullName>
    <description>Shorthand version of reporting req&apos;s name</description>
    <inlineHelpText>Shorthand version of reporting req&apos;s name</inlineHelpText>
    <label>Short name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <description>Each letter record contains the text of a letter to be either emailed or printed and sent.  Letters are used in cases where the individual pieces of correspondence need to be tracked in SalesForce.</description>
    <label>Letter</label>
    <nameField>
        <displayFormat>LET-{0000000}</displayFormat>
        <label>Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this letter</description>
    <inlineHelpText>The account associated with this letter</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs (if any) linked to the proposal/grant behind this letter</description>
    <inlineHelpText>The custom reqs (if any) linked to the proposal/grant behind this letter</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Date_emailed__c.field-meta.xml
<CustomField>
    <fullName>Date_emailed__c</fullName>
    <description>Date on which this letter was emailed</description>
    <inlineHelpText>Date on which this letter was emailed</inlineHelpText>
    <label>Date emailed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Page_1__c.field-meta.xml
<CustomField>
    <fullName>Page_1__c</fullName>
    <description>First page of letter, or the complete text if emailed</description>
    <inlineHelpText>First page of letter, or the complete text if emailed</inlineHelpText>
    <label>Page 1</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this letter</description>
    <inlineHelpText>The proposal linked to this letter</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template on which this letter is based</description>
    <inlineHelpText>The template on which this letter is based</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Contract_signer_2__c.field-meta.xml
<CustomField>
    <fullName>Contract_signer_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact linked to this proposal&apos;s account who is the second designated contract signer (usually blank as most contracts have only one signer)</description>
    <inlineHelpText>The contact linked to this proposal&apos;s account who is the second designated contract signer (usually blank as most contracts have only one signer)</inlineHelpText>
    <label>Contract signer 2</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The contract signer&apos;s account must be the same as this proposal&apos;s account</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>The contract signer&apos;s account must be the same as this proposal&apos;s account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals (Contract signer 2)</relationshipLabel>
    <relationshipName>Proposals5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Contract_signer__c.field-meta.xml
<CustomField>
    <fullName>Contract_signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact linked to this proposal&apos;s account who is the designated contract signer</description>
    <inlineHelpText>The contact linked to this proposal&apos;s account who is the designated contract signer</inlineHelpText>
    <label>Contract signer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The contract signer&apos;s account must be the same as this proposal&apos;s account</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>The contract signer&apos;s account must be the same as this proposal&apos;s account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals (Contract signer 1)</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs for this proposal (if any)</description>
    <inlineHelpText>The custom reqs for this proposal (if any)</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>Template is composed of template pieces which are conditionally composed to instantiate the template (usually as a letter).</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Source_object__c.field-meta.xml
<CustomField>
    <fullName>Source_object__c</fullName>
    <description>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</description>
    <inlineHelpText>The name of the SalesForce object for this correspondence template.  Letters based on this template should be linked to records of this object. For example, the Final Report Reminder letter template should have Milestone__c as Source Object.</inlineHelpText>
    <label>Source object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>GM_Data__c</fullName>
            </value>
            <value>
                <fullName>Milestone__c</fullName>
            </value>
            <value>
                <fullName>Invite__c</fullName>
            </value>
            <value>
                <fullName>Payment__c</fullName>
            </value>
            <value>
                <fullName>Payment_Method__c</fullName>
            </value>
            <value>
                <fullName>Profile__c</fullName>
            </value>
            <value>
                <fullName>Proposal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of this template (for example, Development, Grantmaking, etc.)</description>
    <inlineHelpText>The type of this template (for example, Development, Grantmaking, etc.)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Grantmaking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template_macro__c/Template_macro__c.object-meta.xml
<CustomObject>
    <description>Contains a macro used when instantiating a template - the macro computes the name of a template piece using fields in the context of a letter record.</description>
    <label>Template macro</label>
    <nameField>
        <label>Template macro Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template macros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_macro__c/fields/Macro_text__c.field-meta.xml
<CustomField>
    <fullName>Macro_text__c</fullName>
    <description>The text of this template macro</description>
    <inlineHelpText>The text of this template macro</inlineHelpText>
    <label>Macro text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_macro__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template parent of this template macro. If blank, then the macro is &quot;generic&quot;.</description>
    <inlineHelpText>The template parent of this template macro. If blank, then the macro is &quot;generic&quot;.</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template macros</relationshipLabel>
    <relationshipName>Template_macros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_piece__c/Template_piece__c.object-meta.xml
<CustomObject>
    <description>Contains a piece of text used to instantiate a template.</description>
    <label>Template piece</label>
    <nameField>
        <label>Template piece</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template pieces</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_piece__c/fields/Custom_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reqs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The custom reqs to which this template piece is assigned</description>
    <inlineHelpText>The custom reqs to which this template piece is assigned</inlineHelpText>
    <label>Custom Reqs</label>
    <referenceTo>Custom_Reqs__c</referenceTo>
    <relationshipLabel>Template pieces</relationshipLabel>
    <relationshipName>Template_pieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_piece__c/fields/Piece_text__c.field-meta.xml
<CustomField>
    <fullName>Piece_text__c</fullName>
    <description>The text of this template piece</description>
    <inlineHelpText>The text of this template piece</inlineHelpText>
    <label>Piece text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_piece__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The template parent of this template piece (blank if this is a generic template piece)</description>
    <inlineHelpText>The template parent of this template piece (blank if this is a generic template piece)</inlineHelpText>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template pieces</relationshipLabel>
    <relationshipName>Template_pieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LetterControllerTest.cls
@isTest
public class LetterControllerTest {
    /*
     * Test of LetterReset class
     */

    static testMethod void LetterResetTest1() {
        // Build new accounts, letters, template pieces, template macros, templates
        InitTestRecords1(3);
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id FROM Letter__c]
        );

        Test.StartTest();
        LetterReset lr = new LetterReset();
        lr.resetLettersHandler(lMap.keySet());
        Test.StopTest();

        validate1(lMap.keySet());
    }

    // Build sample accounts, letters, template pieces, template macros, templates
    static void initTestRecords1(Integer NumberOfRecords) {
        insert new Template__c(Name = 'TY General', Type__c = 'Development');
        Id tId = [SELECT Id FROM Template__c LIMIT 1].Id;
        insert new Custom_Reqs__c(
            Name = 'Test reporting reqs',
            Short_name__c = 'Test'
        );
        Id iId = [SELECT Id FROM Custom_Reqs__c LIMIT 1].Id;
        insert new Template_macro__c(
            Template__c = tId,
            Name = 'TRUE MACRO',
            Macro_text__c = 'true'
        );
        insert new Template_macro__c( // Evals to non-null in this test.
            Template__c = tId,
            Name = 'DESCRIPTION',
            Macro_text__c = 'Account.Description'
        );
        insert new Template_macro__c( // Includes test of embedded macro call.
            Template__c = tId,
            Name = 'TEST MACRO',
            Macro_text__c = 'if([[DESCRIPTION]] == "0" && [[TRUE MACRO]], "{{Test piece EVEN}}", "{{Test piece ODD}}")'
        );
        insert new Template_macro__c( // Should eval to blank, and not try to eval the DATEVALUE call.
            Template__c = tId,
            Name = 'TEST IF',
            Macro_text__c = 'IF(ISBLANK(Account.Site), "", CONCATENATE(" (", DATEVALUE(Account.LastModifiedDate), ")"))'
        );
        insert new Template_macro__c(
            Template__c = tId,
            Name = 'TEST FLOOR',
            Macro_text__c = 'TEXT(FLOOR(15.5))'
        );
        insert new Template_piece__c(
            Template__c = tId,
            Name = 'PAGE 1',
            Piece_text__c = '{{Test empty piece}}{{Test generic}} [[TEST MACRO]]'
        );
        insert new Template_piece__c(
            Template__c = null,
            Name = 'Test empty piece',
            Piece_text__c = ''
        );
        insert new Template_piece__c(
            Template__c = null,
            Name = 'Test generic',
            Piece_text__c = 'Letter body'
        );
        insert new Template_piece__c(
            Template__c = null,
            Custom_Reqs__c = iId,
            Name = 'Test generic',
            Piece_text__c = 'Letter body'
        );
        insert new Template_piece__c(
            Template__c = tId,
            Custom_Reqs__c = iId,
            Name = 'Test piece EVEN',
            Piece_text__c = 'EVEN (reporting reqs) for account = <<Account.Name>>[[TEST IF]]'
        );
        insert new Template_piece__c(
            Template__c = tId,
            Name = 'Test piece ODD',
            Piece_text__c = 'ODD for account = <<Account.Name>> [[TEST FLOOR]]'
        );
        List<Account> accts = new List<Account>();
        for (Integer x = 0; x < NumberOfRecords; x++)
            accts.add(
                new Account(
                    Name = 'LetterTest_' + String.valueOf(x),
                    // Record type Household is currently (10/8/20) hidden for FFDB
                    RecordTypeId = Utilities.getRecTypeId(
                        'Account',
                        'Organization' // 'Household'
                    ),
                    Description = String.valueOf(Math.mod(x, 2))
                )
            );
        insert accts;
        List<Letter__c> lets = new List<Letter__c>();
        for (Integer x = 0; x < NumberOfRecords; x++)
            lets.add(
                new Letter__c(
                    Account__c = accts[x].Id,
                    Template__c = tId,
                    Custom_Reqs__c = (Math.mod(x, 2) == 0) ? iId : null
                )
            );
        insert lets;
    }

    // Test the error checking code.
    static testMethod void LetterResetTest2() {
        // Build new account, letter, template piece, template macro, template
        InitTestRecords2(1);
        Letter__c let = [SELECT Id FROM Letter__c LIMIT 1];
        Template_piece__c tp = [
            SELECT Id, Piece_text__c
            FROM Template_piece__c
            LIMIT 1
        ];
        Template_macro__c tm = [
            SELECT Id, Macro_text__c
            FROM Template_macro__c
            LIMIT 1
        ];

        Test.StartTest();
        // Test a bunch of different errors.
        // Unknown field in PAGE 1 template piece.
        testResetLetter(let.Id);
        // Empty field in PAGE 1 template piece.
        tp.Piece_text__c = '<<>>';
        update tp;
        testResetLetter(let.Id);
        // Unknown macro call in PAGE 1 template piece.
        tp.Piece_text__c = '[[UnknownMacro]]';
        update tp;
        testResetLetter(let.Id);
        // Unknown piece in template macro.
        tp.Piece_text__c = '[[Testing macro]]';
        update tp;
        testResetLetter(let.Id);
        // Unknown field name in template macro.
        tm.Macro_text__c = 'UnknownField';
        update tm;
        testResetLetter(let.Id);
        // Recursive call in template macro.
        tm.Macro_text__c = '[[Testing macro]]';
        update tm;
        testResetLetter(let.Id);
        Test.StopTest();
    }

    // Reset given letter in try/catch with debugging statements.
    static void testResetLetter(Id letId) {
        try {
            LetterReset lr = new LetterReset();
            lr.resetLettersHandler(new Set<Id>{ letId });
        } catch (exception e) {
            system.debug('testResetLetter: exception = ' + e);
        }
        Letter__c let = [SELECT Id, Page_1__c FROM Letter__c WHERE Id = :letId];
        system.debug('testResetLetter: Page_1__c = ' + let.Page_1__c);
    }

    // Build sample accounts, letters, template pieces, template macros, templates
    static void initTestRecords2(Integer NumberOfRecords) {
        insert new Template__c(Name = 'TY General', Type__c = 'Development');
        Id tId = [SELECT Id FROM Template__c LIMIT 1].Id;
        insert new Custom_Reqs__c(
            Name = 'Test reporting reqs',
            Short_name__c = 'Test'
        );
        Id iId = [SELECT Id FROM Custom_Reqs__c LIMIT 1].Id;
        insert new Template_macro__c(
            Template__c = tId,
            Name = 'Testing macro',
            Macro_text__c = '"{{UnknownPiece}}"'
        );
        insert new Template_piece__c(
            Template__c = tId,
            Name = 'PAGE 1',
            Piece_text__c = '<<UnknownField>>'
        );
        List<Account> accts = new List<Account>();
        for (Integer x = 0; x < NumberOfRecords; x++)
            accts.add(
                new Account(
                    Name = 'LetterTest_' + String.valueOf(x),
                    // Record type Household is currently (10/8/20) hidden for FFDB
                    RecordTypeId = Utilities.getRecTypeId(
                        'Account',
                        'Organization' // 'Household'
                    ),
                    Description = String.valueOf(Math.mod(x, 2))
                )
            );
        insert accts;
        List<Letter__c> lets = new List<Letter__c>();
        for (Integer x = 0; x < NumberOfRecords; x++)
            lets.add(
                new Letter__c(
                    Account__c = accts[x].Id,
                    Template__c = tId,
                    Custom_Reqs__c = (Math.mod(x, 2) == 0) ? iId : null
                )
            );
        insert lets;
    }

    static void validate1(Set<ID> lIds) {
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [
                SELECT Account__r.Name, Account__r.Description, Page_1__c
                FROM Letter__c
                WHERE Id IN :lIds
            ]
        );

        // "Even" accounts need to have "even" letter bodies, and likewise for "odd" accounts.
        // The "even" ones should get the reporting reqs-based piece.
        for (Letter__c l : lMap.values()) {
            if (l.Account__r.Description == '0') {
                system.assertEquals(
                    'Letter body EVEN (reporting reqs) for account = ' +
                    l.Account__r.Name,
                    l.Page_1__c
                );
            } else {
                system.assertEquals(
                    'Letter body ODD for account = ' +
                    l.Account__r.Name +
                    ' 15',
                    l.Page_1__c
                );
            }
        }
    }

    // Test batch process - no problems (that is, none unprocessed because of non-blank date sent).
    static testMethod void LetterControllerTestBatch1() {
        Map<Id, Letter__c> letMap = initTestLetters(1);
        Test.StartTest();
        // Run the batch reset process.
        Database.executeBatch(
            new LetterResetBatch(letMap.keySet(), false),
            LetterController.resetBatchSize
        );
        Test.StopTest();
    }

    // Test batch process - one problem (that is, one unprocessed because of non-blank date sent).
    static testMethod void LetterControllerTestBatch2() {
        Map<Id, Letter__c> letMap = initTestLetters(2);
        Test.StartTest();
        // Set date emailed to cause a problem for reset.
        letMap.values()[0].Date_emailed__c = Date.today();
        update letMap.values();
        // Run the batch reset process.
        Database.executeBatch(
            new LetterResetBatch(letMap.keySet(), false),
            LetterController.resetBatchSize
        );
        Test.StopTest();
    }

    // Test batch process - two problems (that is, both letters unprocessed because of non-blank date sent).
    static testMethod void LetterControllerTestBatch3() {
        Map<Id, Letter__c> letMap = initTestLetters(2);
        Test.StartTest();
        // Set date emailed to cause a problem for reset.
        letMap.values()[0].Date_emailed__c = Date.today();
        letMap.values()[1].Date_emailed__c = Date.today();
        update letMap.values();
        // Run the batch reset process.
        Database.executeBatch(
            new LetterResetBatch(letMap.keySet(), false),
            LetterController.resetBatchSize
        );
        Test.StopTest();
    }

    // Test print process.
    static testMethod void LetterControllerTestPrint() {
        Map<Id, Letter__c> letMap = initTestLetters(2);
        // Build new standard set controller for the letters.
        ApexPages.StandardSetController ssct = new ApexPages.StandardSetController(
            letMap.values()
        );
        ssct.setSelected(letMap.values());
        LetterController lc1 = new LetterController(ssct);
        // Build standard controller for a single letter
        ApexPages.StandardController sct = new ApexPages.StandardController(
            letMap.values()[0]
        );
        LetterController lc2 = new LetterController(sct);
        Test.StartTest();
        lc1.printLetters();
        lc2.printLetters();
        // Invocations for code coverage
        lc1.resetLetters();
        lc1.emailLetters();
        lc1.doCancel();
        lc2.doCancel();
        Test.StopTest();
    }

    // Build a test letter for proposal contract letter.
    static Map<Id, Letter__c> initTestLetters(Integer numRecords) {
        // Build new accounts, letters, template pieces, template macros, templates
        insert new Account(
            Name = 'LetterTest',
            // Record type Household is currently (10/8/20) hidden for FFDB
            RecordTypeId = Utilities.getRecTypeId(
                'Account',
                'Organization' // 'Household'
            )
        );
        Id acc1Id = [SELECT Id FROM Account LIMIT 1].Id;
        insert new Contact(
            AccountId = acc1Id,
            LastName = 'Smith',
            Email = 'abc@def.org',
            RecordTypeId = Utilities.getRecTypeId('Contact', 'Contact_Dev')
        );
        Id ct1Id = [SELECT Id FROM Contact LIMIT 1].Id;
        for (Integer x = 0; x < numRecords; x++) {
            insert new Proposal__c(
                Account__c = acc1Id,
                Contract_signer__c = ct1Id,
                Contract_signer_2__c = ct1Id
            );
        }
        insert new Template__c(
            Name = 'Contract letter & cover',
            Type__c = 'Grantmaking',
            Source_object__c = 'Proposal__c'
        );
        Map<Id, Proposal__c> pMap = new Map<Id, Proposal__c>(
            [SELECT Id FROM Proposal__c]
        );
        // Build new standard set controller and build letters for the new proposals.
        ApexPages.StandardSetController ssct = new ApexPages.StandardSetController(
            pMap.values()
        );
        ssct.setSelected(pMap.values());
        ProposalController pc = new ProposalController(ssct);
        pc.selectedTemplate = 'Contract letter & cover';
        pc.buildLetters();
        Map<Id, Letter__c> lMap = new Map<Id, Letter__c>(
            [SELECT Id, Proposal__c FROM Letter__c]
        );
        return lMap;
    }

    // Test code to update date field in related record.
    static testMethod void LetterControllerTest2() {
        BuildTestProposals.InitTestObjects(1, 1);
        Proposal__c p = [SELECT Id FROM Proposal__c LIMIT 1];
        insert new Template__c(
            Name = 'Decline letter',
            Type__c = 'Grantmaking',
            Date_sent_recd_object_name__c = 'Proposal__c',
            Date_sent_recd_field_name__c = 'Date_declined__c'
        );
        Template__c t = [SELECT Id FROM Template__c LIMIT 1];
        Date d = Date.today();
        insert new Letter__c(
            Template__c = t.Id,
            Proposal__c = p.Id,
            Date_emailed__c = d
        );
        Letter__c l = [SELECT Id FROM Letter__c LIMIT 1];

        Test.startTest();
        LetterUpdatedInvocable.letterUpdated(new List<Id>{ l.Id });
        Test.stopTest();

        p = [SELECT Id, Date_declined__c FROM Proposal__c LIMIT 1];
        system.assertEquals(d, p.Date_declined__c);
    }
}