force-app/main/default/objects/Decline_reason__c/Decline_reason__c.object-meta.xml
<CustomObject>
    <description>Official reasons for decline</description>
    <label>Decline reason</label>
    <nameField>
        <label>Decline reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decline reasons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Decline_reason__c.field-meta.xml
<CustomField>
    <fullName>Decline_reason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reason that this profile is ineligible (restricted to one of the type 1 declines)</description>
    <inlineHelpText>Reason that this profile is ineligible (restricted to one of the type 1 declines)</inlineHelpText>
    <label>Not-eligible reason</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>May only select active decline reasons that are appropriate for profile declines.</errorMessage>
        <filterItems>
            <field>Decline_reason__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Decline_reason__c.For_profile__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>May only select active decline reasons that are appropriate for profile declines.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Decline_reason__c</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProfileCloneBatch.cls
global class ProfileCloneBatch implements Database.Batchable<sObject>, Database.Stateful {
    global final String query;
    global final List<Id> profileIds;
    global Map<Id, Profile__c> pCloneMap = new Map<Id, Profile__c>();

    global ProfileCloneBatch(String q) {
        system.debug('ProfileCloneBatch create: q = ' + q);
        query = q;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('ProfileCloneBatch start: query = ' + query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        system.debug(
            'ProfileCloneBatch execute: scope = ' + JSON.serialize(scope)
        );
        Map<Id, Profile__c> pMap = new Map<Id, Profile__c>(
            (List<Profile__c>) scope
        );
        // Clone profiles and gather results.
        // Note that we're cloning one profile at a time, so keep the batch size small.
        for (Profile__c p : pMap.values()) {
            system.debug('ProfileCloneBatch execute in loop: p.Id = ' + p.Id);
            Profile__c pClone = ProfileController.profileDeepClone(p.Id);
            // Don't send notification email if the original profile was ineligible, that is, had a type 1 decline reason.
            Boolean ineligible =
                p.Decline_reason__c != null &&
                p.Decline_reason__r.Name.startsWith('1');
            if (pClone != null && !ineligible)
                pCloneMap.put(pClone.Id, pClone);
        }
    }

    global void finish(Database.BatchableContext BC) {
        AsyncApexJob a = [
            SELECT
                Id,
                Status,
                NumberOfErrors,
                JobItemsProcessed,
                TotalJobItems,
                CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :BC.getJobId()
        ];
        system.debug('ProfileCloneBatch finish: a = ' + JSON.serialize(a));
        // Send error email if there were errors.
        if (a.NumberOfErrors > 0)
            Utilities.BatchErrorEmail('ProfileCloneBatch', a);
        else
            // Send notification emails to group.
            ProfileController.sendCloneNotificationEmails(pCloneMap.keySet());
    }
}