force-app/main/default/objects/Decline_reason__c/Decline_reason__c.object-meta.xml
<CustomObject>
    <description>Official reasons for decline</description>
    <label>Decline reason</label>
    <nameField>
        <label>Decline reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decline reasons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Decline_reason__c.field-meta.xml
<CustomField>
    <fullName>Decline_reason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reason that this profile is ineligible (restricted to one of the type 1 declines)</description>
    <inlineHelpText>Reason that this profile is ineligible (restricted to one of the type 1 declines)</inlineHelpText>
    <label>Not-eligible reason</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>May only select active decline reasons that are appropriate for profile declines.</errorMessage>
        <filterItems>
            <field>Decline_reason__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Decline_reason__c.For_profile__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>May only select active decline reasons that are appropriate for profile declines.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Decline_reason__c</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Date on which this profile will &quot;expire&quot;, at which point the applicant needs to complete a new one</description>
    <inlineHelpText>Date on which this profile will &quot;expire&quot;, at which point the applicant needs to complete a new one</inlineHelpText>
    <label>Expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/Next_profile__c.field-meta.xml
<CustomField>
    <fullName>Next_profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The subsequent profile, created after this one expires</description>
    <inlineHelpText>The subsequent profile, created after this one expires</inlineHelpText>
    <label>Next profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Prior profile</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProfileCloneSchedule.cls
/*
 * Clone profiles that have reached their expiration dates.
 * Schedule using Schedule button in setup.
 */
global with sharing class ProfileCloneSchedule implements Schedulable {
    global void execute(SchedulableContext scMain) {
        // Build a query that searches for profiles with expiration dates today or earlier.
        // Require that they haven't already been cloned (Next Profile field is blank).
        Integer batchSize = 1;
        String q =
            'SELECT Id, Decline_reason__c, Decline_reason__r.Name FROM Profile__c ' +
            ' WHERE Expiration_date__c <> null ' +
            ' AND Expiration_date__c <= TODAY ' +
            ' AND Next_profile__c = null';
        system.debug('ProfileCloneSchedule execute: q = ' + q);
        Database.executeBatch(new ProfileCloneBatch(q), batchSize);
    }
}