force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Assignment__c/Portfolio_Assignment__c.object-meta.xml
<CustomObject>
    <description>An assignment of one proposal to one portfolio</description>
    <label>Portfolio Assignment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Portfolio Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Assignment__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <description>Portfolio to which this &quot;join&quot; assignment record is assigned</description>
    <inlineHelpText>Portfolio to which this &quot;join&quot; assignment record is assigned</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Portfolio Assignments</relationshipLabel>
    <relationshipName>Portfolio_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Portfolio_Assignment__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>Proposal to which this &quot;join&quot; assignment record is assigned</description>
    <inlineHelpText>Proposal to which this &quot;join&quot; assignment record is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Portfolio Assignments</relationshipLabel>
    <relationshipName>Initiative_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account record representing the Organization that submitted this proposal/grant</description>
    <inlineHelpText>Account record representing the Organization that submitted this proposal/grant</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Amount_awarded__c.field-meta.xml
<CustomField>
    <fullName>Amount_awarded__c</fullName>
    <description>Actual amount awarded to the group (possibly over multiple payments)</description>
    <inlineHelpText>Actual amount awarded to the group (possibly over multiple payments)</inlineHelpText>
    <label>Amount awarded</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Date_awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_awarded__c</fullName>
    <description>Date on which the proposal becomes a grant</description>
    <inlineHelpText>Date on which the proposal becomes a grant</inlineHelpText>
    <label>Date awarded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Status_numeric__c.field-meta.xml
<CustomField>
    <fullName>Status_numeric__c</fullName>
    <description>A numeric version of this proposal&apos;s status, suitable for sorting</description>
    <formula>VALUE( LEFT( Status__c, FIND(&quot; &quot;, Status__c) - 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A numeric version of this proposal&apos;s status, suitable for sorting</inlineHelpText>
    <label>Status numeric</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PortfolioController.cls
public with sharing class PortfolioController {
    /**********************************
     * For use in Lightning components
     *********************************/

    @AuraEnabled
    public static Portfolio__c[] getPortfolios() {
        String objName = 'Portfolio__c';
        String[] fieldNames = Utilities.fieldNamesForObject(objName);
        String q =
            'SELECT ' +
            String.join(fieldNames, ', ') +
            ' FROM ' +
            objName;
        return Database.query(q);
    }

    @AuraEnabled
    public static Portfolio__c getPortfolio(Id recordId) {
        String objName = 'Portfolio__c';
        String[] fieldNames = Utilities.fieldNamesForObject(objName);
        String q =
            'SELECT ' +
            String.join(fieldNames, ', ') +
            ' FROM ' +
            objName +
            ' WHERE Id = : recordId';
        system.debug('apex get method for ' + objName + ': q = ' + q);
        return Database.query(q);
    }

    @AuraEnabled
    public static Proposal__c[] getPropsForPortfolio(Id portfolioId) {
        // Fetch proposals that are linked from the join records for the given portfolio.
        return [
            SELECT
                Id,
                Name,
                Account__c,
                Account__r.Name,
                Status_numeric__c,
                Amount_awarded__c,
                Date_awarded__c
            FROM Proposal__c
            WHERE
                Id IN (
                    SELECT Proposal__c
                    FROM Portfolio_Assignment__c
                    WHERE Portfolio__c = :portfolioId
                )
        ];
    }

    @AuraEnabled
    public static Portfolio__c savePortfolio(Portfolio__c record) {
        update record;
        return record;
    }
}