force-app/main/default/objects/Application_Setting__mdt/Application_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata object to hold keys, values and settings.</description>
    <label>Application Setting</label>
    <pluralLabel>Application Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Application_Setting__mdt/fields/String_Value__c.field-meta.xml
<CustomField>
    <fullName>String_Value__c</fullName>
    <description>Text-based value</description>
    <label>String Value</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>Represents a classification option, either a population, strategy or issue.</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Assign__c/Classification_Assign__c.object-meta.xml
<CustomObject>
    <description>Assignment of a single classification to a proposal</description>
    <label>Classification Assign</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Classification Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification assigned to the proposal</description>
    <inlineHelpText>The classification assigned to the proposal</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Assign__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>The proposal to which the classification is assigned</description>
    <inlineHelpText>The proposal to which the classification is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Classification Assigns</relationshipLabel>
    <relationshipName>Classification_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/Classification_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a single classification to a profile</description>
    <label>Classification-Profile Assign</label>
    <nameField>
        <displayFormat>CA-Prof-{00000}</displayFormat>
        <label>Classification-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classification-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification linked from this join record</description>
    <inlineHelpText>The classification linked from this join record</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Classification-Profile Assigns</relationshipLabel>
    <relationshipName>Classification_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GM_Data__c/GM_Data__c.object-meta.xml
<CustomObject>
    <description>Contains grant-related data and indicators stemming from the group&apos;s grant application and their milestones</description>
    <label>GM Data</label>
    <nameField>
        <displayFormat>GMD-{0000000}</displayFormat>
        <label>GM Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GM Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GM_Data__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The portfolio (if any) providing the context for restricted and eligibility-related fields in this GM Data record</description>
    <inlineHelpText>The portfolio (if any) providing the context for restricted and eligibility-related fields in this GM Data record</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GM_Data__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile record, if any, to which this GM data is linked</description>
    <inlineHelpText>The profile record, if any, to which this GM data is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GM_Data__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The proposal linked to this GM data</description>
    <inlineHelpText>The proposal linked to this GM data</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>GM Data</relationshipLabel>
    <relationshipName>GM_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Indicator__c/Indicator__c.object-meta.xml
<CustomObject>
    <description>Represents an indicator for LEI grantmaking analysis</description>
    <label>Indicator</label>
    <nameField>
        <label>Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Assign__c/Indicator_Assign__c.object-meta.xml
<CustomObject>
    <description>Assignment of a single indicator to a GM Data record</description>
    <label>Indicator Assign</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Indicator Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Assign__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>The comment (if any) associated with this indicator assignment</description>
    <inlineHelpText>The comment (if any) associated with this indicator assignment</inlineHelpText>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Indicator_Assign__c/fields/GM_Data__c.field-meta.xml
<CustomField>
    <fullName>GM_Data__c</fullName>
    <description>The GM Data to which this indicator assign record is linked</description>
    <inlineHelpText>The GM Data to which this indicator assign record is linked</inlineHelpText>
    <label>GM Data</label>
    <referenceTo>GM_Data__c</referenceTo>
    <relationshipLabel>Indicator Assigns</relationshipLabel>
    <relationshipName>Indicator_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Indicator_Assign__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>The indicator to which this indicator assign record is linked</description>
    <inlineHelpText>The indicator to which this indicator assign record is linked</inlineHelpText>
    <label>Indicator</label>
    <referenceTo>Indicator__c</referenceTo>
    <relationshipLabel>Indicator Assigns</relationshipLabel>
    <relationshipName>Indicator_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Indicator_Assign__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>The quantity (if any) associated with this indicator assignment</description>
    <inlineHelpText>The quantity (if any) associated with this indicator assignment</inlineHelpText>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>A grouping or &quot;portfolio&quot; that represents the linked proposals</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Assignment__c/Portfolio_Assignment__c.object-meta.xml
<CustomObject>
    <description>An assignment of one proposal to one portfolio</description>
    <label>Portfolio Assignment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Portfolio Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Assignment__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <description>Portfolio to which this &quot;join&quot; assignment record is assigned</description>
    <inlineHelpText>Portfolio to which this &quot;join&quot; assignment record is assigned</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Portfolio Assignments</relationshipLabel>
    <relationshipName>Portfolio_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Portfolio_Assignment__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <description>Proposal to which this &quot;join&quot; assignment record is assigned</description>
    <inlineHelpText>Proposal to which this &quot;join&quot; assignment record is assigned</inlineHelpText>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Portfolio Assignments</relationshipLabel>
    <relationshipName>Initiative_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile_Assign__c/Portfolio_Profile_Assign__c.object-meta.xml
<CustomObject>
    <description>Represents the assignment of a portfolio to a profile</description>
    <label>Portfolio-Profile Assign</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Portfolio-Profile Assign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio-Profile Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Profile_Assign__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <description>The portfolio linked from this join record</description>
    <inlineHelpText>The portfolio linked from this join record</inlineHelpText>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Portfolio-Profile Assigns</relationshipLabel>
    <relationshipName>Portfolio_Profile_Assigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile_Assign__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>The profile linked from this join record</description>
    <inlineHelpText>The profile linked from this join record</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Portfolio-Profile Assigns</relationshipLabel>
    <relationshipName>Portfolio_Profile_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>Information about an organization gathered in advance of them submitting a proposal</description>
    <label>Profile</label>
    <nameField>
        <displayFormat>PROF-{YYYY}-{00000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Proposals hold tracking and classification information related to proposals submitted to GFW.  If the proposal is awarded, then the records also hold information related to the grant.</description>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PROP-{000000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/GM_Data__c.field-meta.xml
<CustomField>
    <fullName>GM_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the GM Data record holding information for this proposal/grant</description>
    <inlineHelpText>Link to the GM Data record holding information for this proposal/grant</inlineHelpText>
    <label>GM Data</label>
    <referenceTo>GM_Data__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The profile to which this proposal is linked</description>
    <inlineHelpText>The profile to which this proposal is linked</inlineHelpText>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReviewFormController.cls
public with sharing class ReviewFormController {
    
    @AuraEnabled //Do not cache
    public static String getInternalReview(String recordId) {
        InternalReview rev = new InternalReview(recordId);
        return JSON.serialize(rev);
    }    

    @AuraEnabled
    public static void updateNumber (String objectType, String objectId, String fieldName, Decimal value){

        try {
            sObject sObj = Schema.getGlobalDescribe().get(objectType).newSObject() ;
            sobj.Id = objectId;
            sobj.put(fieldName, value);
            update sobj;
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.updateNumber', 'Could not update field value, please refresh and try again.', e);
        }
    }
    
    @AuraEnabled
    public static void updateTextPickOrLookup(String objectType, String objectId, String fieldName, String value){

        try {
            sObject sObj = Schema.getGlobalDescribe().get(objectType).newSObject() ;
            sobj.Id = objectId;
            sobj.put(fieldName, value);
            update sobj;
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.updateTextPickOrLookup', 'Could not update field value, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static void updateBoolean(String objectType, String objectId, String fieldName, Boolean value){
        try {
            sObject sObj = Schema.getGlobalDescribe().get(objectType).newSObject() ;
            sobj.Id = objectId;
            sobj.put(fieldName, value);
            update sobj;
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.updateBoolean', 'Could not update field value, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static void addClassificationJoin(String objectName, String recordId, List < String > classificationIds){
        try {
            if (objectName=='Proposal') {
                List < Classification_Assign__c > newAssigns = new List < Classification_Assign__c >();
                for (String cId: classificationIds) {
                    Classification_Assign__c ca = new Classification_Assign__c(
                        Proposal__c = recordId,
                        Classification__c = cId
                    );
                    newAssigns.add(ca);
                }
                insert newAssigns;
            } else if (objectName=='Profile') {
                List < Classification_Profile_Assign__c > newAssigns = new List < Classification_Profile_Assign__c >();
                for (String cId: classificationIds) {
                    Classification_Profile_Assign__c ca = new Classification_Profile_Assign__c(
                        Profile__c = recordId,
                        Classification__c = cId
                    );
                    newAssigns.add(ca);
                }
                insert newAssigns;
            }
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.addClassificationJoin', 'Could not update classifications, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static void removeClassificationJoin(String objectName, String recordId, List < String > classificationIds){
        try {
            if (objectName=='Proposal') {
                List < Classification_Assign__c > cAssigns = [SELECT ID FROM Classification_Assign__c WHERE Proposal__c=:recordId AND Classification__c in:classificationIds];
                delete cAssigns;
            } else if (objectName=='Profile') {
                List < Classification_Profile_Assign__c > cAssigns = [SELECT ID FROM Classification_Profile_Assign__c WHERE Profile__c=:recordId AND Classification__c in:classificationIds];
                delete cAssigns;
            }
            
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.removeClassificationJoin', 'Could not remove classifications, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static void addPortfolioAssign(String objectName, String recordId, List < String > portfolioIds){
        try {
            if (objectName=='Proposal') {
                List < Portfolio_Assignment__c > newAssigns = new List < Portfolio_Assignment__c >();
                for (String pId: portfolioIds) {
                    Portfolio_Assignment__c pa = new Portfolio_Assignment__c(
                        Proposal__c = recordId,
                        Portfolio__c = pId
                    );
                    newAssigns.add(pa);
                }
                insert newAssigns;
            } else if (objectName=='Profile') {
                List < Portfolio_Profile_Assign__c > newAssigns = new List < Portfolio_Profile_Assign__c >();
                for (String pId: portfolioIds) {
                    Portfolio_Profile_Assign__c pa = new Portfolio_Profile_Assign__c(
                        Profile__c = recordId,
                        Portfolio__c = pId
                    );
                    newAssigns.add(pa);
                }
                insert newAssigns;
            }
            
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.addPortfolioAssign', 'Could not update portfolio assignments, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static void removePortfolioAssign(String objectName, String recordId, List < String > portfolioIds){
        try {
            if (objectName=='Proposal') {
                List < Portfolio_Assignment__c > pAssigns = [SELECT ID FROM Portfolio_Assignment__c WHERE Proposal__c=:recordId AND Portfolio__c in:portfolioIds];
                delete pAssigns;
            } else if (objectName=='Profile') {
                List < Portfolio_Profile_Assign__c > pAssigns = [SELECT ID FROM Portfolio_Profile_Assign__c WHERE Profile__c=:recordId AND Portfolio__c in:portfolioIds];
                delete pAssigns;
            }
            
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.removePortfolioAssign', 'Could not remove portfolio assignments, please refresh and try again.', e);
        }
    }
    
    @AuraEnabled
    public static void addIndicatorAssign (String gmDataId, String indicatorId, Integer quantity, String comments){
        try {
            Indicator_Assign__c indAssign = new Indicator_Assign__c (
                GM_Data__c = gmDataId,
                Indicator__c = indicatorId,
                Quantity__c = quantity,
                Comment__c = comments
            );
            insert indAssign;
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.addIndicatorAssign', 'Could not add indicator, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static void updateIndicatorComment (String gmDataId, String indicatorId, String comment){
        try {
            Indicator_Assign__c indicator = [SELECT ID, GM_Data__c, Indicator__c, Comment__c FROM Indicator_Assign__c WHERE GM_Data__c=:gmDataId AND Indicator__c=:indicatorId LIMIT 1];
            indicator.Comment__c = comment;
            update indicator;
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.addIndicatorAssign', 'Could not update indicator, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static void updateIndicatorQuantity (String gmDataId, String indicatorId, Integer quantity){
        try {
            Indicator_Assign__c indicator = [SELECT ID, GM_Data__c, Indicator__c, Quantity__c FROM Indicator_Assign__c WHERE GM_Data__c=:gmDataId AND Indicator__c=:indicatorId LIMIT 1];
            indicator.Quantity__c = quantity;
            update indicator;
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.addIndicatorAssign', 'Could not update indicator, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static void removeIndicatorAssign (String gmDataId, String indicatorId){
        try {
            List < Indicator_Assign__c > indicators = [SELECT ID, GM_Data__c, Indicator__c FROM Indicator_Assign__c WHERE GM_Data__c=:gmDataId AND Indicator__c=:indicatorId];
            delete indicators;
        } catch (Exception e) {
            throw new GFW_Exception('ReviewFormController.removeIndicatorAssign', 'Could not remove indicator, please refresh and try again.', e);
        }
    }

    @AuraEnabled
    public static boolean submitInternalReview(String recordId){
        InternalReview rev = new InternalReview(recordId);
        rev.submit();
        return true;
    }

    @AuraEnabled(cacheable = true)
    public static string getInternalReviewVFPageName() {
        Application_Setting__mdt pageName = Application_Setting__mdt.getInstance('Internal_Review_Mode');
        return pageName.String_Value__c;
    }
    
}